force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InputLookUpController.cls
public class InputLookUpController { 

/*
     * Returns the "Name" field for a given SObject (e.g. Case has CaseNumber, Account has Name)
    */
    private static String getSobjectNameField(SobjectType sobjType){
        
        //describes lookup obj and gets its name field
        String nameField = 'Name';
        Schema.DescribeSObjectResult dfrLkp = sobjType.getDescribe();
        for(schema.SObjectField sotype : dfrLkp.fields.getMap().values()){
            Schema.DescribeFieldResult fieldDescObj = sotype.getDescribe();
            if(fieldDescObj.isNameField() ){
                nameField = fieldDescObj.getName();
                break;
            }
        }
        system.debug(nameField);
        return nameField;
    }

    /*
     * Loads the initial value of the given SObject type with ID "value"
     */
    @AuraEnabled
    public static List<SObject> getCurrentValue(String searchVal, String typeVal){
        
        SObjectType objType = Schema.getGlobalDescribe().get(typeVal);
        if(objType == null){
            return null;
        }
        System.debug('typeVal: ' + typeVal);
        System.debug('objType: ' + objType);
        String nameField = getSobjectNameField(objType);
        System.debug('nameField: ' + nameField);
        System.debug('Search Param:' + searchVal);
        
        //if searchVal have special char
        if(searchVal.contains('\'')){
            searchVal = searchVal.split('\'')[0] + '\\\'';
        }

        //max. number of records to display for payor field
        Integer noOfRec = 20; 

        //Generate Query
        system.debug('searchVal: ' + searchVal);
        String s = '\'%' + searchVal + '%\'';
        String nl = '\'***Deleted%'; 
        String query = 'Select Id, '+ nameField + ' from ' + typeVal +' where '+ nameField + ' LIKE ' + s + ' LIMIT ' + noOfRec;
        if(typeVal == 'DIR_Employee__c'){
            query = 'Select Id, '+ nameField + ', Position__c from ' + typeVal +' where '+ nameField + ' LIKE ' + s + ' and Position__c = \'Senior Deputy\' LIMIT 5';
        }
        System.debug('### Query: ' + query);
        List<SObject> oList = Database.query(query);
        System.debug('### Query oList: ' + oList);
        
        return oList;
    }

}