force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The office the user is associated to. Related fields are used on output documents</description>
    <inlineHelpText>The office to which the employee is associated.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Internal Employees</relationshipLabel>
    <relationshipName>Internal_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Offices</relationshipLabel>
    <relationshipName>Offices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Identifies offices as BOFE</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/CCU.recordType-meta.xml
<RecordType>
    <fullName>CCU</fullName>
    <active>true</active>
    <description>Central Cashiering Unit</description>
    <label>CCU</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/JEU.recordType-meta.xml
<RecordType>
    <fullName>JEU</fullName>
    <active>true</active>
    <label>JEU</label>
</RecordType>

force-app/main/default/objects/Office_Account__c/Office_Account__c.object-meta.xml
<CustomObject>
    <description>This object allows a cashier to view the details associated to a deposit into and office account so that they can monitor the historical transactions associated with a deposit account.</description>
    <label>Office Account</label>
    <nameField>
        <label>Office Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Account__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Office Accounts</relationshipLabel>
    <relationshipName>Office_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the payee record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Incomplete-2nd Request</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Undeliverable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Position on Loan</fullName>
            </value>
            <value>
                <fullName>Temporarily Vacant</fullName>
            </value>
            <value>
                <fullName>Abolished</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>607 Pending Finance Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <description>Represents a receivable: an incoming payment, or an advice of incoming funds.</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCT-{0000000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Bank_Location__c.field-meta.xml
<CustomField>
    <fullName>Bank_Location__c</fullName>
    <description>Picklist field allows users to designate whether the bank is out of state or in CA</description>
    <label>Bank Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA Bank</fullName>
            </value>
            <value>
                <fullName>Out of State Bank</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <description>Required date field that captures the date of receipt on a payment</description>
    <label>Date Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Deposit_Account__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account__c</fullName>
    <description>Picklist for capturing the Deposit Account</description>
    <label>Deposit Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>01-116</fullName>
            </value>
            <value>
                <fullName>04-116</fullName>
            </value>
            <value>
                <fullName>05-113</fullName>
            </value>
            <value>
                <fullName>06-113</fullName>
            </value>
            <value>
                <fullName>07-119</fullName>
            </value>
            <value>
                <fullName>08-116</fullName>
            </value>
            <value>
                <fullName>09-117</fullName>
            </value>
            <value>
                <fullName>10-117</fullName>
            </value>
            <value>
                <fullName>11-119</fullName>
            </value>
            <value>
                <fullName>12-119</fullName>
            </value>
            <value>
                <fullName>13-113</fullName>
            </value>
            <value>
                <fullName>14-116</fullName>
            </value>
            <value>
                <fullName>15-116</fullName>
            </value>
            <value>
                <fullName>17-113</fullName>
            </value>
            <value>
                <fullName>18-113</fullName>
            </value>
            <value>
                <fullName>23-119</fullName>
            </value>
            <value>
                <fullName>32-117</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>01-112</fullName>
                <isActive>false</isActive>
                <label>01-112</label>
            </value>
            <value>
                <fullName>04-112</fullName>
                <isActive>false</isActive>
                <label>04-112</label>
            </value>
            <value>
                <fullName>06-114</fullName>
                <isActive>false</isActive>
                <label>06-114</label>
            </value>
            <value>
                <fullName>14-112</fullName>
                <isActive>false</isActive>
                <label>14-112</label>
            </value>
            <value>
                <fullName>23-124</fullName>
                <isActive>false</isActive>
                <label>23-124</label>
            </value>
            <value>
                <fullName>633-114</fullName>
                <isActive>false</isActive>
                <label>633-114</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field for capturing the Payee on a payment, field is a look up to Account</description>
    <label>Payee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Required field. Refers to the amount of the incoming instrument; or for Deduction payments derived from one incoming instrument, refers to the net amount of the resultant Net RCT. The deduction amount of the resultant affiliated Deduction RCT will be in Deduction_Amount__c and this field will be $0.00.</description>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Picklist field for designating the payment type</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cashier's Check</fullName>
            </value>
            <value>
                <fullName>Money Order</fullName>
            </value>
            <value>
                <fullName>State Warrant</fullName>
            </value>
            <value>
                <fullName>State Warrant - Returned by USPS</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DepositReceiptsControllerTest.cls
@isTest(SeeAllData=false)
private class DepositReceiptsControllerTest {

    static testMethod void depositReceiptsControllerTest(){
       
        List<Trigger_Settings__c> triggerSettings = new List<Trigger_Settings__c>();
        Trigger_Settings__c rctTriggerSetting = new Trigger_Settings__c(
            Name = 'Receipt Trigger',
            Is_Active__c = true
        );
        triggerSettings.add(rctTriggerSetting);
        insert triggerSettings;
        
        Account acc = new Account();
        acc.name = 'Test Account';
        
        insert acc;
        
        DIR_Employee__c emp = new DIR_Employee__c();
        emp.Position__c = 'Cashiering';
        emp.User__c = UserInfo.getUserId();
        
        insert emp;
        
        Office__c o = new Office__c();
        o.RecordTypeId = Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('BOFE').getRecordTypeID();
        insert o;
        
        Office_Account__c oa = new Office_Account__c();
        oa.Office__c = o.Id;
        oa.Name = '32-117';
        
        insert oa;
        
        Receipt__c rct = new Receipt__c();
        rct.Bank_Location__c = 'CA Bank';
        rct.Payment_Type__c = 'Check';
        rct.Date_Received__c = date.today();
        rct.Payment_Amount__c = 3000;
        rct.Payee__c = acc.id;
        rct.Deposit_Account__c = '32-117';
        rct.Status__c = 'New';
        insert rct;
        
        List<Receipt__c> receipts = new List<Receipt__c>();
        receipts.add(rct);
        
        String[] rctArray = new String[]{};
        rctArray.add(rct.id);
        
        PageReference myVfPage = Page.DepositReceiptsVFP;
        Test.setCurrentPage(myVfPage);
        ApexPages.currentPage().getParameters().put('ids','(' + rct.Id + ')');
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(receipts);
        ssc.setSelected(receipts);
        
        DepositReceiptsController rdc = new DepositReceiptsController(ssc);
        rdc.ids = rctArray;
        rdc.retURL = 'www.google.com';
        rdc.recordDeposits();
        rdc.returnToList();
    }
    
    static testMethod void depositReceiptsControllerErrorTest(){
    
        List<Trigger_Settings__c> triggerSettings = new List<Trigger_Settings__c>();
        Trigger_Settings__c rctTriggerSetting = new Trigger_Settings__c(
            Name = 'Receipt Trigger',
            Is_Active__c = true
        );
        triggerSettings.add(rctTriggerSetting);
        
        /* Trigger_Settings__c cpTriggerSetting = new Trigger_Settings__c(
            Name = 'CasePaymentTrigger',
            Is_Active__c = true
        );
        triggerSettings.add(cpTriggerSetting); */
        insert triggerSettings;
    
        Account acc = new Account();
        acc.name = 'Test Account';
        
        insert acc;

        Receipt__c rct = new Receipt__c();
        rct.Bank_Location__c = 'CA Bank';
        rct.Payment_Type__c = 'Check';
        rct.Date_Received__c = date.today();
        rct.Payment_Amount__c = 3000;
        rct.Payee__c = acc.id;
        rct.Deposit_Account__c = '32-117';
        rct.Office_Unit__c = 'CCU 32';
        rct.Status__c = 'New';
        
        insert rct;
    
        Receipt__c rct2 = new Receipt__c();
        rct2.Bank_Location__c = 'CA Bank';
        rct2.Payment_Type__c = 'Check';
        rct2.Date_Received__c = date.today();
        rct2.Payment_Amount__c = 3000;
        rct2.Payee__c = acc.id;
        rct2.Deposit_Account__c = '17-113';
        rct2.Office_Unit__c = 'JEU';
        rct2.Status__c = 'New';
        
        insert rct2;
        
        Receipt__c rct3 = new Receipt__c();
        rct3.Bank_Location__c = 'CA Bank';
        rct3.Payment_Type__c = 'Check';
        rct3.Date_Received__c = date.today();
        rct3.Payment_Amount__c = 0.00;
        rct3.Deduction_Amount__c = 30;
        rct3.Payee__c = acc.id;
        rct3.Deposit_Account__c = '108';
        rct3.Office_Unit__c = 'JEU';
        rct3.Status__c = 'New';
        insert rct3;
        
        Receipt__c rct4 = new Receipt__c();
        rct4.Bank_Location__c = 'CA Bank';
        rct4.Payment_Type__c = 'Check';
        rct4.Date_Received__c = date.today();
        rct4.Payment_Amount__c = 200.00;
        rct4.Deduction_Amount__c = 0.00;
        rct4.Payee__c = acc.id;
        rct4.Deposit_Account__c = 'None';
        rct4.Office_Unit__c = 'JEU';
        rct4.Status__c = 'New';
        insert rct4;
        
        Receipt__c rct5 = new Receipt__c();
        rct5.Bank_Location__c = 'CA Bank';
        rct5.Payment_Type__c = 'Check';
        rct5.Date_Received__c = date.today();
        rct5.Payment_Amount__c = 200.00;
        rct5.Deduction_Amount__c = 0.00;
        rct5.Payee__c = acc.id;
        rct5.Deposit_Account__c = null;
        rct5.Office_Unit__c = 'JEU';
        rct5.Status__c = 'New';
        insert rct5;
        
        String[] rctArray = new String[]{};
        rctArray.add(rct.id);
        rctArray.add(rct2.id);
        rctArray.add(rct3.id);
        rctArray.add(rct4.id);
        rctArray.add(rct5.id);
        
        List<Receipt__c> receipts = new List<Receipt__c>();
        receipts.add(rct);
        receipts.add(rct2);
        receipts.add(rct3);
        receipts.add(rct4);
        receipts.add(rct5);
        
        PageReference myVfPage = Page.DepositReceiptsVFP;
        Test.setCurrentPage(myVfPage);
        ApexPages.currentPage().getParameters().put('ids','(' + rct.Id + ')');
        
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(receipts);
        ssc.setSelected(receipts);
        
        DepositReceiptsController rdc = new DepositReceiptsController(ssc);
        rdc.ids = null;
        rdc.retURL = null;
        rdc.recordDeposits();
        
    }

}