force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <description>Represents a receivable: an incoming payment, or an advice of incoming funds.</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCT-{0000000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Bank_Location__c.field-meta.xml
<CustomField>
    <fullName>Bank_Location__c</fullName>
    <description>Picklist field allows users to designate whether the bank is out of state or in CA</description>
    <label>Bank Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA Bank</fullName>
            </value>
            <value>
                <fullName>Out of State Bank</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Deposit_Account__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Account__c</fullName>
    <description>Picklist for capturing the Deposit Account</description>
    <label>Deposit Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>01-116</fullName>
            </value>
            <value>
                <fullName>04-116</fullName>
            </value>
            <value>
                <fullName>05-113</fullName>
            </value>
            <value>
                <fullName>06-113</fullName>
            </value>
            <value>
                <fullName>07-119</fullName>
            </value>
            <value>
                <fullName>08-116</fullName>
            </value>
            <value>
                <fullName>09-117</fullName>
            </value>
            <value>
                <fullName>10-117</fullName>
            </value>
            <value>
                <fullName>11-119</fullName>
            </value>
            <value>
                <fullName>12-119</fullName>
            </value>
            <value>
                <fullName>13-113</fullName>
            </value>
            <value>
                <fullName>14-116</fullName>
            </value>
            <value>
                <fullName>15-116</fullName>
            </value>
            <value>
                <fullName>17-113</fullName>
            </value>
            <value>
                <fullName>18-113</fullName>
            </value>
            <value>
                <fullName>23-119</fullName>
            </value>
            <value>
                <fullName>32-117</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>01-112</fullName>
                <isActive>false</isActive>
                <label>01-112</label>
            </value>
            <value>
                <fullName>04-112</fullName>
                <isActive>false</isActive>
                <label>04-112</label>
            </value>
            <value>
                <fullName>06-114</fullName>
                <isActive>false</isActive>
                <label>06-114</label>
            </value>
            <value>
                <fullName>14-112</fullName>
                <isActive>false</isActive>
                <label>14-112</label>
            </value>
            <value>
                <fullName>23-124</fullName>
                <isActive>false</isActive>
                <label>23-124</label>
            </value>
            <value>
                <fullName>633-114</fullName>
                <isActive>false</isActive>
                <label>633-114</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Office_Unit__c.field-meta.xml
<CustomField>
    <fullName>Office_Unit__c</fullName>
    <description>Picklist field that allows user to designate the Office Unit on the Payment record.</description>
    <label>Office Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCU 32</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>WCA 1</fullName>
            </value>
            <value>
                <fullName>WCA 4</fullName>
            </value>
            <value>
                <fullName>WCA 5</fullName>
            </value>
            <value>
                <fullName>WCA 6</fullName>
            </value>
            <value>
                <fullName>WCA 7</fullName>
            </value>
            <value>
                <fullName>WCA 8</fullName>
            </value>
            <value>
                <fullName>WCA 9</fullName>
            </value>
            <value>
                <fullName>WCA 10</fullName>
            </value>
            <value>
                <fullName>WCA 11</fullName>
            </value>
            <value>
                <fullName>WCA 12</fullName>
            </value>
            <value>
                <fullName>WCA 13</fullName>
            </value>
            <value>
                <fullName>WCA 14</fullName>
            </value>
            <value>
                <fullName>WCA 15</fullName>
            </value>
            <value>
                <fullName>WCA 17</fullName>
            </value>
            <value>
                <fullName>WCA 18</fullName>
            </value>
            <value>
                <fullName>WCA 23</fullName>
            </value>
            <value>
                <fullName>RCI</fullName>
            </value>
            <value>
                <fullName>WCA 633</fullName>
                <isActive>false</isActive>
                <label>WCA 633</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Exchange__c.field-meta.xml
<CustomField>
    <fullName>Payment_Exchange__c</fullName>
    <description>Defines to whom the payment was directed.</description>
    <label>Payment Exchange</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Division Payment</fullName>
            </value>
            <value>
                <fullName>Direct Payment</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
            <value>
                <fullName>Party to Party</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Picklist field for designating the payment type</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cashier's Check</fullName>
            </value>
            <value>
                <fullName>Money Order</fullName>
            </value>
            <value>
                <fullName>State Warrant</fullName>
            </value>
            <value>
                <fullName>State Warrant - Returned by USPS</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReceiptLogFormController.cls
public class ReceiptLogFormController {
	//TODO: create a single get function for init pickList.

	@AuraEnabled
	public static List<String> getPaymentTypes()
	{
	   List<String> options = new List<String>();
        
	   Schema.DescribeFieldResult fieldResult = Receipt__c.Payment_Type__c.getDescribe();
	   List<Schema.PicklistEntry> pickList = fieldResult.getPicklistValues();
        
	   for( Schema.PicklistEntry f : pickList)
	   {
           if(f.getLabel()!='Deduction'){
               options.add(f.getLabel());
           }
	   }
	   return options;
	}

	@AuraEnabled
	public static List<String> getDepositAccount()
	{
	   List<String> options = new List<String>();
        
	   Schema.DescribeFieldResult fieldResult = Receipt__c.Deposit_Account__c.getDescribe();
	   List<Schema.PicklistEntry> pickList = fieldResult.getPicklistValues();
	   for( Schema.PicklistEntry f : pickList)
	   {
		  options.add(f.getLabel());
	   }
	   return options;
	}

	@AuraEnabled
	public static List<String> getBankLocation()
	{
	   List<String> options = new List<String>();
        
	   Schema.DescribeFieldResult fieldResult = Receipt__c.Bank_Location__c.getDescribe();
	   List<Schema.PicklistEntry> pickList = fieldResult.getPicklistValues();
        
	   for( Schema.PicklistEntry f : pickList)
	   {
		  options.add(f.getLabel());
	   }       
	   return options;
	}

	@AuraEnabled
	public static List<String> getPaymentExchange()
	{
	   List<String> options = new List<String>();
        
	   Schema.DescribeFieldResult fieldResult = Receipt__c.Payment_Exchange__c.getDescribe();
	   List<Schema.PicklistEntry> pickList = fieldResult.getPicklistValues();
        
	   for( Schema.PicklistEntry f : pickList)
	   {
		  options.add(f.getLabel());
	   }       
	   return options;
	}

	@AuraEnabled
	public static List<String> getOfficeUnit()
	{
	   List<String> options = new List<String>();
        
	   Schema.DescribeFieldResult fieldResult = Receipt__c.Office_Unit__c.getDescribe();
	   List<Schema.PicklistEntry> pickList = fieldResult.getPicklistValues();
        
	   for( Schema.PicklistEntry f : pickList)
	   {
		  options.add(f.getLabel());
	   }       
	   return options;
	}

	@AuraEnabled
	public static String getPayorName(String payorId){
		System.debug('82 getPayorName called: ' + payorId);

		Account payor = [SELECT Id, Name FROM Account WHERE Id =: payorId LIMIT 1];

		System.debug('86 payor: ' + payor);
		
		return payor.Name;
	}

	
    @AuraEnabled
	public static String getDeputyName(String deputyId){ 
		DIR_Employee__c deputy = [Select Id, Name from DIR_Employee__c where id =: deputyId Limit 1];
		return deputy.Name;
	}
    

	//add field set in receiptLogForm
	@AuraEnabled
    public static List<FieldSetMember> getFields(String typeName, String fsName) {
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(typeName);
        Schema.DescribeSObjectResult describe = targetType.getDescribe();
        
		Map<String, Schema.FieldSet> fsMap = describe.fieldSets.getMap();
        Schema.FieldSet fs = fsMap.get(fsName);
		System.debug('fs: ' + fsMap);
        List<Schema.FieldSetMember> fieldSet = fs.getFields();
        List<FieldSetMember> fset = new List<FieldSetMember>();
        
		for (Schema.FieldSetMember f: fieldSet) {
            fset.add(new FieldSetMember(f));
        }
		return fset;
    }

	public class FieldSetMember {

		public FieldSetMember(Schema.FieldSetMember f) {
			this.DBRequired = f.DBRequired;
			this.fieldPath = f.fieldPath;
			this.label = f.label;
			this.required = f.required;
			this.type = '' + f.getType();
		}

		public FieldSetMember(Boolean DBRequired) {
			this.DBRequired = DBRequired;
		}

		@AuraEnabled
		public Boolean DBRequired { get;set; }

		@AuraEnabled
		public String fieldPath { get;set; }

		@AuraEnabled
		public String label { get;set; }

		@AuraEnabled
		public Boolean required { get;set; }

		@AuraEnabled
		public String type { get; set; }
	}
 	

}