force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InputLookUpControllerTest.cls
@isTest
public class InputLookUpControllerTest { 

    static testmethod void testInputLookupVal(){
        
        String strSearchVal = '%tes%';
        String objectType = 'Account';


        List<Account> compList = [Select Id, Name from Account where Name like :strSearchVal Limit 5];

        List<SObject> firstList1 = InputLookUpController.getCurrentValue(strSearchVal, objectType);

        strSearchVal = '%cr%';
        objectType = 'DIR_Employee__c';

        List<DIR_Employee__c> emplList = [Select Id, Name, Position__c from DIR_Employee__c where Name like :strSearchVal Limit 5];

        List<SObject> firstList2 = InputLookUpController.getCurrentValue(strSearchVal, objectType);
        System.assertEquals(emplList, firstList2);
        System.assertEquals(compList, firstList1);
    }

}