force-app/main/default/objects/Case_Note__c/Case_Note__c.object-meta.xml
<CustomObject>
    <description>Case Notes and Events that correspond to Case Management.</description>
    <label>Case Note</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Case Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Businesses__c/Related_Businesses__c.object-meta.xml
<CustomObject>
    <label>Related Business</label>
    <nameField>
        <displayFormat>RBO-{00000000}</displayFormat>
        <label>Related Businesses Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Businesses__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to store business Account for the Rbo record</description>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Business)</relationshipLabel>
    <relationshipName>Related_Businessess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Related Business)</relationshipLabel>
    <relationshipName>Related_Businessess1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alter Ego</fullName>
            </value>
            <value>
                <fullName>LC 238 (Related Business)</fullName>
            </value>
            <value>
                <fullName>Parent Company</fullName>
            </value>
            <value>
                <fullName>Predecessor</fullName>
            </value>
            <value>
                <fullName>Single Enterprise</fullName>
            </value>
            <value>
                <fullName>Subsidiary</fullName>
            </value>
            <value>
                <fullName>Successor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Used for the read only access for business, Related Business and Related Business Name.</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Related_Party__c/Related_Party__c.object-meta.xml
<CustomObject>
    <label>Related Party</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Related Party  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/RelatedBusinessTriggerTest.cls
@IsTest
public class RelatedBusinessTriggerTest {
    @testSetup static void methodName(){
        List<Account> listOfAccount = DIRDataFactory.createAccount();
    }
    @IsTest public static void checkInverseRelatedBusinessRecordTestForTypeSuccessor(){
        List<Account> listOfAccount = DIRDataFactory.createAccount();
        DIRDataFactory.caseRoleRecord(listOfAccount[0].Id);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[0].Id,Related_Business__c=listOfAccount[1].Id,Type__c='Successor');
        Test.startTest();
        Database.saveResult result = Database.insert(relatedBusinessesObj);
        Test.stopTest();
        System.assertEquals(true, result.isSuccess());
        
    }
    @IsTest public static void checkInverseRelatedBusinessRecordTestForTypeRelatedBusiness(){
        List<Account> listOfAccount = DIRDataFactory.createAccount();
        DIRDataFactory.caseRoleRecord(listOfAccount[0].Id);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[0].Id,Related_Business__c=listOfAccount[1].Id,Type__c='LC 238 (Related Business)');
        Test.startTest();
        Database.saveResult result = Database.insert(relatedBusinessesObj);
        Test.stopTest();
        System.assertEquals(true, result.isSuccess());
        
    }
    @IsTest public static void checkInverseRelatedBusinessRecordTestForTypeAlterEgo(){
        List<Account> listOfAccount = DIRDataFactory.createAccount();
        DIRDataFactory.caseRoleRecord(listOfAccount[0].Id);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[0].Id,Related_Business__c=listOfAccount[1].Id,Type__c='Alter Ego');
        Test.startTest();
        Database.saveResult result = Database.insert(relatedBusinessesObj);
        Test.stopTest();
        System.assertEquals(true, result.isSuccess());
        
    }
    @IsTest public static void checkInverseRelatedBusinessRecordTestForTypeParentCompany(){
        List<Account> listOfAccount = DIRDataFactory.createAccount();
        DIRDataFactory.caseRoleRecord(listOfAccount[0].Id);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[0].Id,Related_Business__c=listOfAccount[1].Id,Type__c='Parent Company');
        Test.startTest();
        Database.saveResult result = Database.insert(relatedBusinessesObj);
        Test.stopTest();
        System.assertEquals(true, result.isSuccess());
        
    }
    @IsTest public static void checkInverseRelatedBusinessRecordTestForTypeSubsidiary(){
        List<Account> listOfAccount = DIRDataFactory.createAccount();
        DIRDataFactory.caseRoleRecord(listOfAccount[0].Id);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[0].Id,Related_Business__c=listOfAccount[1].Id,Type__c='Subsidiary');
        Test.startTest();
        Database.saveResult result = Database.insert(relatedBusinessesObj);
        Test.stopTest();
        System.assertEquals(true, result.isSuccess());
        
    }
    @IsTest public static void checkInverseRelatedBusinessRecordTestForTypeSingleEnterprise(){
        List<Account> listOfAccount = DIRDataFactory.createAccount();
        DIRDataFactory.caseRoleRecord(listOfAccount[0].Id);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[0].Id,Related_Business__c=listOfAccount[1].Id,Type__c='Single Enterprise');
        Test.startTest();
        Database.saveResult result = Database.insert(relatedBusinessesObj);
        Test.stopTest();
        System.assertEquals(true, result.isSuccess());
        
    }
    @IsTest public static void checkInverseRelatedBusinessRecordTestForTypePredecessor(){
        List<Account> listOfAccount = DIRDataFactory.createAccount();
        DIRDataFactory.caseRoleRecord(listOfAccount[1].Id);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[1].Id,Related_Business__c=listOfAccount[0].Id,Type__c='Predecessor');
        Test.startTest();
        Database.saveResult result = Database.insert(relatedBusinessesObj);
        Test.stopTest();
        System.assertEquals(true, result.isSuccess());
        
    }
    @IsTest public static void checkDuplicateRelatedBusinessesTest(){ 
        List<Account> listOfAccount = DIRDataFactory.createAccount();
        DIRDataFactory.caseRoleRecord(listOfAccount[1].Id);
        DIRDataFactory.relatedBusinessesRecord('Test Account - EXIST', listOfAccount);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[0].Id,Related_Business__c=listOfAccount[1].Id,Type__c='LC 238 (Related Business)');
        Test.startTest();
        Database.saveResult result = Database.insert(relatedBusinessesObj, False);
        Test.stopTest();
        System.assertEquals(true, result.isSuccess());
        
    }
    @IsTest public static void checkCreateCaseNoteTest(){
        String caseNote = 'A potential related business has been identified.';
        DIR_Case__c caseObj = DIRDataFactory.createCaseManagementTestRecord();
        Test.startTest();
        Case_Note__c caseNoteObj = RelatedBusinessTriggerHelper.createCaseNote(caseObj.Id, caseNote);
        Test.stopTest();
        System.assert(caseNoteObj != null);
    }
    @IsTest public static void checkCreateRelatedPartyRecord(){
        DIR_Case__c caseObj = DIRDataFactory.createCaseManagementTestRecord();
        List<Related_Businesses__c> relatedBusinessObjList = DIRDataFactory.createRelatedBusinessesTestData1();
        Test.startTest();
        Related_Party__c relatedPartyObj = RelatedBusinessTriggerHelper.createRelatedPartyRecord(caseObj.Id, relatedBusinessObjList[0].Id, relatedBusinessObjList[0].Id);
        Test.stopTest();
        System.assert(relatedPartyObj != null);
    }
    @IsTest public static void checkRelatedBusinessAfterUpdate(){
        List<String> accNameSet = new List<String>{'%William%','%Nina KalKat%'};
        List<Account> listOfAccount = [select Name from Account WHERE Name LIKE :accNameSet];
        DIRDataFactory.caseRoleRecord(listOfAccount[0].Id);
        Related_Businesses__c relatedBusinessesObj = new Related_Businesses__c(Name__c='Test Account - BPAAS',Business__c=listOfAccount[1].Id,Related_Business__c=listOfAccount[0].Id,Type__c='Predecessor');
        insert relatedBusinessesObj;
        relatedBusinessesObj.Type__c = 'Alter Ego';
        Test.startTest();
        DirUtils.isFirstTime = true; 
        Database.SaveResult result = Database.update(relatedBusinessesObj);
        Test.stopTest();
        System.assert(result.isSuccess());
        System.assert(result.getId() != null);
    }
}