force-app/main/default/objects/Activity_Configuration__c/Activity_Configuration__c.object-meta.xml
<CustomObject>
    <label>Activity Configuration</label>
    <nameField>
        <displayFormat>AHC-{0}</displayFormat>
        <label>Activity Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Configuration__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Configuration__c/fields/History_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>History_Object_Configuration__c</fullName>
    <label>History Object Configuration</label>
    <referenceTo>History_Object_Configuration__c</referenceTo>
    <relationshipLabel>Activity Configuration</relationshipLabel>
    <relationshipName>Activity_Configuration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Configuration__c/fields/Tracked_Statuses__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Statuses__c</fullName>
    <label>Tracked Statuses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessments__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</description>
    <inlineHelpText>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</inlineHelpText>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Violations are tied together as an assessment.</description>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defaults to "open" but may be set to "affirmed" or "modified" by the hearing process via the hearing results vfp.</description>
    <inlineHelpText>If Sr. administratively dismisses violation, they must also adjust penalties and/or wages due to zero.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>NTD - Full Compliance</fullName>
            </value>
            <value>
                <fullName>NTD - No Compliance</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Affirmed</fullName>
            </value>
            <value>
                <fullName>Modified</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Administrative Dismissal</fullName>
            </value>
            <value>
                <fullName>De Novo Appeal</fullName>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
            </value>
            <value>
                <fullName>Appeal Withdrawn</fullName>
            </value>
            <value>
                <fullName>Request Dismissal</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Referred for Judgment</fullName>
            </value>
            <value>
                <fullName>Judgment Accepted</fullName>
            </value>
            <value>
                <fullName>Judgment Rejected</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Writ Dismissed</fullName>
            </value>
            <value>
                <fullName>Writ Settled by Legal</fullName>
            </value>
            <value>
                <fullName>Writ Affirmed</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Offer in Compromise</fullName>
            </value>
            <value>
                <fullName>Self Audit Discount</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Canceled - Invalid</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Judgment</fullName>
            </value>
            <value>
                <fullName>Claimant Withdrew</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Dismissed at Conference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/History_Object_Configuration__c.object-meta.xml
<CustomObject>
    <label>History Object Configuration</label>
    <nameField>
        <displayFormat>HOC-{0}</displayFormat>
        <label>History Object Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Object Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Object_Configuration__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/fields/Path_to_Case__c.field-meta.xml
<CustomField>
    <fullName>Path_to_Case__c</fullName>
    <inlineHelpText>This is the path to get to the Case Management object. .Case__r should be at the end of each string.

Example: If you are going from Meeting Participant object to Case it would be Meeting_Participant__r.Meeting__r.Case__r</inlineHelpText>
    <label>Path to Case</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateActivityHistoryActionTEST.cls
@isTest(SeeAllData=false)
private class GenerateActivityHistoryActionTEST {

    static testMethod void testGenerateActivityHistory() {
        
        List<History_Object_Configuration__c> hocList = new List<History_Object_Configuration__c>();

        History_Object_Configuration__c hoc1 = new History_Object_Configuration__c(
            Object_name__c = 'Case Violation',
            Object_API_Name__c = 'DIR_Violation__c',
            Active__c = true,
            Path_to_Case__c = 'Case__r'
        );
        hocList.add(hoc1);
        
        History_Object_Configuration__c hoc2 = new History_Object_Configuration__c(
            Object_name__c = 'Event',
            Object_API_Name__c = 'Event',
            Active__c = true
        );
        hocList.add(hoc2);

        History_Object_Configuration__c hoc3 = new History_Object_Configuration__c(
            Object_name__c = 'Task',
            Object_API_Name__c = 'Task',
            Active__c = true
        );
        hocList.add(hoc3);

        insert hocList;
        
        RecordType caseRT = [SELECT Id FROM RecordType WHERE sObjectType = 'DIR_Case__c' AND IsActive = true LIMIT 1];
                
        DIR_Case__c dirCase = new DIR_Case__c(
            RecordTypeId = caseRT.Id
        );
        insert dirCase;
        
        RecordType violRT = [SELECT Id FROM RecordType WHERE sObjectType = 'DIR_Violation__c' AND Name LIKE '%BOFE%' AND IsActive = true LIMIT 1];

        Assessments__c assess = new Assessments__c(
            Case_Management__c = dirCase.Id
            );
        insert assess;
        
        DIR_Violation__c viol = new DIR_Violation__c(
            Case__c = dirCase.Id,
            Assessment__c = assess.Id,
            Status__c = 'Open',
            RecordTypeId = violRT.Id
        );
        insert viol;

        List<Activity_Configuration__c> acList = new List<Activity_Configuration__c>();

        Activity_Configuration__c ac = new Activity_Configuration__c(
            History_Object_Configuration__c = hoc3.Id,
            Active__c = true,
            Activity_Type__c = 'Call',
            Tracked_Statuses__c = 'In Progress'
        );
        acList.add(ac);
        
        Activity_Configuration__c ac2 = new Activity_Configuration__c(
            History_Object_Configuration__c = hoc2.Id,
            Active__c = true,
            Activity_Type__c = 'Call'
        );
        acList.add(ac2);

        insert acList;

        Task t =  new Task(
            WhatId = viol.Id,
            Subject = 'test Task',
            Type = 'Call',
            Status = 'Not Started'
        );
        insert t;

        t.Status = 'In Progress';
        update t;
        
        Event e = new Event(
            WhatId = viol.Id,
            Subject = 'Test',
            startDateTime = date.today(),
            endDateTime = date.today() + 1,
            Type = 'Call'
        );
        insert e;
        
        
        Event e1 = new Event(
            WhatId = dirCase.Id,
            Subject = 'Test',
            startDateTime = date.today(),
            endDateTime = date.today() + 1,
            Type = 'Call'
        );
        insert e1;
        
        e1.Event_Status__c = 'Cancelled';
        update e1;
        
        GenerateActivityHistoryAction.executeFromFlow(new List<String>());

    }
}