force-app/main/default/objects/Activity_Configuration__c/Activity_Configuration__c.object-meta.xml
<CustomObject>
    <label>Activity Configuration</label>
    <nameField>
        <displayFormat>AHC-{0}</displayFormat>
        <label>Activity Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Configuration__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Configuration__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Configuration__c/fields/History_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>History_Object_Configuration__c</fullName>
    <label>History Object Configuration</label>
    <referenceTo>History_Object_Configuration__c</referenceTo>
    <relationshipLabel>Activity Configuration</relationshipLabel>
    <relationshipName>Activity_Configuration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Configuration__c/fields/Tracked_Statuses__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Statuses__c</fullName>
    <label>Tracked Statuses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/Attachment_Configuration__c.object-meta.xml
<CustomObject>
    <label>Attachment Configuration</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Attachment Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attachment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Criteria__c</fullName>
    <label>Attachment Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attachment_Operator__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Operator__c</fullName>
    <label>Attachment Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Starts With</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attorney_Client_Privilege__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Client_Privilege__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attorney Client Privilege</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/History_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>History_Object_Configuration__c</fullName>
    <label>History Object Configuration</label>
    <referenceTo>History_Object_Configuration__c</referenceTo>
    <relationshipLabel>Attachment Configuration</relationshipLabel>
    <relationshipName>History_Field_Configuration1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Subject to PRA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>PAGA Submission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attorney_Client_Privilege__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Client_Privilege__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is subject to attorney-client privilege.</inlineHelpText>
    <label>Attorney-Client Privilege</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is considered confidential</inlineHelpText>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is not subject to PRA requests</inlineHelpText>
    <label>Not Subject to PRA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <label>Case History</label>
    <nameField>
        <displayFormat>CH-{0}</displayFormat>
        <label>Case History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <label>Confidential</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <label>Not Subject to PRA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Field Update</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Attachment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/History_Field_Configuration__c/History_Field_Configuration__c.object-meta.xml
<CustomObject>
    <label>History Field Configuration</label>
    <nameField>
        <displayFormat>HF-{0}</displayFormat>
        <label>History Field Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Field Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Field_Configuration__c/fields/API_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Field_Name__c</fullName>
    <label>API Field Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Field_Configuration__c/fields/History_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>History_Object_Configuration__c</fullName>
    <label>History Object Configuration</label>
    <referenceTo>History_Object_Configuration__c</referenceTo>
    <relationshipLabel>History Field Configuration</relationshipLabel>
    <relationshipName>History_Field_Configuration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/History_Field_Configuration__c/fields/Tracked_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Record_Types__c</fullName>
    <label>Tracked Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/History_Object_Configuration__c.object-meta.xml
<CustomObject>
    <label>History Object Configuration</label>
    <nameField>
        <displayFormat>HOC-{0}</displayFormat>
        <label>History Object Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Object Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Object_Configuration__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/fields/Path_to_Case__c.field-meta.xml
<CustomField>
    <fullName>Path_to_Case__c</fullName>
    <inlineHelpText>This is the path to get to the Case Management object. .Case__r should be at the end of each string.

Example: If you are going from Meeting Participant object to Case it would be Meeting_Participant__r.Meeting__r.Case__r</inlineHelpText>
    <label>Path to Case</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateAttachmentsPlusAction.cls
public class GenerateAttachmentsPlusAction extends TriggerAction{
    
    private static Set<Id> performedAudits = new Set<Id>();
    
    public boolean shouldRun;
    private String sObjectName;
    private String parentObjectName;
    private String pathToParent;
    //private String parentPathToParent;
    private History_Object_Configuration__c hist;
    private History_Object_Configuration__c parentHist;
    
    private Map<Id, sObject> parentMap = new Map<Id, sObject>();
    private Map<String, History_Object_Configuration__c> histMap = new Map<String, History_Object_Configuration__c>();
    private Map<String, Set<String>> filterMap = new Map<String, Set<String>>();
    private Map<String, Attachment_Configuration__c> startsWithMap = new Map<String, Attachment_Configuration__c>();
    private Map<String, Attachment_Configuration__c> containsMap = new Map<String, Attachment_Configuration__c>();
    private Map<String, Attachment_Configuration__c> equalsMap = new Map<String, Attachment_Configuration__c>();
    private List<Attachments_Plus__c> newAttPlusList = new List<Attachments_Plus__c>();
    private List<Case_History__c> chList = new List<Case_History__c>();
    
    private Map<Id, sObject> sObjMap = new Map<Id, sObject>();
    
    public GenerateAttachmentsPlusAction(Map<Id, sObject> triggerNewMap){
        //This class does not support bulk inserts of Attachments that have different parent object types.
        //For this code to operate correctly in a bulk Insert, all Attachments must have the same Parent object type
        super(triggerNewMap);
        sObjectName = 'Attachment';
        List<History_Object_Configuration__c> hocList = [SELECT Id, Name, Active__c, Object_API_Name__c, Object_Name__c, Path_to_Case__c,
                                                            (SELECT Id, Name, Active__c, API_Field_Name__c, History_Object_Configuration__c, Tracked_Record_Types__c FROM History_Field_Configuration__r WHERE Active__c = true),
                                                            (SELECT Id, Name, Active__c, Attachment_Criteria__c, Attachment_Operator__c,  History_Object_Configuration__c, Type__c, Attorney_Client_Privilege__c, Not_Subject_to_PRA__c, Confidential__c FROM History_Field_Configuration1__r WHERE Active__c = true),
                                                            (SELECT Id, Name, Active__c, Activity_Status__c, Activity_Type__c, Tracked_Statuses__c, History_Object_Configuration__c FROM Activity_Configuration__r WHERE Active__c = true)
                                                        FROM History_Object_Configuration__c 
                                                        WHERE Active__c = true];
        Id tempParentObjId = String.valueOf(triggerNewMap.values()[0].get('ParentId'));                                             
        parentObjectName = tempParentObjId.getSObjectType().getDescribe().getName();
        for(History_Object_Configuration__c h : hocList){
            if(!histMap.containsKey(h.Object_API_Name__c)){
                histMap.put(h.Object_API_Name__c, h);
            }
        }
        hist = histMap.get(sObjectName);
        parentHist = histMap.get(parentObjectName);
        if(hist == null || parentHist == null){
            return;
        }
        else{
            getFilterMap(hist);
            pathToParent = parentHist.Path_to_case__c;
            getSObjectMap(triggerNewMap.values(), hist, sObjectName);
            for(sObject s : triggerNewMap.values()){
                Attachment att = (Attachment)s;
                String parentId = att.ParentId;
                if(sObjMap.containsKey(parentId)){
                    sObject parentObj = sObjMap.get(parentId);
                    String pId;
                    List<Attachment_Configuration__c> configList = new List<Attachment_Configuration__c>();
                    for(String str : filterMap.keySet()){
                        Set<String> tempSet = filterMap.get(str);
                        for(String cStr : tempSet){
                            String compareString = cStr;
                            String attName = att.Name;
                            Boolean createAP = false;
                            Map<String, Attachment_Configuration__c> acConfigMap = new Map<String, Attachment_Configuration__c>();
                            if(str == 'Starts With'){
                                if(cStr.length() > attName.length()){
                                    continue;
                                }
                                else if(attName.subString(0, cStr.length()) == cStr){
                                    acConfigMap = startsWithMap;
                                }
                            }
                            else if(str == 'Contains' && attName.contains(cStr)){
                                acConfigMap = containsMap;
                            }
                            else if(str == 'Equals' && attName == cStr){
                                acConfigMap = equalsMap;
                            }
                            pId = getParentId(sObjMap.get(parentId), parentObjectName);
                            Attachment_Configuration__c thisAC;
                            if(acConfigMap.containsKey(cStr)){
                                thisAC = acConfigMap.get(cStr);
                                configList.add(thisAC);
                            }
                        }
                    }
                    if(!hasBeenAudited(att.Id)){
                        if(!configList.isEmpty()){
                            for(Attachment_Configuration__c thisAC : configList){
                                Attachments_Plus__c ap = new Attachments_Plus__c(
                                    Attachment_ID__c = att.Id,
                                    Attachment_Name__c = att.Name,
                                    Attorney_Client_Privilege__c = thisAC.Attorney_Client_Privilege__c,
                                    Confidential__c = thisAC.Confidential__c,
                                    Not_Subject_to_PRA__c = thisAC.Not_Subject_to_PRA__c,
                                    Object__c = parentObjectName,
                                    Parent_Record_ID__c = pId,
                                    Record_ID__c = parentId,
                                    Type__c = thisAC.Type__c
                                );
                                newAttPlusList.add(ap);

                                if(parentObjectName.equalsIgnoreCase('account')) continue;

                                Case_History__c ch = new Case_History__c(
                                    Case_Management__c = pId,
                                    Record_ID__c = parentId,
                                    Type__c = 'Attachment',
                                    New_Value__c = 'New '+thisAC.Type__c+' Attachment Created: '+att.Name
                                );
                                chList.add(ch);
                            }
                        }
                        else{
                            Attachments_Plus__c ap = new Attachments_Plus__c(
                                    Attachment_ID__c = att.Id,
                                    Attachment_Name__c = att.Name,
                                    Attorney_Client_Privilege__c = false,
                                    Confidential__c = false,
                                    Not_Subject_to_PRA__c = false,
                                    Object__c = parentObjectName,
                                    Parent_Record_ID__c = pId,
                                    Record_ID__c = parentId,
                                    Type__c = 'Unknown'
                                );
                            newAttPlusList.add(ap);

                            if(parentObjectName.equalsIgnoreCase('account')) continue;

                            Case_History__c ch = new Case_History__c(
                                Case_Management__c = pId,
                                Record_ID__c = parentId,
                                Type__c = 'Attachment',
                                New_Value__c = 'New Unknown Attachment Created: '+att.Name
                            );
                            chList.add(ch);
                        }
                        
                        performedAudits.add(att.Id);
                    }
                }
            }
        }
    }
    
    private void getFilterMap(History_Object_Configuration__c hist){
        for(Attachment_Configuration__c ac : hist.History_Field_Configuration1__r){
            if(ac.Attachment_Operator__c != null && ac.Attachment_Criteria__c != null){
                Set<String> tempSet = new Set<String>();
                if(!filterMap.containsKey(ac.Attachment_Operator__c)){
                    tempSet.add(ac.Attachment_Criteria__c);
                    filterMap.put(ac.Attachment_Operator__c, tempSet);
                }
                else{
                    tempSet = filterMap.get(ac.Attachment_Operator__c);
                    tempSet.add(ac.Attachment_Criteria__c);
                    filterMap.put(ac.Attachment_Operator__c, tempSet);
                }

                if(ac.Attachment_Operator__c == 'Starts With' && !startsWithMap.containsKey(ac.Attachment_Criteria__c)){
                    startsWithMap.put(ac.Attachment_Criteria__c, ac);
                }
                if(ac.Attachment_Operator__c == 'Contains' && !containsMap.containsKey(ac.Attachment_Criteria__c)){
                    containsMap.put(ac.Attachment_Criteria__c, ac);
                }
                if(ac.Attachment_Operator__c == 'Equals' && !equalsMap.containsKey(ac.Attachment_Criteria__c)){
                    equalsMap.put(ac.Attachment_Criteria__c, ac);
                }
            }
        }
    }
    
    private String getParentId(sObject newSObject, String sObjectName){
        
        sObject tempSobj = sObjMap.get(newSObject.Id);
        String idVal = 'Id';
        String parentId = string.valueOf(tempSobj.get(idVal));
        if(pathToParent.contains('.Id')){
            String tempPathToParent = pathToParent.replace('.Id', '');
            List<String> tempList = tempPathToParent.split('\\.');
            if(tempList.size() == 1){
                parentId = string.valueOf(tempSobj.getsObject(tempList[0]).get('Id'));
            }
            else if(tempList.size() == 2){
                parentId = string.valueOf(tempSobj.getsObject(tempList[0]).getsObject(tempList[1]).get('Id'));
            }
            else if(tempList.size() == 3){
                parentId = string.valueOf(tempSobj.getsObject(tempList[0]).getsObject(tempList[1]).getsObject(tempList[2]).get('Id'));
            }
        }
        return parentId;

    }
    
    private void getSObjectMap(List<sObject> newList, History_Object_Configuration__c hist, String sObjectName){
        if(pathToParent == null){
            pathToParent = 'Id';
        }
        else{
            pathToParent += '.Id';
        }
        String queryStr = 'SELECT '+pathToParent;
        
        List<Id> idList = new List<Id>();
        for(sObject newSObject : newList){
            idList.add(String.valueOf(newSObject.get('ParentId')));
        }
        String operator;
        String idVar;
        if(idList.size() == 1){
            operator = '=';
            idVar = '\''+idList[0]+'\'';
        }
        else{
            operator = 'IN';
            idvar = '(';
            for(Id i : idList){
                idvar += '\''+i+'\',';
            }
            idVar = idVar.subString(0, idVar.length() - 1) + ')';
        }
        queryStr += ', Name FROM '+parentObjectName+' WHERE Id '+operator+' '+idVar;
        system.debug('*************queryStr: '+queryStr);
        try{
            sObjMap = new Map <Id, sObject>(database.query(queryStr));
            for(sObject s : newList){
                String parentId = String.valueOf(s.get('ParentId'));
                if(sObjMap.containsKey(parentId)){
                    sObject parent = sObjMap.get(parentId);
                    parentMap.put(s.Id, parent);
                }
            }
        }
        catch(exception e){
         //add error handling if needed
        }
        finally{
            if(sObjMap == null || sObjMap.isEmpty()){
                sObjMap = new Map <Id, sObject>(database.query(queryStr));
            }
        }
    }
    
    public override boolean shouldRunOnInsert() {

        shouldRun = newAttPlusList.size() > 0 ? true : false;
        
        return shouldRun;
    }
     
    public override boolean shouldRunOnDelete() { return false;} 
    
    public override boolean shouldRunOnUpdate() { return false;}
    
    public override void doAction() {
        
        insert newAttPlusList;
        insert chList;
        
    }
    
    private static boolean hasBeenAudited(String attId) {
        if (performedAudits.contains(attId)){
            return true;
        }
        else{
            return false;
        }
    }

    public static void runHandler() {
        if(Util.skipTrigger()){
            return;
        }
        
        if (trigger.isBefore) {
            return;
        }   
        
        if (trigger.isInsert) {
            GenerateAttachmentsPlusAction action = new GenerateAttachmentsPlusAction(trigger.newMap);
            if(action.shouldRunOnInsert()){
                action.doAction();
            }
        } 
        
    }
}