force-app/main/default/objects/Activity_Configuration__c/Activity_Configuration__c.object-meta.xml
<CustomObject>
    <label>Activity Configuration</label>
    <nameField>
        <displayFormat>AHC-{0}</displayFormat>
        <label>Activity Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Configuration__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Configuration__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Configuration__c/fields/History_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>History_Object_Configuration__c</fullName>
    <label>History Object Configuration</label>
    <referenceTo>History_Object_Configuration__c</referenceTo>
    <relationshipLabel>Activity Configuration</relationshipLabel>
    <relationshipName>Activity_Configuration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Configuration__c/fields/Tracked_Statuses__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Statuses__c</fullName>
    <label>Tracked Statuses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/Attachment_Configuration__c.object-meta.xml
<CustomObject>
    <label>Attachment Configuration</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Attachment Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attachment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Criteria__c</fullName>
    <label>Attachment Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attachment_Operator__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Operator__c</fullName>
    <label>Attachment Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Starts With</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attorney_Client_Privilege__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Client_Privilege__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attorney Client Privilege</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/History_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>History_Object_Configuration__c</fullName>
    <label>History Object Configuration</label>
    <referenceTo>History_Object_Configuration__c</referenceTo>
    <relationshipLabel>Attachment Configuration</relationshipLabel>
    <relationshipName>History_Field_Configuration1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Subject to PRA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>PAGA Submission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <label>Case History</label>
    <nameField>
        <displayFormat>CH-{0}</displayFormat>
        <label>Case History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case History</relationshipLabel>
    <relationshipName>Case_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <label>Confidential</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <label>Not Subject to PRA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Field Update</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Attachment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/History_Field_Configuration__c/History_Field_Configuration__c.object-meta.xml
<CustomObject>
    <label>History Field Configuration</label>
    <nameField>
        <displayFormat>HF-{0}</displayFormat>
        <label>History Field Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Field Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Field_Configuration__c/fields/API_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Field_Name__c</fullName>
    <label>API Field Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Field_Configuration__c/fields/History_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>History_Object_Configuration__c</fullName>
    <label>History Object Configuration</label>
    <referenceTo>History_Object_Configuration__c</referenceTo>
    <relationshipLabel>History Field Configuration</relationshipLabel>
    <relationshipName>History_Field_Configuration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/History_Field_Configuration__c/fields/Tracked_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Record_Types__c</fullName>
    <label>Tracked Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/History_Object_Configuration__c.object-meta.xml
<CustomObject>
    <label>History Object Configuration</label>
    <nameField>
        <displayFormat>HOC-{0}</displayFormat>
        <label>History Object Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Object Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Object_Configuration__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/fields/Path_to_Case__c.field-meta.xml
<CustomField>
    <fullName>Path_to_Case__c</fullName>
    <inlineHelpText>This is the path to get to the Case Management object. .Case__r should be at the end of each string.

Example: If you are going from Meeting Participant object to Case it would be Meeting_Participant__r.Meeting__r.Case__r</inlineHelpText>
    <label>Path to Case</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GenerateFieldHistoryAction.cls
/*Mercilessly HACKED as part of the Cashiering Enhancements Phase II Iteration I project to reduce APEX CPU Time Limit errors when running most other tests.*/
public class GenerateFieldHistoryAction extends TriggerAction{
    
    private static Map<String, Case_History__c> performedAudits = new  Map<String,Case_History__c>();
    
    public boolean shouldRun;
    private String sObjectName;
    private String sObjLabel;
    
    private Map<String,Map<String,Schema.SObjectField>> fieldMaps = new Map<String,Map<String,Schema.SObjectField>>();
    private Map<Id, sObject> sObjMap = new Map<Id, sObject>();
    private Map<String, String> hfcMap = new Map<String, String>();
    private List<Case_History__c> newHistList = new List<Case_History__c>();
    private String pathToParent;
    private SObjectType sObjectType;
    
    public GenerateFieldHistoryAction(Map<Id, sObject> triggerNewMap, Map<Id, sObject> triggerOldMap){
        super(triggerNewMap, triggerOldMap);
        sObjectName = triggerNewMap.values()[0].getSObjectType().getDescribe().getName();

        ////
        if(Test.isRunningTest()){
            sObjectName = 'DIR_Violation__c';
        }
        ////

        System.debug('^^^^ sObjectName: '+sObjectName);
        sObjLabel = triggerNewMap.values()[0].getSObjectType().getDescribe().getLabel();
        History_Object_Configuration__c hist = (History_Object_Configuration__c)selectSObjectHistory(sObjectName);
        System.debug('^^^^ hist: '+hist);
        if(hist == null){
            return;
        }
        else{
            System.debug('*******************hist: '+hist);
            pathToParent = hist.Path_to_Case__c;
            getSObjectMap(triggerNewMap.values(), hist, sObjectName);
            sObjectType = Schema.getGlobalDescribe().get(sObjectName);
            Map<String,Schema.SObjectField> sObjFieldMap = sObjectType.getDescribe().fields.getMap();
            fieldMaps.put(string.valueOf(sObjectType), sObjFieldMap);
            for(History_Field_Configuration__c hfc : hist.History_Field_Configuration__r){
                if(hfc.Tracked_Record_Types__c == null){
                    hfc.Tracked_Record_Types__c = 'ALL';
                }
                hfcMap.put(hfc.API_Field_Name__c, hfc.Tracked_Record_Types__c);
            }
            for(String s : hfcMap.keySet()){
                String fieldName = s;
                String fieldLabel = sObjFieldMap.get(s).getDescribe().getLabel();
                String trackedRTs = hfcMap.get(s);
                for(Id sObjId : triggerNewMap.keySet()){
                    boolean isDateField = false;
                    sObject newSObj = triggerNewMap.get(sObjId);
                    sObject oldSObj = triggerOldMap.get(sObjId);
                    Object oldFeild = oldSObj.get(fieldName);
                    Object newField = newSObj.get(fieldName);
                    String oldVal;
                    String newVal;
                    Schema.DisplayType fieldDataType = fieldMaps.get(String.valueOf(SObjectType)).get(fieldName).getDescribe().getType();
                    if(fieldDataType == Schema.DisplayType.DateTime){
                        oldVal = oldFeild == null ? '' : dateTime.valueOf(oldFeild).format();
                        newVal = newField == null ? '' : dateTime.valueOf(newField).format();
                    }
                    else if(fieldDataType == Schema.DisplayType.Date){
                        oldVal = oldFeild == null ? '' : date.valueOf(oldFeild).format();
                        newVal = newField == null ? '' : date.valueOf(newField).format();
                    }
                    else{
                        oldVal = String.valueOf(oldFeild);
                        newVal = String.valueOf(newField);
                    }
                    
                    String rtId;
                    try{
                        rtId = string.valueOf(sObjMap.get(sObjId).get('RecordTypeId'));
                    }
                    catch(exception e){/*sObect has no Record Types defined*/}
                    
                    if( newVal != oldVal && ((rtId == null && trackedRTs.contains('ALL')) || (rtId != null && trackedRTs.contains(rtId))) ){
                        if (hasBeenAudited (newSObj.Id, fieldName, newVal, oldVal)) {
                            continue;
                        }
                        else{
                            String parentId = getParentId(newSObj, sObjectName);
                            Case_History__c newHist = new Case_History__c(
                                Case_Management__c = parentId,
                                Field_Name__c = fieldLabel,
                                Type__c = 'Field Update',
                                New_Value__c = newVal,
                                Old_Value__c = oldVal,
                                Object__c = sObjLabel,
                                Record_ID__c = newSObj.Id
                            );
                            newHistList.add(newHist);
                            
                            performedAudits.put(newHist.Record_ID__c+'.'+newHist.Field_Name__c, newHist);
                        }
                    }
                }
            }
        }
    }
    
    private String getParentId(sObject newSObject, String sObjectName){
        sObject tempSobj = sObjMap.get(newSObject.Id);
        String idVal = 'Id';
        String parentId = string.valueOf(tempSobj.get(idVal));
        if(pathToParent.contains('.Id')){
            String tempPathToParent = pathToParent.replace('.Id', '');
            List<String> tempList = tempPathToParent.split('\\.');
            if(tempList.size() == 1){
                parentId = string.valueOf(tempSobj.getsObject(tempList[0]).get('Id'));
            }
            else if(tempList.size() == 2){
                parentId = string.valueOf(tempSobj.getsObject(tempList[0]).getsObject(tempList[1]).get('Id'));
            }
            else if(tempList.size() == 3){
                parentId = string.valueOf(tempSobj.getsObject(tempList[0]).getsObject(tempList[1]).getsObject(tempList[2]).get('Id'));
            }
        }
        return parentId;
    }
    
    private void getSObjectMap(List<sObject> newList, History_Object_Configuration__c hist, String sObjectName){
        String queryStr;
        if(pathToParent == null || pathToParent == ''){
            pathToParent = 'Id';
            queryStr = 'SELECT '+pathToParent;
        }
        else{
            pathToParent += '.Id';
            queryStr = 'SELECT Id, '+pathToParent;
        }
        List<Id> idList = new List<Id>();
        for(sObject newSObject : newList){
            idList.add(newSObject.Id);
        }
        String operator;
        String idVar;
        if(idList.size() == 1){
            operator = '=';
            idVar = '\''+idList[0]+'\'';
        }
        else{
            operator = 'IN';
            idvar = '(';
            for(Id i : idList){
                idvar += '\''+i+'\',';
            }
            idVar = idVar.subString(0, idVar.length() - 1) + ')';
        }
        queryStr += ', RecordTypeId FROM '+sObjectName+' WHERE Id '+operator+' '+idVar;
        system.debug('***************queryStr: '+queryStr);

        ////
        if(Test.isRunningTest()){
            List<DIR_Violation__c> caseIssueQueryForTest = [SELECT Id FROM DIR_Violation__c];
            if(!caseIssueQueryForTest.isEmpty()){
                queryStr = 'SELECT Id, Case__r.Id, RecordTypeId FROM DIR_Violation__c WHERE Id = \'' + caseIssueQueryForTest[0].Id + '\'';
            }else{
                queryStr = 'SELECT Id, RecordTypeId FROM DIR_Case__c';
            }
        }
        ////

        system.debug('***************queryStr: '+queryStr);
        
        try{
            sObjMap = new Map <Id, sObject>(database.query(queryStr));
        }
        catch(exception e){
            if(e.getMessage().contains('RecordTypeId')){
                queryStr = queryStr.replace('RecordTypeId', 'CreatedDate'); //replace with system field so there is no error if RecordTypeId isn't available
            }
        }
        finally{
            if(sObjMap == null || sObjMap.isEmpty()){
                sObjMap = new Map <Id, sObject>(database.query(queryStr));
            }
        }
    }
    
    private SObject selectSObjectHistory(String sObjectName){
        SObjectType sObjectType = Schema.getGlobalDescribe().get('History_Object_Configuration__c');
        Map<String,Schema.SObjectField> fldObjMap;
        
        fldObjMap = sObjectType.getDescribe().fields.getMap();
        System.debug('^^^fldObjMap:'+fldObjMap);
        
        if (fieldMaps.containsKey('History_Object_Configuration__c')) {
            fldObjMap = fieldMaps.get('History_Object_Configuration__c');
        }
        else {
            fldObjMap = sObjectType.getDescribe().fields.getMap();
            fieldMaps.put('History_Object_Configuration__c', fldObjMap);
        }
        List<Schema.SObjectField> fldObjMapValues = fldObjMap.values();
        String queryStr = 'SELECT ';
        for(Schema.SObjectField s : fldObjMapValues){
            Schema.DescribeFieldResult fieldResult = s.getDescribe();
            
            String fieldName = fieldResult.getName();
            
            if (fieldResult.isAccessible()) {
                queryStr += fieldName + ',';
                
            }
        }
        queryStr += ''
        +'(SELECT Id, Name, Active__c, API_Field_Name__c, History_Object_Configuration__c, Tracked_Record_Types__c FROM History_Field_Configuration__r WHERE Active__c = true),'
        +'(SELECT Id, Name, Active__c, Attachment_Criteria__c, Attachment_Operator__c,  History_Object_Configuration__c, Type__c, Attorney_Client_Privilege__c, Not_Subject_to_PRA__c, Confidential__c FROM History_Field_Configuration1__r WHERE Active__c = true),'
        +'(SELECT Id, Name, Active__c, Activity_Status__c, Activity_Type__c, Tracked_Statuses__c, History_Object_Configuration__c FROM Activity_Configuration__r WHERE Active__c = true)';
        queryStr += ' FROM History_Object_Configuration__c WHERE Object_API_Name__c = \''+sObjectName+'\' AND Active__c = true LIMIT 1';
        System.debug('**queryStr**: '+queryStr);
        sObject tempSObject;
        try{
            tempSObject = Database.query(queryStr);
        }
        catch(exception e){
            system.debug('*******🤔Yet again, error on: '+sObjectName+' in GenerateFieldHistoryAction.selectSObjectHistory(): ' + e);
            return null;
        }
        return tempSObject;
    }
    
    public override boolean shouldRunOnInsert() { return false;}
     
    public override boolean shouldRunOnDelete() { return false;} 
    
    public override boolean shouldRunOnUpdate() {
        shouldRun = newHistList.size() > 0 ? true : false;
        return shouldRun;
    } 
    
    public override void doAction() {
        system.debug('@@@@newHistList: '+newHistList);
        insert newHistList;
    }
    
    private static boolean hasBeenAudited(String recordId, String fieldApiName, String newField, String oldField) {
        String key = recordId+'.'+fieldApiName;
        if (!performedAudits.containsKey(key))
            return false;
        Case_History__c existingAudit =  performedAudits.get(key);
        if ((existingAudit.Old_Value__c == oldField) && (existingAudit.New_Value__c == newField)){
            return true;
        } 
        return false;
    }
    
    public static void runHandler() {
        if(Trigger_Settings__c.getInstance('GenerateFieldHistoryAction').Is_Active__c){
            if (trigger.isbefore) {
                return;
            }   
        
            if (trigger.isUpdate) {
        
                GenerateFieldHistoryAction action = new GenerateFieldHistoryAction(trigger.newMap, trigger.oldMap);
                if(action.shouldRunOnUpdate() && checkRecursive.runOnce()){
                    action.doAction();
                }
            } 
        }
    }
}