force-app/main/default/objects/OWC_Self_Register_Config__mdt/OWC_Self_Register_Config__mdt.object-meta.xml
<CustomObject>
    <label>OWC Self Register Config</label>
    <pluralLabel>OWC Self Register Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/OWC_Self_Register_Config__mdt/fields/UserName_suffix__c.field-meta.xml
<CustomField>
    <fullName>UserName_suffix__c</fullName>
    <label>UserName suffix</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OWCLightningLoginFormController.cls
public class OWCLightningLoginFormController {
    public OWCLightningLoginFormController() {
        
    }
    
    @AuraEnabled
    public static String login(String username, String password, String startUrl) {
        try{
            //Add the community suffix.
            OWC_Self_Register_Config__mdt  self_Register_config = OWC_Self_Register_Config__mdt.getInstance('Online_Claim_Community');
            System.debug('----->'+self_Register_config.UserName_suffix__c );
            username = String.isNotBlank(self_Register_config.UserName_suffix__c) ? username + '.'+ self_Register_config.UserName_suffix__c : username;
            ApexPages.PageReference lgn = Site.login(username, password, startUrl);
            aura.redirect(lgn);
            return null;
        }
        catch (Exception ex) {
            return ex.getMessage();            
        }
    }
    
    @AuraEnabled
    public static Boolean getIsUsernamePasswordEnabled() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        return authConfig.getUsernamePasswordEnabled();
    }

    @AuraEnabled
    public static Boolean getIsSelfRegistrationEnabled() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        return authConfig.getSelfRegistrationEnabled();
    }

    @AuraEnabled
    public static String getSelfRegistrationUrl() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        if (authConfig.getSelfRegistrationEnabled()) {
            return authConfig.getSelfRegistrationUrl();
        }
        return null;
    }

    @AuraEnabled
    public static String getForgotPasswordUrl() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        return authConfig.getForgotPasswordUrl();
    }
    
    @TestVisible
    private static Auth.AuthConfiguration getAuthConfig(){
        Id networkId = Network.getNetworkId();
        Auth.AuthConfiguration authConfig = new Auth.AuthConfiguration(networkId,'');
        return authConfig;
    }

    @AuraEnabled
    public static String setExperienceId(String expId) {
        // Return null if there is no error, else it will return the error message 
        try {
            if (expId != null) {
                Site.setExperienceId(expId);
            }
            return null; 
        } catch (Exception ex) {
            return ex.getMessage();            
        }
    } 
}