force-app/main/default/objects/Attachments_Data__c/Attachments_Data__c.object-meta.xml
<CustomObject>
    <label>Attachments + Data</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Attachments + Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments + Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Data__c/fields/Attachments__c.field-meta.xml
<CustomField>
    <fullName>Attachments__c</fullName>
    <label>Attachments +</label>
    <referenceTo>Attachments_New__c</referenceTo>
    <relationshipLabel>Attachments + Data</relationshipLabel>
    <relationshipName>Attachments_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <formula>Attachments__r.File_Type__c</formula>
    <label>File Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateExistingAttachmentDataBatchTest.cls
@IsTest
public class UpdateExistingAttachmentDataBatchTest {
    @IsTest
    public static void testAttachmentDataBatch(){
        Attachments_New__c attachPlus = new Attachments_New__c();
        attachPlus.File_Name__c = 'test.pdf';
        attachPlus.File_Type__c = 'Intake';
        insert attachPlus;
        
        Attachments_Data__c attachDataObj = new Attachments_Data__c();
        attachDataObj.Attachments__c = [SELECT Id, File_Name__c FROM Attachments_New__c WHERE File_Name__c = 'test.pdf' LIMIT 1].Id;
        attachDataObj.Value__c = 'test';
        attachDataObj.Field_API_Name__c = 'test';
        attachDataObj.Field_Name__c = 'test';
        insert attachDataObj;
        
        Test.startTest();
        UpdateExistingAttachmentDataBatch scope = new UpdateExistingAttachmentDataBatch();
        Database.executeBatch(scope);
        Test.stopTest();
        
    }
}