force-app/main/default/objects/Attachments_Data__c/Attachments_Data__c.object-meta.xml
<CustomObject>
    <label>Attachments + Data</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Attachments + Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments + Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Data__c/fields/Attachments__c.field-meta.xml
<CustomField>
    <fullName>Attachments__c</fullName>
    <label>Attachments +</label>
    <referenceTo>Attachments_New__c</referenceTo>
    <relationshipLabel>Attachments + Data</relationshipLabel>
    <relationshipName>Attachments_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <formula>Attachments__r.File_Type__c</formula>
    <label>File Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/APlus_Json__c.field-meta.xml
<CustomField>
    <fullName>APlus_Json__c</fullName>
    <label>APlus Json</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <label>Community</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Id__c</fullName>
    <label>Related Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Visible__c.field-meta.xml
<CustomField>
    <fullName>Visible__c</fullName>
    <label>Visible</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateExistingAttachmentDataBatch.cls
global class UpdateExistingAttachmentDataBatch implements Database.Batchable<sObject>, Database.Stateful{
    public integer count = 0;
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id,APlus_Json__c, Name, Community__c, File_Name__c, File_Type__c, Related_Id__c, Visible__c, Description__c ';
        //query += ' (SELECT Id, Name, Attachments__c, Field_API_Name__c, Field_Name__c, File_Type__c, Value__c FROM Attachments_Data__r)';
        query += ' FROM Attachments_New__c';// + ' WHERE Related_Id__c = \'a1Bt00000005PO9EAM\'';
        //query += (!Test.isRunningTest()) ? '': ' LIMIT 1';
        System.debug('query ::: '+query);
        return Database.getQueryLocator(query); 
    }
    global void execute(Database.BatchableContext bc, List<Attachments_New__c> scope){
        List<Attachments_New__c> attachPlusToBeUpdated = new List<Attachments_New__c>();
        Map<Id, List<Attachments_Data__c>> aPlusWithaDatasMap = new Map<Id, List<Attachments_Data__c>>();
        Set<Id> aPlusIds = new Set<Id>();
        System.debug('result ::: '+scope);
        for(Attachments_New__c aPlus: scope)
        {
           aPlusIds.add(aPlus.Id); 
        }
        for(Attachments_Data__c aData : [SELECT Id, Name, Attachments__c, Field_API_Name__c, Field_Name__c, File_Type__c, Value__c FROM Attachments_Data__c
                                        WHERE Attachments__c IN: aPlusIds ])
        {
            if(!aPlusWithaDatasMap.containsKey(aData.Attachments__c)){
                aPlusWithaDatasMap.put(aData.Attachments__c, new List<Attachments_Data__c>());
            }
            aPlusWithaDatasMap.get(aData.Attachments__c).add(aData);
        }
        if(scope != null && scope.size() > 0){
            for(Attachments_New__c aPlus : scope){
                if(aPlusWithaDatasMap.containsKey(aPlus.Id)){
                    List<OWCServiceUtility.attachmentPlusWrapperObj> updateAttachPlusRec = new List<OWCServiceUtility.attachmentPlusWrapperObj>();
                    for(Attachments_Data__c attachDataObj : aPlusWithaDatasMap.get(aPlus.Id)){
                        updateAttachPlusRec.add(new OWCServiceUtility.attachmentPlusWrapperObj(attachDataObj.Field_API_Name__c, attachDataObj.Field_Name__c, attachDataObj.Value__c, attachDataObj.File_Type__c));
                    }
                    
                    aPlus.APlus_Json__c = (updateAttachPlusRec != null && updateAttachPlusRec.size() > 0) ? JSON.serialize(updateAttachPlusRec) : '';
                    attachPlusToBeUpdated.add(aPlus);
                }
            }
        }
        
        if(attachPlusToBeUpdated != null && attachPlusToBeUpdated.size() > 0){
            update attachPlusToBeUpdated;
        }
    }
    
    global void finish(Database.BatchableContext bc){
    }
}