force-app/main/default/objects/Attachments_Data__c/Attachments_Data__c.object-meta.xml
<CustomObject>
    <label>Attachments + Data</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Attachments + Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments + Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Data__c/fields/Attachments__c.field-meta.xml
<CustomField>
    <fullName>Attachments__c</fullName>
    <label>Attachments +</label>
    <referenceTo>Attachments_New__c</referenceTo>
    <relationshipLabel>Attachments + Data</relationshipLabel>
    <relationshipName>Attachments_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Data__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/Release_to_Public__c.field-meta.xml
<CustomField>
    <fullName>Release_to_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Release to Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AttachmentsDataTriggerHandler.cls
public class AttachmentsDataTriggerHandler {
    public static void afterUpdateAttachmentsDataTriggerHandler(List<Attachments_Data__c> newList, Map<Id,Attachments_Data__c> oldMapList){
        Map<Id, String> mapAttId2Release = new  Map<Id, String>();
        String fieldApiName = 'Release_to_Public';
        for(Attachments_Data__c attList : newList){
            Attachments_Data__c oldObject = oldMapList.get(attList.Id);
            if(attList.Value__c != oldObject.Value__c && attList.Field_API_Name__c != '' && attList.Field_API_Name__c.contains(fieldApiName)){
                mapAttId2Release.put(attList.Attachments__c, attList.Value__c);
            }
        }
        if(mapAttId2Release.size() > 0){
            alterAttachmentNew(mapAttId2Release);
        }
    }
    public static void afterInsertAttachmentsDataTriggerHandler(List<Attachments_Data__c> newList){
        Map<Id, String> mapAttId2Release = new  Map<Id, String>();
        String fieldApiName = 'Release_to_Public';
        for(Attachments_Data__c attachementObj : newList){
            if(attachementObj.Field_API_Name__c.contains(fieldApiName)){
                mapAttId2Release.put(attachementObj.Attachments__c,attachementObj.Value__c);
            }
        }
        if(mapAttId2Release.size() > 0){
            alterAttachmentNew(mapAttId2Release);
        }
    }
    
    private static void alterAttachmentNew(Map<Id, String> alterDataMap){
        List<Attachments_New__c> attachmentsToUpdate = [SELECT ID, Release_to_Public__c FROM Attachments_New__c WHERE
                                                        ID IN:alterDataMap.keyset()];
        if(attachmentsToUpdate.size() > 0){
            List<Attachments_New__c> attachmentsListToUpdate = new List<Attachments_New__c>();
            for(Attachments_New__c attObj : attachmentsToUpdate){
                attObj.Release_to_Public__c = ('true'.equalsIgnoreCase(alterDataMap.get(attObj.Id))) ? true : false;
                attachmentsListToUpdate.add(attObj);
            }
            update attachmentsListToUpdate;
        }
    }
}