force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>Referrals for action by other business units related to cases within case management system.</description>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/First_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder_Date__c</fullName>
    <description>Date that the first reminder should be sent. Determined by taking the value of the First Reminder Days field as an input to a the setReminderDate method on the referralMethods class called from the update event on the referral. Method calculates the number of business days from the current date to the date on which a reminder should be sent to the assigned individuals</description>
    <label>First Reminder Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/First_Reminder_Days__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder_Days__c</fullName>
    <description>Business days after being sent for referral that a reminder should be set.</description>
    <formula>/* setup BOFE Legal Referrals settings */
IF (
     (
       RecordType.DeveloperName = 'BOFE_Civil_Litigation_Referral' 
       || RecordType.DeveloperName = 'BOFE_Request_for_Legal_Court_Action'
       || RecordType.DeveloperName = 'BOFE_Request_for_Legal_Services'
     )
    , 3 
    , null
   )</formula>
    <label>First Reminder Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Second_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder_Date__c</fullName>
    <description>Date that the second reminder should be sent. Determined by taking the value of the First Reminder Days field as an input to a the setReminderDate method on the referralMethods class called from the update event on the referral. Method calculates the number of business days from the current date to the date on which a reminder should be sent to the assigned individuals</description>
    <label>Second Reminder Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Second_Reminder_Days__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder_Days__c</fullName>
    <description>Business days after being sent for referral that a reminder should be set.</description>
    <formula>/* setup BOFE Legal Referrals settings */ 
IF ( 
( 
RecordType.DeveloperName = 'BOFE_Civil_Litigation_Referral' 
|| RecordType.DeveloperName = 'BOFE_Request_for_Legal_Court_Action' 
|| RecordType.DeveloperName = 'BOFE_Request_for_Legal_Services' 
) 
, 8 
, null 
)</formula>
    <label>Second Reminder Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Referral_Assignment__c/Referral_Assignment__c.object-meta.xml
<CustomObject>
    <description>Persons to which a referral has been assigned</description>
    <label>Referral Assignment</label>
    <nameField>
        <displayFormat>AID-{000000}</displayFormat>
        <label>Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Assignment__c/fields/Currently_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Currently_Assigned__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allows a user to be unassigned and keep the history of who was assigned</description>
    <inlineHelpText>If unassigning an individual from this referral, uncheck this box and create a new assignment</inlineHelpText>
    <label>Currently Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referral_Assignment__c/fields/First_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder_Date__c</fullName>
    <description>For referrals where only one employee can be assigned at a time, defines the date on which the first reminder is to be sent.</description>
    <label>First Reminder Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral_Assignment__c/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <description>Parent referral - Referral may be assigned to multiple individuals.</description>
    <inlineHelpText>Referral to which this person is being assigned. Click this field to access the parent referral</inlineHelpText>
    <label>Referral</label>
    <referenceTo>Referral__c</referenceTo>
    <relationshipLabel>Referral Assignments</relationshipLabel>
    <relationshipName>Referral_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Referral_Assignment__c/fields/Second_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder_Date__c</fullName>
    <description>For referrals where only one employee can be assigned at a time, defines the date on which the second reminder is to be sent.</description>
    <label>Second Reminder Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/referralAssignmentMethods.cls
public class referralAssignmentMethods {

    public static void updateReminderDates(list<Referral_Assignment__c> refAList, Map<ID, Referral_Assignment__c> oldMap){
        for(Referral_Assignment__c ref : refAList){
            Referral_Assignment__c oldRef = oldMap.get(ref.Id);
            // 
            if (ref.Currently_Assigned__c && !oldRef.Currently_Assigned__c){
                    if (ref.First_Reminder_Date__c == null)
                    	customDateUtils.daysFrom('Referral_Assignment__c', ref.Id, date.today(), 'First_Reminder_Date__c', (Integer)ref.Referral__r.First_Reminder_days__c, 'Weekdays');
                    if (ref.Second_Reminder_Date__c == null)
                    	customDateUtils.daysFrom('Referral_Assignment__c', ref.Id, date.today(), 'Second_Reminder_Date__c', (Integer)ref.Referral__r.Second_Reminder_days__c, 'Weekdays');
            }
        }
    }
    
    public static void updateReminderDates(list<Referral_Assignment__c> refAList){
        System.debug('****  Running updateReminderDates with list only.');
        Set <Id> refSet = new set<Id>();

        for (Referral_Assignment__c r : refAList){
            refSet.add(r.Referral__c);
        }

            Map<Id, Referral__c> refMap = new Map <Id, Referral__c> ([Select Id, First_Reminder_days__c, Second_Reminder_days__c From Referral__c Where Id in :refSet]);
        
        if(refMap.size() > 0){
            for(Referral_Assignment__c ref : refAList){
                if (ref.Currently_Assigned__c){
                        System.debug('****  Currently_Assigned__c = true, running updates. Input variables: refID = ' + ref.Id + ' & First_Reminder_days__c= ' + (integer)refMap.get(ref.Referral__c).First_Reminder_Days__c  + ' & Second_Reminder_days__c = ' + (Integer)refMap.get(ref.Referral__c).Second_Reminder_days__c);
                        if (ref.First_Reminder_Date__c == null)
                        	customDateUtils.daysFrom('Referral_Assignment__c', ref.Id, date.today(), 'First_Reminder_Date__c', (integer)refMap.get(ref.Referral__c).First_Reminder_Days__c, 'Weekdays');
                        if (ref.Second_Reminder_Date__c == null)
                        	customDateUtils.daysFrom('Referral_Assignment__c', ref.Id, date.today(), 'Second_Reminder_Date__c', (Integer)refMap.get(ref.Referral__c).Second_Reminder_days__c, 'Weekdays');
                }
            }
        }
    }
}