force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Division</description>
    <inlineHelpText>Select the Division</inlineHelpText>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin-Accounting</fullName>
            </value>
            <value>
                <fullName>Admin-Admin Services</fullName>
            </value>
            <value>
                <fullName>Admin-Budgets</fullName>
            </value>
            <value>
                <fullName>Admin-Business Serv</fullName>
            </value>
            <value>
                <fullName>Admin-Human Resources</fullName>
            </value>
            <value>
                <fullName>Admin-OIS</fullName>
            </value>
            <value>
                <fullName>Admin-RTWS</fullName>
            </value>
            <value>
                <fullName>CHSWC</fullName>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
            <value>
                <fullName>DLSE</fullName>
            </value>
            <value>
                <fullName>DLSE-IWC</fullName>
            </value>
            <value>
                <fullName>DLSE/PIU</fullName>
            </value>
            <value>
                <fullName>DLSE-PWD/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH</fullName>
            </value>
            <value>
                <fullName>DOSH-CFOI/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH-OIIS/OD-Research</fullName>
            </value>
            <value>
                <fullName>DWC</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/Claims Mgmt</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/SELSP</fullName>
            </value>
            <value>
                <fullName>Fast Food Council</fullName>
            </value>
            <value>
                <fullName>OD-Drug Formulary</fullName>
            </value>
            <value>
                <fullName>OD-Legal N</fullName>
            </value>
            <value>
                <fullName>OD-Legal S</fullName>
            </value>
            <value>
                <fullName>OD-PAGA</fullName>
            </value>
            <value>
                <fullName>OD-PIO/Communications</fullName>
            </value>
            <value>
                <fullName>Office of The Director</fullName>
            </value>
            <value>
                <fullName>OIS</fullName>
            </value>
            <value>
                <fullName>OSHAB</fullName>
            </value>
            <value>
                <fullName>OSHSB</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Division_Unit__c.field-meta.xml
<CustomField>
    <fullName>Division_Unit__c</fullName>
    <description>Text field combining DIR division and unit, it's updated by Unit (Position Method class)</description>
    <label>Division/Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Position Location</description>
    <inlineHelpText>Enter the DIR office location for this position.</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMERICAN CANYON</fullName>
            </value>
            <value>
                <fullName>ANAHEIM</fullName>
            </value>
            <value>
                <fullName>BAKERSFIELD</fullName>
            </value>
            <value>
                <fullName>CHICO</fullName>
            </value>
            <value>
                <fullName>CONCORD</fullName>
            </value>
            <value>
                <fullName>EL CENTRO</fullName>
            </value>
            <value>
                <fullName>EUREKA</fullName>
            </value>
            <value>
                <fullName>FOSTER CITY</fullName>
            </value>
            <value>
                <fullName>FREMONT</fullName>
            </value>
            <value>
                <fullName>FRESNO</fullName>
            </value>
            <value>
                <fullName>GLENDALE</fullName>
            </value>
            <value>
                <fullName>GOLETA</fullName>
            </value>
            <value>
                <fullName>LA PALMA</fullName>
            </value>
            <value>
                <fullName>LODI</fullName>
            </value>
            <value>
                <fullName>LOS ANGELES</fullName>
            </value>
            <value>
                <fullName>LONG BEACH</fullName>
            </value>
            <value>
                <fullName>MARINA DEL REY</fullName>
            </value>
            <value>
                <fullName>MODESTO</fullName>
            </value>
            <value>
                <fullName>MONROVIA</fullName>
            </value>
            <value>
                <fullName>OAKLAND</fullName>
            </value>
            <value>
                <fullName>OXNARD</fullName>
            </value>
            <value>
                <fullName>POMONA</fullName>
            </value>
            <value>
                <fullName>REDDING</fullName>
            </value>
            <value>
                <fullName>RIVERSIDE</fullName>
            </value>
            <value>
                <fullName>SACRAMENTO</fullName>
            </value>
            <value>
                <fullName>SALINAS</fullName>
            </value>
            <value>
                <fullName>SAN BERNARDINO</fullName>
            </value>
            <value>
                <fullName>SAN DIEGO</fullName>
            </value>
            <value>
                <fullName>SAN FRANCISCO</fullName>
            </value>
            <value>
                <fullName>SAN JOSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Reporting_Unit_CodeNo__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Unit_CodeNo__c</fullName>
    <label>Reporting Unit CodeNo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial #</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Position on Loan</fullName>
            </value>
            <value>
                <fullName>Temporarily Vacant</fullName>
            </value>
            <value>
                <fullName>Abolished</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>607 Pending Finance Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>HR - Lookup to HR unit names</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin-Accounting</fullName>
            </value>
            <value>
                <fullName>Admin-Admin Services</fullName>
            </value>
            <value>
                <fullName>Admin-Budgets</fullName>
            </value>
            <value>
                <fullName>Admin-Business Serv</fullName>
            </value>
            <value>
                <fullName>Admin-Human Resources</fullName>
            </value>
            <value>
                <fullName>Admin-OIS</fullName>
            </value>
            <value>
                <fullName>Admin-RTWS</fullName>
            </value>
            <value>
                <fullName>Admin-TPSP</fullName>
            </value>
            <value>
                <fullName>CHSWC</fullName>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
            <value>
                <fullName>DLSE</fullName>
            </value>
            <value>
                <fullName>DLSE-IWC</fullName>
            </value>
            <value>
                <fullName>DLSE-PWD/OD-Research</fullName>
            </value>
            <value>
                <fullName>DLSR</fullName>
            </value>
            <value>
                <fullName>DOSH</fullName>
            </value>
            <value>
                <fullName>DOSH-CFOI/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH-OIIS/OD-Research</fullName>
            </value>
            <value>
                <fullName>DWC</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/Claims Mgmt</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/SELSP</fullName>
            </value>
            <value>
                <fullName>Fast Food Council</fullName>
            </value>
            <value>
                <fullName>OD-Drug Formulary</fullName>
            </value>
            <value>
                <fullName>OD-Legal N</fullName>
            </value>
            <value>
                <fullName>OD-Legal S</fullName>
            </value>
            <value>
                <fullName>OD-PAGA</fullName>
            </value>
            <value>
                <fullName>OD-PIO/Communications</fullName>
            </value>
            <value>
                <fullName>OD/Anti-Fraud Unit</fullName>
            </value>
            <value>
                <fullName>Office of The Director</fullName>
            </value>
            <value>
                <fullName>OSHAB</fullName>
            </value>
            <value>
                <fullName>OSHSB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Division_Unit__c.field-meta.xml
<CustomField>
    <fullName>Division_Unit__c</fullName>
    <description>Combination of division and unit, for reporting</description>
    <label>Division/Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OAS/HR</fullName>
            </value>
            <value>
                <fullName>OAS/CNTRS</fullName>
            </value>
            <value>
                <fullName>OAS/FCLTS</fullName>
            </value>
            <value>
                <fullName>OAS/BS</fullName>
            </value>
            <value>
                <fullName>OAS/TPSSB</fullName>
            </value>
            <value>
                <fullName>OAS/AS</fullName>
            </value>
            <value>
                <fullName>OAS/RTW</fullName>
            </value>
            <value>
                <fullName>OAS/SSU</fullName>
            </value>
            <value>
                <fullName>OD/HQ</fullName>
            </value>
            <value>
                <fullName>OD/AFU</fullName>
            </value>
            <value>
                <fullName>OD/OEA</fullName>
            </value>
            <value>
                <fullName>OD/L(N)</fullName>
            </value>
            <value>
                <fullName>OD/L(S)</fullName>
            </value>
            <value>
                <fullName>OD/DIO</fullName>
            </value>
            <value>
                <fullName>OD/ARC</fullName>
            </value>
            <value>
                <fullName>OD/PAGA</fullName>
            </value>
            <value>
                <fullName>OD/DF</fullName>
            </value>
            <value>
                <fullName>OD/RESEARCH</fullName>
            </value>
            <value>
                <fullName>OFS/ACCTG</fullName>
            </value>
            <value>
                <fullName>OFS/OCFO</fullName>
            </value>
            <value>
                <fullName>OFS/BUDGETS</fullName>
            </value>
            <value>
                <fullName>OSIP</fullName>
            </value>
            <value>
                <fullName>OIS</fullName>
            </value>
            <value>
                <fullName>WCAB</fullName>
            </value>
            <value>
                <fullName>CHSWC</fullName>
            </value>
            <value>
                <fullName>DWC/DO</fullName>
            </value>
            <value>
                <fullName>DWC/RO</fullName>
            </value>
            <value>
                <fullName>DWC/ADM-HQ</fullName>
            </value>
            <value>
                <fullName>DWC/ACR-HQ</fullName>
            </value>
            <value>
                <fullName>DWC/PSM</fullName>
            </value>
            <value>
                <fullName>DWC/LBI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/position_Methods_Test.cls
@isTest
(SeeAllData = true)
public with sharing class position_Methods_Test {
    public static testMethod void position_Methods_UnitTest() {
        Unit__c unit = new Unit__c();
        unit.Division__c = 'DLSE';
        unit.Name = '999';
        unit.Division_Unit__c = 'DWC/LBI';
        unit.Location__c = 'TestLoc';
        insert unit;
        
        Position__c p = new Position__c();
        p.Reporting_Unit_CodeNo__c = unit.Name;
        try {
            p.Serial_Number__c = 'asdf';
            insert p;
            p = new Position__c();
            p.Reporting_Unit_CodeNo__c = unit.Name;
        }
        catch (Exception e) {}
        try {
            p.Serial_Number__c = '123';
            insert p;
            p = new Position__c();
            p.Reporting_Unit_CodeNo__c = unit.Name;
        }
        catch (Exception e) {}
        try {
            p.Serial_Number__c = '123';
            p.Status__c = 'Abolished';
            insert p;
        }
        catch (Exception e) {}
        
        p.Serial_Number__c = '909';
        p.Reporting_Unit_CodeNo__c = unit.Name;
        insert p;        
        update p;
        Position__c p2 = new Position__c();
        p2.Serial_Number__c = '988';
        insert p2;
        update p2;
        
    }
}