force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>HR - Look up table for Classication Descriptions</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>Classification Number</description>
    <inlineHelpText>Enter the Classification number for this position.</inlineHelpText>
    <label>Classification(old)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0030</fullName>
            </value>
            <value>
                <fullName>0130</fullName>
            </value>
            <value>
                <fullName>0187</fullName>
            </value>
            <value>
                <fullName>0397</fullName>
            </value>
            <value>
                <fullName>1139</fullName>
            </value>
            <value>
                <fullName>1148</fullName>
            </value>
            <value>
                <fullName>1150</fullName>
            </value>
            <value>
                <fullName>1151</fullName>
            </value>
            <value>
                <fullName>1176</fullName>
            </value>
            <value>
                <fullName>1181</fullName>
            </value>
            <value>
                <fullName>1224</fullName>
            </value>
            <value>
                <fullName>1229</fullName>
            </value>
            <value>
                <fullName>1245</fullName>
            </value>
            <value>
                <fullName>1247</fullName>
            </value>
            <value>
                <fullName>1262</fullName>
            </value>
            <value>
                <fullName>1277</fullName>
            </value>
            <value>
                <fullName>1278</fullName>
            </value>
            <value>
                <fullName>1282</fullName>
            </value>
            <value>
                <fullName>1303</fullName>
            </value>
            <value>
                <fullName>1304</fullName>
            </value>
            <value>
                <fullName>1312</fullName>
            </value>
            <value>
                <fullName>1314</fullName>
            </value>
            <value>
                <fullName>1316</fullName>
            </value>
            <value>
                <fullName>1317</fullName>
            </value>
            <value>
                <fullName>1337</fullName>
            </value>
            <value>
                <fullName>1340</fullName>
            </value>
            <value>
                <fullName>1360</fullName>
            </value>
            <value>
                <fullName>1373</fullName>
            </value>
            <value>
                <fullName>1379</fullName>
            </value>
            <value>
                <fullName>1381</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial #</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Position on Loan</fullName>
            </value>
            <value>
                <fullName>Temporarily Vacant</fullName>
            </value>
            <value>
                <fullName>Abolished</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>607 Pending Finance Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - Civil Service</fullName>
            </value>
            <value>
                <fullName>4 - Exempt</fullName>
            </value>
            <value>
                <fullName>7 - Salary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/X607__c.field-meta.xml
<CustomField>
    <fullName>X607__c</fullName>
    <label>607 #</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>HR - Lookup to HR unit names</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X607__c/X607__c.object-meta.xml
<CustomObject>
    <description>HR - Change in Positions - SCO Form 607</description>
    <label>607</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>607 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>607s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X607__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks the status of the Change in Position through the process</description>
    <inlineHelpText>Select the current status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>607 Created</fullName>
                <default>true</default>
                <label>607 Created</label>
            </value>
            <value>
                <fullName>Submitted to Budget</fullName>
            </value>
            <value>
                <fullName>Submitted to DOF</fullName>
            </value>
            <value>
                <fullName>Submitted to SCO</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Form 1 Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X607__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Proposed New</fullName>
            </value>
            <value>
                <fullName>Extension of Present</fullName>
            </value>
            <value>
                <fullName>Reclassification</fullName>
            </value>
            <value>
                <fullName>Abolishment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Reporting Unit Change</fullName>
            </value>
            <value>
                <fullName>Reestablish</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
            <value>
                <fullName>Combine</fullName>
            </value>
            <value>
                <fullName>Disencumbrance</fullName>
            </value>
            <value>
                <fullName>Encumbrance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/X607_Position_Modification__c.object-meta.xml
<CustomObject>
    <description>HR - Change in Positions</description>
    <label>607 Position Modification</label>
    <nameField>
        <displayFormat>607PM-{00000000}</displayFormat>
        <label>Position Modification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>607 Position Modifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X607_Position_Modification__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>607 Position Modifications</relationshipLabel>
    <relationshipName>X607_Position_Modifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>607 Position Modifications</relationshipLabel>
    <relationshipName>X607_Position_Modifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <label>Serial #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Modification</fullName>
            </value>
            <value>
                <fullName>Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>607 Position Modifications</relationshipLabel>
    <relationshipName>X607_Position_Modifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/X607__c.field-meta.xml
<CustomField>
    <fullName>X607__c</fullName>
    <label>607</label>
    <referenceTo>X607__c</referenceTo>
    <relationshipName>X607_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/x607_Methods.cls
public with sharing class x607_Methods {

	public static void afterUpdate(List<x607__c> newList, List<x607__c> oldList){
		Set<Id> submittedIds = new Set<Id>();
		Map<Id, String> positionTo607Type = new Map<Id, String>();
		for ( Integer i=0;i<newList.size();i++ ){
			if ( newList[i].Status__c == 'Submitted to Budget' &&  oldList[i].Status__c != 'Submitted to Budget' ){
				submittedIds.add(newList[i].Id);
			}
		}
		
		List<Id> positionAdditionIds = new List<Id>();
		List<Id> positionDeletionIds = new List<Id>();
		
		List<Position__c> positionAdditionUpdates = new List<Position__c>();
		List<Position__c> positionDeletionUpdates = new List<Position__c>();
		List<X607_Position_Modification__c> lineItems = [Select Id, Classification__c, Position__c, Position__r.Id, Serial__c, Type__c, Unit__c, X607__c, X607__r.Type__c from X607_Position_Modification__c where x607__c in :submittedIds]; 
		for ( X607_Position_Modification__c x : lineItems ){
			if ( x.Type__c == 'Addition' && x.Position__c != null){
				positionAdditionIds.add(x.Position__c);
			} else 
			if ( x.Type__c == 'Deletion' && x.Position__c != null ){
				positionDeletionIds.add(x.Position__c);
				positionTo607Type.put(x.Position__c, x.X607__r.Type__c);
			} /*else 
			if ( x.Type__c == 'Modification' ){
				Position__c p = x.Position__r;
				p.Expiration_Date__c = String.valueOf(x.Expiration_date__c);
				positionUpdates.add(p);
			}*/
		}
		
		for(Position__c pos : [select Id, IsActive__c from Position__c where Id in :positionAdditionIds]) {
			pos.IsActive__c = true;
			pos.Status__c = 'Vacant';
			positionAdditionUpdates.add(pos);
		}
		
		for(Position__c pos : [select Id, IsActive__c from Position__c where Id in :positionDeletionIds]) {
			pos.IsActive__c = false;
			if(positionTo607Type.containsKey(pos.Id)) {
				if(positionTo607Type.get(pos.Id) != null && positionTo607Type.get(pos.Id) == 'Abolishment') {
					pos.Status__c = 'Abolished';
				}
				else {
					pos.Status__c = 'CLOSED';
				}
			}
			else {
				pos.Status__c = 'CLOSED';
			}
			positionDeletionUpdates.add(pos);
		}
		
		update positionAdditionUpdates;
		update positionDeletionUpdates;
		/*Set<Id> submittedIds = new Set<Id>();
		for ( Integer i=0;i<newList.size();i++ ){
			if ( newList[i].Status__c == 'Submitted to Budget' &&  oldList[i].Status__c != 'Submitted to Budget' ){
				submittedIds.add(newList[i].Id);
			}
		}
		//if Status == 'Submitted to Budget' then upsert the Positions
		//Approval needs to assign Approvals to Helen
		List<Position__c> positionInserts = new List<Position__c>();
		List<Position__c> positionUpdates = new List<Position__c>();
		List<X607_Position_Modification__c> lineItems = [Select Id, Classification__c, Expiration_Date__c, Position__c, Position__r.Id, Serial__c, Type__c, Unit__c, X607__c from X607_Position_Modification__c where x607__c in :submittedIds]; 
		for ( X607_Position_Modification__c x : lineItems ){
			if ( x.Type__c == 'Addition' ){
				Position__c newP = new Position__c();
				newP.Classification__c = x.Classification__c;
				newP.Unit__c = x.Unit__c;
				newP.Serial_Number__c = decimal.valueOf(x.Serial__c);
				positionInserts.add(newP);
			} else 
			if ( x.Type__c == 'Deletion' ){
				Position__c p = x.Position__r;
				p.Status__c = 'Closed';
				positionUpdates.add(p);
			} else 
			if ( x.Type__c == 'Modification' ){
				Position__c p = x.Position__r;
				p.Expiration_Date__c = String.valueOf(x.Expiration_date__c);
				positionUpdates.add(p);
			}
		}
		insert positionInserts;
		
		update positionUpdates;
		Integer i=0;
		for ( X607_Position_Modification__c x : lineItems ){
			if ( x.Type__c == 'Addition' ){
				x.Position__c = positionInserts[i].Id;
				i++;
			}
		}		
		update lineItems;*/
	}

}