force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>HR - Look up table for Classication Descriptions</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_1__c/Form_1__c.object-meta.xml
<CustomObject>
    <description>HR - Form to advertise an open position</description>
    <label>Form 1</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Form 1 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form 1s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_1__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Form 1s</relationshipLabel>
    <relationshipName>Form_1s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_1__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Form 1s</relationshipLabel>
    <relationshipName>Form_1s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>Classification Number</description>
    <inlineHelpText>Enter the Classification number for this position.</inlineHelpText>
    <label>Classification(old)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0030</fullName>
            </value>
            <value>
                <fullName>0130</fullName>
            </value>
            <value>
                <fullName>0187</fullName>
            </value>
            <value>
                <fullName>0397</fullName>
            </value>
            <value>
                <fullName>1139</fullName>
            </value>
            <value>
                <fullName>1148</fullName>
            </value>
            <value>
                <fullName>1150</fullName>
            </value>
            <value>
                <fullName>1151</fullName>
            </value>
            <value>
                <fullName>1176</fullName>
            </value>
            <value>
                <fullName>1181</fullName>
            </value>
            <value>
                <fullName>1224</fullName>
            </value>
            <value>
                <fullName>1229</fullName>
            </value>
            <value>
                <fullName>1245</fullName>
            </value>
            <value>
                <fullName>1247</fullName>
            </value>
            <value>
                <fullName>1262</fullName>
            </value>
            <value>
                <fullName>1277</fullName>
            </value>
            <value>
                <fullName>1278</fullName>
            </value>
            <value>
                <fullName>1282</fullName>
            </value>
            <value>
                <fullName>1303</fullName>
            </value>
            <value>
                <fullName>1304</fullName>
            </value>
            <value>
                <fullName>1312</fullName>
            </value>
            <value>
                <fullName>1314</fullName>
            </value>
            <value>
                <fullName>1316</fullName>
            </value>
            <value>
                <fullName>1317</fullName>
            </value>
            <value>
                <fullName>1337</fullName>
            </value>
            <value>
                <fullName>1340</fullName>
            </value>
            <value>
                <fullName>1360</fullName>
            </value>
            <value>
                <fullName>1373</fullName>
            </value>
            <value>
                <fullName>1379</fullName>
            </value>
            <value>
                <fullName>1381</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - Civil Service</fullName>
            </value>
            <value>
                <fullName>4 - Exempt</fullName>
            </value>
            <value>
                <fullName>7 - Salary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/X607__c.field-meta.xml
<CustomField>
    <fullName>X607__c</fullName>
    <label>607 #</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>HR - Lookup to HR unit names</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X607__c/X607__c.object-meta.xml
<CustomObject>
    <description>HR - Change in Positions - SCO Form 607</description>
    <label>607</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>607 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>607s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X607__c/fields/Form_1__c.field-meta.xml
<CustomField>
    <fullName>Form_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Originating Form 1</label>
    <referenceTo>Form_1__c</referenceTo>
    <relationshipLabel>607s</relationshipLabel>
    <relationshipName>X607s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X607__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Proposed New</fullName>
            </value>
            <value>
                <fullName>Extension of Present</fullName>
            </value>
            <value>
                <fullName>Reclassification</fullName>
            </value>
            <value>
                <fullName>Abolishment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Reporting Unit Change</fullName>
            </value>
            <value>
                <fullName>Reestablish</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
            <value>
                <fullName>Combine</fullName>
            </value>
            <value>
                <fullName>Disencumbrance</fullName>
            </value>
            <value>
                <fullName>Encumbrance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/X607_Position_Modification__c.object-meta.xml
<CustomObject>
    <description>HR - Change in Positions</description>
    <label>607 Position Modification</label>
    <nameField>
        <displayFormat>607PM-{00000000}</displayFormat>
        <label>Position Modification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>607 Position Modifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/X607_Position_Modification__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>607 Position Modifications</relationshipLabel>
    <relationshipName>X607_Position_Modifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>607 Position Modifications</relationshipLabel>
    <relationshipName>X607_Position_Modifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <label>Serial #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Modification</fullName>
            </value>
            <value>
                <fullName>Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>607 Position Modifications</relationshipLabel>
    <relationshipName>X607_Position_Modifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X607_Position_Modification__c/fields/X607__c.field-meta.xml
<CustomField>
    <fullName>X607__c</fullName>
    <label>607</label>
    <referenceTo>X607__c</referenceTo>
    <relationshipName>X607_Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/form1_Extension.cls
public with sharing class form1_Extension {
    
    public Form_1__c form1 {get;set;}

    public form1_Extension(apexPages.standardController controller){
        form1 = (Form_1__c)controller.getRecord();
    }
    
    public PageReference create607OnLoad(){
        /*if ( form1 == null || form1.Id == null ){
            Id i = apexPages.currentPage().getParameters().get('id');
            form1 = [Select Id, Classification__c, /*Position__c, Unit__c, Serial__c from Form_1__c where Id = :i limit 1];
        }
        x607__c x607 = new x607__c();
        x607.Form_1__c = form1.Id;
        insert x607;
        
        x607_Position_Modification__c pm = new x607_Position_Modification__c();
        pm.X607__c = x607.Id;
        //pm.Position__c = form1.Position__c;
        pm.Type__c = 'Modification';
        pm.Classification__c = form1.Classification__c;
        pm.Unit__c = form1.Unit__c;
        pm.Serial__c = form1.Serial__c;
        insert pm;
        
        PageReference p = new PageReference('/'+x607.Id);
        p.setRedirect(true);
        return p;*/
        
        if(form1.Id != null) {
            PageReference p = page.form607;
            p.getParameters().put('fid',form1.Id);
            p.setRedirect(true);
            return p;
        }
        else {
            return null;
        }
    }

}