force-app/main/default/objects/Online_Claim_Draft__c/Online_Claim_Draft__c.object-meta.xml
<CustomObject>
    <label>Online Claim Draft</label>
    <nameField>
        <displayFormat>OWCD-{0000000000}</displayFormat>
        <label>Online Claim Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Claim Drafts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Online_Claim_Draft__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Online Claim Drafts</relationshipLabel>
    <relationshipName>Online_Claim_Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Online_Claim_Draft__c/fields/Draft_JSON__c.field-meta.xml
<CustomField>
    <fullName>Draft_JSON__c</fullName>
    <label>Draft JSON</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Online_Claim_Draft__c/fields/Section_Id__c.field-meta.xml
<CustomField>
    <fullName>Section_Id__c</fullName>
    <label>Section Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OnlineWageClaimDraftControllerTest.cls
@isTest
public class OnlineWageClaimDraftControllerTest {
    @testSetup static void setUpMethod() {
        Online_Claim_Draft__c owcDraftList = new Online_Claim_Draft__c();
        owcDraftList.Section_Id__c = '1';
        insert owcDraftList;
    }
    @istest 
    public static void getDraftRecordsTest(){
        List<Online_Claim_Draft__c>  owcDraftListGetRecord  = [SELECT Id, Name, Draft_JSON__c, Section_Id__c, Case_Management__c FROM Online_Claim_Draft__c];
        Test.startTest();
        List<OnlineWageClaimDraftController.owcDraftWrapper>  getReturnList = OnlineWageClaimDraftController.getDraftRecords();
        Test.stopTest();
        System.assert(getReturnList.size()>0);
        System.assertEquals(getReturnList.size(), owcDraftListGetRecord.size());
    }
}