force-app/main/default/objects/Registration_Account__c/Registration_Account__c.object-meta.xml
<CustomObject>
    <description>Staging object used to collect Company/Account information on Registration forms.</description>
    <label>Registration Account</label>
    <nameField>
        <displayFormat>RA-{000000000}</displayFormat>
        <label>Registration Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Account__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Map to Email__c on Account</description>
    <inlineHelpText>DLSE uses this to communicate with Applicant.</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/UpdateRegistrationAccountEmailBatch.cls
global class UpdateRegistrationAccountEmailBatch implements Database.Batchable<sObject> { 
   
    global Database.QueryLocator start(Database.BatchableContext info){
    
        String q;
        
        if(Test.isRunningTest())
        {
            q = 'Select Id, Email_Address__c from Registration_Account__c where Email_Address__c != \'\' and (not Email_Address__c like \'%.uat%\') limit 1' ;
        } else 
        {
            q = 'Select Id, Email_Address__c from Registration_Account__c where Email_Address__c != \'\' and (not Email_Address__c like \'%.uat%\') ' ;    
        }
        return Database.getQueryLocator(q);
    }
    
    global void execute(Database.BatchableContext info, List<sObject> scopeX){
    
        String sandboxName;

        List<Organization> orgsList = [SELECT id, Name, isSandbox, instancename FROM Organization limit 1];
        if (orgsList != null)
        {
            for (Organization org : orgsList)
            {
                if (org.isSandbox)
                {
                    sandboxName = URL.getOrgDomainURL().getHost().substringBetween('--','.').toLowerCase();
                }
            }
        }
        
        List<Registration_Account__c> scope = (List<Registration_Account__c>)scopeX;
        for(Registration_Account__c ci : scope) {
             if (sandboxName != null)
             {
             	ci.Email_Address__c = ci.Email_Address__c + '.' + sandboxName;                 
             }
        }
        update scope; 
    }
    
    global void finish(Database.BatchableContext bc) {
    }    
}