force-app/main/default/objects/A_Config_Details__mdt/A_Config_Details__mdt.object-meta.xml
<CustomObject>
    <label>A+ Config Details</label>
    <pluralLabel>A+ Config Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/A_Config_Details__mdt/fields/A_Configuration__c.field-meta.xml
<CustomField>
    <fullName>A_Configuration__c</fullName>
    <label>A+ Configuration</label>
    <referenceTo>A_Configuration__mdt</referenceTo>
    <relationshipLabel>A+ Config Details</relationshipLabel>
    <relationshipName>A_Config_Details</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/A_Config_Details__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A_Configuration__mdt/A_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>A+ Configuration</label>
    <pluralLabel>A+ Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/A_Configuration__mdt/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A_Configuration__mdt/fields/Record_Type_API_Names__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_API_Names__c</fullName>
    <description>Record Type API Names (Comma seperated)</description>
    <inlineHelpText>Record Type API Names (Comma seperated)</inlineHelpText>
    <label>Record Type API Names</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/APlus_Json__c.field-meta.xml
<CustomField>
    <fullName>APlus_Json__c</fullName>
    <label>APlus Json</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Submitted__c</fullName>
    <label>Date Submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Primary_Document__c.field-meta.xml
<CustomField>
    <fullName>Primary_Document__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To signify the main document submitted for PAGA cases</description>
    <label>Primary Document</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Id__c</fullName>
    <label>Related Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Release_to_Public__c.field-meta.xml
<CustomField>
    <fullName>Release_to_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Release to Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Share_Point_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Share_Point_Item_Id__c</fullName>
    <label>Share Point Item Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Sharepoint_File_Status__c.field-meta.xml
<CustomField>
    <fullName>Sharepoint_File_Status__c</fullName>
    <label>Sharepoint File Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Sharepoint_File_Upload_Error__c.field-meta.xml
<CustomField>
    <fullName>Sharepoint_File_Upload_Error__c</fullName>
    <label>Sharepoint File Upload Error</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attorney_Client_Privilege__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Client_Privilege__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is subject to attorney-client privilege.</inlineHelpText>
    <label>Attorney-Client Privilege</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is considered confidential</inlineHelpText>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Submitted__c</fullName>
    <inlineHelpText>When was this form first officially submitted?</inlineHelpText>
    <label>Date Submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is not subject to PRA requests</inlineHelpText>
    <label>Not Subject to PRA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Primary_document__c.field-meta.xml
<CustomField>
    <fullName>Primary_document__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to track the primary document in order to limit the number of notification emails sent for multiple document uploads per submission.</description>
    <label>Primary document</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OWCUpdateAPlusSubDetail.cls
public class OWCUpdateAPlusSubDetail {
    public static List<Attachments_New__c> attachPlusObj;
    
    @InvocableMethod
    public static void updateAPlusSubDetail(List<Attachments_Plus__c> attachmentObj){
        // Rollback to here if any errors occuring in the following
        System.Savepoint sp = Database.setSavepoint();
        try{
            List<OWCServiceUtility.attachmentPlusWrapperObj> attPlusObj;
            Set<Id> contentDocIds = new Set<Id>();
            Set<Id> attachPlusIds = new Set<Id>();
            List<Attachments_New__c> updatedAttachRecs = new List<Attachments_New__c>();
            List<OWCServiceUtility.attachmentPlusWrapperObj> attachPlusDataCreate = new List<OWCServiceUtility.attachmentPlusWrapperObj>();
            List<Attachments_New__c> attachPlusToBeUpdated = new List<Attachments_New__c>();
            A_Configuration__mdt aConfigurations;
            A_Config_Details__mdt aConfigConfidentialObj;
            A_Config_Details__mdt aConfigPrivilegeObj;
            A_Config_Details__mdt aConfigPRAObj;
            List<ContentDocumentLink> allCDLs;
            
            List<ContentDocumentLink> cdls = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink
                                              WHERE LinkedEntityId =: attachmentObj[0].Id LIMIT 1];
            
            if(cdls != null && cdls.size() > 0){
                allCDLs = [SELECT Id, LinkedEntityId, ContentDocumentId 
                           FROM ContentDocumentLink 
                           WHERE ContentDocumentId =: cdls[0].ContentDocumentId];
            }
            
            for(ContentDocumentLink cdlObj : allCDLs){
                if(((String) cdlObj.LinkedEntityId).startsWith('a4C')){
                    attachPlusIds.add(cdlObj.LinkedEntityId);
                }
            }
            
            Map<Id, Attachments_New__c> attachNewMap = new Map<Id, Attachments_New__c>([SELECT Id, Name, File_Name__c, File_Type__c, Related_Id__c, Date_Submitted__c, 
                                                                                        Primary_Document__c, APlus_Json__c, Short_Description__c, 
                                                                                        Release_to_Public__c, Share_Point_Item_Id__c, 
                                                                                        Sharepoint_File_Status__c, Sharepoint_File_Upload_Error__c 
                                                                                        FROM Attachments_New__c WHERE Id IN: attachPlusIds]);
                        
            for(ContentDocumentLink cdlObj : allCDLs){
                if(((String) cdlObj.LinkedEntityId).startsWith('a4C')){
                    Attachments_New__c attachObj = attachNewMap.get(cdlObj.LinkedEntityId);
                    
                    if(String.isNotBlank(attachObj.APlus_Json__c)){
                        //Update A+ data record for PAGA
                        attPlusObj = (List<OWCServiceUtility.attachmentPlusWrapperObj>) JSON.deserialize(attachObj.APlus_Json__c, List<OWCServiceUtility.attachmentPlusWrapperObj>.class);
                        for(OWCServiceUtility.attachmentPlusWrapperObj attData : attPlusObj){
                            if(attData.fieldAPIName == 'File_Name' || attData.fieldAPIName == 'Description' || attData.fieldAPIName == 'Private'){
                                attachPlusDataCreate.add(new OWCServiceUtility.attachmentPlusWrapperObj(attData.fieldAPIName, attData.fieldAPIName, attData.value, ''));
                            }
                        }
                    }
                    
                    //Create A+ data record for PAGA
                    Map<String, A_Configuration__mdt> aConfigutaionMap = A_Configuration__mdt.getAll();
                    for(A_Configuration__mdt aConfigObj : aConfigutaionMap.values()){
                        if(aConfigObj.Record_Type_API_Names__c.contains('PAGA') && aConfigObj.File_Type__c == attachObj.File_Type__c){
                            aConfigurations = aConfigObj;
                            break;
                        }
                    }
                    System.debug('attachObj.File_Type__c ::: '+attachObj.File_Type__c);
                    System.debug('attachObj ::: '+attachObj);
                    System.debug('aConfigurations ::: '+aConfigurations);
                    Map<String, A_Config_Details__mdt> aConfigDetailsMap = A_Config_Details__mdt.getAll();
                    System.debug('aConfigurations ::: '+aConfigurations);
                    for(A_Config_Details__mdt aCongiDetailObj : aConfigDetailsMap.values()){
                        System.debug('aCongiDetailObj ::: '+aCongiDetailObj);
                        if((aConfigurations != null) && (aCongiDetailObj.A_Configuration__c == aConfigurations.Id) && (aCongiDetailObj.Field_Name__c.contains('Confidential'))){
                            aConfigConfidentialObj = aCongiDetailObj;
                            break;
                        }
                    }
                    
                    for(A_Config_Details__mdt aCongiDetailObj : aConfigDetailsMap.values()){
                        if((aConfigurations != null) && (aCongiDetailObj.A_Configuration__c == aConfigurations.Id) && (aCongiDetailObj.Field_Name__c.contains('Privilege'))){
                            aConfigPrivilegeObj = aCongiDetailObj;
                            break;
                        }
                    }
                    
                    for(A_Config_Details__mdt aCongiDetailObj : aConfigDetailsMap.values()){
                        if((aConfigurations != null) && (aCongiDetailObj.A_Configuration__c == aConfigurations.Id) && (aCongiDetailObj.Field_Name__c.contains('PRA'))){
                            aConfigPRAObj = aCongiDetailObj;
                            break;
                        }
                    }
                    
                    //Create A + Data for Privileged doc
                    if(aConfigPrivilegeObj != null){
                        attachPlusDataCreate.add(new OWCServiceUtility.attachmentPlusWrapperObj(aConfigPrivilegeObj.QualifiedApiName, aConfigPrivilegeObj.QualifiedApiName, (attachmentObj[0].Attorney_Client_Privilege__c) ? 'true' : 'false', ''));
                    }
                    
                    //Create A + Data for PRA doc
                    if(aConfigConfidentialObj != null){
                        attachPlusDataCreate.add(new OWCServiceUtility.attachmentPlusWrapperObj(aConfigConfidentialObj.QualifiedApiName, aConfigConfidentialObj.QualifiedApiName, (attachmentObj[0].Confidential__c) ? 'true' : 'false', ''));
                    }
                    
                    //Create A + Data for Confidential doc
                    if(aConfigPRAObj != null){
                        attachPlusDataCreate.add(new OWCServiceUtility.attachmentPlusWrapperObj(aConfigPRAObj.QualifiedApiName, aConfigPRAObj.QualifiedApiName, (attachmentObj[0].Not_Subject_to_PRA__c) ? 'true' : 'false', ''));
                    }
                    
                    attachObj.APlus_Json__c = (attachPlusDataCreate != null && attachPlusDataCreate.size() > 0) ? JSON.serialize(attachPlusDataCreate) : '';
                    attachPlusToBeUpdated.add(attachObj);
                }
            }
            
            if(attachPlusToBeUpdated != null && attachPlusToBeUpdated.size() > 0){
                update attachPlusToBeUpdated;
            }
            
            for(ContentDocumentLink cdlObj : allCDLs){
                if(((String) cdlObj.LinkedEntityId).startsWith('a4C')){
                    System.debug('attachmentObj ::: '+attachmentObj[0]);
                    Attachments_New__c attachObj = new Attachments_New__c();
                    attachObj.Date_Submitted__c = attachmentObj[0].Date_Submitted__c;
                    attachObj.File_Type__c = attachmentObj[0].Type__c;
                    attachObj.Primary_Document__c = attachmentObj[0].Primary_document__c;
                    attachObj.Related_Id__c = attachmentObj[0].Record_ID__c;
                    attachObj.Id = cdlObj.LinkedEntityId;
                    updatedAttachRecs.add(attachObj);
                }
            }
            
            if(updatedAttachRecs != null && updatedAttachRecs.size() > 0){
                update updatedAttachRecs;
            }
        }
        catch(Exception ex){
            System.debug('Exception ::: '+ex.getMessage() + 'Line Number ::: '+ex.getLineNumber());
            // Rollback everything done up until this point
            Database.rollback(sp);  
        }
    }
    
}