force-app/main/default/objects/Claimant_Confirmation__c/Claimant_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Claimant Confirmation</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Claimant Confirmation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claimants Confirmation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claimant_Confirmation__c/fields/Case_Promoted__c.field-meta.xml
<CustomField>
    <fullName>Case_Promoted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case Promoted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claimant_Confirmation__c/fields/Claimant_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Confirmation__c</fullName>
    <label>Claimant Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Deny</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Date_of_Docket__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Docket__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date of Docket</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Garment Cases</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Office_Email__c.field-meta.xml
<CustomField>
    <fullName>Office_Email__c</fullName>
    <description>For "LaborComm...: office email in Conga docs.</description>
    <label>Office Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Office__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Identifies an office as a garment office</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Identifies offices as WAGE</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/classes/OWCThirdPartyFileUploadWebService.cls
/*
* Name: OWCThirdPartyFileUploadWebService
* Description: Used to upload the claimant confirmation from the third party system.
* Primary Record: Content Document
* Related Records: Content Document Link, Content Version
*/ 
@RestResource(urlMapping='/ClaimantConfirmationAPI/*')
global class OWCThirdPartyFileUploadWebService {
    public static DIR_Case__c caseObj;
    public static String caseNumber;
    public static String communityUserId;
    public static String contenttype;
    public static String name;
    public static String jsonString;
    public static String fieldValidationError;
    public static String fileExtension;
    
    
    @HttpPost
    global static void uploadDocument()
    {   
        OWCThirdPartyModel.ClaimantConfirmUploadResponseWrapper claimantWrapObj = new OWCThirdPartyModel.ClaimantConfirmUploadResponseWrapper();
        RestRequest responseObj = RestContext.request;
        String requestBody = responseObj.requestBody.toString();
        try
        {
            if(String.isNotBlank(requestBody)){
                //Deserialize the third party response
                Map<String, Object> responseWrapper = (Map<String, Object>) JSON.deserializeUntyped(requestBody);
                caseNumber = (String) responseWrapper.get('caseNumber');
                communityUserId = (String) responseWrapper.get('communityUserId');
                contenttype = (String) responseWrapper.get('contenttype');
                name = (String) responseWrapper.get('name');
                jsonString = (String) responseWrapper.get('versionData');
                fileExtension = (String) responseWrapper.get('fileExtension');
                
                //Validate third party response
                //OWCThirdPartyValidationCheckerController.validateCCAPIResponse(caseNumber, communityUserId);
                if(String.isNotBlank(fieldValidationError)){
                    claimantWrapObj.isSuccess = false;
                    claimantWrapObj.message = fieldValidationError;
                }
                else{
                    String wca_Case_RecordType_Id = OWCConstants.WCA_CASE_RECORD_TYPE_ID;
                    String garment_Case_RecordType_Id = OWCConstants.Garment_CASE_RECORD_TYPE_ID;
                    String garment_Office_Los_Angeles = OWCConstants.Garment_Office_Los_Angeles;
                    
                    //Get the case management record
                    if(String.isNotBlank(caseNumber)){
                        caseObj = [SELECT Id, Name, Case_Number__c, Office__r.Name, Office__r.Office_Email__c,
                                   Applicant_Type__c FROM DIR_Case__c
                                   WHERE Case_Number__c =: caseNumber LIMIT 1];
                    }
                    
                    //Insert ContentVersion
                    ContentVersion cVersion = new ContentVersion();
                    cVersion.PathOnClient = name + fileExtension;//File name with extention
                    cVersion.Title = name;//Name of the file
                    cVersion.VersionData = EncodingUtil.base64Decode(jsonString);//File content
                    Insert cVersion;
                    
                    //After saved the Content Verison, get the ContentDocumentId
                    Id conDocument = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cVersion.Id].ContentDocumentId;
                    
                    //Insert ContentDocumentLink
                    ContentDocumentLink cDocLink = new ContentDocumentLink();
                    cDocLink.ContentDocumentId = conDocument;//Add ContentDocumentId
                    cDocLink.LinkedEntityId = caseObj.Id;//Add attachment parentId
                    Insert cDocLink;
                    
                    //update the case record.
                    if(caseObj.Applicant_Type__c == 'Representative Garment'){
                        //emailTemplateName = 'Claim Email Reply Confirm Garment';
                        //update case RecordType to Garment
                        caseObj.recordTypeId = garment_Case_RecordType_Id;
                        caseObj.Office__c = garment_Office_Los_Angeles;
                    } else {
                        // CONFIRM Response
                        //emailTemplateName = 'Claim Email Reply Confirm';
                        //update case RecordType to WCA
                        caseObj.recordTypeId = wca_Case_RecordType_Id;
                        caseObj = OWCServiceUtility.populateOfficeOnCM(caseObj);
                    }
                    //create the Claimant Confirmation record
                    Claimant_Confirmation__c  cc = new Claimant_Confirmation__c ();
                    cc.Claimant_Confirmation__c = 'Confirm';
                    cc.Case_Promoted__c = true;
                    caseObj.Date_of_Docket__c = OWCOnlineClaimFormService.nextBusinessDate();
                    /*
                    //get Current Time as per Org Time Zone
                    DateTime currenTime = System.now();
                    // Get the default business hours
                    BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
                    // Find whether the time is within the default business hours
                    Boolean isWithin= BusinessHours.isWithin(bh.id, currenTime);
                    //lets set the next business datetime if current time is outside of business hours
                    if(isWithin){
                        caseObj.Date_of_Docket__c = currenTime.dateGMT();
                    }
                    else{
                        Datetime nextStart = BusinessHours.nextStartDate(bh.id, currenTime);
                        nextStart = nextStart;//OWCOnlineClaimFormService.getTimeInOrgTimeZone(nextStart);
                        caseObj.Date_of_Docket__c = nextStart.dateGMT();
                    }
                    */
                    update caseObj;
                    insert cc;
                    
                    DIR_Case__c updatedCase = [SELECT Id, Name, Case_Number__c, Office__r.Name, Office__r.Office_Email__c,
                                   Applicant_Type__c FROM DIR_Case__c
                                   WHERE Case_Number__c =: caseNumber LIMIT 1];
                    
                    claimantWrapObj.isSuccess = true;
                    claimantWrapObj.message = 'Success';
                    claimantWrapObj.districtOffice = updatedCase.Office__r.Name;
                    claimantWrapObj.officeEmail = updatedCase.Office__r.Office_Email__c;
                    claimantWrapObj.documentId = conDocument;
                }
            }
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(claimantWrapObj));
        }
        catch(Exception e)
        {
            System.debug('exception ::: '+e.getMessage());
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(claimantWrapObj));
        }
    }
}