force-app/main/default/objects/Claimant_Confirmation__c/Claimant_Confirmation__c.object-meta.xml
<CustomObject>
    <label>Claimant Confirmation</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Claimant Confirmation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claimants Confirmation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claimant_Confirmation__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Claimants Confirmation</relationshipLabel>
    <relationshipName>Claimants_Confirmation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claimant_Confirmation__c/fields/Case_Promoted__c.field-meta.xml
<CustomField>
    <fullName>Case_Promoted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case Promoted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claimant_Confirmation__c/fields/Claimant_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Confirmation__c</fullName>
    <label>Claimant Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Deny</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claimant_Confirmation__c/fields/Claimant_response__c.field-meta.xml
<CustomField>
    <fullName>Claimant_response__c</fullName>
    <label>Claimant response</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Advocate_Name_in_Text__c.field-meta.xml
<CustomField>
    <fullName>Advocate_Name_in_Text__c</fullName>
    <label>Advocate Name in Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Claimant_Name_in_Text__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Name_in_Text__c</fullName>
    <label>Claimant Name in Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <inlineHelpText>County is used to prepare official documents</inlineHelpText>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outside CA</fullName>
            </value>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>Amador</fullName>
            </value>
            <value>
                <fullName>Butte</fullName>
            </value>
            <value>
                <fullName>Calaveras</fullName>
            </value>
            <value>
                <fullName>Colusa</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Del Norte</fullName>
            </value>
            <value>
                <fullName>El Dorado</fullName>
            </value>
            <value>
                <fullName>Fresno</fullName>
            </value>
            <value>
                <fullName>Glenn</fullName>
            </value>
            <value>
                <fullName>Humboldt</fullName>
            </value>
            <value>
                <fullName>Imperial</fullName>
            </value>
            <value>
                <fullName>Inyo</fullName>
            </value>
            <value>
                <fullName>Kern</fullName>
            </value>
            <value>
                <fullName>Kings</fullName>
            </value>
            <value>
                <fullName>Lake</fullName>
            </value>
            <value>
                <fullName>Lassen</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Madera</fullName>
            </value>
            <value>
                <fullName>Marin</fullName>
            </value>
            <value>
                <fullName>Mariposa</fullName>
            </value>
            <value>
                <fullName>Mendocino</fullName>
            </value>
            <value>
                <fullName>Merced</fullName>
            </value>
            <value>
                <fullName>Modoc</fullName>
            </value>
            <value>
                <fullName>Mono</fullName>
            </value>
            <value>
                <fullName>Monterey</fullName>
            </value>
            <value>
                <fullName>Napa</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Date_of_Docket__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Docket__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date of Docket</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/DIR_Office_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>DIR_Office_Phone_Number__c</fullName>
    <description>Designed for use in the wage claim email notification template (when a claimant registers a claim).</description>
    <formula>Office__r.Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DIR Office Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/DIR_WCA_Office_Address__c.field-meta.xml
<CustomField>
    <fullName>DIR_WCA_Office_Address__c</fullName>
    <description>This field is referenced in Email template which is sent out to WCA claim's Advocate who submits claim form via form assembly or his email is supplied in the claim</description>
    <formula>Office__r.Address_1__c + ", " + Office__r.Address_2__c + " " + Office__r.City__c + ", " + Office__r.State__c + " " + Office__r.Zip_Code__c</formula>
    <label>DIR WCA Office Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Related_Party_Employee_Email__c.field-meta.xml
<CustomField>
    <fullName>Related_Party_Employee_Email__c</fullName>
    <label>Related Party Employee Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Related_Party_Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Party_Employer_Name__c</fullName>
    <label>Related Party Employer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Not Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Garment Cases</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>County of the BOFE/Wage office</description>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Identifies an office as a garment office</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Identifies offices as WAGE</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClaimantConfirmationEmailservice.cls
global class ClaimantConfirmationEmailservice implements Messaging.InboundEmailHandler {
    public static String templateLang = 'English';
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email,Messaging.InboundEnvelope envelop){
        String wca_Case_RecordType_Id = OWCConstants.WCA_CASE_RECORD_TYPE_ID;
        String garment_Case_RecordType_Id = OWCConstants.Garment_CASE_RECORD_TYPE_ID;
        String garment_Office_Los_Angeles = OWCConstants.Garment_Office_Los_Angeles;
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        String emailTemplateName = '';
        String accname = email.fromName;
        system.debug('fromAddress: '+email.fromAddress);
        String emailBody = email.plainTextBody;
        emailBody = emailBody.toLowerCase();
        String subject = email.Subject;
        system.debug('subject: '+subject);
        system.debug('emailBody: '+emailBody);
        if(subject.containsIgnoreCase('Confirmation') || subject.containsIgnoreCase('Confirmación')){
            String caseName = subject.substringBetween('(', ')');
            List<DIR_Case__c>  cseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,
                                          Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, 
                                          Related_Party_Employee_Email__c, Status__c,County__c,Office__c,
                                          Date_of_Docket__c,Applicant_Type__c  
                                          FROM DIR_Case__c 
                                          WHERE Name = : caseName AND Status__c = 'Not Confirmed'];
            if(!cseList.isEmpty() && cseList.size() >0){
                if(emailBody.containsIgnoreCase('email.fromAddress')){
                    emailBody = emailBody.split(email.fromAddress.toLowerCase())[0];
                } else if(emailBody.containsIgnoreCase('hello')){
                    emailBody = emailBody.split('hello')[0];
                } else if(emailBody.containsIgnoreCase('wrote')){
                    emailBody = emailBody.split('wrote')[0];
                } else if(emailBody.containsIgnoreCase('noreply@salesforce.com')){
                    emailBody = emailBody.split('noreply@salesforce.com')[0];
                    
                }
                
                //create the Claimant Confirmation record
                Claimant_Confirmation__c  cc = new Claimant_Confirmation__c ();
                cc.Case_Management__c = cseList[0].Id;
                if(emailBody.length() > 10000){
                    cc.Claimant_response__c = emailBody.substring(0, 9999); 
                } else{
                    cc.Claimant_response__c = emailBody; 
                } 
                if(subject.containsIgnoreCase('Confirmation') || subject.containsIgnoreCase('confirmation')){
                    emailBody = emailBody.remove('Confirmation');
                    emailBody = emailBody.remove('confirmation');
                    
                    system.debug('email.fromAddress: '+email.fromAddress);
                    Integer confirmIndex = emailBody.indexOfIgnoreCase('confirm');
                    Integer denyIndex = emailBody.indexOfIgnoreCase('deny');
                    //Integer wroteIndex = emailBody.split('wrote')[0];
                    system.debug('emailBody: '+emailBody);
                    //System.debug(confirmIndex + ' -- ' + denyIndex + ' -- '+ wroteIndex);
                    if(emailBody.containsIgnoreCase('confirm') && emailBody.containsIgnoreCase('deny')){
                        // NOT VALID Response
                        emailTemplateName = 'Claim Email Reply INVALID';
                        insert cc;
                        
                        List<DIR_Case__c>  caseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,recordTypeId,
                                                       Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, Related_Party_Employee_Email__c,
                                                       Status__c,Office__c,Office__r.Name,DIR_WCA_Office_Address__c,DIR_Office_Phone_Number__c 
                                                       FROM DIR_Case__c 
                                                       WHERE Id =: cseList[0].Id];
                        
                        // set auto reply mail to the end user.
                        OCEmailServiceUtility.sendAutoResponse(caseList, emailTemplateName, caseList[0].Related_Party_Employee_Email__c);
                        
                    }
                    else if((emailBody.containsIgnoreCase('confirm') ) ){
                        cseList[0].Status__c = 'New';
                        if(cseList[0].Applicant_Type__c == 'Representative Garment'){
                            emailTemplateName = 'Claim Email Reply Confirm Garment';
                            //update case RecordType to Garment
                            cseList[0].recordTypeId = garment_Case_RecordType_Id;
                            cseList[0].Office__c = garment_Office_Los_Angeles;
                        } else {
                            // CONFIRM Response
                            emailTemplateName = 'Claim Email Reply Confirm';
                            //update case RecordType to WCA
                            cseList[0].recordTypeId = wca_Case_RecordType_Id;
                            cseList[0] = OWCServiceUtility.populateOfficeOnCM(cseList[0]);
                        }
                        system.debug('emailTemplateName: '+emailTemplateName);
                        cc.Claimant_Confirmation__c = 'Confirm';
                        cc.Case_Promoted__c = true;
                        	
                        //get Current Time as per Org Time Zone
                        DateTime currenTime = System.now();
                        cseList[0].Date_of_Docket__c = OWCOnlineClaimFormService.nextBusinessDate();
                        /*
                        // Get the default business hours
                        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
                        // Find whether the time is within the default business hours
                        Boolean isWithin= BusinessHours.isWithin(bh.id, currenTime);
                        //lets set the next business datetime if current time is outside of business hours
                        
                        
                        if(isWithin){
                            cseList[0].Date_of_Docket__c = OWCOnlineClaimFormService.nextBusinessDate();
                        }
                        else{
                            Datetime nextStart = BusinessHours.nextStartDate(bh.id, currenTime);
                            nextStart = nextStart;//OWCOnlineClaimFormService.getTimeInOrgTimeZone(nextStart);
                            cseList[0].Date_of_Docket__c = nextStart.dateGMT();
                        }
                        */
                        update cseList[0];
                        insert cc;
                        
                        List<DIR_Case__c>  caseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,recordTypeId,
                                                       Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, Related_Party_Employee_Email__c,
                                                       Status__c,Office__c,Office__r.Name,DIR_WCA_Office_Address__c,DIR_Office_Phone_Number__c,
                                                       Closure_Disposition__c
                                                       FROM DIR_Case__c 
                                                       WHERE Id =: cseList[0].Id];
                        
                        // set auto reply mail to the end user.
                        OCEmailServiceUtility.sendAutoResponse(caseList, emailTemplateName,caseList[0].Related_Party_Employee_Email__c);
                        
                    }else if(emailBody.containsIgnoreCase('deny') ) {   //(denyIndex < confirmIndex)
                        // DENY Response
                        emailTemplateName = 'Claim Email Reply Deny';
                        cc.Claimant_Confirmation__c = 'Deny';
                        cc.Case_Promoted__c = false;
                        cseList[0].Closure_Disposition__c = 'Closed for Lack of Claimant Confirmation';
                        cseList[0].Case_Closed_Date__c = Date.today();
                        cseList[0].Status__c = 'Closed';
                        cseList[0].Sent_Confirmation_Email__c = true;
                        update cseList[0];
                        insert cc;
                        
                        List<DIR_Case__c>  caseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,recordTypeId,
                                                       Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, Related_Party_Employee_Email__c,
                                                       Status__c,Office__c,Office__r.Name,DIR_WCA_Office_Address__c,DIR_Office_Phone_Number__c,
                                                       Related_Party_Advocate_Email__c
                                                       FROM DIR_Case__c 
                                                       WHERE Id =: cseList[0].Id];
                        
                        // set auto reply mail to the end user.
                        OCEmailServiceUtility.sendAutoResponse(caseList, emailTemplateName,caseList[0].Related_Party_Employee_Email__c);
                        
                        //send the Case Closer response to the Advocate
                        if(caseList[0].Related_Party_Advocate_Email__c != null){
                            OCEmailServiceUtility.sendAutoResponse(caseList, 'Advocate Email Reply Deny', caseList[0].Related_Party_Advocate_Email__c);  
                        }
                        
                    }
                    else {
                        // NOT VALID Response
                        emailTemplateName = 'Claim Email Reply INVALID';
                        insert cc;
                        
                        List<DIR_Case__c>  caseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,recordTypeId,
                                                       Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, Related_Party_Employee_Email__c,
                                                       Status__c,Office__c,Office__r.Name,DIR_WCA_Office_Address__c,DIR_Office_Phone_Number__c 
                                                       FROM DIR_Case__c 
                                                       WHERE Id =: cseList[0].Id];
                        
                        // set auto reply mail to the end user.
                        OCEmailServiceUtility.sendAutoResponse(caseList, emailTemplateName, caseList[0].Related_Party_Employee_Email__c);
                        
                        
                    }
                    system.debug('emailTemplateName: '+emailTemplateName);
                }
                else if(subject.containsIgnoreCase('Confirmación') || subject.containsIgnoreCase('confirmación')){
                    templateLang = 'es';
                    //for spanish	confirmación 
                    emailBody = emailBody.remove('Confirmación');
                    emailBody = emailBody.remove('confirmación');
                    system.debug('email.fromAddress: '+email.fromAddress);
                    Integer confirmIndex = emailBody.indexOfIgnoreCase('confirmar');
                    Integer denyIndex = emailBody.indexOfIgnoreCase('negar');
                    //Integer wroteIndex = emailBody.split('wrote')[0];
                    system.debug('emailBody: '+emailBody);
                    //System.debug(confirmIndex + ' -- ' + denyIndex + ' -- '+ wroteIndex);
                    if(emailBody.containsIgnoreCase('confirmar') && emailBody.containsIgnoreCase('negar')){
                        // NOT VALID Response
                        emailTemplateName = 'Claim Email Reply INVALID_es';
                        insert cc;
                        system.debug('todayDate:invalid '+emailBody);
                        List<DIR_Case__c>  caseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,recordTypeId,
                                                       Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, Related_Party_Employee_Email__c,
                                                       Status__c,Office__c,Office__r.Name,DIR_WCA_Office_Address__c,DIR_Office_Phone_Number__c 
                                                       FROM DIR_Case__c 
                                                       WHERE Id =: cseList[0].Id];
                        
                        // set auto reply mail to the end user.
						
                        OCEmailServiceUtility.sendAutoResponse(caseList, emailTemplateName, caseList[0].Related_Party_Employee_Email__c);
                        
                    }
                    else if((emailBody.containsIgnoreCase('confirmar') ) ){
                        //check for Garment
                        if(cseList[0].Applicant_Type__c == 'Representative Garment'){
                            emailTemplateName = 'Claim Email Reply Confirm_es Garment';
                        } else {
                            // CONFIRM Response
                            emailTemplateName = 'Claim Email Reply Confirm_es';
                        }
                        
                        cc.Claimant_Confirmation__c = 'Confirm';
                        cc.Case_Promoted__c = true;
                        cseList[0].Status__c = 'New';	
                        //get Current Time as per Org Time Zone
                        DateTime currenTime = System.now();
                        // Get the default business hours
                        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
                        // Find whether the time is within the default business hours
                        Boolean isWithin= BusinessHours.isWithin(bh.id, currenTime);
                        //lets set the next business datetime if current time is outside of business hours
                        cseList[0].Date_of_Docket__c = OWCOnlineClaimFormService.nextBusinessDate();
                        /*
                        if(isWithin){
                            cseList[0].Date_of_Docket__c = currenTime.dateGMT();
                        }
                        else{
                            Datetime nextStart = BusinessHours.nextStartDate(bh.id, currenTime);
                            nextStart = nextStart;//OWCOnlineClaimFormService.getTimeInOrgTimeZone(nextStart);
                            cseList[0].Date_of_Docket__c = nextStart.dateGMT();
                        }
                        */
                        cseList[0] = OWCServiceUtility.populateOfficeOnCM(cseList[0]);
                        update cseList[0];
                        insert cc;
                        
                        List<DIR_Case__c>  caseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,recordTypeId,
                                                       Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, Related_Party_Employee_Email__c,
                                                       Status__c,Office__c,Office__r.Name,DIR_WCA_Office_Address__c,DIR_Office_Phone_Number__c,
                                                       Closure_Disposition__c
                                                       FROM DIR_Case__c 
                                                       WHERE Id =: cseList[0].Id];
                        
                        // set auto reply mail to the end user.
                        OCEmailServiceUtility.sendAutoResponse(caseList, emailTemplateName,caseList[0].Related_Party_Employee_Email__c);
                        
                    }else if(emailBody.containsIgnoreCase('negar') ) {   //(denyIndex < confirmIndex)
                        // DENY Response
                        emailTemplateName = 'Claim Email Reply Deny_es';
                        cc.Claimant_Confirmation__c = 'Deny';
                        cc.Case_Promoted__c = false;
                        cseList[0].Closure_Disposition__c = 'Closed for Lack of Claimant Confirmation';
                        cseList[0].Case_Closed_Date__c = Date.today();
                        cseList[0].Status__c = 'Closed';
                        cseList[0].Sent_Confirmation_Email__c = true;
                        update cseList[0];
                        insert cc;
                        
                        List<DIR_Case__c>  caseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,recordTypeId,
                                                       Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, Related_Party_Employee_Email__c,
                                                       Status__c,Office__c,Office__r.Name,DIR_WCA_Office_Address__c,DIR_Office_Phone_Number__c,
                                                       Related_Party_Advocate_Email__c
                                                       FROM DIR_Case__c 
                                                       WHERE Id =: cseList[0].Id];
                        
                        // set auto reply mail to the end user.
                        OCEmailServiceUtility.sendAutoResponse(caseList, emailTemplateName,caseList[0].Related_Party_Employee_Email__c);
                        
                        //send the Case Closer response to the Advocate
                        if(caseList[0].Related_Party_Advocate_Email__c != null){
                            OCEmailServiceUtility.sendAutoResponse(caseList, 'Advocate Email Reply Deny', caseList[0].Related_Party_Advocate_Email__c);  
                        }
                        
                    }
                    else {
                        // NOT VALID Response
                        emailTemplateName = 'Claim Email Reply INVALID_es';
                        insert cc;
                        
                        List<DIR_Case__c>  caseList = [SELECT Id,Case_Number__c,Name,Advocate_Name_in_Text__c ,recordTypeId,
                                                       Related_Party_Employer_Name__c,Claimant_Name_in_Text__c, Related_Party_Employee_Email__c,
                                                       Status__c,Office__c,Office__r.Name,DIR_WCA_Office_Address__c,DIR_Office_Phone_Number__c 
                                                       FROM DIR_Case__c 
                                                       WHERE Id =: cseList[0].Id];
                        
                        // set auto reply mail to the end user.
                        OCEmailServiceUtility.sendAutoResponse(caseList, emailTemplateName, caseList[0].Related_Party_Employee_Email__c);
                        
                        
                    }
                    system.debug('emailTemplateName: '+emailTemplateName);
                }
                
            }
            
        }
        return null;
    }
    
}