force-app/main/default/objects/Accounting_Code__c/Accounting_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the code mapping for accounting to set the codes based on industry, program, labor code for BOFE. Can be expanded for other coding by creating new record types, picklists, and page layouts where necessary. Lookups to this object performed when creating a case payment to code the payment. This occurs in the casePaymentAll trigger.</description>
    <label>Accounting Code</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Code ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounting_Code__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Car Wash</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Day Labor</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Garment</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Nail Salon</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicable_Accounting_Code__c/Applicable_Accounting_Code__c.object-meta.xml
<CustomObject>
    <description>Junction object between violation types and accounting codes to define the accounting codes that are applied on each violation type when a payment is made on a violation. Serves to define to which fund, pca, etc monies received apply when a payment is applied by accounting.</description>
    <label>Applicable Accounting Code</label>
    <nameField>
        <displayFormat>AAC-{00000}</displayFormat>
        <label>Applicable Accounting Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicable Accounting Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicable_Accounting_Code__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>text( Accounting_Code__r.Industry__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicable_Accounting_Code__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <description>Links one or more codes to a violation type so that monies applied as payments to a violation type can be applied to the appropriate accounts</description>
    <inlineHelpText>Select the Violation Type for which the selected code is to apply</inlineHelpText>
    <label>Violation Type</label>
    <referenceTo>Violation_Type__c</referenceTo>
    <relationshipLabel>Applicable Accounting Codes</relationshipLabel>
    <relationshipName>Applicable_Accounting_Codes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/DIR_Accounting_Program__c.field-meta.xml
<CustomField>
    <fullName>DIR_Accounting_Program__c</fullName>
    <description>Some DLSE Programs are the same as others for the purpose of looking up DIR Accounting Codes.</description>
    <formula>"BOFE"</formula>
    <inlineHelpText>This field is used to find a DIR Accounting Code for a DLSE Program that is the same as another for the purpose of reporting to DIR Accounting. This field saves having to setup new Accounting Codes and Applicable Accounting Codes for a new DLSE Program.</inlineHelpText>
    <label>DIR Accounting Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer_Industry__c.field-meta.xml
<CustomField>
    <fullName>Employer_Industry__c</fullName>
    <formula>IF (NOT(ISBLANK(TEXT( Employer__r.Low_wage_Industry_Selection__c ))), TEXT( Employer__r.Low_wage_Industry_Selection__c ), "Not Specified")</formula>
    <label>Employer Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <label>Violation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Labor Relations</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Labor Code 3070 – 3098</fullName>
            </value>
            <value>
                <fullName>Child Labor</fullName>
            </value>
            <value>
                <fullName>Classified as Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Improper or Incomplete Wage Statements</fullName>
            </value>
            <value>
                <fullName>Improper payment form incl. NSF check</fullName>
            </value>
            <value>
                <fullName>Industrial Homework</fullName>
            </value>
            <value>
                <fullName>Kickbacks</fullName>
            </value>
            <value>
                <fullName>Lactation Accommodation (LC 1030‐1033)</fullName>
            </value>
            <value>
                <fullName>Licensing, Registration or Permit</fullName>
            </value>
            <value>
                <fullName>Meal and Rest Breaks</fullName>
            </value>
            <value>
                <fullName>Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Nonexempt Classified as Exempt</fullName>
            </value>
            <value>
                <fullName>Not paid for all hours worked</fullName>
            </value>
            <value>
                <fullName>Not Paid Wages Due on Termination</fullName>
            </value>
            <value>
                <fullName>Not providing required time off, other</fullName>
            </value>
            <value>
                <fullName>No Wage Statements</fullName>
            </value>
            <value>
                <fullName>No Workers’ Compensation</fullName>
            </value>
            <value>
                <fullName>Occupational SAFE HLTH (LC 6300 et seq)</fullName>
            </value>
            <value>
                <fullName>Other Notice or Posting or Recordkeeping</fullName>
            </value>
            <value>
                <fullName>Other Unpaid Wages</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Pay Discrim on basis of sex (LC1197.5)</fullName>
            </value>
            <value>
                <fullName>PMNT Reimbursement of Empl Expenses</fullName>
            </value>
            <value>
                <fullName>Public Works (Labor Code §§ 1720 – 1815)</fullName>
            </value>
            <value>
                <fullName>Retaliation - Protected Status Activity</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Tips or Gratuities</fullName>
            </value>
            <value>
                <fullName>Unfair Immigration Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the type of violation from the list of available violations</description>
    <label>Case Issue Type</label>
    <referenceTo>Violation_Type__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Violation_Accounting_Code__c/Violation_Accounting_Code__c.object-meta.xml
<CustomObject>
    <description>Joins together violations on cases to the accounting codes that apply based on the violation type. Used for creating reports for AR only. Table is populated via trigger on Case Violation.</description>
    <label>Violation Accounting Code</label>
    <nameField>
        <displayFormat>VAC-{0000000}</displayFormat>
        <label>Violation Accounting Code ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Violation Accounting Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Violation_Accounting_Code__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <formula>TEXT(Applicable_Accounting_Code__r.Accounting_Code__r.Industry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Violation_Type__c/Violation_Type__c.object-meta.xml
<CustomObject>
    <description>Holds the types of violations that are used on Case Management cases. Records here become "Case Violation" records when a violation is recorded by a deputy or inspector.</description>
    <label>Violation Type</label>
    <nameField>
        <label>Labor Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Violation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Violation_Type__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <description>Defines the form on which this violation should appear. Used within the violations vfp to group violations into an assessment. All violations created at the same time on a case with the same Citation Form are grouped into a single assessment</description>
    <inlineHelpText>Select the citation form that this violation should appear on. Note that this is for grouping purposes and may not be an actual citation. For example, a NTD would be a citation form even though a penalty may not be levied.</inlineHelpText>
    <label>Citation Form</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BOFE 240A</fullName>
            </value>
            <value>
                <fullName>BOFE 240B</fullName>
            </value>
            <value>
                <fullName>BOFE 335</fullName>
            </value>
            <value>
                <fullName>BOFE 336</fullName>
            </value>
            <value>
                <fullName>BOFE 8</fullName>
            </value>
            <value>
                <fullName>BOFE 812</fullName>
            </value>
            <value>
                <fullName>BOFE 814</fullName>
            </value>
            <value>
                <fullName>BOFE 815</fullName>
            </value>
            <value>
                <fullName>BOFE 816</fullName>
            </value>
            <value>
                <fullName>JEU 238</fullName>
            </value>
            <value>
                <fullName>JEU 238e</fullName>
            </value>
            <value>
                <fullName>LR 240A</fullName>
            </value>
            <value>
                <fullName>Notice to Discontinue - DLSE 84</fullName>
            </value>
            <value>
                <fullName>PW 240A</fullName>
            </value>
            <value>
                <fullName>PW 336</fullName>
            </value>
            <value>
                <fullName>NTD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseViolationAccountCodeAction.cls
public class CaseViolationAccountCodeAction extends TriggerAction {
 
   
    public boolean shouldRun;
    private Map<ID,Set<ID>> violationToAccountCodes;
    public CaseViolationAccountCodeAction(List<DIR_Violation__c> triggerList) {
        
        super(triggerList);
        
        Set<Id> caseIds = new Set<Id>();
    
        violationToAccountCodes = new Map<ID,Set<ID>>();
        Map<ID,ID> violationToViolationType =  new Map<ID,ID>();
        Set<ID> violationIDs = new Set<ID>();
        for (Sobject result: triggerList) {
            
            DIR_Violation__c violation= (DIR_Violation__c)result;
            
            if (violation.Violation_Type__c!=null) {
                violationIDs.add(violation.Violation_Type__c);
                violationToViolationType.put(violation.id,violation.Violation_Type__c);
            }
            
            if (violation.Case__c != null) {
                caseIds.add(violation.Case__c);
            }
        }
        
        Map<Id, DIR_Case__c> casesMap = new Map<Id, DIR_Case__c>([SELECT Id, Employer_Industry__c, DIR_Accounting_Program__c FROM DIR_Case__c WHERE Id IN :caseIds]);
        //get violationTypes 
        
        List<Applicable_Accounting_Code__c> acctCodes = [select id, Accounting_Code__c, Violation_Type__c, Active__c, Industry__c, Program__c from Applicable_Accounting_Code__c where Violation_Type__c in : violationIDs AND Active__c = true];
        Map<ID,List<Applicable_Accounting_Code__c>> violationTypeToAccountCodes = new Map<ID,List<Applicable_Accounting_Code__c>>();
        //map violationTypes to appropriate accountcodes
        for (Applicable_Accounting_Code__c code : acctCodes) {
            List<Applicable_Accounting_Code__c> codeIDs  =  (violationTypeToAccountCodes.containsKey(code.Violation_Type__c))? violationTypeToAccountCodes.get(code.Violation_Type__c): new List<Applicable_Accounting_Code__c>();
            codeIDs.add(code);
            
            //codeIDs.add(code.Accounting_Code__c);
            violationTypeToAccountCodes.put(code.Violation_Type__c,codeIDs);
        }
        //map violations to accountcodes
        violationToAccountCodes = new Map<ID,Set<ID>>();
        for (Sobject result: triggerList) {
            
            DIR_Violation__c violation= (DIR_Violation__c)result;
        
            if (violation.Violation_Type__c!=null) {
                violationToAccountCodes.put(violation.ID, new Set<Id>());
                if (violationTypeToAccountCodes.containsKey(violation.Violation_Type__c)) {
                    for (Applicable_Accounting_Code__c code : violationTypeToAccountCodes.get(violation.Violation_Type__c)) {
                        if (code.Industry__c == casesMap.get(violation.Case__c).Employer_Industry__c && code.Program__c == casesMap.get(violation.Case__c).DIR_Accounting_Program__c) {
                            violationToAccountCodes.get(violation.ID).add(code.Id);
                        }
                    }
                }
                
            }
        
        }
    }
    public override boolean shouldRunOnInsert() { 
    
        
        shouldRun = ( violationToAccountCodes.keyset().size()>0)? true: false;
        
        return shouldRun;
    } 
    public override boolean shouldRunOnDelete() { return false;} 
    
 
    public override boolean shouldRunOnUpdate() {  return false; } 
    
 
    public override void doAction() {
        
        List<Violation_Accounting_Code__c> vacList = new List<Violation_Accounting_Code__c>();
        
        for (ID vid : violationToAccountCodes.keySet()) {
            if (violationToAccountCodes.get(vid) != null) {
                for ( ID accId :violationToAccountCodes.get(vid)){
                    Violation_Accounting_Code__c vac = new Violation_Accounting_Code__c();
                    vac.Applicable_Accounting_Code__c = accId;
                    vac.Case_Violation__c = vid;
                    vacList.add(vac);
                }
            }
        }
        insert vacList;
        
     
    } 
    public static void runHandler() {
    
        if (trigger.isbefore) {
            return;
        }   
        
        if (trigger.isInsert) {
            CaseViolationAccountCodeAction action = new CaseViolationAccountCodeAction(Trigger.new);
            if (action.shouldRunOnInsert()) {
                action.doAction(); 
            }
            
        }   
      

    } 
    
}