force-app/main/default/objects/Inactive_Tracking__c/Inactive_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracks dir case's inactive duration</description>
    <label>Inactive &amp; Stay Tracking</label>
    <nameField>
        <displayFormat>IT-{00000}</displayFormat>
        <label>Inactive Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inactive &amp; Stay Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inactive_Tracking__c/fields/Comment_Entry__c.field-meta.xml
<CustomField>
    <fullName>Comment_Entry__c</fullName>
    <label>Comment Entry</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Inactive_Tracking__c/fields/Plaintiff_contact_information__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_contact_information__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plaintiff contact information</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inactive_Tracking__c/fields/Todays_Date_Hidden__c.field-meta.xml
<CustomField>
    <fullName>Todays_Date_Hidden__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Mimicking system.today() to use in DLRS roll up. Update nightly by class WCAbatchInactiveTrackingTodayUpdate</description>
    <label>Todays Date Hidden</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inactive_Tracking__c/fields/X1st_Attempt_Contact_Info__c.field-meta.xml
<CustomField>
    <fullName>X1st_Attempt_Contact_Info__c</fullName>
    <inlineHelpText>Enter the phone number/ email/ mailing address used to contact the Claimant on 1st attempt.</inlineHelpText>
    <label>1st Attempt Contact Info</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Inactive_Tracking__c/fields/X1st_Attempt_Date__c.field-meta.xml
<CustomField>
    <fullName>X1st_Attempt_Date__c</fullName>
    <inlineHelpText>Enter date of 1st attempt made to contact the Claimant.
The date first attempt must be a date on or after the creation of the Inactive Record, or no less than 5 days prior to the creation of the Inactive Record. If the first attempt date was made 5 days prior to the creation of the Inactive Record, the Senior deputy can modify the date</inlineHelpText>
    <label>1st Attempt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inactive_Tracking__c/fields/X1st_Attempt_Method__c.field-meta.xml
<CustomField>
    <fullName>X1st_Attempt_Method__c</fullName>
    <label>1st Attempt Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email &amp; Phone</fullName>
                <default>true</default>
                <label>Email &amp; Phone</label>
            </value>
            <value>
                <fullName>Email &amp; Mail</fullName>
            </value>
            <value>
                <fullName>Phone &amp; Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WCAbatchInactiveTrackingTodayUpdate_Test.cls
@isTest
public class WCAbatchInactiveTrackingTodayUpdate_Test {

   Static testMethod void testBatchExecuteMethod()
   {    
     	List<Inactive_Tracking__c> ITsList = new List<Inactive_Tracking__c>();       
       		for(Integer i=0; i < 5; i++){                
                Inactive_Tracking__c rec = new Inactive_Tracking__c();
                rec.X1st_Attempt_Date__c = date.parse('12/27/2024');
                rec.Todays_Date_Hidden__c = date.parse('12/27/2024');
                rec.X1st_Attempt_Method__c ='Email';
                rec.X1ST_Attempt_Contact_Info__c ='Mr.A';
                rec.Plaintiff_contact_information__c =TRUE;
                rec.Comment_Entry__c = 'test';
                ITsList.add(rec);
       		}
     	insert ITsList;       
        Test.startTest();       
        WCAbatchInactiveTrackingTodayUpdate ub =  new WCAbatchInactiveTrackingTodayUpdate();
        database.BatchableContext bc;
        ub.execute(bc, ITsList);
        database.executeBatch(ub,5);
        WCAInactiveTrackingTodayUpdateSchedule ITSsched = new WCAInactiveTrackingTodayUpdateSchedule(); 
		String sch = '0 0 23 * * ?';
		system.schedule('Test status Check', sch, ITSsched );
        Test.stopTest(); 

        List<Inactive_Tracking__c> ITchecklist = new List<Inactive_Tracking__c>();
        ITchecklist = [Select Todays_Date_Hidden__c from Inactive_Tracking__c where Todays_Date_Hidden__c = 2022-04-08];
  }
}