force-app/main/default/objects/Inactive_Tracking__c/Inactive_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracks dir case's inactive duration</description>
    <label>Inactive &amp; Stay Tracking</label>
    <nameField>
        <displayFormat>IT-{00000}</displayFormat>
        <label>Inactive Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inactive &amp; Stay Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inactive_Tracking__c/fields/Todays_Date_Hidden__c.field-meta.xml
<CustomField>
    <fullName>Todays_Date_Hidden__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Mimicking system.today() to use in DLRS roll up. Update nightly by class WCAbatchInactiveTrackingTodayUpdate</description>
    <label>Todays Date Hidden</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/WCAbatchInactiveTrackingTodayUpdate.cls
global class WCAbatchInactiveTrackingTodayUpdate implements Database.Batchable<sObject> {

    
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        //String RTnameFilters = 'Intake Stage';
             String query= 'SELECT Todays_Date_Hidden__c from Inactive_Tracking__c';

        //return Database.QueryLocator(query);
        return Database.getQueryLocator(query); 
    }
    
    global void execute(Database.BatchableContext bc, List<Inactive_Tracking__c> scope)
    {
        for(Inactive_Tracking__c InactiveTracking: scope)
        {

                InactiveTracking.Todays_Date_Hidden__c = system.today();
               
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext bc)
    {
        
    }
}