force-app/main/default/objects/Account/recordTypes/Court.recordType-meta.xml
<RecordType>
    <fullName>Court</fullName>
    <active>true</active>
    <label>Court</label>
</RecordType>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Judgement__c/Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment</label>
    <nameField>
        <displayFormat>J-{0}</displayFormat>
        <label>Judgment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgement__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipName>Judgements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Judgement_Date__c.field-meta.xml
<CustomField>
    <fullName>Judgement_Date__c</fullName>
    <inlineHelpText>Date the clerk entered the judgement</inlineHelpText>
    <label>Judgment Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending/Open</fullName>
            </value>
            <value>
                <fullName>Open/Unpaid</fullName>
            </value>
            <value>
                <fullName>Open - Partial Payment/Satisfaction</fullName>
            </value>
            <value>
                <fullName>Open - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Closed - Satisfied</fullName>
            </value>
            <value>
                <fullName>Closed - Discharged in Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Stayed - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Stayed - Other</fullName>
            </value>
            <value>
                <fullName>Vacated</fullName>
            </value>
            <value>
                <fullName>Closed-Claimant Judgment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/X2810_4_List_Status__c.field-meta.xml
<CustomField>
    <fullName>X2810_4_List_Status__c</fullName>
    <label>2810.4 List Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed-On List</fullName>
            </value>
            <value>
                <fullName>Confirmed-Off List</fullName>
            </value>
            <value>
                <fullName>Under Investigation/Appeal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/Liability_Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment Party</label>
    <nameField>
        <displayFormat>LJ-{0}</displayFormat>
        <label>Judgment Party</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Judgement__c/fields/Judgement__c.field-meta.xml
<CustomField>
    <fullName>Judgement__c</fullName>
    <label>Judgment</label>
    <referenceTo>Judgement__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Liable_Party__c.field-meta.xml
<CustomField>
    <fullName>Liable_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liable Party</label>
    <referenceTo>Liable_Party__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Related_Businesses__c</referenceTo>
    <relationshipLabel>Judgment Parties</relationshipLabel>
    <relationshipName>Judgment_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/X2810_4_List_Status__c.field-meta.xml
<CustomField>
    <fullName>X2810_4_List_Status__c</fullName>
    <label>2810.4 List Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed-On List</fullName>
            </value>
            <value>
                <fullName>Confirmed-Off List</fullName>
            </value>
            <value>
                <fullName>Under Investigation/Appeal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liable_Party__c/Liable_Party__c.object-meta.xml
<CustomObject>
    <label>Liable Party</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Liable Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liable Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liable_Party__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The liable party is related to a case role on the record. This field holds the value of that case role and is used for generating output document based on the party.</description>
    <inlineHelpText>Case role of the liable party</inlineHelpText>
    <label>Case Role</label>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Liable Parties</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Liable</fullName>
            </value>
            <value>
                <fullName>Not Liable</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/Related_Businesses__c.object-meta.xml
<CustomObject>
    <label>Related Business</label>
    <nameField>
        <displayFormat>RBO-{00000000}</displayFormat>
        <label>Related Businesses Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Businesses__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to store business Account for the Rbo record</description>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Business)</relationshipLabel>
    <relationshipName>Related_Businessess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Related Business)</relationshipLabel>
    <relationshipName>Related_Businessess1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/classes/DirQuerySelectorTest.cls
@IsTest
public class DirQuerySelectorTest {
    @IsTest static void testGetDuplicateRelatedBusinessRecord(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord(); 
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Related_Businesses__c> relatedBusinessRec = DIRDataFactory.createRelatedBusinessesTestData1();
        Set<Id> businessIdsSet = new Set<Id>();
        Set<Id> relatedBusinessIdsSet = new Set<Id>();
        for(Related_Businesses__c relObj : relatedBusinessRec){
            businessIdsSet.add(relObj.Business__c);
            relatedBusinessIdsSet.add(relObj.Related_Business__c);
        }
        Test.startTest();
        List<Related_Businesses__c> result = DirQuerySelector.getDuplicateRelatedBusinessRecord(businessIdsSet, relatedBusinessIdsSet);
        Test.stopTest();
        System.assertEquals(5, result.size());
    }
    @IsTest static void testGetRelatedBusinessRecord(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Related_Businesses__c> relatedBusinessRec = DIRDataFactory.createRelatedBusinessesTestData1();
        Test.startTest();
        Boolean result = DirQuerySelector.getRelatedBusinessRecord(relatedBusinessRec[0].Related_Business__c, relatedBusinessRec[0].Business__c);
        Test.stopTest();
        System.assertEquals(true, result);
    }
    @IsTest static void testGetValidBusinessForPositiveCase(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Account> accList = DIRDataFactory.createBusinessTestRecord();
        Test.startTest();
        Boolean result = DirQuerySelector.getValidBusiness(accList[0].id);
        Test.stopTest();
        System.assertEquals(true, result);
    }
    @IsTest static void testCheckCaseRoleForNotes(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Account> accList = DIRDataFactory.createBusinessTestRecord();
        Case_Role__c caseRoleObj = DIRDataFactory.caseRoleRecord(accList[0].id);
        Set<Id> accIds = new Set<Id>();
        for(Account accObj : accList){
            accIds.add(accObj.id);
        }
        Test.startTest();
        Map<Id, Case_Role__c> result = DirQuerySelector.checkCaseRoleForNotes(accIds);
        Test.stopTest();
        System.debug('testCheckCaseRoleForNotes ::: '+result);
    }
    @IsTest static void testCheckCaseRoleForRelatedParty(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        Map<string,Set<string>> businessWithRbMap = DIRDataFactory.createCheckCaseRoleForRelatedPartyRecord();
        Test.startTest();
        Map<Id,Set<Id>> result = DirQuerySelector.checkCaseRoleForRelatedParty(businessWithRbMap);
        Test.stopTest();
        System.debug('testCheckCaseRoleForRelatedParty ::: '+result);
    }
    @IsTest static void testGetJudgmentRecordWithZipCode(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        String listStatus2810 = 'test';
        String naicsCode = 'test';
        String accountName = '';
        String City = 'test';
        String ZipCode = '250001';
        Date judgmentEntryDateFrom = System.today() + 1;
        Date judgmentEntryDateTo = System.today();
        String court = 'test';
        String status = 'Open';
        List<String> judgmentStatus = status.split(',');
        String defandantEmployerName = 'test';
        Double judgmentTotalTo = 1;
        Double judgmentTotalFrom = 1;
        String citationNumber = 'test';
        String dirOffice = 'test';
        String county = 'test';
        Test.startTest();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecord();
        DirQuerySelector.judgmentSearchRecordWrapper judgmentRecList = DirQuerySelector.getJudgmentRecords(listStatus2810, naicsCode, accountName, City, ZipCode, judgmentEntryDateFrom, judgmentEntryDateTo, court, judgmentStatus, defandantEmployerName, judgmentTotalFrom , judgmentTotalTo ,citationNumber, dirOffice, county);
        Test.stopTest();
        System.debug('testGetJudgmentRecordWithZipCode ::: '+judgmentRecList);
    }
   @IsTest static void testGetJudgmentRecordWithCity(){
       Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
       Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        String listStatus2810 = 'test';
        String naicsCode = 'test';
        String accountName = '';
        String City = 'test';
        String ZipCode = '';
        Date judgmentEntryDateFrom = System.today() + 1;
        Date judgmentEntryDateTo = System.today();
        String court = 'test';
        String status = 'Open';
        List<String> judgmentStatus = status.split(',');
        String defandantEmployerName = 'test';
        Double judgmentTotalTo = 1;
        Double judgmentTotalFrom = 1;
        String citationNumber = 'test';
        String dirOffice = 'test';
        String county = 'test';
        Test.startTest();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecord();
        DirQuerySelector.judgmentSearchRecordWrapper judgmentRecList = DirQuerySelector.getJudgmentRecords(listStatus2810, naicsCode, accountName, City, ZipCode, judgmentEntryDateFrom, judgmentEntryDateTo, court, judgmentStatus, defandantEmployerName, judgmentTotalFrom , judgmentTotalTo ,citationNumber, dirOffice, county);
        Test.stopTest();
        System.debug('testGetJudgmentRecordWithCity ::: '+judgmentRecList);
    }
    @IsTest static void testGetJudgmentRecordWithCityAndZipCode(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        String listStatus2810 = 'test';
        String naicsCode = 'test';
        String accountName = '';
        String City = '';
        String ZipCode = 'test';
        Date judgmentEntryDateFrom = System.today() + 1;
        Date judgmentEntryDateTo = System.today();
        String court = 'test';
        String status = 'Open';
        List<String> judgmentStatus = status.split(',');
        String defandantEmployerName = 'test';
        Double judgmentTotalTo = 1;
        Double judgmentTotalFrom = 1;
        String citationNumber = 'test';
        String dirOffice = 'test';
        String county = 'test';
        Test.startTest();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecord();
        DirQuerySelector.judgmentSearchRecordWrapper judgmentRecList = DirQuerySelector.getJudgmentRecords(listStatus2810, naicsCode, accountName, City, ZipCode, judgmentEntryDateFrom, judgmentEntryDateTo, court, judgmentStatus, defandantEmployerName, judgmentTotalFrom , judgmentTotalTo ,citationNumber, dirOffice, county);
        Test.stopTest();
        System.debug('testGetJudgmentRecordWithCityAndZipCode ::: '+judgmentRecList);
    }
    @IsTest static void testGetJudgmentRecordWithoutCityAndZipCode(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        String listStatus2810 = 'test';
        String naicsCode = 'test';
        String accountName = '';
        String City = '';
        String ZipCode = '';
        Date judgmentEntryDateFrom = System.today() + 1;
        Date judgmentEntryDateTo = System.today();
        String court = 'test';
        String status = 'Open';
        List<String> judgmentStatus = status.split(',');
        String defandantEmployerName = 'test';
        Double judgmentTotalTo = 1;
        Double judgmentTotalFrom = 1;
        String citationNumber = 'test';
        String dirOffice = 'test';
        String county = 'test';
        Test.startTest();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecord();
        DirQuerySelector.judgmentSearchRecordWrapper judgmentRecList = DirQuerySelector.getJudgmentRecords(listStatus2810, naicsCode, accountName, City, ZipCode, judgmentEntryDateFrom, judgmentEntryDateTo, court, judgmentStatus, defandantEmployerName, judgmentTotalFrom , judgmentTotalTo ,citationNumber, dirOffice, county);
        Test.stopTest();
        System.debug('testGetJudgmentRecordWithoutCityAndZipCode ::: '+judgmentRecList);
    }
    @IsTest static void testGetJudgmentRecordWithAccountName(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        String listStatus2810 = 'test';
        String naicsCode = 'test';
        String accountName = 'test';
        String City = '';
        String ZipCode = '';
        Date judgmentEntryDateFrom = System.today() + 1;
        Date judgmentEntryDateTo = System.today();
        String court = 'test';
        String status = 'Open';
        List<String> judgmentStatus = status.split(',');
        String defandantEmployerName = 'test';
        Double judgmentTotalTo = 1;
        Double judgmentTotalFrom = 1;
        String citationNumber = 'test';
        String dirOffice = 'test';
        String county = 'test';
        Test.startTest();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecord();
        DirQuerySelector.judgmentSearchRecordWrapper judgmentRecList = DirQuerySelector.getJudgmentRecords(listStatus2810, naicsCode, accountName, City, ZipCode, judgmentEntryDateFrom, judgmentEntryDateTo, court, judgmentStatus, defandantEmployerName, judgmentTotalFrom , judgmentTotalTo ,citationNumber, dirOffice, county);
        Test.stopTest();
        System.debug('testGetJudgmentRecordWithAccountName ::: '+judgmentRecList);
    }
    @IsTest
    public static void testGetPortDrayageRecord(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecords();
        Date asOfDate = System.today();
        Date fromDate = System.today();
        Date toDate = System.today();
        Test.startTest();
        DirQuerySelector.judgmentSearchRecordWrapper portDrayageRecList = DirQuerySelector.getPortDrayageRecords(asOfDate, fromDate, toDate);
        Test.stopTest();
        System.debug('testGetPortDrayageRecord :::: '+portDrayageRecList);
    }
    @IsTest
    public static void testGetPortDrayageRecordWithoutAsOfDate(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecords();
        Date asOfDate;
        Date fromDate = System.today();
        Date toDate = System.today();
        Test.startTest();
        DirQuerySelector.judgmentSearchRecordWrapper portDrayageRecList = DirQuerySelector.getPortDrayageRecords(asOfDate, fromDate, toDate);
        Test.stopTest();
        System.debug('testGetPortDrayageRecordWithoutAsOfDate :::: '+portDrayageRecList);
    }
    @IsTest
    public static void testGetPortDrayageRecordWithCaseRole(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecords();
        Date asOfDate;
        Date fromDate = System.today();
        Date toDate = System.today();
        Test.startTest();
        List<Case_Role__c> caseRoleList = DIRDataFactory.createCaseRoleRec();
        DirQuerySelector.judgmentSearchRecordWrapper portDrayageRecList = DirQuerySelector.getPortDrayageRecords(asOfDate, fromDate, toDate);
        Test.stopTest();
        System.debug('testGetPortDrayageRecordWithCaseRole :::: '+portDrayageRecList);
    }
    @IsTest public static void testGetJudgmentDetails(){
        Trigger_Settings__c triggerSettingObj = DIRDataFactory.createTriggerCustomSettingRecord();
        Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1(); 
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        Map<Id,Related_Businesses__c> relatedBusinessMap = DIRDataFactory.createRelatedBusinessRecord();
        Liability_Judgement__c liableJudgmentObj = new Liability_Judgement__c();
        liableJudgmentObj.Related_Business__c = relatedBusinessMap.values()[0].Id;
        liableJudgmentObj.X2810_4_List_Status__c = 'Confirmed-on List';
        liableJudgmentObj.Judgement__c = judgmentRecordsLists[0].Id;
        insert liableJudgmentObj;
        Test.startTest();
        //Case_Role__c caseRoleList = DIRDataFactory.createCaseRoleRecs();
        DirQuerySelector.judgmentDetailModel result = DirQuerySelector.getJudgmentDetails(judgmentRecordsLists[0].Id, liableJudgmentObj.Id);
        Test.stopTest();
        System.debug('testGetJudgmentDetails :::: >?>>> '+result);
    }
    /*@IsTest(seeAllData=true) static void testGetJudgmentDetails(){
        //Trigger_Settings__c triggerSettingObj1 = DIRDataFactory.createTriggerCustomSettingRecord1();
        Account mainA = new Account(); 
        mainA.Name = 'Lucian459487';
        insert mainA;
        
        DIR_Case__c caseObj = DIRDataFactory.createCaseManagement(mainA.Id);
        
        
        Judgement__c judgmentRecordObj = new Judgement__c();
        judgmentRecordObj.X2810_4_List_Status__c = 'Confirmed-On List';
        judgmentRecordObj.Judgement_Date__c = System.today();
        judgmentRecordObj.Case_Management__c = caseObj.Id;
        judgmentRecordObj.Status__c = 'Open';
        insert judgmentRecordObj;
        
        //Liable_Party__c liablePartyObj = DIRDataFactory.createTestLiablePartyRecords();
        Map<Id,Related_Businesses__c> relatedBusinessMap = DIRDataFactory.createRelatedBusinessRecord();
        Liability_Judgement__c liableJudgmentObj = new Liability_Judgement__c();
        liableJudgmentObj.Related_Business__c = relatedBusinessMap.values()[0].Id;
        liableJudgmentObj.X2810_4_List_Status__c = 'Confirmed-on List';
        liableJudgmentObj.Judgement__c = judgmentRecordObj.Id;
        insert liableJudgmentObj;
        Test.startTest();
        //Case_Role__c caseRoleList = DIRDataFactory.createCaseRoleRecs();
        DirQuerySelector.judgmentDetailModel result = DirQuerySelector.getJudgmentDetails(judgmentRecordObj.Id, liableJudgmentObj.Id);
        Test.stopTest();
        System.debug('testGetJudgmentDetails :::: >?>>> '+result);
    }*/
}