force-app/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

force-app/main/default/objects/Associated_Agents__c/Associated_Agents__c.object-meta.xml
<CustomObject>
    <label>Associated Agents</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Associated Agents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Agents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Agents</relationshipLabel>
    <relationshipName>Associated_Agents1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Agents__c/fields/Associated_Account__c.field-meta.xml
<CustomField>
    <fullName>Associated_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Agents (Associated Account)</relationshipLabel>
    <relationshipName>Associated_Agents2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Agents__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent for Service</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Employer Representative</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To populate Region field</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Identifies offices as BOFE</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Office_Zip_Code_Map__c/Office_Zip_Code_Map__c.object-meta.xml
<CustomObject>
    <description>Maps zip codes to office locations. Used for assigning records to offices based on zip codes</description>
    <label>Office-Zip Code Map</label>
    <nameField>
        <displayFormat>Map-{00000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office-Zip Code Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>The office that the zip code is assigned to</description>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>the zip code assigned to the office</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Record_Type_Mapping__c/Record_Type_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Provides mapping for record types for the creation of records based on a parent case's record type.

Defines which violation types to display in the violation engine for which case type, based on record types, and which case violation rec type should be created as a result.</description>
    <label>Record Type Mapping</label>
</CustomObject>

force-app/main/default/objects/Record_Type_Mapping__c/fields/Case_Rec_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Rec_Type__c</fullName>
    <inlineHelpText>Record type of case that is the source of the violations</inlineHelpText>
    <label>Case Rec Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Type_Mapping__c/fields/Violation_Type_Rec_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type_Rec_Type__c</fullName>
    <inlineHelpText>Enter the record type of the violation types that should display in the violation engine for the related case rec type.</inlineHelpText>
    <label>Violation Type Rec Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OWCAssociateAgentController_Test.cls
@isTest
public class OWCAssociateAgentController_Test {
    @isTest
     public static void saveValuesTest(){
          Trigger_Settings__c ts = new Trigger_Settings__c(
            Name = 'GenerateFieldHistoryAction',
            Is_Active__c = false
        );
        insert ts;
     Id caseRecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE').getRecordTypeId();
        Record_Type_Mapping__c custSet=new Record_Type_Mapping__c();
        custset.Case_Rec_Type__c='BOFE'; 
        custset.Name='BOFE';
        custset.Violation_Type_Rec_Type__c='BOFE';
        insert custset;
        
        Office__c office = new Office__c();
        office.Name = 'Lucian832474';
        insert office;
        
        Zip_Code__c zip = new Zip_Code__c();
        zip.Name = '234889';
        insert zip;
        
        Office_Zip_Code_Map__c map1 = new Office_Zip_Code_Map__c();
        map1.Zip_Code__c = zip.Id;
        map1.Office__c = office.Id;
        insert map1;
        
        Account mainA = new Account();
        mainA.Name = 'name';
        mainA.ShippingPostalCode = '234889';
        insert mainA;
        
        Account affA = new Account();
        affA.Name = 'Lucian235432';
        insert AffA;
       
         
         Associated_Agents__c agent =new Associated_Agents__c();
         agent.Account__c=mainA.Id;
         agent.Type__c='Client';
         agent.Associated_Account__c=affA.Id;
         insert agent;
         OWCAssociateAgentController.saveValues(affA.Id,mainA.Id,agent.Type__c,true,null);
         OWCAssociateAgentController.saveValues(mainA.Id,affA.Id,agent.Type__c,false,'Please enter valid reason for Inactive relationship');
         
         
     }
    

}