force-app/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Cash_Balance_on_Case__c.field-meta.xml
<CustomField>
    <fullName>Cash_Balance_on_Case__c</fullName>
    <description>Difference of deposited funds and checks written against deposits.</description>
    <formula>Deposited_Funds__c - Funds_Drawn_on_Deposits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cash Balance on Case</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Garment Cases</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Office_Account__c.field-meta.xml
<CustomField>
    <fullName>Office_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Account</label>
    <referenceTo>Office_Account__c</referenceTo>
    <relationshipLabel>Offices</relationshipLabel>
    <relationshipName>Offices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Identifies offices as BOFE</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/CCU.recordType-meta.xml
<RecordType>
    <fullName>CCU</fullName>
    <active>true</active>
    <description>Central Cashiering Unit</description>
    <label>CCU</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Identifies an office as a garment office</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Identifies offices as WAGE</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office_Account__c/Office_Account__c.object-meta.xml
<CustomObject>
    <description>This object allows a cashier to view the details associated to a deposit into and office account so that they can monitor the historical transactions associated with a deposit account.</description>
    <label>Office Account</label>
    <nameField>
        <label>Office Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Account__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Office Accounts</relationshipLabel>
    <relationshipName>Office_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CashOnHandReportControllerTest.cls
/* CashOnHandReportControllerTest */
@isTest(SeeAllData=true) //SeeAllData=true to bring in all Office_Account__c records, and these records are quite static--well, except for newly spun sandboxes with zero data.
public with sharing class CashOnHandReportControllerTest{
    
    @isTest
    static void testOA(){

        List<Office_Account__c> oaList = [SELECT Id, Name FROM Office_Account__c];
        Office_Account__c oa;

        if(oaList.size() == 0){
            Office__c office = new Office__c(
                Name = 'Sacramento CCU',
                RecordTypeId = Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('CCU').getRecordTypeId()
            );
            insert office;
       
            oa = new Office_Account__c(
                Name = '32-117',
                Office__c = office.Id
            );
            insert oa;
        
            office.Office_Account__c = oa.Id;
            update office;

        }else{
            oa = oaList[0];
        }
        
        System.debug('oa:'+oa);
        
        ApexPages.StandardController cohOaReportSC = new ApexPages.StandardController(oa);
        PageReference cohOaPageRef = Page.CashOnHandReportVFP;
        cohOaPageRef.getParameters().put('Id', oa.Id);
        
        Test.setCurrentPage(cohOaPageRef);
        
        CashOnHandReportController cohReportController = new CashOnHandReportController(cohOaReportSC);
        
        List<DIR_Case__c> testCases = [SELECT Id, Name, Case_Number__c, Cash_Balance_on_Case__c, 
                                        Office__c, Office__r.Name, Office__r.Office_Account__c, Office__r.Office_Account__r.Id, Office__r.Office_Account__r.Name, Employer__c, Employer__r.Name
                                            FROM DIR_Case__c
                                            WHERE Cash_Balance_on_Case__c != 0.00
                                                AND Office__r.Office_Account__r.Id = :oa.Id];
        
        Decimal testSum = 0.00;
        
        for(DIR_Case__c cm : testCases){
            testSum += cm.Cash_Balance_on_Case__c;
        }
        
        System.assertEquals(cohReportController.sum, testSum);
        
    }
    
    @isTest
    static void testOther(){
        
        //ApexPages.StandardController cohOaReportSC = new ApexPages.StandardController(oa);
        PageReference cohOaPageRef = Page.CashOnHandReportOtherVFP;
        //cohOaPageRef.getParameters().put('Id', oa.Id);
        
        Test.setCurrentPage(cohOaPageRef);
        
        CashOnHandReportController cohReportController = new CashOnHandReportController();
        
        List<Id> ourOfficeRTIDs = new List<Id>();
        ourOfficeRTIDs.add(Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId());
        ourOfficeRTIDs.add(Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('Garment').getRecordTypeId());
        ourOfficeRTIDs.add(Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('BOFE').getRecordTypeId());
        ourOfficeRTIDs.add(Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('CCU').getRecordTypeId());
        
        List<DIR_Case__c> testCases = [SELECT Id, Name, Case_Number__c, Cash_Balance_on_Case__c, 
                                            Office__c, Office__r.RecordTypeID, Office__r.Office_Account__c, Office__r.Office_Account__r.Name, Office__r.Office_Account__r.Id, Employer__c, Employer__r.Name
                                        FROM DIR_Case__c
                                        WHERE Cash_Balance_on_Case__c != 0.00
                                            AND (Office__c = NULL
                                                OR Office__r.Office_Account__c = NULL)];
        
        
        Decimal testSum = 0.00;
        
        for(DIR_Case__c cm : testCases){
            testSum += cm.Cash_Balance_on_Case__c;
        }
        
        System.assertEquals(cohReportController.sum, testSum);
        
    }
}