force-app/main/default/objects/DBA__c/DBA__c.object-meta.xml
<CustomObject>
    <label>DBA</label>
    <nameField>
        <label>DBA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DBAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DBA__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>DBAs</relationshipLabel>
    <relationshipName>DBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Abestos__c.field-meta.xml
<CustomField>
    <fullName>Abestos__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Asbestos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Boilermaker_Blacksmith__c.field-meta.xml
<CustomField>
    <fullName>Boilermaker_Blacksmith__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Boilermaker-Blacksmith</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Bricklayer_Brick_Tender__c.field-meta.xml
<CustomField>
    <fullName>Bricklayer_Brick_Tender__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Bricklayer/Brick Tender</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Carpenter__c.field-meta.xml
<CustomField>
    <fullName>Carpenter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Carpenter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Carpet_Linoleum_Resilient_Tile_Layer__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Linoleum_Resilient_Tile_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Carpet, Linoleum, Resilient Tile Layer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Cement_Mason__c.field-meta.xml
<CustomField>
    <fullName>Cement_Mason__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Cement Mason</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>Mailing County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Driver_On_Off_Hauling__c.field-meta.xml
<CustomField>
    <fullName>Driver_On_Off_Hauling__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Driver (On/Off Hauling)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Drywall_Installer_Lather_Finisher__c.field-meta.xml
<CustomField>
    <fullName>Drywall_Installer_Lather_Finisher__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Drywall Installer/Lather/Finisher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Electrical_Utility__c.field-meta.xml
<CustomField>
    <fullName>Electrical_Utility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Electrical Utility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Electrician__c.field-meta.xml
<CustomField>
    <fullName>Electrician__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Electrician</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Field_Surveyor__c.field-meta.xml
<CustomField>
    <fullName>Field_Surveyor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Field Surveyor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Glazier__c.field-meta.xml
<CustomField>
    <fullName>Glazier__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Glazier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Inspector_Field_Soils_Material_Tester__c.field-meta.xml
<CustomField>
    <fullName>Inspector_Field_Soils_Material_Tester__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Inspector/Field Soils,Material Tester</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Iron_Worker__c.field-meta.xml
<CustomField>
    <fullName>Iron_Worker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Iron Worker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Landscape__c.field-meta.xml
<CustomField>
    <fullName>Landscape__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Landscape</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <inlineHelpText>Please enter name registered with CA Secretary of State.  For Sole Proprietor enter full legal name.</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Line_1__c</fullName>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Line_2__c</fullName>
    <label>Mailing Address Line 2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Postal_Code__c</fullName>
    <label>Mailing Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Marble_Mason_Finisher__c.field-meta.xml
<CustomField>
    <fullName>Marble_Mason_Finisher__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Marble Mason/Finisher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Painter__c.field-meta.xml
<CustomField>
    <fullName>Painter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Painter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Plasterer_Tender__c.field-meta.xml
<CustomField>
    <fullName>Plasterer_Tender__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Plasterer/Tender</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Plumber__c.field-meta.xml
<CustomField>
    <fullName>Plumber__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Plumber</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Roofing__c.field-meta.xml
<CustomField>
    <fullName>Roofing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Roofing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Sheet_Metal_Worker__c.field-meta.xml
<CustomField>
    <fullName>Sheet_Metal_Worker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Sheet Metal Worker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Stator_Rewinder__c.field-meta.xml
<CustomField>
    <fullName>Stator_Rewinder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Stator Rewinder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Teamster__c.field-meta.xml
<CustomField>
    <fullName>Teamster__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Teamster</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Terrazzo_Worker_Finisher__c.field-meta.xml
<CustomField>
    <fullName>Terrazzo_Worker_Finisher__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Terrazzo Worker/Finisher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Tile_Setter_Finisher__c.field-meta.xml
<CustomField>
    <fullName>Tile_Setter_Finisher__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Tile Setter/Finisher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Water_Well_Driller__c.field-meta.xml
<CustomField>
    <fullName>Water_Well_Driller__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Water Well Driller</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/exportRegDetailsController.cls
global class exportRegDetailsController{
    
    public List<String> regIdList {get;set;}
    public List<License_Registration__c> regList {get;set;}
    
    public exportRegDetailsController() 
    {
            regIdList = new List<String>();
            String listReg = apexpages.currentpage().getparameters().get('myList');
            system.debug('reg list is '+listReg);
            if(String.isNotBlank(listReg) && listReg.contains(','))
                regIdList =  listReg.split(',');
            else{
                list<String> lis=new List<String>();
                lis.add(listReg);
                regIdList=lis;
            }
            
            System.debug('regIdList-'+regIdList);
            if(regIdList!=null && regIdList.size()>0){
            regList = [select id,status__c,License_Registration_Number__c,Effective_Date__c,Expiration_Date__c,Legal_Entity_Name__c,County__c,Mailing_Address_Line_1__c,
                    Mailing_Address_Line_2__c,Mailing_City__c,Mailing_Country__c,Mailing_Postal_Code__c,
                    Boilermaker_Blacksmith__c,Bricklayer_Brick_Tender__c,Carpet_Linoleum_Resilient_Tile_Layer__c,Drywall_Installer_Lather_Finisher__c,
                    Electrician__c,Field_Surveyor__c,Glazier__c,Marble_Mason_Finisher__c,Painter__c,Plasterer_Tender__c,Plumber__c,Roofing__c,Sheet_Metal_Worker__c,
                    Terrazzo_Worker_Finisher__c,Tile_Setter_Finisher__c,Water_Well_Driller__c,Iron_Worker__c,Electrical_Utility__c,Landscape__c,Stator_Rewinder__c,
                    Driver_On_Off_Hauling__c,Teamster__c,Abestos__c,Inspector_Field_Soils_Material_Tester__c,Carpenter__c,Cement_Mason__c,Elevator_Constructor__c,Laborer__c,
                    Parking_Highway_Improvement__c,Operating_Engineer__c,General_Engineering__c,General_Building__c,Crafts__c ,
                    (select id,name from DBAS__r where active__c = 'Yes')
                    from License_Registration__c where id in : regIdList];
                    
            for(License_Registration__c reg: regList){
                
                reg.Crafts__c ='';
                
                if(reg.Boilermaker_Blacksmith__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Boilermaker-Blacksmith' + ',';
                }
                if(reg.Bricklayer_Brick_Tender__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Bricklayer/Brick Tender' + ',';
                }
                if(reg.Carpet_Linoleum_Resilient_Tile_Layer__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Carpet, Linoleum, Resilient Tile Layer' + ',';
                }
                if(reg.Drywall_Installer_Lather_Finisher__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Drywall Installer/Lather/Finisher' + ',';
                }
                if(reg.Electrician__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Electrician' + ',';
                }
                if(reg.Field_Surveyor__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Field Surveyor' + ',';
                }
                if(reg.Glazier__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Glazier' + ',';
                }
                if(reg.Marble_Mason_Finisher__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Marble Mason/Finisher' + ',';
                }
                if(reg.Painter__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Painter' + ',';
                }
                if(reg.Plasterer_Tender__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Plasterer/Tender' + ',';
                }                
                if(reg.Plumber__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Plumber' + ',';
                }                
                if(reg.Roofing__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Roofing' + ',';
                }                
                if(reg.Sheet_Metal_Worker__c){ 
                    reg.Crafts__c =  reg.Crafts__c + 'Sheet Metal Worker' + ',';
                }                
                if(reg.Terrazzo_Worker_Finisher__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Terrazzo Worker/Finisher' + ',';
                } 
                if(reg.Tile_Setter_Finisher__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Tile Setter/Finisher' + ',';
                }
                if(reg.Water_Well_Driller__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Water Well Driller' + ',';
                }
                if(reg.Iron_Worker__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Iron Worker' + ',';
                }
                if(reg.Electrical_Utility__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Electrical Utility' + ',';
                }
                if(reg.Landscape__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Landscape' + ',';
                }
                if(reg.Stator_Rewinder__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Stator Rewinder' + ',';
                }
                if(reg.Driver_On_Off_Hauling__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Driver (On/Off Hauling)' + ',';
                }                
                if(reg.Teamster__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Teamster' + ',';
                }                
                if(reg.Abestos__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Abestos' + ',';
                }                
                if(reg.Inspector_Field_Soils_Material_Tester__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Inspector/Field Soils,Material Tester' + ',';
                }                
                if(reg.Carpenter__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Carpenter' + ',';
                }                
                if(reg.Cement_Mason__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Cement Mason' + ',';
                }  
                if(reg.Elevator_Constructor__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Elevator Constructor' + ',';
                }
                if(reg.Laborer__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Laborer' + ',';
                }
                if(reg.Parking_Highway_Improvement__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Parking/Highway/Improvement' + ',';
                }
                if(reg.Operating_Engineer__c){
                    reg.Crafts__c =  reg.Crafts__c + 'Operating Engineer' + ',';
                }
                if(reg.General_Engineering__c){
                    reg.Crafts__c =  reg.Crafts__c + 'General Engineering' + ',';
                }
                if(reg.General_Building__c){
                    reg.Crafts__c =  reg.Crafts__c + 'General Building' + ',';
                }
                
                if(reg.Crafts__c!=''){
                    reg.Crafts__c =  reg.Crafts__c.removeEnd(',');
                }
            }        
            
            System.debug('regList'+regList);
            }
    }
}