force-app/main/default/objects/Pay_Period__c/Pay_Period__c.object-meta.xml
<CustomObject>
    <description>HR - Monthly Pay Periods</description>
    <label>Pay Period</label>
    <nameField>
        <label>Pay Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pay Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>HR - Payment information pertaining to an employee</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pmt-{00000000}</displayFormat>
        <label>Payment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Employee_Contact__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact__c</fullName>
    <label>Employee (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Pay_Period__c.field-meta.xml
<CustomField>
    <fullName>Pay_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pay Period</label>
    <referenceTo>Pay_Period__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Position Location</description>
    <inlineHelpText>Enter the DIR office location for this position.</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMERICAN CANYON</fullName>
            </value>
            <value>
                <fullName>ANAHEIM</fullName>
            </value>
            <value>
                <fullName>BAKERSFIELD</fullName>
            </value>
            <value>
                <fullName>CHICO</fullName>
            </value>
            <value>
                <fullName>CONCORD</fullName>
            </value>
            <value>
                <fullName>EL CENTRO</fullName>
            </value>
            <value>
                <fullName>EUREKA</fullName>
            </value>
            <value>
                <fullName>FOSTER CITY</fullName>
            </value>
            <value>
                <fullName>FREMONT</fullName>
            </value>
            <value>
                <fullName>FRESNO</fullName>
            </value>
            <value>
                <fullName>GLENDALE</fullName>
            </value>
            <value>
                <fullName>GOLETA</fullName>
            </value>
            <value>
                <fullName>LA PALMA</fullName>
            </value>
            <value>
                <fullName>LODI</fullName>
            </value>
            <value>
                <fullName>LOS ANGELES</fullName>
            </value>
            <value>
                <fullName>LONG BEACH</fullName>
            </value>
            <value>
                <fullName>MARINA DEL REY</fullName>
            </value>
            <value>
                <fullName>MODESTO</fullName>
            </value>
            <value>
                <fullName>MONROVIA</fullName>
            </value>
            <value>
                <fullName>OAKLAND</fullName>
            </value>
            <value>
                <fullName>OXNARD</fullName>
            </value>
            <value>
                <fullName>POMONA</fullName>
            </value>
            <value>
                <fullName>REDDING</fullName>
            </value>
            <value>
                <fullName>RIVERSIDE</fullName>
            </value>
            <value>
                <fullName>SACRAMENTO</fullName>
            </value>
            <value>
                <fullName>SALINAS</fullName>
            </value>
            <value>
                <fullName>SAN BERNARDINO</fullName>
            </value>
            <value>
                <fullName>SAN DIEGO</fullName>
            </value>
            <value>
                <fullName>SAN FRANCISCO</fullName>
            </value>
            <value>
                <fullName>SAN JOSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Manual_Entry__c.field-meta.xml
<CustomField>
    <fullName>Manual_Entry__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial #</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/payment_Tests.cls
@isTest
(SeeAllData = true)
private class payment_Tests {

    static testMethod void payment_Methods_UnitTest() {
        test.startTest();
        Contact c = new Contact();
        c.LastName = 'Test';
        insert c;
        
        Position__c p = new Position__c();
        p.Name = '400-152-1441-888';
        p.Serial_Number__c = '888';
        p.Manual_Entry__c = false;
        p.IsActive__c = true;
        //p.Location__c = 'Van Nuys';
        insert p;
        
        Pay_Period__c pp = new Pay_Period__c();
        pp.Start_date__c = system.today().addDays(-7);
        pp.End_date__c = system.today().addDays(7);
        insert pp;
        
        Payment__c pay = new Payment__c();
        pay.Employee_Contact__c = c.Id;
        pay.Position__c = p.Id;
        pay.Pay_Period__c = pp.Id;
        pay.Hours__c = 1;
        insert pay;
        
        pay.Hours__c = 2;
        update pay;

        test.stopTest();
    }

}