force-app/main/default/objects/Key_Value_Store__c/Key_Value_Store__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores keys and associated values for use in code so that changes can be made without modifying code whenever possible.</description>
    <label>Key Value Store</label>
</CustomObject>

force-app/main/default/objects/Key_Value_Store__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <description>Used for the Renewal buttonon the community</description>
    <label>Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Key_Value_Store__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value associated with the key ( Name field )</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/purgeIncompleteRegistrations.cls
/********************************************************************************************************
Name:    purgeIncompleteRegistrations.cls
Author:  Shivam Goyal (shivam.goyal@sapient.com)
Date:    18/12/2018
Modified by: 
Date:
Test class: 

Behavior:
    Schedule a purge of all Registrations that are in an Incomplete Status and the Last Modified Date is greater than 30 days.
       
********************************************************************************************************/

global class purgeIncompleteRegistrations implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc) { 
        
        Integer purgeDuration = integer.valueOf(Key_Value_Store__c.getValues('Purge Public Works Registrations').Value__c);
        String recordType = Key_Value_Store__c.getValues('Purge Public Works Registrations').Record_Type__c;
        date purgeDurDate;
        
        if(Test.isRunningTest())
        purgeDurDate = system.today().addDays(10);
        else
        purgeDurDate = system.today().addDays(-purgeDuration);        
        
        return Database.getQueryLocator(
            'SELECT ID FROM License_Registration__c ' +
            'where Status__c=\'Incomplete\' and Record_Type_Name__c= :recordType and LastModifiedDate <=:purgeDurDate' 
        );
    }
    
    global void execute(Database.BatchableContext bc, List<License_Registration__c> scope){
     
     if(scope.size()>0){
         delete scope;
     }    
    }
    
    global void finish(Database.BatchableContext bc){
        
    }    

}