force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the payee record</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Incomplete-2nd Request</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Undeliverable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Record__c/Payment_Record__c.object-meta.xml
<CustomObject>
    <label>Payment Record</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Record__c/fields/Disbursement_Type__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Type__c</fullName>
    <description>This should match the Disbursement Type on the parent Warrant. Populated by the Warrant generation automation. Used for generating the UWF schedule.</description>
    <label>Disbursement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Attorney Fees</fullName>
            </value>
            <value>
                <fullName>BOFE Penalty</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
            <value>
                <fullName>CAC Payment</fullName>
            </value>
            <value>
                <fullName>Certified Payroll Fee (CPR)</fullName>
            </value>
            <value>
                <fullName>Conceded</fullName>
            </value>
            <value>
                <fullName>Court Costs</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>EDD Payment</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>IRS</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Over payment</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Photo Copy Fee</fullName>
            </value>
            <value>
                <fullName>Plaintiff</fullName>
            </value>
            <value>
                <fullName>Redemption of Check (NSF)</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Refund Certified Payroll Fee (CPR)</fullName>
            </value>
            <value>
                <fullName>Refund Garment Registration</fullName>
            </value>
            <value>
                <fullName>Return Taxes</fullName>
            </value>
            <value>
                <fullName>Return to Defendant</fullName>
            </value>
            <value>
                <fullName>Subpoena Cost Recovery</fullName>
            </value>
            <value>
                <fullName>Tax Lien</fullName>
            </value>
            <value>
                <fullName>To Assignee</fullName>
            </value>
            <value>
                <fullName>Training Fund</fullName>
            </value>
            <value>
                <fullName>Unpaid Wage Fund</fullName>
            </value>
            <value>
                <fullName>Witness Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warrant__c/Warrant__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Warrant</label>
    <nameField>
        <displayFormat>WR-{000000}</displayFormat>
        <label>Warrant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warrants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warrant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Secondary Approval Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>Status_Comment__c</fullName>
    <description>Pick List for Void/Cancel/Stop Reason</description>
    <label>Status Comment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incorrect address</fullName>
            </value>
            <value>
                <fullName>Payee did not receive</fullName>
            </value>
            <value>
                <fullName>Payee lost warrant</fullName>
            </value>
            <value>
                <fullName>Returned USPS/Undeliverable</fullName>
            </value>
            <value>
                <fullName>Stale dated</fullName>
            </value>
            <value>
                <fullName>Stolen</fullName>
            </value>
            <value>
                <fullName>Warrant damaged</fullName>
            </value>
            <value>
                <fullName>Warrant not approved to print</fullName>
            </value>
            <value>
                <fullName>Wrong payee</fullName>
            </value>
            <value>
                <fullName>Wrong payment amount</fullName>
            </value>
            <value>
                <fullName>Warrant batch void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <inlineHelpText>Date of last status change</inlineHelpText>
    <label>Status Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Warrant_Batch__c.field-meta.xml
<CustomField>
    <fullName>Warrant_Batch__c</fullName>
    <label>Warrant Batch</label>
    <referenceTo>Warrant_Batch__c</referenceTo>
    <relationshipLabel>Warrants</relationshipLabel>
    <relationshipName>Warrant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Warrant_Number__c.field-meta.xml
<CustomField>
    <fullName>Warrant_Number__c</fullName>
    <description>The complete check number consist of warrant serial with check digit.</description>
    <formula>Serial_Number__c &amp; TEXT(9-MOD (VALUE (MID (Serial_Number__c, 1, 1))
+ VALUE (MID (Serial_Number__c, 2, 1))
+ VALUE (MID (Serial_Number__c, 3, 1))
+ VALUE (MID (Serial_Number__c, 4, 1))
+ VALUE (MID (Serial_Number__c, 5, 1))
+ VALUE (MID (Serial_Number__c, 6, 1))
+ VALUE (MID (Serial_Number__c, 7, 1))
+ VALUE (MID (Serial_Number__c, 8, 1)),9))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warrant Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warrant_Batch__c/Warrant_Batch__c.object-meta.xml
<CustomObject>
    <description>Object for associating groups of checks so that they can be approved/voided in batches</description>
    <label>Warrant Batch</label>
    <nameField>
        <displayFormat>WB-{0}</displayFormat>
        <label>Warrant Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warrant Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warrant_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that allows a disbursement clerk to indicate whether or not a batch of warrants has been successfully printed so that the balances update and the batch closes.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Review Complete</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warrant_Batch__c/fields/Void_Reason__c.field-meta.xml
<CustomField>
    <fullName>Void_Reason__c</fullName>
    <description>Description of the Void Request to be submitted.</description>
    <label>Void Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/WBPrintUpdateController.cls
public with sharing class WBPrintUpdateController {
    public WBPrintUpdateController() {
        System.debug('WBPrintUpdateController');
    }

    @AuraEnabled(cacheable=true)
    public static List<PermissionSetAssignment> getUserInfo(String userId) {
        System.debug('>>>>>>>>>>>>>>>>>>>>>> User Info >>>>>>>>>>>>>>>>>>>>');
        List<PermissionSetAssignment> userProfilePermissionInfo = new List<PermissionSetAssignment> ([SELECT Id, PermissionSetId, PermissionSet.Name, 
        PermissionSet.ProfileId, PermissionSet.Profile.Name, AssigneeId, Assignee.Name 
        FROM PermissionSetAssignment WHERE AssigneeId =: userId]);

        return userProfilePermissionInfo;
    }

    @AuraEnabled(cacheable=true)
    public static List<WarrantPaymentRecordListWrapper> getWarrantsCaseDetails(String apxWbRecId){
        System.debug('>>>>>>>>>>>>>>> getWarrants---apxWbRecId >>>>>>>>>>>>>'+apxWbRecId);
        List<WarrantPaymentRecordListWrapper> warrantWbandPRlist = new List<WarrantPaymentRecordListWrapper>();
        List<Warrant_Batch__c> wbWarrantList = new List<Warrant_Batch__c>([SELECT Id, Name, Void_Reason__c, Status__c, 
        (SELECT Id, Name, Warrant_Number__c, Amount__c, Status__c, Status_Comment__c, Status_Date__c, Disbursement_Type__c, 
        Approved_By__c, Approved_Warrant__c, Approved_Date__c, Not_Approved_Comments__c, Office_Account__c, 
        Case_Number__c, Case__r.Id, Case__r.Name, Case__r.Cash_Balance_on_Case__c, Case__r.Deposited_Funds__c, Case__r.Funds_Drawn_on_Deposits__c, 
        Payee__r.Id, Payee__r.Name 
        FROM Warrant__r) FROM Warrant_Batch__c WHERE Id=:apxWbRecId]);
        System.debug('>>>>>>>>>> GetWarrantsCaseDetails --- wbWarrantList >>>>>>>>>>'+wbWarrantList);
        System.debug('>>>>>>>>>> GetWarrantsCaseDetails --- Related Warrants >>>>>>>>>>'+wbWarrantList[0].Warrant__r);

        List<String> warrantIdList = new List<String>();
        for (Warrant__c wrList:wbWarrantList[0].Warrant__r) {
            warrantIdList.add(wrList.Id);
        }
        List<Payment_Record__c> paymentRecDetailList = new List<Payment_Record__c>([SELECT Id, Name, 
        Warrant__r.Id, Warrant__r.Name, Warrant_Issued__c from Payment_Record__c WHERE Warrant__r.Id=:warrantIdList]);
        System.debug('>>>>>>>>>> GetWarrantsCaseDetails --- Related Payment Records >>>>>>>>>>'+paymentRecDetailList);

        WarrantPaymentRecordListWrapper warrantPmtRecWrapper = new WarrantPaymentRecordListWrapper();
        warrantPmtRecWrapper.warrantBatch = wbWarrantList;
        warrantPmtRecWrapper.warrantList = wbWarrantList[0].Warrant__r;
        warrantPmtRecWrapper.paymentRecList = paymentRecDetailList;
        warrantWbandPRlist.add(warrantPmtRecWrapper);
        System.debug('>>>>>>>>>> GetWarrantsCaseDetails --- Wrapper List >>>>>>>>>>'+warrantWbandPRlist);

        return warrantWbandPRlist;
    }

     //wrapper class with @AuraEnabled and {get;set;} properties
     public class WarrantPaymentRecordListWrapper{
        @AuraEnabled
        public List<Warrant_Batch__c> warrantBatch{get;set;}
        @AuraEnabled
        public List<Warrant__c> warrantList{get;set;}
        @AuraEnabled
        public List<Payment_Record__c> paymentRecList{get;set;}
    }

    @AuraEnabled
    public static Boolean updateWBandWRstatus(List<Warrant_Batch__c> wbForUpdate, List<Warrant__c> wrForUpdate, List<Payment_Record__c> prForUpdate, String wbLink){
        System.debug('------------------- WB, WR, PR Update -------------------');
        Boolean updatedRec = false;
        try{
            updatedRec = true;
            System.enqueueJob(new WRandPRupdateQable(wbForUpdate, wrForUpdate, prForUpdate, wbLink));
        }
        catch(DmlException e){
            System.debug('Error updating WB: '+e);
            updatedRec = false;
        }
        return updatedRec;
    }

}