force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Hearing_Date__c.field-meta.xml
<CustomField>
    <fullName>Hearing_Date__c</fullName>
    <description>Settlement Hearing Date for PAGA Case</description>
    <inlineHelpText>Settlement Hearing Date for PAGA Case</inlineHelpText>
    <label>Settlement Hearing Date for PAGA Case</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Refer_to_JEU__c.field-meta.xml
<CustomField>
    <fullName>Refer_to_JEU__c</fullName>
    <description>Use this to set the status of the JEU Referral.  Other information may be required based on the selection.</description>
    <inlineHelpText>Use this to set the status of the JEU Referral.  Other information may be required based on the selection.</inlineHelpText>
    <label>Refer to JEU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/JEU.recordType-meta.xml
<RecordType>
    <fullName>JEU</fullName>
    <active>true</active>
    <description>JEU Cases, may or may not be affiliated with BOFE, WCA or RCI cases.</description>
    <label>JEU</label>
</RecordType>

force-app/main/default/objects/Hearing__c/Hearing__c.object-meta.xml
<CustomObject>
    <description>This stores all of the hearings/conferences related to an Appeal, which gets information from the Assessment, Liability Appeal, Case, and Account from a relationship level.</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Meeting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hearing__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Lookup to parent case. Used for easy identification and for rules related to referrals that deal with hearing dates.</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Hearings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Hearing_Date__c.field-meta.xml
<CustomField>
    <fullName>Hearing_Date__c</fullName>
    <label>Legacy Meeting Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Key_Value_Store__c/Key_Value_Store__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores keys and associated values for use in code so that changes can be made without modifying code whenever possible.</description>
    <label>Key Value Store</label>
</CustomObject>

force-app/main/default/objects/Key_Value_Store__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value associated with the key ( Name field )</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <description>This object stores the payment plan information for a Liability, tied to a Liable Party for a Citation.</description>
    <label>Payment Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Payment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Case to which this payment plan belongs.</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Payment_Plan_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Not Current</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DIRCaseAllHelper.cls
public with sharing class DIRCaseAllHelper {

	public static boolean stopAffiliationCreation = false;

	public static void AddErrorsToCase(List<DIR_Case__c> cases) {
		
		Set<Id> caseIds = new Set<Id>();
		for (DIR_Case__c cs : cases) {
			if (cs.Refer_to_JEU__c == 'Referred') {
				caseIds.add(cs.Id);
			}
		}
		
		Map<Id, AggregateResult> PaymentPlans = new Map<Id, AggregateResult>([SELECT Case__c Id, COUNT(Id) Number FROM Payment_Plan__c WHERE Case__c IN :caseIds AND Payment_Plan_Status__c = 'Not Current' GROUP BY Case__c]);
		system.debug('PaymentPlans::: ' + PaymentPlans);
        
		//Map<Id, AggregateResult> Hearings = new Map<Id, AggregateResult>([SELECT Case__c Id, MAX(Hearing_Date__c) MaxDate FROM Hearing__c WHERE Case__c IN :caseIds  GROUP BY Case__c]);
		
		integer noDays = 0;
		List<Key_Value_Store__c> keyValueStoreList = [SELECT Id, Value__c FROM Key_Value_Store__c WHERE Name = 'BOFE JEU Referral Hearing Timeframe'];
		if (keyValueStoreList.size() != 0)
			noDays = integer.valueOf(keyValueStoreList.get(0).Value__c);
				
		for (DIR_Case__c cs : cases) {
			if (cs.Refer_to_JEU__c == 'Referred') {
				if (!PaymentPlans.containsKey(cs.Id) & PaymentPlans.size() > 0) {
					cs.addError('All Payment Plans are current for this case, it cannot be referred to JEU');
				}
				/*
				// performing this via flow and standard valication rule now
				if (Hearings.containsKey(cs.Id)) {
					if (Date.today().daysbetween(((DateTime)Hearings.get(cs.Id).get('MaxDate')).Date()) < noDays) {
						cs.addError('A hearing has been scheduled too recently to refer this case to JEU.');
					}
				}
				*/
			}
		}
		
	}

}