force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Low_Wage_Occupation__c.field-meta.xml
<CustomField>
    <fullName>Low_Wage_Occupation__c</fullName>
    <label>Low Wage Occupation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Domestic Worker</fullName>
            </value>
            <value>
                <fullName>Agricultural Employee</fullName>
            </value>
            <value>
                <fullName>Food processing</fullName>
            </value>
            <value>
                <fullName>Garment Employee</fullName>
            </value>
            <value>
                <fullName>Car Wash Employee</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Hotel worker</fullName>
            </value>
            <value>
                <fullName>Residential Care worker</fullName>
            </value>
            <value>
                <fullName>Nail salon worker</fullName>
            </value>
            <value>
                <fullName>Security guard</fullName>
            </value>
            <value>
                <fullName>Day laborer</fullName>
            </value>
            <value>
                <fullName>Other - Paid at minimum wage rate or less</fullName>
            </value>
            <value>
                <fullName>Other - Paid via piece rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Judgment_Dir_Office__mdt/Judgment_Dir_Office__mdt.object-meta.xml
<CustomObject>
    <label>Judgment Dir Office</label>
    <pluralLabel>Judgment Dir Offices</pluralLabel>
</CustomObject>

force-app/main/default/classes/WageClaimSearchController.cls
public class WageClaimSearchController {
	 //public searchClass searchClassObj {get; set;}
    @AuraEnabled
    public static WageClaimWrapperClass getAllPicklist(){
        WageClaimWrapperClass wrapperObj = new WageClaimWrapperClass();
        wrapperObj.dirOffice = getJudgmentDirOffice();
        wrapperObj.lowWage = getLowWageOccupationPicklist();
        return wrapperObj;
    }
    public static List<String> getJudgmentDirOffice() 
    {
        List<String> options = new List<String>();
        for(Judgment_Dir_Office__mdt mdtObj : [SELECT Label FROM Judgment_Dir_Office__mdt Order By Label ASC]){
            options.add(mdtObj.Label);
        }
        return options;
    }
    
    
    public static List<String> getLowWageOccupationPicklist() 
    {
        List<String> options = new List<String>();
        string fieldName = 'Low_Wage_Occupation__c';
        String objectName = 'DIR_Case__c';
        
        Schema.SObjectType s = Schema.getGlobalDescribe().get(objectName) ;
        Schema.DescribeSObjectResult r = s.getDescribe() ;
        Map<String,Schema.SObjectField> fields = r.fields.getMap() ;
        Schema.DescribeFieldResult fieldResult = fields.get(fieldName).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            options.add(pickListVal.getValue());
        } 
        return options;
    }
    
    public class WageClaimWrapperClass{
       
        @AuraEnabled
        public List<String> dirOffice;
        @AuraEnabled
        public List<String> lowWage;
       
    }
}