force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Office_Email__c.field-meta.xml
<CustomField>
    <fullName>Office_Email__c</fullName>
    <description>For "LaborComm...: office email in Conga docs.</description>
    <label>Office Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/OnlineWageClaimThirdPartyWebService.cls
@RestResource(urlMapping='/Owcwebserviceapi/*')
global with sharing class OnlineWageClaimThirdPartyWebService {
    public static String fieldValidationError;
    @HttpPost
    global static void getResponce(){
        OWCThirdPartyModel.NewClaimResponseWrapper responseWrapObj = new OWCThirdPartyModel.NewClaimResponseWrapper();
        RestRequest responseObj = RestContext.request;
        String requestBody = responseObj.requestBody.toString();
        
        try{
            String caseId = OnlineWageClaimThirdPartyAPIController.onlineClaimSubmit(requestBody);
            System.debug('caseId::::::'+caseId);
            System.debug('fieldValidationError::::::'+fieldValidationError);
            if(String.isNotBlank(fieldValidationError)){
                responseWrapObj.message = fieldValidationError;
                responseWrapObj.isSuccess = false;
            }
            else{
                DIR_Case__c caseObj = [SELECT Id, Office__r.Name, Office__r.Office_Email__c, Case_Number__c FROM DIR_Case__c
                                       WHERE Id =: caseId LIMIT 1];
                if(String.isNotBlank(caseId)){
                    responseWrapObj.isSuccess = true;
                    responseWrapObj.message = 'Success';
                    responseWrapObj.caseNumber = caseObj.Case_Number__c;
                    //responseWrapObj.districtOffice = caseObj.Office__r.Name;
                    //responseWrapObj.officeEmail = caseObj.Office__r.Office_Email__c;
                }
                else{
                    responseWrapObj.isSuccess = false;
                    responseWrapObj.message = 'Something went wrong...';
                }
            }
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(responseWrapObj));
        }
        catch(Exception e){
            RestContext.response.addHeader('Content-Type', 'text/plain');
            RestContext.response.responseBody = Blob.valueOf(e.getMessage());
        }
    }
}