force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <description>Bank name</description>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee's manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Online_Claim_Draft__c/Online_Claim_Draft__c.object-meta.xml
<CustomObject>
    <label>Online Claim Draft</label>
    <nameField>
        <displayFormat>OWCD-{0000000000}</displayFormat>
        <label>Online Claim Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Claim Drafts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Online_Claim_Draft__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Online Claim Drafts</relationshipLabel>
    <relationshipName>Online_Claim_Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Online_Claim_Draft__c/fields/Draft_JSON__c.field-meta.xml
<CustomField>
    <fullName>Draft_JSON__c</fullName>
    <label>Draft JSON</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Online_Claim_Draft__c/fields/Section_Id__c.field-meta.xml
<CustomField>
    <fullName>Section_Id__c</fullName>
    <label>Section Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OWCSaveDraftControllerTest.cls
@isTest
public class OWCSaveDraftControllerTest {
    @testSetup static void setUpMethod() {
        Online_Claim_Draft__c owcDraftList = new Online_Claim_Draft__c();
        owcDraftList.Section_Id__c = '1';
        owcDraftList.Draft_JSON__c = 'Test Demo area';
        insert owcDraftList;
        
        List<Trigger_Settings__c> triggerSettings = new List<Trigger_Settings__c>();
        Trigger_Settings__c rctTriggerSetting = new Trigger_Settings__c(
            Name = 'Receipt Trigger',
            Is_Active__c = true
        );
        triggerSettings.add(rctTriggerSetting);
        
        Trigger_Settings__c GenerateFieldHistoryActionTriggerSetting = new Trigger_Settings__c(
            Name = 'GenerateFieldHistoryAction',
            Is_Active__c = true
        );
        
        triggerSettings.add(GenerateFieldHistoryActionTriggerSetting);
        insert triggerSettings;
        
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.User__c = UserInfo.getUserId();
        de.Position__c = 'Deputy';
        de.Manager__c = ma.Id;
        insert de; 
        
        RecordType caseRT = [SELECT Id FROM RecordType WHERE sObjectType = 'DIR_Case__c' AND DeveloperName = 'WCA' AND IsActive = true LIMIT 1];
        
        DIR_Case__c dirCase = new DIR_Case__c(
            RecordTypeId = caseRT.Id,            
            Assigned_Deputy__c = de.Id
        );
        insert dirCase;
    }
    @istest 
    public static void getDraftRecordsTestOne(){
        Online_Claim_Draft__c  owcDraftListGetRecord  = [SELECT Id, Name, Draft_JSON__c, Section_Id__c, Case_Management__c FROM Online_Claim_Draft__c];
        DIR_Case__c getDemoCase = [SELECT Id, Name, Bank__c FROM DIR_Case__c]; 
        String recordId = owcDraftListGetRecord.Id;
        String sectionId = owcDraftListGetRecord.Section_Id__c;
        String caseId = getDemoCase.Id;
        String onlineClaimDetails = owcDraftListGetRecord.Draft_JSON__c;
        Test.startTest();
        OWCSaveDraftController.wrapperMsgObj getReturnRecordIfCase = OWCSaveDraftController.createOWCJSONResponse(onlineClaimDetails,sectionId,recordId);
        Online_Claim_Draft__c getOWCJSONResponseTest = OWCSaveDraftController.getOWCJSONResponse(recordId);
        //Online_Claim_Draft__c getOWCSubmittedResponseDataTest = OWCSaveDraftController.getOWCSubmittedJSONResponse(caseId);
        Test.stopTest();
        System.assert(getOWCJSONResponseTest != Null);
        //System.assert(getOWCSubmittedResponseDataTest != Null);
        System.assert(getReturnRecordIfCase != Null);
    }
    @istest 
    public static void getDraftRecordsTestTwo(){
        Online_Claim_Draft__c  owcDraftListGetRecord  = [SELECT Id, Name, Draft_JSON__c, Section_Id__c, Case_Management__c FROM Online_Claim_Draft__c];
        DIR_Case__c getDemoCase = [SELECT Id, Name, Bank__c FROM DIR_Case__c]; 
        String recordIdNull = Null;
        String sectionId = owcDraftListGetRecord.Section_Id__c;
        String caseId = getDemoCase.Id;
        String onlineClaimDetails = owcDraftListGetRecord.Draft_JSON__c;
        Test.startTest();
        OWCSaveDraftController.wrapperMsgObj getReturnRecordElseCase = OWCSaveDraftController.createOWCJSONResponse(onlineClaimDetails,sectionId,recordIdNull);
        Test.stopTest();
        System.assert(getReturnRecordElseCase != Null);
    }
}