force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Employee_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_First_Name__c</fullName>
    <inlineHelpText>Do not enter a name in this box if it is blank. Later if you need to make a change to the Case Name, then edit the name in this box. Note: Editing the name in this box does not change the Account Name.</inlineHelpText>
    <label>Employee First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employee_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Last_Name__c</fullName>
    <inlineHelpText>Do not enter a name in this box if it is blank. Later if you need to make a change to the Case Name, then edit the name in this box. Note: Editing the name in this box does not change the Account Name.</inlineHelpText>
    <label>Employee Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Import__c/Import__c.object-meta.xml
<CustomObject>
    <description>Used for imports requiring a batch job due to the size of the file to be imported and the downstream processes. This is to prevent dml and cpu errors</description>
    <label>Import</label>
    <nameField>
        <displayFormat>im-{00000}</displayFormat>
        <label>Import ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Import__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>related case</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Imports</relationshipLabel>
    <relationshipName>Imports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/Employee_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_First_Name__c</fullName>
    <label>Employee First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/Employee_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Last_Name__c</fullName>
    <label>Employee Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/Employee_Street__c.field-meta.xml
<CustomField>
    <fullName>Employee_Street__c</fullName>
    <label>Employee Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/Employee_Zip__c.field-meta.xml
<CustomField>
    <fullName>Employee_Zip__c</fullName>
    <label>Employee Zip</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/form40ImportControllerTest.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/

@isTest
private class form40ImportControllerTest {
    
    static testMethod void importData() {

        List<Trigger_Settings__c> triggerSettings = new List<Trigger_Settings__c>();
        Trigger_Settings__c cpTriggerSetting = new Trigger_Settings__c(
            Name = 'CasePaymentTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(cpTriggerSetting);
        
        Trigger_Settings__c caseRoleAllTriggerSetting = new Trigger_Settings__c(
            Name = 'CaseRoleAll',
            Is_Active__c = false
        );
        triggerSettings.add(caseRoleAllTriggerSetting);
            
        Trigger_Settings__c dlrs_DIR_ViolationTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_DIR_ViolationTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(dlrs_DIR_ViolationTriggerSetting);

        Trigger_Settings__c dlrs_JudgementTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_JudgementTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(dlrs_JudgementTriggerSetting);

        Trigger_Settings__c generateFieldHistoryActionTriggerSetting = new Trigger_Settings__c(
            Name = 'GenerateFieldHistoryAction',
            Is_Active__c = false
        );
        triggerSettings.add(generateFieldHistoryActionTriggerSetting);

        Trigger_Settings__c liabilityPaymentTriggerSetting = new Trigger_Settings__c(
            Name = 'LiabilityPaymentTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(liabilityPaymentTriggerSetting);

        Trigger_Settings__c receiptTriggerSetting = new Trigger_Settings__c(
            Name = 'ReceiptTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(receiptTriggerSetting);
        insert triggerSettings;

        
        List<StaticResource> csvData = [select id, name, body from StaticResource where name = 'form40TestCSV']; 
        
        Id accRTID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id accRTID2 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();

        Account acc = new Account();
        acc.recordtypeid = accRTID;
        acc.name = 'testAccount';        
        insert acc;
        
        Account acc2 = new Account();
        acc2.recordtypeid = accRTID2;
        acc2.FirstName = 'testName';  
        acc2.LastName  = 'TestlastName'; 
        acc2.ShippingStreet = 'testStreet'; 
        acc2.ShippingPostalCode  = 'testZip';       
        insert acc2;

        Dir_Case__c dirCase = new Dir_Case__c();
        dirCase.employer__c = acc.id;        
        insert dirCase;

        Dir_Case__c dirCase2 = new Dir_Case__c();
        dirCase2.employer__c = acc2.id;        
        insert dirCase2;
        
        Import__c newImport = new Import__c();
        newImport.Case_Management__c = dirCase.Id;
        insert newImport;

        Import__c newImport2 = new Import__c();
        newImport2.Case_Management__c = dirCase.Id;
        newImport2.Employee_First_Name__c = 'testName';
        newImport2.Employee_Last_Name__c = 'TestlastName';
        newImport2.Employee_Zip__c = 'testZip';
        newImport2.Employee_Street__c = 'testStreet';
        insert newImport2;

        Import__c newImport3 = new Import__c();
        newImport3.Case_Management__c = dirCase.Id;
        newImport3.Employee_First_Name__c = 'testName1';
        newImport3.Employee_Last_Name__c = 'TestlastName1';
        newImport3.Employee_Zip__c = 'testZip1';
        newImport3.Employee_Street__c = 'testStreet1';
        insert newImport3;

        PageReference testPage = Page.form40Import;
        testPage.getParameters().put('id', dirCase.id);
        
        Test.setCurrentPage(testPage);
        
        form40ImportController cont = new form40ImportController();
        cont.nameFile = 'form40TestCSV.csv';
        cont.contentFile = csvData[0].body;
        
        form40ImportController cont2 = new form40ImportController();
        cont2.nameFile = 'form40TestCSV.csv';
        cont2.contentFile = csvData[0].body;

        Test.StartTest();
        
        cont.ImportFile();
        cont.ProcessFile();
        
        cont2.ImportFile();
        
        Test.StopTest();
        
        
    }
    
}