force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Violation_Type__c.field-meta.xml
<CustomField>
    <fullName>Violation_Type__c</fullName>
    <label>Violation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agricultural Labor Relations</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Labor Code 3070 – 3098</fullName>
            </value>
            <value>
                <fullName>Child Labor</fullName>
            </value>
            <value>
                <fullName>Classified as Independent Contractor</fullName>
            </value>
            <value>
                <fullName>Improper or Incomplete Wage Statements</fullName>
            </value>
            <value>
                <fullName>Improper payment form incl. NSF check</fullName>
            </value>
            <value>
                <fullName>Industrial Homework</fullName>
            </value>
            <value>
                <fullName>Kickbacks</fullName>
            </value>
            <value>
                <fullName>Lactation Accommodation (LC 1030‐1033)</fullName>
            </value>
            <value>
                <fullName>Licensing, Registration or Permit</fullName>
            </value>
            <value>
                <fullName>Meal and Rest Breaks</fullName>
            </value>
            <value>
                <fullName>Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Nonexempt Classified as Exempt</fullName>
            </value>
            <value>
                <fullName>Not paid for all hours worked</fullName>
            </value>
            <value>
                <fullName>Not Paid Wages Due on Termination</fullName>
            </value>
            <value>
                <fullName>Not providing required time off, other</fullName>
            </value>
            <value>
                <fullName>No Wage Statements</fullName>
            </value>
            <value>
                <fullName>No Workers’ Compensation</fullName>
            </value>
            <value>
                <fullName>Occupational SAFE HLTH (LC 6300 et seq)</fullName>
            </value>
            <value>
                <fullName>Other Notice or Posting or Recordkeeping</fullName>
            </value>
            <value>
                <fullName>Other Unpaid Wages</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Pay Discrim on basis of sex (LC1197.5)</fullName>
            </value>
            <value>
                <fullName>PMNT Reimbursement of Empl Expenses</fullName>
            </value>
            <value>
                <fullName>Public Works (Labor Code §§ 1720 – 1815)</fullName>
            </value>
            <value>
                <fullName>Retaliation - Protected Status Activity</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Tips or Gratuities</fullName>
            </value>
            <value>
                <fullName>Unfair Immigration Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Garment Cases</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Defines if a role is currently active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee's manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Position on Loan</fullName>
            </value>
            <value>
                <fullName>Temporarily Vacant</fullName>
            </value>
            <value>
                <fullName>Abolished</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>607 Pending Finance Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NewViolationTest.cls
@isTest(SeeAllData=true)
public with sharing class NewViolationTest {
    
    private static Id gRT = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('Garment').getRecordTypeId();
    
    public static testMethod void TestNewViolation1() {
        
        Trigger_Settings__c triggerSettings = Trigger_Settings__c.getInstance('GenerateFieldHistoryAction');
        triggerSettings.Is_Active__c = false;
        update triggerSettings;

        Account a = new Account();
        a.Name = 'Lucian395274';
        insert a;
        
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.User__c = UserInfo.getUserId();
        de.Position__c = 'Deputy';
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Case__c cm = new DIR_Case__c();
        //cm.recordTypeId = gRT;
        cm.Employer__c = a.Id;
        cm.Status__c = 'Open';
        cm.Assigned_Deputy__c = de.Id;
        cm.RecordtypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        insert cm;
        
        Violation_Type__c vt = new Violation_Type__c();
        vt.RecordTypeId = Schema.SObjectType.Violation_Type__c.getRecordTypeInfosByName().get('WCA Issues - New').getRecordTypeId();
        vt.Appeal_Deadline_Days__c = 12;
        vt.Active__c = true;
        vt.Appeal_Deadline_Selector__c = 'Business Days';
        insert vt;
        
        Violation_Type_Variable__c vtv = new Violation_Type_Variable__c();
        vtv.Violation_Type__c = vt.Id;
        vtv.Data_Type__c = 'Text';
        vtv.Description__c = 'test';
        vtv.value__c = '100';
        insert vtv;
        
        vtv = [SELECT Id, Name, Violation_Type__c, Data_Type__c, Description__c, value__c FROM Violation_Type_Variable__c WHERE Id =: vtv.Id];
        
        vt.Assessment_Formula__c = vtv.Name + '+' + vtv.Name;
        vt.Penalty_Assessment_Description__c = 'test Assess desc {~'+vtv.Name +'~+~'+vtv.Name + '~}';
        vt.Wage_Assessment_Formula__c = vtv.Name + '+' + vtv.Name;
        vt.Wage_Assessment_Description__c = 'test Wage desc ~'+vtv.Name + '~';
        
        update vt;
        
        test.startTest();
        
        ApexPages.currentPage().getParameters().put('id', cm.Id);
        NewViolation newV = new NewViolation ();
        newV.LoadCase();
        newV.violationId = vt.Id;
        newV.selectedTypes.add(new NewViolation.ViolationTypeWrapper(vt, newV.wrapperIndex++));
        newV.selectedTypes[0].vtvWrapperList = new List<NewViolation.violationTypeVarWrapper>();
        newV.selectedTypes[0].vtvWrapperList.add(new NewViolation.violationTypeVarWrapper(vtv, newV.wrapperIndex++));
        newV.addViolation();
        
        ApexPages.currentPage().getParameters().put('id', cm.Id);
        newViolation newV2 = new newViolation ();
        newV2.LoadCase();
        newV2.violationId = vt.Id;
        newV2.addViolation();
        
        newV2.selectedTypes.clear();
        newV2.selectedTypes.add(new NewViolation.ViolationTypeWrapper(vt, newV2.wrapperIndex++));
        newV2.selectedTypes[0].vtvWrapperList = new List<NewViolation.violationTypeVarWrapper>();
        newV2.selectedTypes[0].vtvWrapperList.add(new NewViolation.violationTypeVarWrapper(vtv, newV2.wrapperIndex++));
        
        String s1 = newV2.selectedTypes[0].wageFormula;
        String s2 = newV2.selectedTypes[0].formula;
        String s3 = newV2.selectedTypes[0].amountPaidFormula;
        String s4 = newV2.selectedTypes[0].amountEarnedFormula;
        
        newV2.GoToSecondStep();
        
        newV2.Liabilities[0].selected = true;
        newV2.Liabilities[0].propShare = '100';
        newV2.Liabilities[0].acc = a;
        newV2.valueString = ''
            + String.valueOf(newV2.SelectedTypes[0].indexCounter) + String.valueOf(newV2.SelectedTypes[0].vtvWrapperList[0].indexCounter) + ':' + '100' 
            + '::'+String.valueOf(newV2.SelectedTypes[0].indexCounter)+'TOTALA:10' 
            + '::'+String.valueOf(newV2.SelectedTypes[0].indexCounter)+'TOTALW:20'
            + '::'+String.valueOf(newV2.SelectedTypes[0].indexCounter)+'TOTALIW:30'
            + '::'+String.valueOf(newV2.SelectedTypes[0].indexCounter)+'AMTP:40'
            + '::'+String.valueOf(newV2.SelectedTypes[0].indexCounter)+'AMTE:50';
        newV2.SelectedCitation = 'Single';
        newV2.Finalize();
        newV2.SelectedCitation = 'Multiple';
        newV2.Finalize();
        
        newV2.violationIndex = string.valueOf(newV2.SelectedTypes[0].indexCounter);
        newV2.removeViolation();
        newV2.BackTo1stStep();
        newV2.getCitationItems();
        newV2.SearchEmployee();
        newV2.SelectEmployee();
        boolean testb = newV2.getRTError;
        integer testInt = newV2.SelectedSize;
        newV2.emptyMethod();
        
        test.stopTest();
    }
    
    /////////////////////////////////
    public static testMethod void TestNewViolation2() {
        
        Trigger_Settings__c triggerSettings = Trigger_Settings__c.getInstance('GenerateFieldHistoryAction');
        triggerSettings.Is_Active__c = false;
        update triggerSettings;

        Account a = new Account();
        a.Name = 'Lucian395274';
        insert a;
        
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.User__c = UserInfo.getUserId();
        de.Position__c = 'Deputy';
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Case__c cm = new DIR_Case__c();
        //cm.recordTypeId = gRT;
        cm.Employer__c = a.Id;
        cm.Status__c = 'Open';
        cm.Assigned_Deputy__c = de.Id;
        cm.RecordtypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
        insert cm;
        
        Violation_Type__c vt = new Violation_Type__c();
        vt.RecordTypeId = Schema.SObjectType.Violation_Type__c.getRecordTypeInfosByName().get('BOFE Violations').getRecordTypeId();
        vt.Appeal_Deadline_Days__c = 12;
        vt.Active__c = true;
        vt.Appeal_Deadline_Selector__c = 'Business Days';
        vt.Civil_Penalty_Section__c = '';
        vt.Wizard_Search_Text__c = 'any text';
        vt.Name = 'L.C. 238(f) – Subsequent Violations';
        insert vt;
        
        Violation_Type_Variable__c vtv = new Violation_Type_Variable__c();
        vtv.Violation_Type__c = vt.Id;
        vtv.Data_Type__c = 'Text';
        vtv.Description__c = 'test';
        vtv.value__c = '100';
        insert vtv;
        
        vtv = [SELECT Id, Name, Violation_Type__c, Data_Type__c, Description__c, value__c FROM Violation_Type_Variable__c WHERE Id =: vtv.Id];
        
        vt.Assessment_Formula__c = vtv.Name + '+' + vtv.Name;
        vt.Penalty_Assessment_Description__c = 'test Assess desc {~'+vtv.Name +'~+~'+vtv.Name + '~}';
        vt.Wage_Assessment_Formula__c = vtv.Name + '+' + vtv.Name;
        vt.Wage_Assessment_Description__c = 'test Wage desc ~'+vtv.Name + '~';
        
        update vt;
        
        test.startTest();
        
        ApexPages.currentPage().getParameters().put('id', cm.Id);
        NewViolation newV = new NewViolation ();
        newV.LoadCase();
        newV.violationId = vt.Id;
        newV.selectedTypes.add(new NewViolation.ViolationTypeWrapper(vt, newV.wrapperIndex++));
        newV.selectedTypes[0].vtvWrapperList = new List<NewViolation.violationTypeVarWrapper>();
        newV.selectedTypes[0].vtvWrapperList.add(new NewViolation.violationTypeVarWrapper(vtv, newV.wrapperIndex++));
        newV.addViolation();
        
        ApexPages.currentPage().getParameters().put('id', cm.Id);
        newViolation newV2 = new newViolation ();
        newV2.LoadCase();
        newV2.violationId = vt.Id;
        newV2.addViolation();
        
        newV2.selectedTypes.clear();
        newV2.selectedTypes.add(new NewViolation.ViolationTypeWrapper(vt, newV2.wrapperIndex++));
        newV2.selectedTypes[0].vtvWrapperList = new List<NewViolation.violationTypeVarWrapper>();
        newV2.selectedTypes[0].vtvWrapperList.add(new NewViolation.violationTypeVarWrapper(vtv, newV2.wrapperIndex++));
        
        String s1 = newV2.selectedTypes[0].wageFormula;
        String s2 = newV2.selectedTypes[0].formula;
        String s3 = newV2.selectedTypes[0].amountPaidFormula;
        String s4 = newV2.selectedTypes[0].amountEarnedFormula;
        
        newV2.GoToSecondStep();
        
        newV2.Liabilities[0].selected = true;
        newV2.Liabilities[0].propShare = '100';
        newV2.Liabilities[0].acc = a;
        newV2.valueString = ''
            + String.valueOf(newV2.SelectedTypes[0].indexCounter) + String.valueOf(newV2.SelectedTypes[0].vtvWrapperList[0].indexCounter) + ':' + '100' 
            + '::'+String.valueOf(newV2.SelectedTypes[0].indexCounter)+'TOTALA:10' 
            + '::'+String.valueOf(newV2.SelectedTypes[0].indexCounter)+'TOTALW:20'
            + '::'+String.valueOf(newV2.SelectedTypes[0].indexCounter)+'TOTALIW:30';
        newV2.SelectedCitation = 'Single';
        newV2.Finalize();
        newV2.SelectedCitation = 'Multiple';
        newV2.Finalize();
        
        newV2.violationIndex = string.valueOf(newV2.SelectedTypes[0].indexCounter);
        newV2.removeViolation();
        newV2.BackTo1stStep();
        newV2.getCitationItems();
        newV2.SearchEmployee();
        newV2.SelectEmployee();
        boolean testb = newV2.getRTError;
        integer testInt = newV2.SelectedSize;
        newV2.emptyMethod();
        
        test.stopTest();
    }
    
    /////////////////////////////////
    public static testMethod void TestNewViolation3() {
        
        Trigger_Settings__c triggerSettings = Trigger_Settings__c.getInstance('GenerateFieldHistoryAction');
        triggerSettings.Is_Active__c = false;
        update triggerSettings;
        
        Account a = new Account();
        a.Name = 'Lucian395274';
        insert a;
        
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.User__c = UserInfo.getUserId();
        de.Position__c = 'Deputy';
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Case__c cm = new DIR_Case__c();
        //cm.recordTypeId = gRT;
        cm.Employer__c = a.Id;
        cm.Status__c = 'Open';
        cm.Assigned_Deputy__c = de.Id;
        cm.RecordtypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE Intake').getRecordTypeId();
        insert cm;
        
        Violation_Type__c vt = new Violation_Type__c();
        vt.RecordTypeId = Schema.SObjectType.Violation_Type__c.getRecordTypeInfosByName().get('BOFE Violations').getRecordTypeId();
        vt.Appeal_Deadline_Days__c = 12;
        vt.Active__c = true;
        vt.Appeal_Deadline_Selector__c = 'Business Days';
        vt.Civil_Penalty_Section__c = 'L.C. 3722(a)';
        vt.Wizard_Search_Text__c = 'BOFE 335';
        insert vt;
        
        Violation_Type__c vt2 = new Violation_Type__c();
        vt2.RecordTypeId = Schema.SObjectType.Violation_Type__c.getRecordTypeInfosByName().get('BOFE Violations').getRecordTypeId();
        vt2.Appeal_Deadline_Days__c = 12;
        vt2.Active__c = true;
        vt2.Appeal_Deadline_Selector__c = 'Business Days';
        vt2.Civil_Penalty_Section__c = 'L.C. 3710.1';
        vt2.Wizard_Search_Text__c = 'BOFE 335';
        insert vt2;
        
        Violation_Type_Variable__c vtv = new Violation_Type_Variable__c();
        vtv.Violation_Type__c = vt.Id;
        vtv.Data_Type__c = 'Text';
        vtv.Description__c = 'test';
        vtv.value__c = '100';
        insert vtv;
        
        vtv = [SELECT Id, Name, Violation_Type__c, Data_Type__c, Description__c, value__c FROM Violation_Type_Variable__c WHERE Id =: vtv.Id];
        
        vt.Assessment_Formula__c = vtv.Name + '+' + vtv.Name;
        vt.Penalty_Assessment_Description__c = 'test Assess desc {~'+vtv.Name +'~+~'+vtv.Name + '~}';
        vt.Wage_Assessment_Formula__c = vtv.Name + '+' + vtv.Name;
        vt.Wage_Assessment_Description__c = 'test Wage desc ~'+vtv.Name + '~';
        
        update vt;
        
        
  
        test.startTest();
        
        ApexPages.currentPage().getParameters().put('id', cm.Id);
        NewViolation newV = new NewViolation ();
        newV.LoadCase();
        newV.violationId = vt.Id;
        newV.selectedTypes.add(new NewViolation.ViolationTypeWrapper(vt, newV.wrapperIndex++));
        newV.selectedTypes[0].vtvWrapperList = new List<NewViolation.violationTypeVarWrapper>();
        newV.selectedTypes[0].vtvWrapperList.add(new NewViolation.violationTypeVarWrapper(vtv, newV.wrapperIndex++));
        newV.addViolation();
        
    
        test.stopTest();
    }
}