force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for Archiving Content Document in OB Archiver</description>
    <label>Archive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Closed_Date__c</fullName>
    <description>Case Closed Date</description>
    <inlineHelpText>The date on which a case was finally closed</inlineHelpText>
    <label>Case Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Total_Interest_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Balance_Due__c</fullName>
    <formula>Total_Interest_Assessed__c - Total_Interest_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Balance of interest due on case issues on this case.</inlineHelpText>
    <label>Total Interest Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Total_Penalties_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Penalties_Balance_Due__c</fullName>
    <description>Calculates the balance due from the rolled up values</description>
    <formula>Total_Penalties_Assessed__c -  Total_Penalty_Payments_Received1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance of Civil Penalties Due to State</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Total_Wages_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Wages_Balance_Due__c</fullName>
    <formula>Total_Wage_Penalties__c + Total_Wage_Interest_Amount__c - Total_Wage_Payments_Received1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount Payable To Employee(s) + Total Wage Interest Amount - Total Paid By Defendant(s)</inlineHelpText>
    <label>Balance Due to Employee(s)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ScheduleDIRCaseArchiveBatch.cls
global class ScheduleDIRCaseArchiveBatch Implements Schedulable {
    
    // Seconds  Minutes  Hours  Day_of_month  Month  Day_of_week  optional_year
    // runs a scheduled job at midnight July. 1st. every year
    
    public static String CRON_SCHEDULE = '0 0 0 7 1 ?';
    
    global void execute (SchedulableContext sc)
    {
        archiveBOFEAplus();
    }
    
    public void archiveBOFEAplus(){
        string q = 'SELECT Id, Archive__c from DIR_Case__c WHERE Status__c = \'Closed\'' +
            ' AND ' + 'Case_Closed_Date__c < LAST_N_DAYS:366' + ' AND ' + 'Total_Penalties_Balance_Due__c = 0.00' +
            ' AND ' + 'Total_Wages_Balance_Due__c = 0.00' + ' AND ' + 'Total_Interest_Balance_Due__c = 0.00' +
            ' AND ' + 'Archive__c = False' + ' AND ' + 'RecordType.Name LIKE \'%BOFE%\'' + ' LIMIT 20000';    
        
        Id job = Database.executeBatch(new DIRCaseArchiveBatch(q),50);
    }
}