force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for Archiving Content Document in OB Archiver</description>
    <label>Archive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Closed_Date__c</fullName>
    <description>Case Closed Date</description>
    <inlineHelpText>The date on which a case was finally closed</inlineHelpText>
    <label>Case Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Total_Interest_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Balance_Due__c</fullName>
    <formula>Total_Interest_Assessed__c - Total_Interest_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Balance of interest due on case issues on this case.</inlineHelpText>
    <label>Total Interest Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Total_Penalties_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Penalties_Balance_Due__c</fullName>
    <description>Calculates the balance due from the rolled up values</description>
    <formula>Total_Penalties_Assessed__c -  Total_Penalty_Payments_Received1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance of Civil Penalties Due to State</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Total_Wages_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Wages_Balance_Due__c</fullName>
    <formula>Total_Wage_Penalties__c + Total_Wage_Interest_Amount__c - Total_Wage_Payments_Received1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount Payable To Employee(s) + Total Wage Interest Amount - Total Paid By Defendant(s)</inlineHelpText>
    <label>Balance Due to Employee(s)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DIRCaseArchiveBatch.cls
/*

*/
global without sharing class DIRCaseArchiveBatch implements Database.Batchable<sObject>, Database.Stateful { 
    
    public list<DIR_Case__c> scope = new list<DIR_Case__c> ();
    public static Boolean dirCaseArchive = true;
    public String query;
    
    
    public DIRCaseArchiveBatch(String q) {
        
        this.query = q;
    }
    
    global Database.QueryLocator start(Database.BatchableContext info){
        /*
        string q = 'SELECT Id, Archive__c from DIR_Case__c WHERE Status__c = \'Closed\'' +
            ' AND ' + 'Case_Closed_Date__c < LAST_N_DAYS:366' + ' AND ' + 'Total_Penalties_Balance_Due__c = 0.00' +
            ' AND ' + 'Total_Wages_Balance_Due__c = 0.00' + ' AND ' + 'Total_Interest_Balance_Due__c = 0.00';
		*/
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext info, List<sObject> scopeX){
        List<DIR_Case__c> objList = (List<DIR_Case__c>)scopeX;
        System.debug('DIRCaseArchiveBatchexecute');     
        for(DIR_Case__c ci : objList) {
            if(dirCaseArchive){
                ci.Archive__c = true;
            }
            
            scope.add(ci);
        }
        if(dirCaseArchive){
            update objList;
        }
        
    }
    
    global void finish(Database.BatchableContext info) {
        System.debug('DIRCaseArchive Batch Finish');
        //Chains ContentDocumentArchiveBatch to update Aplus records, and Content Document Title.
        Database.executeBatch(new ContentDocumentArchiveBatch(scope),100);
        
        
        AsyncApexJob job = [Select Id, ApexClassId, CompletedDate, CreatedBy.Email, CreatedBy.Name,
                            CreatedDate, JobItemsProcessed, JobType, NumberOfErrors, Status, 
                            TotalJobItems from AsyncApexJob where Id = :info.getJobId()];
        
        // Send an email to the Apex job's submitter notifying of job completion.
        sendJobCompleteEmail(job);
        
    }
   
    private void sendJobCompleteEmail(AsyncApexJob job) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {job.CreatedBy.Email};
            String html = ''
            + '<table style="font: normal 12px verdana;" border="1" cellpadding="5" cellspacing="0" width="100%">'
            + '<tr style="font-weight: bold">'
            + '<td>Total Job Items</td>'
            + '<td>Job Items Processed</td>'
            + '<td>Number of Errors</td>'
            + '<td>Status</td>'
            + '<td>Job Type</td>'
            + '<td>Created By</td>'
            + '<td>Created Date</td>'
            + '<td>Completed Date</td>'
            + '</tr>'
            + '<tr>'
            + '<td>' + job.TotalJobItems + '</td>'
            + '<td>' + job.JobItemsProcessed + '</td>'
            + '<td>' + job.NumberOfErrors + '</td>'
            + '<td>' + job.Status + '</td>'
            //+ '<td><a href="https://login.salesforce.com/' + job.ApexClassId + '">' + job.ApexClassId + '</a></td>'
            + '<td>' + job.JobType + '</td>'
            + '<td>' + job.CreatedBy.Name + '</td>'
            + '<td>' + job.CreatedDate + '</td>'
            + '<td>' + job.CompletedDate + '</td>'
            + '</tr>'
            + '</table>'
            + '<br/>';
        mail.setToAddresses(toAddresses);
        mail.setSubject('DIR Case Archive Batch - ' + job.Status);
        mail.setHtmlBody(html);
        if (!Test.isRunningTest()) {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
    
}