force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Cash_Balance_on_Case__c.field-meta.xml
<CustomField>
    <fullName>Cash_Balance_on_Case__c</fullName>
    <description>Difference of deposited funds and checks written against deposits.</description>
    <formula>Deposited_Funds__c - Funds_Drawn_on_Deposits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cash Balance on Case</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Deposited_Funds__c.field-meta.xml
<CustomField>
    <fullName>Deposited_Funds__c</fullName>
    <description>Populated by Case Payment Flow, after "Query All CPs Under A Case." Totals up all the eligible Case Payments for this Case for which funds were deposited into DLSE Office Accounts.
Also indirectly populated by CashNightlyRollup scheduled Apex class as that triggers the CP Flow.</description>
    <inlineHelpText>Total of deposited Case Payments on this Case.</inlineHelpText>
    <label>Deposited Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Funds_Drawn_on_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Funds_Drawn_on_Deposits__c</fullName>
    <description>Sum of all applicable Warrants on this Case. Populated by Warrant Flow. Also populated by the CashNightlyRollup scheduled Apex class.</description>
    <inlineHelpText>Sum of all applicable Disbursements on this Case.</inlineHelpText>
    <label>Funds Drawn on Deposits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Warrants_Pending__c.field-meta.xml
<CustomField>
    <fullName>Warrants_Pending__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Warrants requested for the given amount and waiting to be approved and printed.</description>
    <label>Warrants Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/Payment_Record__c.object-meta.xml
<CustomObject>
    <label>Payment Record</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Record__c/fields/Batched_Under_Warrant__c.field-meta.xml
<CustomField>
    <fullName>Batched_Under_Warrant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by Wage_Payable_Balance, Wage_Interest_Payable_Balance, Penalty_Payable_Balance, and Interest_Other_Payable_Balance roll up summary fields on Payee__c. Populated by ?</description>
    <label>Batched Under Warrant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Payee__r.Case_Management__r.Case_Number__c</formula>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Cash_Balance_on_Case__c.field-meta.xml
<CustomField>
    <fullName>Cash_Balance_on_Case__c</fullName>
    <formula>Payee__r.Case_Management__r.Cash_Balance_on_Case__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cash Balance on Case</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Disbursement_Type__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Type__c</fullName>
    <description>This should match the Disbursement Type on the parent Warrant. Populated by the Warrant generation automation. Used for generating the UWF schedule.</description>
    <label>Disbursement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Attorney Fees</fullName>
            </value>
            <value>
                <fullName>BOFE Penalty</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
            <value>
                <fullName>CAC Payment</fullName>
            </value>
            <value>
                <fullName>Certified Payroll Fee (CPR)</fullName>
            </value>
            <value>
                <fullName>Conceded</fullName>
            </value>
            <value>
                <fullName>Court Costs</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>EDD Payment</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>IRS</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Over payment</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Photo Copy Fee</fullName>
            </value>
            <value>
                <fullName>Plaintiff</fullName>
            </value>
            <value>
                <fullName>Redemption of Check (NSF)</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Refund Certified Payroll Fee (CPR)</fullName>
            </value>
            <value>
                <fullName>Refund Garment Registration</fullName>
            </value>
            <value>
                <fullName>Return Taxes</fullName>
            </value>
            <value>
                <fullName>Return to Defendant</fullName>
            </value>
            <value>
                <fullName>Subpoena Cost Recovery</fullName>
            </value>
            <value>
                <fullName>Tax Lien</fullName>
            </value>
            <value>
                <fullName>To Assignee</fullName>
            </value>
            <value>
                <fullName>Training Fund</fullName>
            </value>
            <value>
                <fullName>Unpaid Wage Fund</fullName>
            </value>
            <value>
                <fullName>Witness Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/UWF_Payee__c.field-meta.xml
<CustomField>
    <fullName>UWF_Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For UWF warrants</description>
    <label>UWF Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payment Records (UWF Payee)</relationshipLabel>
    <relationshipName>Payment_Records_UWF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Warrant__c.field-meta.xml
<CustomField>
    <fullName>Warrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warrant</label>
    <referenceTo>Warrant__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warrant__c/Warrant__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Warrant</label>
    <nameField>
        <displayFormat>WR-{000000}</displayFormat>
        <label>Warrant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warrants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warrant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case Managment object</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Warrants</relationshipLabel>
    <relationshipName>Warrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Case__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Disbursement_Type__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Type__c</fullName>
    <label>Disbursement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Attorney Fees</fullName>
            </value>
            <value>
                <fullName>BOFE Penalty</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
            <value>
                <fullName>CAC Payment</fullName>
            </value>
            <value>
                <fullName>Certified Payroll Fee (CPR)</fullName>
            </value>
            <value>
                <fullName>Conceded</fullName>
            </value>
            <value>
                <fullName>Court Costs</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>EDD Payment</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>IRS</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Over payment</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Photo Copy Fee</fullName>
            </value>
            <value>
                <fullName>Plaintiff</fullName>
            </value>
            <value>
                <fullName>Redemption of Check (NSF)</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Refund Certified Payroll Fee (CPR)</fullName>
            </value>
            <value>
                <fullName>Refund Garment Registration</fullName>
            </value>
            <value>
                <fullName>Return Taxes</fullName>
            </value>
            <value>
                <fullName>Return to Defendant</fullName>
            </value>
            <value>
                <fullName>Subpoena Cost Recovery</fullName>
            </value>
            <value>
                <fullName>Tax Lien</fullName>
            </value>
            <value>
                <fullName>To Assignee</fullName>
            </value>
            <value>
                <fullName>Training Fund</fullName>
            </value>
            <value>
                <fullName>Unpaid Wage Fund</fullName>
            </value>
            <value>
                <fullName>Witness Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Payee to whom the check is written</inlineHelpText>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Warrants</relationshipLabel>
    <relationshipName>Warrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Warrant_Number__c.field-meta.xml
<CustomField>
    <fullName>Warrant_Number__c</fullName>
    <description>The complete check number consist of warrant serial with check digit.</description>
    <formula>Serial_Number__c &amp; TEXT(9-MOD (VALUE (MID (Serial_Number__c, 1, 1))
+ VALUE (MID (Serial_Number__c, 2, 1))
+ VALUE (MID (Serial_Number__c, 3, 1))
+ VALUE (MID (Serial_Number__c, 4, 1))
+ VALUE (MID (Serial_Number__c, 5, 1))
+ VALUE (MID (Serial_Number__c, 6, 1))
+ VALUE (MID (Serial_Number__c, 7, 1))
+ VALUE (MID (Serial_Number__c, 8, 1)),9))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warrant Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WarrantInsertPRUpdateQable.cls
public with sharing class WarrantInsertPRUpdateQable implements Queueable{

    List<Warrant__c> wrsToInsert = new List<Warrant__c>();
    List<Warrant__c> overflowWRs = new List<Warrant__c>();
    List<Payment_Record__c> prsToUpdate = new List<Payment_Record__c>();
    List<Payment_Record__c> prsUpdated = new List<Payment_Record__c>();
    Set<Id> caseId = new Set<Id>();
    List<Id> caseIdList = new List<Id>();
    Map<String, List<Id>> qJobIdMap = new Map<String, List<Id>>();
    String wbURL;
    String reqType;
    Integer maxRows = 100;
    String actType;

    public WarrantInsertPRUpdateQable(List<Warrant__c> wrListToInsert, List<Payment_Record__c> prListToUpdate, String type, String wbLink) {
        wbURL = wbLink;
        reqType = type;
        wrsToInsert = wrListToInsert;
        prsToUpdate = prListToUpdate;
        actType = 'Insert';

        while(wrsToInsert.size() > maxRows){
            overflowWRs.add(wrsToInsert.remove(maxRows));
        }
    }

    public void execute(QueueableContext qc){
        try{
            system.debug('!!!!!!!!!!!!!!!!!! Insert Warrants !!!!!!!!!!!!!!!!!!');
            insert wrsToInsert;
            system.debug('Inserted Warrants ==> ' + wrsToInsert);

            if(reqType == 'RequestWR'){
                for(Warrant__c wr: wrsToInsert){
                    system.debug('For Loop Warrants ==> ' + wr);
                    caseId.add(wr.Case__c);
                    for(Payment_Record__c pr: prsToUpdate){
                        system.debug('For Loop Payment Records ==> ' + wr);
                        system.debug('<====================== wr.Payee <======================' + wr.Payee__c);
                        system.debug('<====================== pr.Payee__c <======================' + pr.Payee__c);
                        system.debug('<====================== wr.Id <======================' + wr.Id);
                        if(wr.Payee__c == pr.Payee__c){
                            pr.Warrant__c = wr.Id;
                            pr.Batched_Under_Warrant__c = true;
                            prsUpdated.add(pr);
                        }
                    }
                }
            }
            else if(reqType == 'reqBOFEwr'){
                for(Warrant__c wr: wrsToInsert){
                    system.debug('For Loop Warrants ==> ' + wr);
                    caseId.add(wr.Case__c);
                    for(Payment_Record__c pr: prsToUpdate){
                        system.debug('For Loop Payment Records ==> ' + wr);
                        system.debug('<====================== wr.Case_Number__c <======================' + wr.Case_Number__c);
                        system.debug('<====================== pr.Case_Number__c <======================' + pr.Case_Number__c);
                        system.debug('<====================== wr.Id <======================' + wr.Id);
                        if(wr.Case_Number__c == pr.Case_Number__c && pr.Payment_Amount__c > 0){
                            pr.Warrant__c = wr.Id;
                            pr.UWF_Payee__c = wr.Payee__c;
                            pr.Batched_Under_Warrant__c = true;
                            pr.Disbursement_Type__c = 'BOFE Penalty';
                            prsUpdated.add(pr);
                        }
                    }
                }
            }
            else if(reqType == 'reqUWFwr'){
                for(Warrant__c wr: wrsToInsert){
                    system.debug('For Loop Warrants ==> ' + wr);
                    caseId.add(wr.Case__c);
                    for(Payment_Record__c pr: prsToUpdate){
                        system.debug('For Loop Payment Records ==> ' + wr);
                        system.debug('<====================== wr.Case_Number__c <======================' + wr.Case_Number__c);
                        system.debug('<====================== pr.Case_Number__c <======================' + pr.Case_Number__c);
                        system.debug('<====================== wr.Id <======================' + wr.Id);
                        if(wr.Case_Number__c == pr.Case_Number__c && pr.Payment_Amount__c > 0){
                            pr.Warrant__c = wr.Id;
                            pr.UWF_Payee__c = wr.Payee__c;
                            pr.Batched_Under_Warrant__c = true;
                            pr.Disbursement_Type__c = 'Unpaid Wage Fund';
                            prsUpdated.add(pr);
                        }
                    }
                }
            }
            

            qJobIdMap.put('Insert Warrants', new List<Id>{qc.getJobId()});

            system.debug('<====================== wbURL <======================' + wbURL);
            if(!overflowWRs.isEmpty()){
                System.enqueueJob(new WarrantInsertPRUpdateQable(overflowWRs, prsToUpdate, reqType, wbURL));
            }
            else{
                system.debug('!!!!!!!!!!!!!!!!!! Case - Warrants Pending !!!!!!!!!!!!!!!!!!');
                caseIdList.addAll(caseId);
                system.debug('Case Ids ==> ' + caseIdList);

                List<DIR_Case__c> caseWarrantList =  new List<DIR_Case__c>([SELECT Id, Name, Cash_Balance_on_Case__c, Deposited_Funds__c, 
                                                                    Funds_Drawn_on_Deposits__c, Warrants_Pending__c, 
                                                                    (SELECT Id, Name, Warrant_Number__c, Amount__c, Status__c, Case__c, 
                                                                    Case__r.Id, Case__r.Name FROM Warrants__r 
                                                                    WHERE Status__c IN ('New','Pending Approval','Approved','Not Approved','Secondary Approval Needed','Printed')) 
                                                                  FROM DIR_Case__c WHERE Id IN :caseIdList]);
                System.debug('caseWarrantList =============> ' +caseWarrantList);

                //Call Update Payment Record
                system.debug('!!!!!!!!!!!!!!!!!! Update Payment Records !!!!!!!!!!!!!!!!!!');
                system.debug('Updated PRs ==> ' + prsUpdated);
                System.enqueueJob(new PaymentRecordUpdateQable(prsUpdated, caseWarrantList, wbURL, qJobIdMap, actType));
                
            }
        }
        catch(Exception e){
            String errorMessage = e.getTypeName() + ': [' + e.getLineNumber() + '] ' + e.getMessage() + '<br/>Stack trace:<br/>' + e.getStackTraceString();
            
            qJobIdMap.put('Insert Warrants', new List<Id>{qc.getJobId()});

            System.attachFinalizer(new WarrantFinalizer(wbURL, qJobIdMap, actType ,errorMessage));
        }
        
    }
}