force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Cash_Balance_on_Case__c.field-meta.xml
<CustomField>
    <fullName>Cash_Balance_on_Case__c</fullName>
    <description>Difference of deposited funds and checks written against deposits.</description>
    <formula>Deposited_Funds__c - Funds_Drawn_on_Deposits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cash Balance on Case</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Deposited_Funds__c.field-meta.xml
<CustomField>
    <fullName>Deposited_Funds__c</fullName>
    <description>Populated by Case Payment Flow, after "Query All CPs Under A Case." Totals up all the eligible Case Payments for this Case for which funds were deposited into DLSE Office Accounts.
Also indirectly populated by CashNightlyRollup scheduled Apex class as that triggers the CP Flow.</description>
    <inlineHelpText>Total of deposited Case Payments on this Case.</inlineHelpText>
    <label>Deposited Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Funds_Drawn_on_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Funds_Drawn_on_Deposits__c</fullName>
    <description>Sum of all applicable Warrants on this Case. Populated by Warrant Flow. Also populated by the CashNightlyRollup scheduled Apex class.</description>
    <inlineHelpText>Sum of all applicable Disbursements on this Case.</inlineHelpText>
    <label>Funds Drawn on Deposits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Warrants_Pending__c.field-meta.xml
<CustomField>
    <fullName>Warrants_Pending__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Warrants requested for the given amount and waiting to be approved and printed.</description>
    <label>Warrants Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Warrant__c/Warrant__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Warrant</label>
    <nameField>
        <displayFormat>WR-{000000}</displayFormat>
        <label>Warrant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warrants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warrant__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case Managment object</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Warrants</relationshipLabel>
    <relationshipName>Warrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Secondary Approval Needed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Warrant_Batch__c.field-meta.xml
<CustomField>
    <fullName>Warrant_Batch__c</fullName>
    <label>Warrant Batch</label>
    <referenceTo>Warrant_Batch__c</referenceTo>
    <relationshipLabel>Warrants</relationshipLabel>
    <relationshipName>Warrant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Warrant_Number__c.field-meta.xml
<CustomField>
    <fullName>Warrant_Number__c</fullName>
    <description>The complete check number consist of warrant serial with check digit.</description>
    <formula>Serial_Number__c &amp; TEXT(9-MOD (VALUE (MID (Serial_Number__c, 1, 1))
+ VALUE (MID (Serial_Number__c, 2, 1))
+ VALUE (MID (Serial_Number__c, 3, 1))
+ VALUE (MID (Serial_Number__c, 4, 1))
+ VALUE (MID (Serial_Number__c, 5, 1))
+ VALUE (MID (Serial_Number__c, 6, 1))
+ VALUE (MID (Serial_Number__c, 7, 1))
+ VALUE (MID (Serial_Number__c, 8, 1)),9))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warrant Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warrant__c/recordTypes/Warrant.recordType-meta.xml
<RecordType>
    <fullName>Warrant</fullName>
    <active>true</active>
    <description>Normal page layout for Warrant record type</description>
    <label>Warrant</label>
</RecordType>

force-app/main/default/objects/Warrant_Batch__c/Warrant_Batch__c.object-meta.xml
<CustomObject>
    <description>Object for associating groups of checks so that they can be approved/voided in batches</description>
    <label>Warrant Batch</label>
    <nameField>
        <displayFormat>WB-{0}</displayFormat>
        <label>Warrant Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warrant Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warrant_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Picklist field that allows a disbursement clerk to indicate whether or not a batch of warrants has been successfully printed so that the balances update and the batch closes.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Review Complete</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WarrantUpdateQable.cls
public with sharing class WarrantUpdateQable implements Queueable{
    List<Warrant_Batch__c> wbToUpdate = new List<Warrant_Batch__c>();
    List<Warrant__c> wrsToUpdate = new List<Warrant__c>();
    List<Warrant__c> overflowWRs = new List<Warrant__c>();
    Set<Id> caseId = new Set<Id>();
    List<Id> caseIdList = new List<Id>();
    Map<String, List<Id>> qJobIdMap = new Map<String, List<Id>>();
    String wbURL;
    Integer maxWrs = 100;
    String actType;

    public WarrantUpdateQable(List<Warrant_Batch__c> wbListToUpdate, List<Warrant__c> wrListToUpdate, String wbLink) {
        wbURL = wbLink;
        wrsToUpdate = wrListToUpdate;
        wbToUpdate = wbListToUpdate;
        actType = 'Update';

        while(wrsToUpdate.size() > maxWrs){
            overflowWRs.add(wrsToUpdate.remove(maxWrs));
        }
    }


    public void execute(QueueableContext qc){
        try{
            system.debug('!!!!!!!!!!!!!!!!!! Update Warrants !!!!!!!!!!!!!!!!!!');
            update wrsToUpdate;
            system.debug('Updated Warrants ==> ' + wrsToUpdate);
            qJobIdMap.put('Update Warrants', new List<Id>{qc.getJobId()});

            for(Warrant__c wr: wrsToUpdate){
                system.debug('For Loop Warrants ==> ' + wr);
                caseId.add(wr.Case__c);
            }

            system.debug('<====================== wbURL <======================' + wbURL);
            if(!overflowWRs.isEmpty()){
                System.enqueueJob(new WarrantUpdateQable(wbToUpdate, overflowWRs, wbURL));
            }
            else{
                system.debug('!!!!!!!!!!!!!!!!!! Update Warrant Batch !!!!!!!!!!!!!!!!!!');
                update wbToUpdate;
                system.debug('!!!!!!!!!!!!!!!!!! Case - Warrants Pending !!!!!!!!!!!!!!!!!!');
                caseIdList.addAll(caseId);
                system.debug('Case Ids ==> ' + caseIdList);

                List<DIR_Case__c> caseWarrantList =  new List<DIR_Case__c>([SELECT Id, Name, Cash_Balance_on_Case__c, Deposited_Funds__c, 
                                                                    Funds_Drawn_on_Deposits__c, Warrants_Pending__c, 
                                                                    (SELECT Id, Name, Warrant_Number__c, Amount__c, Status__c, Case__c, 
                                                                    Case__r.Id, Case__r.Name FROM Warrants__r 
                                                                    WHERE Status__c IN ('New','Pending Approval','Approved','Not Approved','Secondary Approval Needed','Printed')) 
                                                                  FROM DIR_Case__c WHERE Id IN :caseIdList]);
                System.debug('caseWarrantList =============> ' +caseWarrantList);

                //Call Warrant Pending Qable Class
                System.enqueueJob(new WarrantPendingUpdateQable(caseWarrantList, wbURL, qJobIdMap, actType)); 
            }
        }
        catch(Exception e){
            String errorMessage = e.getTypeName() + ': [' + e.getLineNumber() + '] ' + e.getMessage() + '<br/>Stack trace:<br/>' + e.getStackTraceString();
            
            qJobIdMap.put('Update Warrants', new List<Id>{qc.getJobId()});

            System.attachFinalizer(new WarrantFinalizer(wbURL, qJobIdMap, actType ,errorMessage));
        }
        
    }
}