force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Case_Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Closed_Date__c</fullName>
    <description>Case Closed Date</description>
    <inlineHelpText>The date on which a case was finally closed</inlineHelpText>
    <label>Case Closed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Online_Claim_Account__c.field-meta.xml
<CustomField>
    <fullName>Online_Claim_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Online Claim Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Online Claim Account)</relationshipLabel>
    <relationshipName>Online_Claim_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OWCDeactivateOnlineUsersWithClosedCase.cls
/*
* Class Name: OWCDeactivateOnlineUsersWithClosedCase
*Description: automated process for deactivating the community accounts that are 90 days since the 
close of case and If the community user has multiple cases, then the deactivation should occur 90 days 
after the last case closes. * 
* 
*/
global class OWCDeactivateOnlineUsersWithClosedCase implements Database.Batchable<sObject> {
    public static Date dateBefore90Days = System.today().addDays(-90); 
    global Database.QueryLocator start(Database.BatchableContext bc){
        dateBefore90Days = (!Test.isRunningTest()) ? dateBefore90Days : System.today().addDays(1);
        String query = 'SELECT Id, Name, AccountId, ContactId, ProfileId, IsActive FROM User WHERE AccountId != null';
        query += ' AND Profile.Name = \'Customer Online Claim User\'';
        query += ' AND IsActive = true';
        query += ' AND CreatedDate <: dateBefore90Days';
        query += (!Test.isRunningTest()) ? '': ' LIMIT 1';
        System.debug('query ::: '+query);
        return Database.getQueryLocator(query); 
    }
    global void execute(Database.BatchableContext bc, List<User> scope){
        System.debug('scope ::: '+scope);
        List<User> deactivateUsers = new List<User>();
        Set<Id> deactivateUserIds = new Set<Id>();
        Set<Id> userWithActiveCase = new Set<Id>();
        Set<Id> deactivateAccountIds = new Set<Id>();
        for(User userObj : scope){
            deactivateAccountIds.add(userObj.accountId);
        }
        
        for(DIR_Case__c caseObj : [SELECT Id, Name, Online_Claim_Account__c, Status__c, Case_Closed_Date__c, CreatedDate
                                   FROM DIR_Case__c 
                                   WHERE Online_Claim_Account__c IN: deactivateAccountIds
                                   AND (Status__c != 'Closed' OR Case_Closed_Date__c >: dateBefore90Days )])
        {	
            if(deactivateAccountIds.contains(caseObj.Online_Claim_Account__c)){
                deactivateAccountIds.remove(caseObj.Online_Claim_Account__c);
            }
        }
        
        System.debug('deactivateUserIds ::: '+deactivateUserIds);
        //Check the list size of deactivated user
        if(deactivateAccountIds != null && deactivateAccountIds.size() > 0){
            for(User userObj : [SELECT Id, Name, IsActive, accountId, IsPortalEnabled FROM User 
                                WHERE accountId IN: deactivateAccountIds])
            {
                userObj.IsActive = false;
                userObj.IsPortalEnabled = false;
                deactivateUsers.add(userObj);
            }
        }
        
        if(deactivateUsers.size() > 0){
            update deactivateUsers;
        }
    }
    
    global void finish(Database.BatchableContext bc){
    }
}