force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Closure_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Closure_Disposition__c</fullName>
    <description>Dismissed Reason</description>
    <inlineHelpText>Choose the status of the case at closure</inlineHelpText>
    <label>Closure Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive Closure</fullName>
            </value>
            <value>
                <fullName>De Novo Referral</fullName>
            </value>
            <value>
                <fullName>Closed-Discharged in Bankruptcy</fullName>
                <label>Discharged in Bankruptcy</label>
            </value>
            <value>
                <fullName>DISMISSED</fullName>
            </value>
            <value>
                <fullName>Dismissed – Claimant Withdrew</fullName>
            </value>
            <value>
                <fullName>Dismissed – Claimant Abandoned</fullName>
            </value>
            <value>
                <fullName>Duplicate Case</fullName>
            </value>
            <value>
                <fullName>Fast Track Ref to Remedial fund</fullName>
            </value>
            <value>
                <fullName>Judgment</fullName>
                <label>JUDGMENT</label>
            </value>
            <value>
                <fullName>Not confirmed by Claimant</fullName>
                <label>Not confirmed by Plaintiff</label>
            </value>
            <value>
                <fullName>PAID IN FULL</fullName>
            </value>
            <value>
                <fullName>Plaintiff rec’d $0 ODA</fullName>
            </value>
            <value>
                <fullName>Lack of Jurisdiction – DFEH</fullName>
                <label>Lack of Jurisdiction - DFEH</label>
            </value>
            <value>
                <fullName>Lack of Jurisdiction - WCAB</fullName>
            </value>
            <value>
                <fullName>Lack of Jurisdiction - FMLA</fullName>
            </value>
            <value>
                <fullName>Lack of Jurisdiction - NRLA</fullName>
            </value>
            <value>
                <fullName>Lack of Jurisdiction - DOL (WHD)</fullName>
            </value>
            <value>
                <fullName>Lack of Jurisdiction – Atty Referral</fullName>
                <label>Lack of Jurisdiction - Atty Referral</label>
            </value>
            <value>
                <fullName>Lack of Jurisdiction – Other</fullName>
                <label>Lack of Jurisdiction - Other</label>
            </value>
            <value>
                <fullName>Untimely (Outside SOL)</fullName>
            </value>
            <value>
                <fullName>PFC – No Protected Activity</fullName>
                <label>PFC - No Protected Activity</label>
            </value>
            <value>
                <fullName>PFC – No Employer Knowledge</fullName>
                <label>PFC - No Employer Knowledge</label>
            </value>
            <value>
                <fullName>PFC- No Adverse Action</fullName>
                <label>PFC - No Adverse Action</label>
            </value>
            <value>
                <fullName>PFC – No Causal Link</fullName>
                <label>PFC - No Causal Link</label>
            </value>
            <value>
                <fullName>EPA - No Pay Disparity</fullName>
            </value>
            <value>
                <fullName>EPA - No Comparators</fullName>
            </value>
            <value>
                <fullName>EPA - No substantially similar work</fullName>
            </value>
            <value>
                <fullName>EPA - No similar work conditions</fullName>
            </value>
            <value>
                <fullName>EPA - ER JUST Merit</fullName>
            </value>
            <value>
                <fullName>EPA - ER JUST Seniority</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Intake_Origin__c.field-meta.xml
<CustomField>
    <fullName>Intake_Origin__c</fullName>
    <label>Intake Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>OSHA Inspection</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>3rd Party API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Online_Claim_Account__c.field-meta.xml
<CustomField>
    <fullName>Online_Claim_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Online Claim Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Online Claim Account)</relationshipLabel>
    <relationshipName>Online_Claim_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OWCDeleteUnConfirmedClaimsBatch.cls
/**
 * @File Name          : OWCDeleteUnConfirmedClaimsBatch.cls
 * @Test Class         : 
 * @Description        : Enhance current automated process to purge “Incomplete” online claim forms that are 180 days since ‘Last Modified date’.
 * @JIRA Reference     : https://propoint-technology.atlassian.net/browse/OWC-218
 * @Author             : Vikas Singh
 * @Last Modified By   : vikas@cloudsciencelabs.com
 * @Last Modified On   : 23/12/2021
 * @Modification Log   :
 *==============================================================================
 * Ver         Date                     Author                    Modification
 *==============================================================================
 **/
global class OWCDeleteUnConfirmedClaimsBatch implements Database.Batchable<sObject>{
    DateTime todayDate ;
    
    global OWCDeleteUnConfirmedClaimsBatch(Integer noOfDays){
        todayDate = System.now().addDays(-noOfDays);
    }
    //Fetching all the online claim Closed having lastmodifieddate less than 180 days 
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([
            SELECT ID,Name,LastModifiedDate 
            FROM DIR_Case__c  
            WHERE Status__c = 'Closed' AND Intake_Origin__c = 'Online'  
            AND  Online_Claim_Account__c != null 
            AND Closure_Disposition__c = 'Not confirmed by Claimant' 
            AND LastModifiedDate <: todayDate 
        ]);
    }

    global void execute(Database.BatchableContext BC, List<DIR_Case__c>scope){
        delete scope;
    }
    
    global void finish(Database.BatchableContext BC){
    }
}