force-app/main/default/objects/Hearing__c/Hearing__c.object-meta.xml
<CustomObject>
    <description>This stores all of the hearings/conferences related to an Appeal, which gets information from the Assessment, Liability Appeal, Case, and Account from a relationship level.</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Meeting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hearing__c/fields/Meeting_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_End_Date_Time__c</fullName>
    <inlineHelpText>Cannot be more than 14 days after Meeting Start Date/Time</inlineHelpText>
    <label>Meeting End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Meeting_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Start_Date_Time__c</fullName>
    <label>Meeting Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/WCA_Office__c.field-meta.xml
<CustomField>
    <fullName>WCA_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Office where meeting is to take place</description>
    <inlineHelpText>Office where meeting is to take place</inlineHelpText>
    <label>Meeting Location (Office)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>WCA,Garment,BOFE,RCI,WCA_Meeting_Location, JEU</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Hearings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenerateDailyCalendarController.cls
public with sharing class GenerateDailyCalendarController {
    
    public Hearing__c hearing {get;set;}
    public Id userId {get;set;}
    public String docURL {get;set;}
    public String selectedRT {get;set;}
    public List<SelectOption> rtList {get;set;}
    //public Map<string, string> ctMap {get;set;}
    public List<Conga_Template_Mapping__c> objCTMapping {get;set;}
    
    public GenerateDailyCalendarController(){
        hearing = new Hearing__c();
        userId = userInfo.getUserId();
        rtList = new List<SelectOption>();
        List<RecordType> tempList = [SELECT Id, Name FROM RecordType WHERE sObjectType = 'Hearing__c' ORDER BY Name asc];
        for(RecordType rt : tempList){
            rtList.add(new SelectOption(rt.Id, rt.Name));
        }
        selectedRT = rtList[0].getValue();
        
        // get mapping settings from Conga Template Mapping custom setting
        objCTMapping = [Select Name, RecordID__c FROM Conga_Template_Mapping__c WHERE Mapping_Group__c = 'WCA Daily Calendar'];
        system.debug('objCTMapping:::: ' +objCTMapping);
        
    }
    
    
    public void setURL(){
        Map<string, string> ctMap = new Map<string, string>();
        system.debug('objCTMapping:::: ' + objCTMapping);
        for (Conga_Template_Mapping__c c : objCTMapping){
            system.debug('c.Name: ' + c.Name + ' & c.RecordID__c: ' + c.RecordID__c);
            ctMap.put(c.Name, c.RecordID__c); 
        }

        if(ctMap.isEmpty())
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,'CTMap is empty'));
        
        system.debug('ctMAP::::: ' + ctmap);
        docURL += ''
            +'&id=' + userId
            //+'&queryid=[Calendar]a0md00000064cjs?'
            +'&queryid=[Calendar]'+ctMap.get('Calendar')+'?'
            +'pv0='+hearing.Meeting_Start_Date_Time__c.format('yyyy-MM-dd')
            +'~pv1='+hearing.Meeting_End_Date_Time__c.format('yyyy-MM-dd')
            +'~pv2='+hearing.WCA_Office__c
            +'~pv3='+selectedRT
            //+',[Office]a0md00000064cjc?pv0='+hearing.WCA_Office__c
            +',[Office]'+ctMap.get('Office')+'?pv0='+hearing.WCA_Office__c
            //+'&templateid=a0nd0000005OStj'
            +'&templateid='+ctMap.get('TemplateID')
            +'&ofn=Calendar'
            +'&DS7=3';
        system.debug('******************URL: '+docURL);
    }
    
}