force-app/main/default/objects/Related_Businesses__c/Related_Businesses__c.object-meta.xml
<CustomObject>
    <label>Related Business</label>
    <nameField>
        <displayFormat>RBO-{00000000}</displayFormat>
        <label>Related Businesses Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Businesses__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to store business Account for the Rbo record</description>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Business)</relationshipLabel>
    <relationshipName>Related_Businessess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Related Business)</relationshipLabel>
    <relationshipName>Related_Businessess1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Used for the read only access for business, Related Business and Related Business Name.</description>
    <label>Business</label>
</RecordType>

force-app/main/default/classes/DIRNewRelatedBusinessesCreateController.cls
public class DIRNewRelatedBusinessesCreateController {
    public Id parentId {get; set;}
    public Related_Businesses__c relatedBusinesses {get; set;}
    public string businessName {get; set;}
    public Id businessId {get; set;}
    public Boolean accountExist {get; set;}
    public DIRNewRelatedBusinessesCreateController(ApexPages.StandardController controller) {
        accountExist = false;
        relatedBusinesses = new Related_Businesses__c();
        Map<String, String> pageParameters = ApexPages.currentPage().getParameters();
        for(String paramKey : pageParameters.KeySet()){
            if(paramKey.contains('_lkid')){
                parentId = pageParameters.get(paramKey);
                break;
            }
        }
        if(parentId != null && (parentId.getSObjectType().getDescribe().getName().equalsIgnoreCase('Account'))){
              Account currentAccount = [SELECT Id, Name FROM Account WHERE Id =: parentId];
                    relatedBusinesses.Business__c = parentId;
                    businessName = currentAccount.Name;
                    businessId = currentAccount.id;
                    accountExist = true;
        }
    }
    
    public PageReference saveRelatedBusinessesRecord() {
        //create the Related Businesses record
        try {
           Boolean relatedBusinessExist = DirQuerySelector.getRelatedBusinessRecord(relatedBusinesses.Related_Business__c,relatedBusinesses.Business__c);
            if(relatedBusinessExist){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error , 'Related Business Record Already Exists'));
                return null;
            }
            else{
                insert relatedBusinesses;
            }
        }
        
        catch(Exception ex) {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error , 'Something Went Wrong. Please Contact your System Administrator.'));
                return null;
        }
        PageReference pageRef;
            if(accountExist){
                pageRef = new PageReference('/'+parentId);
            }else{
                pageRef = new PageReference('/'+relatedBusinesses.id);
            }
        pageRef.setRedirect(true);
        return pageRef;
    }
}