force-app/main/default/objects/Account/fields/Corp_or_LLC_ID__c.field-meta.xml
<CustomField>
    <fullName>Corp_or_LLC_ID__c</fullName>
    <label>Corp or LLC ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Corp_or_LLC_Name__c.field-meta.xml
<CustomField>
    <fullName>Corp_or_LLC_Name__c</fullName>
    <label>Corp or LLC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Entity Registration</description>
    <inlineHelpText>Expiration Date of the Entity Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Account__c</fullName>
    <label>Registration Account</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Corp_or_LLC_ID__c.field-meta.xml
<CustomField>
    <fullName>Corp_or_LLC_ID__c</fullName>
    <label>Corp or LLC ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Type__c</fullName>
    <label>License/Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>Agricultural Employers of Minors</fullName>
            </value>
            <value>
                <fullName>Agricultural Produce Unloaders</fullName>
            </value>
            <value>
                <fullName>BOE/Seller’s Permit</fullName>
            </value>
            <value>
                <fullName>Bureau of Automotive Repair</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Car Wash</fullName>
            </value>
            <value>
                <fullName>Child Performer Services</fullName>
            </value>
            <value>
                <fullName>CSLB</fullName>
            </value>
            <value>
                <fullName>DOL</fullName>
            </value>
            <value>
                <fullName>DSS Facility</fullName>
            </value>
            <value>
                <fullName>Electricians and electrician trainees</fullName>
            </value>
            <value>
                <fullName>FBNS</fullName>
            </value>
            <value>
                <fullName>Farm Labor Contractor</fullName>
            </value>
            <value>
                <fullName>Garment Manufacturers and Contractors</fullName>
            </value>
            <value>
                <fullName>Health Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworker Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworkers</fullName>
            </value>
            <value>
                <fullName>Industrial Homework License</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Secretary of State Number</fullName>
            </value>
            <value>
                <fullName>SEIN</fullName>
            </value>
            <value>
                <fullName>Sheltered Workshops (non‐profit)</fullName>
            </value>
            <value>
                <fullName>Special Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Studio Teacher Certification</fullName>
            </value>
            <value>
                <fullName>Talent Agency</fullName>
            </value>
            <value>
                <fullName>Work Permits for Child Performers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>BSIS</fullName>
            </value>
            <value>
                <fullName>Entertainment Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Registration_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the registration account that became the account on this registration. Used for matching during renewal</description>
    <label>Registration Account</label>
    <referenceTo>Registration_Account__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations_Key_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Registration_Duration__c.field-meta.xml
<CustomField>
    <fullName>Registration_Duration__c</fullName>
    <label>Registration Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 Days - Temporary Permit</fullName>
            </value>
            <value>
                <fullName>6 Months - Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Submission_Type__c</fullName>
    <label>Submission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
                <default>true</default>
                <label>Online</label>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/VIP_Template_Status__c.field-meta.xml
<CustomField>
    <fullName>VIP_Template_Status__c</fullName>
    <label>VIP Template Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/Registration_Account__c.object-meta.xml
<CustomObject>
    <description>Staging object used to collect Company/Account information on Registration forms.</description>
    <label>Registration Account</label>
    <nameField>
        <displayFormat>RA-{000000000}</displayFormat>
        <label>Registration Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Corp_or_LLC_ID__c.field-meta.xml
<CustomField>
    <fullName>Corp_or_LLC_ID__c</fullName>
    <description>Mapped to Corp_or_LLC_ID__c Account field.</description>
    <label>Corp or LLC ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Corp_or_LLC_Name__c.field-meta.xml
<CustomField>
    <fullName>Corp_or_LLC_Name__c</fullName>
    <description>Mapped to Corp_or_LLC_Name__c Account field.
3/22 PS changed to Name on label.</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Submission_Type__c</fullName>
    <formula>TEXT(Registration__r.Submission_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Submission Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegistrationDocDownloadControllerTest.cls
@istest
public class RegistrationDocDownloadControllerTest {
    
    public static testMethod void testRegDocDLController(){
        
        
        Id p = [SELECT id FROM profile WHERE Name='Community Registrations User'].id;
        Id personAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        Account acc = new Account(
            FirstName = 'test',
            LastName = 'acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212',
            PersonEmail = 'lralltestusers@test.com',
            RecordTypeId = personAccountRTId
        );
        insert acc;
        
        Contact c = new Contact();
        c.FirstName = 'First';
        c.LastName = 'Last';
        c.Email = 'first.last@gmail.com';
        insert c;
        
        Id EWPRecordTypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Entertainment Work').getRecordTypeId();
        Id iPRecordTypeId = Schema.SObjectType.Registration_Account__c.getRecordTypeInfosByName().get('Individual Permit').getRecordTypeId();
 
        License_Registration__c  newLR = new License_Registration__c();
        newLR.Account__c = acc.Id;
        newLR.Applicant__c = c.Id;
        newLR.RecordTypeId = EWPRecordTypeId;
        newLR.License_Registration_Number__c = '222';
        newLR.License_Registration_Type__c = 'Entertainment Work';
        newLR.Status__c = 'Incomplete'; 
        newLR.Expiration_Date__c = Date.today() + 10; 
        newLR.Amount_Paid__c = 100; 
        newLR.Registration_Duration__c = '6 Months - Permit';
        newLR.VIP_Template_Status__c = 'Incomplete';
        newLR.Submission_Type__c = 'Paper';
        insert newLR;
        system.debug('##### newLR: ' + newLR);
        
        Registration_Account__c racc1 = new Registration_Account__c();
        racc1.RecordTypeId = iPRecordTypeId;
        racc1.Corp_or_LLC_ID__c = 'Corp or LLC ID';
        racc1.Corp_or_LLC_Name__c = 'Corp or LLC Name';
        racc1.First_Name__c = 'FirstName';
        racc1.Last_Name__c = 'LastName';
        racc1.Email_Address__c = 'test@asdadad.com';
        racc1.Legal_Entity_Name__c = 'Legal Entity Name';
        racc1.Mailing_City__c = 'San Francisco';
        racc1.Mailing_State__c = 'CA';
        racc1.Mailing_City__c = 'San Francisco';
        racc1.Mailing_Street__c = 'Street ';
        racc1.Mailing_Zip_Code__c = '54434';
        racc1.Business_Phone__c = '4445553434';
        racc1.Mobile_Phone__c = '5445445555';
        racc1.Registration__c = newLR.Id;
        racc1.Birth_Date__c = Date.today() - 60;
        insert racc1;
        System.debug('##### RA1: ' + racc1);

        test.startTest();
        Test.setCurrentPageReference(new PageReference('Page.RegistrationDocDownload')); 
        
        RegistrationDocDownloadController regDownload = new RegistrationDocDownloadController();
        
        regDownload.openMedicalInfoToPdf();
        regDownload.openSchoolInfoToPdf();
        
        test.stopTest();
    }
    //}
}