force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <inlineHelpText>County is used to prepare official documents</inlineHelpText>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outside CA</fullName>
            </value>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>Amador</fullName>
            </value>
            <value>
                <fullName>Butte</fullName>
            </value>
            <value>
                <fullName>Calaveras</fullName>
            </value>
            <value>
                <fullName>Colusa</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Del Norte</fullName>
            </value>
            <value>
                <fullName>El Dorado</fullName>
            </value>
            <value>
                <fullName>Fresno</fullName>
            </value>
            <value>
                <fullName>Glenn</fullName>
            </value>
            <value>
                <fullName>Humboldt</fullName>
            </value>
            <value>
                <fullName>Imperial</fullName>
            </value>
            <value>
                <fullName>Inyo</fullName>
            </value>
            <value>
                <fullName>Kern</fullName>
            </value>
            <value>
                <fullName>Kings</fullName>
            </value>
            <value>
                <fullName>Lake</fullName>
            </value>
            <value>
                <fullName>Lassen</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Madera</fullName>
            </value>
            <value>
                <fullName>Marin</fullName>
            </value>
            <value>
                <fullName>Mariposa</fullName>
            </value>
            <value>
                <fullName>Mendocino</fullName>
            </value>
            <value>
                <fullName>Merced</fullName>
            </value>
            <value>
                <fullName>Modoc</fullName>
            </value>
            <value>
                <fullName>Mono</fullName>
            </value>
            <value>
                <fullName>Monterey</fullName>
            </value>
            <value>
                <fullName>Napa</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To populate Region field</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <description>Vertiba</description>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee's email address</description>
    <inlineHelpText>Email address for Salesforce users will be set automatically.
If the employee is NOT a Salesforce user, please enter their email address here.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The office the user is associated to. Related fields are used on output documents</description>
    <inlineHelpText>The office to which the employee is associated.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Internal Employees</relationshipLabel>
    <relationshipName>Internal_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>County of the BOFE/Wage office</description>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Identifies offices as WAGE</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office_Zip_Code_Map__c/Office_Zip_Code_Map__c.object-meta.xml
<CustomObject>
    <description>Maps zip codes to office locations. Used for assigning records to offices based on zip codes</description>
    <label>Office-Zip Code Map</label>
    <nameField>
        <displayFormat>Map-{00000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office-Zip Code Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>From Zip Code object</description>
    <formula>TEXT(Zip_Code__r.County__c)</formula>
    <inlineHelpText>From Zip Code object</inlineHelpText>
    <label>County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>The office that the zip code is assigned to</description>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>the zip code assigned to the office</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Online_Claim_Error_Log__c/Online_Claim_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Online Claim Error Log</label>
    <nameField>
        <displayFormat>OCEL-{000000}</displayFormat>
        <label>Online Claim Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Claim Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Online_Claim_Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Online_Claim_Error_Log__c/fields/Error_Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Error_Stack_Trace__c</fullName>
    <label>Error Stack trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Online_Claim_Error_Log__c/fields/Line_number__c.field-meta.xml
<CustomField>
    <fullName>Line_number__c</fullName>
    <label>Line number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/Related_Party__c.object-meta.xml
<CustomObject>
    <label>Related Party</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Related Party  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Party__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/recordTypes/Claimant.recordType-meta.xml
<RecordType>
    <fullName>Claimant</fullName>
    <active>true</active>
    <description>This is used for the Online Claim.</description>
    <label>Claimant</label>
</RecordType>

force-app/main/default/objects/Related_Party__c/recordTypes/Employer.recordType-meta.xml
<RecordType>
    <fullName>Employer</fullName>
    <active>true</active>
    <label>Employer</label>
</RecordType>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>Amador</fullName>
            </value>
            <value>
                <fullName>Butte</fullName>
            </value>
            <value>
                <fullName>Calaveras</fullName>
            </value>
            <value>
                <fullName>Colusa</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Del Norte</fullName>
            </value>
            <value>
                <fullName>El Dorado</fullName>
            </value>
            <value>
                <fullName>Fresno</fullName>
            </value>
            <value>
                <fullName>Glenn</fullName>
            </value>
            <value>
                <fullName>Humboldt</fullName>
            </value>
            <value>
                <fullName>Imperial</fullName>
            </value>
            <value>
                <fullName>Inyo</fullName>
            </value>
            <value>
                <fullName>Kern</fullName>
            </value>
            <value>
                <fullName>Kings</fullName>
            </value>
            <value>
                <fullName>Lake</fullName>
            </value>
            <value>
                <fullName>Lassen</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Madera</fullName>
            </value>
            <value>
                <fullName>Marin</fullName>
            </value>
            <value>
                <fullName>Mariposa</fullName>
            </value>
            <value>
                <fullName>Mendocino</fullName>
            </value>
            <value>
                <fullName>Merced</fullName>
            </value>
            <value>
                <fullName>Modoc</fullName>
            </value>
            <value>
                <fullName>Mono</fullName>
            </value>
            <value>
                <fullName>Monterey</fullName>
            </value>
            <value>
                <fullName>Napa</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OWCServiceUtility.cls
/*Name: OWCServiceUtility
* Description: Used to keep the comman utility services for the project and ensure the reusability of the code as possible
*/
public with sharing class OWCServiceUtility {
    public String StackTrace {get; set;}
    public String ClassName {get; set;}
    public static boolean isDeletedErrorClaim = false;
    public static Map<String, Object> getdeserializeUntypedMap(String jsonInput){
        return (Map<String, object>) json.deserializeUntyped (jsonInput);
    }

    //Get the existing account
    public static Account getDuplicateAccount(Account acc){
        List<Account> existingAccounts;
        if(acc.RecordTypeId == OWCConstants.PERSON_ACCOUNT_RECORD_TYPE_ID){
            existingAccounts = [SELECT Id, Name FROM Account
                                WHERE PersonEmail=: acc.PersonEmail AND firstName=: acc.firstName AND lastName=: acc.lastName];
        }else{
            existingAccounts = [SELECT Id, Name FROM Account
                                WHERE Email__c=: acc.Email__c AND Name=: acc.Name];
        }
        if(existingAccounts != null && existingAccounts.size() >0){
            return existingAccounts[0];
        }
        return null;
    }

    //SCR-853
    public static String validateOfficeAssignment(String claimantZipCode, String defendantZipCode, String otherLocationZipCode){
        String claimantOfficeName = getOfficeNameByZipCode(claimantZipCode);
        String defendantOfficeName = getOfficeNameByZipCode(defendantZipCode);
        String otherLocationOfficeName = getOfficeNameByZipCode(otherLocationZipCode);

        // 1.	Assign to office where at least two of the three zip codes are in the same California WCA Office (not the Out of State Office);
        if(String.isNotBlank(claimantOfficeName) && String.isNotBlank(defendantOfficeName) && claimantOfficeName == defendantOfficeName && !claimantOfficeName.contains('OUT OF STATE')){
            return claimantZipCode;
        }else if(String.isNotBlank(claimantOfficeName) && String.isNotBlank(otherLocationOfficeName) && claimantOfficeName == otherLocationOfficeName && !claimantOfficeName.contains('OUT OF STATE')){
            return claimantZipCode;
        }else if(String.isNotBlank(defendantOfficeName) && String.isNotBlank(otherLocationOfficeName) && defendantOfficeName == otherLocationOfficeName && !defendantOfficeName.contains('OUT OF STATE')){
            return defendantZipCode;
        // 2.   If there is not a 2 out of 3 in-state office match, then
		//   a.   1st priority: assign to in-state office handling claimant’s zip code;
        }else if(String.isNotBlank(claimantOfficeName) && !claimantOfficeName.contains('OUT OF STATE')){
            return claimantZipCode;
        //   b.   2nd priority: assign to in-state office handling zip code where work was performed;
        }else if(String.isNotBlank(otherLocationOfficeName) && !otherLocationOfficeName.contains('OUT OF STATE')){
            return otherLocationZipCode;
        // 3.   If the only CA zip code is the address of the employer, then assign to out of state
        // 4.	where there is no California zip code for claimant, employer, or where the work was performed then assign to out of state
        // 5.   No zip code code mapping should be treated as an out of state
        }else{
            return '00000';
        }
        // We need to make sure the caller handles '00000' correctly.
    }

    public static String getOfficeNameByZipCode(String zipCode){
        if(String.isBlank(zipCode)){
            return null;
        }else{
            List<String> zipCodeNameList = new List<String>();
            for(Zip_Code__c zc : [SELECT Id, Name FROM Zip_Code__c]){
                zipCodeNameList.add(zc.Name);
            }
            
            if(!zipCodeNameList.contains(zipCode)){
                zipCode = '00000'; //"Out of state" zip code
            }
            
            List<Office_Zip_Code_Map__c> ozcmList = [SELECT Id, Office__r.Name, Office__r.RecordType.Name, Zip_Code__r.Name
                                                        FROM Office_Zip_Code_Map__c
                                                        WHERE Zip_Code__r.Name =: zipCode
                                                            AND Office__r.RecordType.Name =: Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getname()
                                                        LIMIT 1];
            
            if(!ozcmList.isEmpty()){
                return ozcmList[0].Office__r.Name;
            }else{
                return null;
            }
        }
        // Need to verify caller handles null return and Office named 'WCA - OUT OF STATE' correctly
    }


    /* This method with this signature doesn't seem to be used anywhere, so commenting out for better test coverage
    public static Boolean getOfficeLocationByZIPCode(String zipCode){
        String recordTypeName_Office = Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('RCI').getname();
        String recordTypeName_WCA_Office = Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getname();

        Map<String,Id> zipCodes = new Map<String,Id>();
        Id officePrimaryId ;
        String countyPrimary;

        for(Zip_Code__c zcode: [Select Id, Name from Zip_Code__c WHERE Name =: zipCode]){
            zipCodes.put(zcode.Name,zcode.Id);
        }

        for(Office_Zip_Code_Map__c zcode: [Select Id, Office__c,Office__r.RecordType.Name, Zip_Code__c, County__c
                                           from Office_Zip_Code_Map__c
                                           where Zip_Code__c =: zipCodes.get(zipCode)])
        {

            if(zcode.Office__r.RecordType.Name.equals(recordTypeName_WCA_Office)){
                officePrimaryId = zcode.Office__c;
                countyPrimary = zcode.County__c;
            }

        }

        //B-000977 Fix
        if(string.isBlank(officePrimaryId))
        {
            return false;

        } else {
            return true;
        }
    } */

    /* This method with this signature doesn't seem to be used anywhere, so commenting out for better test coverage
    public static Map<String, String> getOfficeLocationByZIPCode(list<String> zipCodes){

        String recordTypeName_WCA_Office = Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getname();
        Map<String, String> officeZipCodes = new Map<String,String>();

        for(Office_Zip_Code_Map__c zcode: [Select Id, Office__c, Office__r.Name, Office__r.RecordType.Name, Zip_Code__c, Zip_Code__r.Name, County__c
                                           from Office_Zip_Code_Map__c
                                           where Zip_Code__r.Name =: zipCodes])
        {

            if(zcode.Office__r.RecordType.Name.equals(recordTypeName_WCA_Office))
            {

                officeZipCodes.put(zcode.Zip_Code__r.Name, zcode.office__r.Name);
            }

        }


        return officeZipCodes;

    } */


    //Exception handler
    public void log(Exception ex)
    {
        try
        {
            System.debug('ex:::::'+ex);
            writeExToObject(ex);
            System.debug('This is a debug message');
        }
        catch(Exception e)
        {
            System.debug('log catch Exception ex:::::'+e);
            new OWCServiceUtility().log(e);
        }
    }

    //Writting Exception data to excpetion object
    public void writeExToObject(Exception ex)
    {
       // DML statement
        stackTrace = ex.getStackTraceString()
                .substringBefore('\n');

            className = stackTrace.substringAfter('.')
                .substringBefore('.');

            System.debug('writeExToObject ex:::::'+ex);
            System.debug('writeExToObject stackTrace:::::'+stackTrace);
            System.debug('writeExToObject className:::::'+className);
            System.debug('writeExToObject Error_Stack_Trace__c:::::'+ex.getStackTraceString());
            System.debug('writeExToObject getLineNumber:::::'+ex.getLineNumber());
            System.debug('writeExToObject getMessage:::::'+ex.getMessage());

            Online_Claim_Error_Log__c logger = new Online_Claim_Error_Log__c();
            logger.Error_Stack_Trace__c = ex.getStackTraceString();
            logger.Class_Name__c = className;
            logger.Line_number__c = ex.getLineNumber();
        	logger.Error_Message__c  = ex.getMessage();
            system.debug('logger::::'+logger);

        	Database.SaveResult srList = Database.insert(logger, false);

        // Iterate through each returned result
            if (srList.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully inserted account. Account ID: ' + srList.getId());
            }
            else {
                // Operation failed, so get all errors
                for(Database.Error err : srList.getErrors()) {
                    System.debug('The following error has occurred.');
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }

    }

    // To generate JSON response
    public static string generateJSON(String Status,String Content,String error){
        JSONGenerator jsGen = JSON.createGenerator(true);
        jsGen.writeStartObject();
        jsGen.writeStringField('Status',Status);
        jsGen.writeStringField('ContentID', Content);
        jsGen.writeStringField('Error', error);
        jsGen.writeEndObject();
        return jsGen.getAsString();
    }

    /*****************************
* @description: Create wrapper object to store the Attachment + Data records.
* @Class Name: AttachmentPlusWrapperObj
* ***************************/
    public class attachmentPlusWrapperObj{
        @AuraEnabled
        public String fieldAPIName{get;set;}
        @AuraEnabled
        public String fieldName{get;set;}
        @AuraEnabled
        public String fileType{get;set;}
        @AuraEnabled
        public String value{get;set;}

        public attachmentPlusWrapperObj(String fieldAPIName, String fieldName, String value, String fileType){
            this.fieldAPIName = fieldAPIName;
            this.fieldName = fieldName;
            this.value = value;
            this.fileType = fileType;
        }
    }
    public static DIR_Case__c populateOfficeOnCM(DIR_Case__c cseRecord){
        Map<Id,Related_Party__c> newRelatedParties ;
        String recordTypeName_Office = Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('RCI').getname();
        String recordTypeName_WCA_Office = Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getname();
        Id recordTypeId_RC = Schema.SObjectType.Case_Role__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId();
        Id recordTypeId_WCA = Schema.SObjectType.Case_Role__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        Id recordTypeId_RCI_Case = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId();
        Id recordTypeId_WCA_Case = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        Id recordTypeId_Pre_Docketing_Case_Case = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('Pre Docketing Case').getRecordTypeId();

        Map<String,Id> zipCodes = new Map<String,Id>();
        Map<String,DIR_Case__c> casesToUpdate = new Map<String,DIR_Case__c>();
        Id officePrimaryId;
        String countyPrimary;
        Map<Id,Related_Party__c> filteredRelatedParties = new Map<Id,Related_Party__c>();
        Map<String,Related_Party__c> mapFilteredRelatedParties = new Map<String,Related_Party__c>();
        for(Zip_Code__c zcode: [Select Id, Name from Zip_Code__c]){
            zipCodes.put(zcode.Name,zcode.Id);
        }
        for(Related_Party__c objnewRP : [SELECT Id,Case_Management__c,Case_Management__r.recordTypeId,Case_Management__r.Advocate__c,Case_Management__r.Assigned_Screener__c,
                                         Case_Management__r.Assigned_Screener__r.Office__c,Case_Management__r.Employer__c,Case_Management__r.Claimant__c,
                                         Case_Management__r.Work_Location__c,Still_in_business__c,Case_Management__r.Office__c, Zip_Code__c,Role__c
                                         FROM Related_Party__c
                                         WHERE (Case_Management__c =: cseRecord.Id AND Role__c = 'Defendant')]) {
                                             if(objnewRP.Case_Management__c != null && String.isNotBlank(objnewRP.Role__c) && (objnewRP.Role__c == 'Defendant')){
                                                 mapFilteredRelatedParties.put(objnewRP.Id, objnewRP);
                                                 system.debug('objRP.Zip_Code__c: '+objnewRP.Zip_Code__c);
                                             }
                                         }
        system.debug('casesToUpdate: '+mapFilteredRelatedParties);

        for(Related_Party__c objRP : [SELECT Id,Case_Management__c,Case_Management__r.recordTypeId,Case_Management__r.Advocate__c,
                                      Case_Management__r.Assigned_Screener__c,Case_Management__r.Assigned_Screener__r.Office__c,
                                      Case_Management__r.Intake_Origin__c,Case_Management__r.Employer__c,Case_Management__r.Claimant__c,
                                      Case_Management__r.Work_Location__c,Still_in_business__c,Case_Management__r.Office__c, Zip_Code__c,
                                      Role__c, Case_Management__r.Office_Location_Zip_Code__c
                                      FROM Related_Party__c
                                      WHERE (Case_Management__r.Employer__c = Null AND Role__c = 'Defendant')
                                      AND Id IN: mapFilteredRelatedParties.keyset()])
        {
            if(objRP.Role__c == 'Defendant'){
                String zipCode = objRP.Case_Management__r.Office_Location_Zip_Code__c;
                if(zipCode != null){
                    if(zipCode.length() > 5){
                        zipCode = zipCode.subString(0, 5);
                    }
                }
                for(Office_Zip_Code_Map__c zcode: [Select Id, Office__c,Office__r.RecordType.Name, Zip_Code__c, County__c
                                                   from Office_Zip_Code_Map__c
                                                   where Zip_Code__c =: zipCodes.get(zipCode)])
                {

                    if(zcode.Office__r.RecordType.Name.equals(recordTypeName_WCA_Office)){
                        officePrimaryId = zcode.Office__c;
                        countyPrimary = zcode.County__c;
                    }

                }

                //B-000977 Fix
                if(string.isBlank(officePrimaryId))
                {
                    for(Office_Zip_Code_Map__c zcode: [Select Id, Office__c,Office__r.RecordType.Name, Zip_Code__c, County__c from Office_Zip_Code_Map__c where Office__r.Name =:'WCA - OUT OF STATE']){

                        officePrimaryId = zcode.Office__c ;
                        countyPrimary = 'Outside CA';
                    }
                }

                //B-27763 Fix
                if(objRP.Case_Management__r.Office__c == Null && mapFilteredRelatedParties.get(objRP.id).Role__c == 'Defendant'){
                    if(objRP.Case_Management__r.Office__c == Null){
                        //casesToUpdate.put(objRP.Case_Management__c,new DIR_Case__c(Id = objRP.Case_Management__c,County__c = countyPrimary, Office__c = officePrimaryId));
                        cseRecord.County__c = countyPrimary;
                        cseRecord.Office__c = officePrimaryId;
                        return cseRecord;
                    }
                }
            }
        }
        return cseRecord;
    }
}