force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Advocate_Name_in_Text__c.field-meta.xml
<CustomField>
    <fullName>Advocate_Name_in_Text__c</fullName>
    <label>Advocate Name in Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Claimant_Name_in_Text__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Name_in_Text__c</fullName>
    <label>Claimant Name in Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <inlineHelpText>County is used to prepare official documents</inlineHelpText>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outside CA</fullName>
            </value>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>Amador</fullName>
            </value>
            <value>
                <fullName>Butte</fullName>
            </value>
            <value>
                <fullName>Calaveras</fullName>
            </value>
            <value>
                <fullName>Colusa</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Del Norte</fullName>
            </value>
            <value>
                <fullName>El Dorado</fullName>
            </value>
            <value>
                <fullName>Fresno</fullName>
            </value>
            <value>
                <fullName>Glenn</fullName>
            </value>
            <value>
                <fullName>Humboldt</fullName>
            </value>
            <value>
                <fullName>Imperial</fullName>
            </value>
            <value>
                <fullName>Inyo</fullName>
            </value>
            <value>
                <fullName>Kern</fullName>
            </value>
            <value>
                <fullName>Kings</fullName>
            </value>
            <value>
                <fullName>Lake</fullName>
            </value>
            <value>
                <fullName>Lassen</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Madera</fullName>
            </value>
            <value>
                <fullName>Marin</fullName>
            </value>
            <value>
                <fullName>Mariposa</fullName>
            </value>
            <value>
                <fullName>Mendocino</fullName>
            </value>
            <value>
                <fullName>Merced</fullName>
            </value>
            <value>
                <fullName>Modoc</fullName>
            </value>
            <value>
                <fullName>Mono</fullName>
            </value>
            <value>
                <fullName>Monterey</fullName>
            </value>
            <value>
                <fullName>Napa</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer_Name_in_Text__c.field-meta.xml
<CustomField>
    <fullName>Employer_Name_in_Text__c</fullName>
    <description>Hidden field for Form Assembly Employer Name lookups</description>
    <inlineHelpText>Do not enter a name in this box if it is blank. Later if you need to make a change to the Case Name, then edit the name in this box. Note: Editing the name in this box does not change the Account Name.</inlineHelpText>
    <label>Employer Name in Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Referred_From__c.field-meta.xml
<CustomField>
    <fullName>Referred_From__c</fullName>
    <description>Agency which referred the case</description>
    <label>Referred From</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALRB</fullName>
            </value>
            <value>
                <fullName>Legislator</fullName>
            </value>
            <value>
                <fullName>Governor</fullName>
            </value>
            <value>
                <fullName>EDD</fullName>
            </value>
            <value>
                <fullName>Attorney General</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Representative - Individual</fullName>
            </value>
            <value>
                <fullName>Representative - Law Firm / Organization</fullName>
            </value>
            <value>
                <fullName>Representative - Organization</fullName>
            </value>
            <value>
                <fullName>3rd Party API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Related_Party_Advocate_Email__c.field-meta.xml
<CustomField>
    <fullName>Related_Party_Advocate_Email__c</fullName>
    <label>Related Party Advocate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Related_Party_Employee_Email__c.field-meta.xml
<CustomField>
    <fullName>Related_Party_Employee_Email__c</fullName>
    <label>Related Party Employee Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Not Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To populate Region field</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Garment Cases</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>County of the BOFE/Wage office</description>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/recordTypes/Garment.recordType-meta.xml
<RecordType>
    <fullName>Garment</fullName>
    <active>true</active>
    <description>Identifies an office as a garment office</description>
    <label>Garment</label>
</RecordType>

force-app/main/default/objects/Office__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Identifies offices as WAGE</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office_Zip_Code_Map__c/Office_Zip_Code_Map__c.object-meta.xml
<CustomObject>
    <description>Maps zip codes to office locations. Used for assigning records to offices based on zip codes</description>
    <label>Office-Zip Code Map</label>
    <nameField>
        <displayFormat>Map-{00000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office-Zip Code Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>From Zip Code object</description>
    <formula>TEXT(Zip_Code__r.County__c)</formula>
    <inlineHelpText>From Zip Code object</inlineHelpText>
    <label>County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>the zip code assigned to the office</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/Related_Party__c.object-meta.xml
<CustomObject>
    <label>Related Party</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Related Party  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Party__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/recordTypes/Claimant.recordType-meta.xml
<RecordType>
    <fullName>Claimant</fullName>
    <active>true</active>
    <description>This is used for the Online Claim.</description>
    <label>Claimant</label>
</RecordType>

force-app/main/default/objects/Related_Party__c/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>true</active>
    <label>Employee</label>
</RecordType>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the zip code is within</description>
    <inlineHelpText>Enter the city that this zip code is in.</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OCEmailServiceUtilityTest.cls
@isTest
public class OCEmailServiceUtilityTest
{
    
    static testMethod void sendConfirmationEmailtoClaimantTest()
    {
        Trigger_Settings__c setting = new Trigger_Settings__c();
        setting.Name = 'GenerateFieldHistoryAction';
        setting.Is_Active__c = TRUE;
        insert setting;
        
        DIR_Case__c cse = new DIR_Case__c();
        List<DIR_Case__c> dirCases=new List<DIR_Case__c>();
        cse.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
        cse.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
        cse.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
        cse.Status__c = 'Not Confirmed';
        cse.Advocate_Name_in_Text__c = 'Rajat';
        cse.Employer_Name_in_Text__c = 'Amit';
        cse.Claimant_Name_in_Text__c = 'Abhay';
        cse.Case_Number__c = 'testnumber';
        cse.Applicant_Type__c = 'Representative Garment';
        dirCases.add(cse);
        insert dirCases;
        
        ContentVersion content=new ContentVersion(); 
        content.Title='Wage Claim Summary Report'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        //content.LinkedEntityId=sub.id;
         content.PathOnClient='/' + content.Title + '.jpg'; 
        content.origin = 'H';
        insert content;
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=dirCases[0].id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        
        
        insert contentlink;
 
        
         DIR_Case__c cse1 = new DIR_Case__c();
        List<DIR_Case__c> dirCases1=new List<DIR_Case__c>();
        cse1.recordTypeId = OWCConstants.WCA_CASE_RECORD_TYPE_ID;
        cse1.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
        cse1.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
        cse1.Status__c = 'New';
        cse1.Referred_From__c='Claimant';
        cse1.Applicant_Type__c='Claimant Garment';
        cse1.Advocate_Name_in_Text__c = 'Rajat';
        cse1.Employer_Name_in_Text__c = 'Amit';
        cse1.Claimant_Name_in_Text__c = 'Abhay';
        cse1.Case_Number__c = 'testnumber';
        dirCases1.add(cse1);
        insert dirCases1;
        
        
         DIR_Case__c cse2 = new DIR_Case__c();
        List<DIR_Case__c> dirCases2=new List<DIR_Case__c>();
        cse2.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
        cse2.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
        cse2.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
        cse2.Status__c = 'New';
        cse2.Referred_From__c='';
        cse2.Applicant_Type__c='Claimant Garment';
        cse2.Advocate_Name_in_Text__c = 'Rajat';
        cse2.Employer_Name_in_Text__c = 'Amit';
        cse2.Claimant_Name_in_Text__c = 'Abhay';
        cse2.Case_Number__c = 'testnumber';
        dirCases2.add(cse2);
        insert dirCases2;
        
        DIR_Case__c cse3 = new DIR_Case__c();
        List<DIR_Case__c> dirCases3=new List<DIR_Case__c>();
        cse3.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
        cse3.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
        cse3.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
        cse3.Status__c = 'New';
        cse3.Referred_From__c='Claimant';
        cse3.Applicant_Type__c='';
        cse3.Advocate_Name_in_Text__c = 'Rajat';
        cse3.Employer_Name_in_Text__c = 'Amit';
        cse3.Claimant_Name_in_Text__c = 'Abhay';
        cse3.Case_Number__c = 'testnumber';
        dirCases3.add(cse3);
        insert dirCases3;
        
        ContentVersion content1=new ContentVersion(); 
        content1.Title='Wage Claim Summary Report'; 
        Blob bodyBlob1=Blob.valueOf('Unit Test ContentVersion Body'); 
        content1.VersionData=bodyBlob1; 
        //content.LinkedEntityId=sub.id;
         content1.PathOnClient='/' + content1.Title + '.jpg'; 
        content1.origin = 'H';
        insert content1;
        ContentDocumentLink contentlink1=new ContentDocumentLink();
        contentlink1.LinkedEntityId=dirCases3[0].id;
        contentlink1.contentdocumentid=[select contentdocumentid from contentversion where id =: content1.id].contentdocumentid;
        contentlink1.ShareType = 'I';
        contentlink1.Visibility = 'AllUsers'; 
        
        
        insert contentlink1;
        
        
        OCEmailServiceUtility.sendConfirmationEmailtoClaimant(dirCases);
        OCEmailServiceUtility.sendConfirmationEmailtoClaimant(dirCases1);
        OCEmailServiceUtility.sendConfirmationEmailtoClaimant(dirCases2);
        OCEmailServiceUtility.sendConfirmationEmailtoClaimant(dirCases3);
        OCEmailServiceUtility.sendTestEmail('Testing 123');
        OCEmailServiceUtility.sendOfficeChangeEmailToClaimant('Office_Assignment_change_notification', cse.Id);
        OCEmailServiceUtility.sendOfficeChangeEmailToAdvocate('Office_Assignment_change_notification', cse.Id);
    }
    static testMethod void sendConfirmationEmailtoClaimantTest2()
    {	
        User usr = [SELECT Id, LanguageLocaleKey FROM User WHERE Id =: UserInfo.getUserId()];
        usr.LanguageLocaleKey = 'es';
        update usr;
        System.runAs(usr){
            Trigger_Settings__c setting = new Trigger_Settings__c();
            setting.Name = 'GenerateFieldHistoryAction';
            setting.Is_Active__c = TRUE;
            insert setting;
            
            DIR_Case__c cse = new DIR_Case__c();
            List<DIR_Case__c> dirCases=new List<DIR_Case__c>();
            cse.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
            cse.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
            cse.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
            cse.Status__c = 'Not Confirmed';
            cse.Advocate_Name_in_Text__c = 'Rajat';
            cse.Employer_Name_in_Text__c = 'Amit';
            cse.Claimant_Name_in_Text__c = 'Abhay';
            cse.Case_Number__c = 'testnumber';
            dirCases.add(cse);
            insert dirCases;
            
            ContentVersion content=new ContentVersion(); 
            content.Title='Header_Picture1'; 
            Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
            content.VersionData=bodyBlob; 
            //content.LinkedEntityId=sub.id;
             content.PathOnClient='/' + content.Title + '.jpg'; 
            content.origin = 'H';
            insert content;
            ContentDocumentLink contentlink=new ContentDocumentLink();
            contentlink.LinkedEntityId=dirCases[0].id;
            contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
            contentlink.ShareType = 'I';
            contentlink.Visibility = 'AllUsers'; 
            
            
            insert contentlink;
            
            DIR_Case__c cse1 = new DIR_Case__c();
            List<DIR_Case__c> dirCases1=new List<DIR_Case__c>();
            cse1.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
            cse1.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
            cse1.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
            cse1.Status__c = 'New';
            cse1.Referred_From__c='';
            cse1.Applicant_Type__c='Representative Garment';
            cse1.Advocate_Name_in_Text__c = 'Rajat';
            cse1.Employer_Name_in_Text__c = 'Amit';
            cse1.Claimant_Name_in_Text__c = 'Abhay';
            cse1.Case_Number__c = 'testnumber';
            dirCases1.add(cse1);
            insert dirCases1;
            
            DIR_Case__c cse2 = new DIR_Case__c();
            List<DIR_Case__c> dirCases2=new List<DIR_Case__c>();
            cse2.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
            cse2.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
            cse2.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
            cse2.Status__c = 'New';
            cse2.Referred_From__c='';
            cse2.Applicant_Type__c='Claimant Garment';
            cse2.Advocate_Name_in_Text__c = 'Rajat';
            cse2.Employer_Name_in_Text__c = 'Amit';
            cse2.Claimant_Name_in_Text__c = 'Abhay';
            cse2.Case_Number__c = 'testnumber';
            dirCases2.add(cse2);
            insert dirCases2;
            
            DIR_Case__c cse3 = new DIR_Case__c();
            List<DIR_Case__c> dirCases3=new List<DIR_Case__c>();
            cse3.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
            cse3.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
            cse3.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
            cse3.Status__c = 'New';
            cse3.Referred_From__c='Claimant';
            cse3.Applicant_Type__c='';
            cse3.Advocate_Name_in_Text__c = 'Rajat';
            cse3.Employer_Name_in_Text__c = 'Amit';
            cse3.Claimant_Name_in_Text__c = 'Abhay';
            cse3.Case_Number__c = 'testnumber';
            dirCases3.add(cse3);
            insert dirCases3;
            
            OCEmailServiceUtility.sendConfirmationEmailtoClaimant(dirCases);
            OCEmailServiceUtility.sendConfirmationEmailtoClaimant(dirCases1);
            OCEmailServiceUtility.sendConfirmationEmailtoClaimant(dirCases2);
            OCEmailServiceUtility.sendConfirmationEmailtoClaimant(dirCases3);
            OCEmailServiceUtility.sendTestEmail('Testing 123');
            OCEmailServiceUtility.sendOfficeChangeEmailToClaimant('Office_Assignment_change_notification', cse.Id);
            OCEmailServiceUtility.sendOfficeChangeEmailToAdvocate('Office_Assignment_change_notification', cse.Id);
        }
        
    }
    static testMethod void sendAutoResponseTest()
    {
        Trigger_Settings__c setting = new Trigger_Settings__c();
        setting.Name = 'GenerateFieldHistoryAction';
        setting.Is_Active__c = TRUE;
        insert setting;
        
        Account objAcct1 = new Account(Name = 'Acct1', ShippingCity = 'ShippingCity1', BillingCity = 'BillingCity1');
        Account objAcct2 = new Account(Name = 'Acct2', ShippingCity = 'ShippingCity2', BillingCity = 'BillingCity2');
        insert new List<Account> {objAcct1,objAcct2}; 
            
             Zip_Code__c zip=new Zip_Code__c();
        zip.City__c='Santa Clara Ave';
        zip.County__c='Alameda';
        zip.Region__c='North';
        zip.Name='94501';
        insert zip;
        
        Office__c ofc=new Office__c();
        ofc.Name='WCA - OUT OF STATE';
        ofc.Address_1__c='243 Santa Clara Blvd';
        ofc.City__c='Santa Clara Ave';
        ofc.County__c='Alameda';
        ofc.RecordTypeId= Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        insert ofc;
        
        Office_Zip_Code_Map__c ofczip =new Office_Zip_Code_Map__c();
        ofczip.Zip_Code__c=zip.Id;
        ofczip.Office__c=ofc.Id;
        insert ofczip;
        
            
            DIR_Case__c cse = new DIR_Case__c();
        cse.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
        cse.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
        cse.Status__c = 'New';
        cse.Advocate_Name_in_Text__c = 'Rajat12345678';
        cse.Employer_Name_in_Text__c = 'Amit';
        cse.Claimant_Name_in_Text__c = 'Abhay';
        cse.Case_Number__c = 'testnumber';
        cse.Intake_Origin__c='Online';
        cse.Office__c=ofc.Id;
        insert cse;
        
        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = cse.Id,
                                                       Role__c = 'Defendant',
                                                       Street_Address__c = '123 Praire City Drive, Apt B',
                                                       City__c = 'Whittier',
                                                       State__c = 'CA',
                                                       Zip_Code__c = '90607',
                                                       RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                      );
        
       
        insert new List<Related_Party__c> {objRL1};
            
            
            List<DIR_Case__c> cseList = [SELECT Id,Name,Claimant_Name_in_Text__c,Advocate_Name_in_Text__c,Related_Party_Employer_Name__c,Case_Number__c,Office__r.Name  
                                         FROM DIR_Case__c WHERE Advocate_Name_in_Text__c='Rajat12345678' ];
        
          OCEmailServiceUtility.sendAutoResponse(cseList,'Claim Email Reply Confirm',cse.Related_Party_Employee_Email__c);
        OCEmailServiceUtility.sendNewOnlineClaimEmail(cse);
      
        
        
        
    }
    static testMethod void sendAutoResponseTest2()
    {	
        
        User usr = [SELECT Id, LanguageLocaleKey FROM User WHERE Id =: UserInfo.getUserId()];
        usr.LanguageLocaleKey = 'es';
        update usr;
        
        System.runAs(usr){
            Trigger_Settings__c setting = new Trigger_Settings__c();
            setting.Name = 'GenerateFieldHistoryAction';
            setting.Is_Active__c = TRUE;
            insert setting;
            
            Account objAcct1 = new Account(Name = 'Acct1', ShippingCity = 'ShippingCity1', BillingCity = 'BillingCity1');
            Account objAcct2 = new Account(Name = 'Acct2', ShippingCity = 'ShippingCity2', BillingCity = 'BillingCity2');
            insert new List<Account> {objAcct1,objAcct2}; 
                
                Zip_Code__c zip=new Zip_Code__c();
            zip.City__c='Santa Clara Ave';
            zip.County__c='Alameda';
            zip.Region__c='North';
            zip.Name='94501';
            insert zip;
            
            Office__c ofc=new Office__c();
            ofc.Name='WCA - OUT OF STATE';
            ofc.Address_1__c='243 Santa Clara Blvd';
            ofc.City__c='Santa Clara Ave';
            ofc.County__c='Alameda';
            ofc.RecordTypeId= Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
            insert ofc;
            
            Office_Zip_Code_Map__c ofczip =new Office_Zip_Code_Map__c();
            ofczip.Zip_Code__c=zip.Id;
            ofczip.Office__c=ofc.Id;
            insert ofczip;
            
            
            DIR_Case__c cse = new DIR_Case__c();
            cse.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
            cse.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
            cse.Status__c = 'New';
            cse.Advocate_Name_in_Text__c = 'Rajat12345678';
            cse.Employer_Name_in_Text__c = 'Amit';
            cse.Claimant_Name_in_Text__c = 'Abhay';
            cse.Case_Number__c = 'testnumber';
            cse.Intake_Origin__c='Online';
            cse.Office__c=ofc.Id;
            insert cse;
            
            Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = cse.Id,
                                                           Role__c = 'Defendant',
                                                           Street_Address__c = '123 Praire City Drive, Apt B',
                                                           City__c = 'Whittier',
                                                           State__c = 'CA',
                                                           Zip_Code__c = '90607',
                                                           RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                          );
            
            
            insert new List<Related_Party__c> {objRL1};
                
                
                List<DIR_Case__c> cseList = [SELECT Id,Name,Claimant_Name_in_Text__c,Advocate_Name_in_Text__c,Related_Party_Employer_Name__c,Case_Number__c,Office__r.Name  
                                             FROM DIR_Case__c WHERE Advocate_Name_in_Text__c='Rajat12345678' ];
            
            OCEmailServiceUtility.sendAutoResponse(cseList,'Claim Email Reply Confirm',cse.Related_Party_Employee_Email__c);
            OCEmailServiceUtility.sendNewOnlineClaimEmail(cse);
        }
        
    }
        static testMethod void sendAutoResponseTest3()
    {	
        
        
            Trigger_Settings__c setting = new Trigger_Settings__c();
            setting.Name = 'GenerateFieldHistoryAction';
            setting.Is_Active__c = TRUE;
            insert setting;
            
            Account objAcct1 = new Account(Name = 'Acct1', ShippingCity = 'ShippingCity1', BillingCity = 'BillingCity1');
            Account objAcct2 = new Account(Name = 'Acct2', ShippingCity = 'ShippingCity2', BillingCity = 'BillingCity2');
            insert new List<Account> {objAcct1,objAcct2}; 
                
                Zip_Code__c zip=new Zip_Code__c();
            zip.City__c='Santa Clara Ave';
            zip.County__c='Alameda';
            zip.Region__c='North';
            zip.Name='94501';
            insert zip;
            
            Office__c ofc=new Office__c();
            ofc.Name='Callifornia';
            ofc.Address_1__c='243 Santa Clara Blvd';
            ofc.City__c='Santa Clara Ave';
            ofc.County__c='Alameda';
            ofc.RecordTypeId= Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
            insert ofc;
            
            Office_Zip_Code_Map__c ofczip =new Office_Zip_Code_Map__c();
            ofczip.Zip_Code__c=zip.Id;
            ofczip.Office__c=ofc.Id;
            insert ofczip;
            
            DIR_Case__c cse = new DIR_Case__c();
            List<DIR_Case__c> dirCases=new List<DIR_Case__c>();
            cse.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
            cse.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
            cse.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
            cse.Status__c = 'New';
            cse.Advocate_Name_in_Text__c = 'Rajat';
            cse.Employer_Name_in_Text__c = 'Amit';
            cse.Claimant_Name_in_Text__c = 'Abhay';
            cse.Case_Number__c = 'testnumber';
        cse.Office__c = ofc.id;
        dirCases.add(cse);
        insert dirCases;
        ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        //content.LinkedEntityId=sub.id;
        content.origin = 'H';
        content.PathOnClient='/' + content.Title + '.jpg'; 
        insert content;
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=dirCases[0].id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        
        
        insert contentlink;
        
            DIR_Case__c cse1 = new DIR_Case__c();
            List<DIR_Case__c> dirCases1=new List<DIR_Case__c>();
            cse1.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
            cse1.Related_Party_Employee_Email__c = 'rrastogi@cloudsciencelabs.com';
            cse1.Related_Party_Advocate_Email__c='dmaurya@cloudsciencelabs.com';
            cse1.Status__c = 'New';
            cse1.Referred_From__c='';
            cse1.Applicant_Type__c='Representative Garment';
            cse1.Advocate_Name_in_Text__c = 'Rajat12345678';
            cse1.Employer_Name_in_Text__c = 'Amit';
            cse1.Claimant_Name_in_Text__c = 'Abhay';
            cse1.Case_Number__c = 'testnumber';
            dirCases1.add(cse1);
            insert dirCases1;
            
            Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = cse1.Id,
                                                           Role__c = 'Defendant',
                                                           Street_Address__c = '123 Praire City Drive, Apt B',
                                                           City__c = 'Whittier',
                                                           State__c = 'CA',
                                                           Zip_Code__c = '90607',
                                                           RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                          );
            
            
            insert new List<Related_Party__c> {objRL1};
                
                
                List<DIR_Case__c> cseList = [SELECT Id,Name,Related_Party_Advocate_Email__c,Claimant_Name_in_Text__c,Advocate_Name_in_Text__c,CreatedDate,Related_Party_Employer_Name__c,Case_Number__c,Office__r.Name  
                                             FROM DIR_Case__c WHERE Advocate_Name_in_Text__c='Rajat12345678' ];
            
            OCEmailServiceUtility.sendAutoResponse(cseList,'Claim Email Reply Confirm',cse1.Related_Party_Employee_Email__c);
        	OCEmailServiceUtility.sendEmailToClaimantOnYourself('Claimant_notification_Claim_submitted_by_Claimant',dirCases[0].Id,'California');
        	OCEmailServiceUtility.sendEmailToAdvocateOnConfirm('Advocate_notification_Confirmed',dirCases[0]);
        
            List<DIR_Case__c> cseList1 = [SELECT Id,Name,Claimant_Name_in_Text__c,Related_Party_Advocate_Email__c,CreatedDate,Advocate_Name_in_Text__c,Related_Party_Employer_Name__c,Case_Number__c,Office__r.Name  
                                         FROM DIR_Case__c WHERE Advocate_Name_in_Text__c='Rajat' ];
        
        	OCEmailServiceUtility.sendEmailtoAdvocateOnClosed(cseList1[0]);
            OCEmailServiceUtility.sendNewOnlineClaimEmail(cse1);
            
        
    }
    
}