force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <inlineHelpText>County is used to prepare official documents</inlineHelpText>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outside CA</fullName>
            </value>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>Amador</fullName>
            </value>
            <value>
                <fullName>Butte</fullName>
            </value>
            <value>
                <fullName>Calaveras</fullName>
            </value>
            <value>
                <fullName>Colusa</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Del Norte</fullName>
            </value>
            <value>
                <fullName>El Dorado</fullName>
            </value>
            <value>
                <fullName>Fresno</fullName>
            </value>
            <value>
                <fullName>Glenn</fullName>
            </value>
            <value>
                <fullName>Humboldt</fullName>
            </value>
            <value>
                <fullName>Imperial</fullName>
            </value>
            <value>
                <fullName>Inyo</fullName>
            </value>
            <value>
                <fullName>Kern</fullName>
            </value>
            <value>
                <fullName>Kings</fullName>
            </value>
            <value>
                <fullName>Lake</fullName>
            </value>
            <value>
                <fullName>Lassen</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Madera</fullName>
            </value>
            <value>
                <fullName>Marin</fullName>
            </value>
            <value>
                <fullName>Mariposa</fullName>
            </value>
            <value>
                <fullName>Mendocino</fullName>
            </value>
            <value>
                <fullName>Merced</fullName>
            </value>
            <value>
                <fullName>Modoc</fullName>
            </value>
            <value>
                <fullName>Mono</fullName>
            </value>
            <value>
                <fullName>Monterey</fullName>
            </value>
            <value>
                <fullName>Napa</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>A picklist for North or South Region</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Related_Party_Employee_Email__c.field-meta.xml
<CustomField>
    <fullName>Related_Party_Employee_Email__c</fullName>
    <label>Related Party Employee Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To populate Region field</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <description>Line 1 of address</description>
    <label>Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>County of the BOFE/Wage office</description>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Identifies offices as WAGE</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/Office_Zip_Code_Map__c/Office_Zip_Code_Map__c.object-meta.xml
<CustomObject>
    <description>Maps zip codes to office locations. Used for assigning records to offices based on zip codes</description>
    <label>Office-Zip Code Map</label>
    <nameField>
        <displayFormat>Map-{00000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office-Zip Code Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>From Zip Code object</description>
    <formula>TEXT(Zip_Code__r.County__c)</formula>
    <inlineHelpText>From Zip Code object</inlineHelpText>
    <label>County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>The office that the zip code is assigned to</description>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Office_Zip_Code_Map__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>the zip code assigned to the office</description>
    <label>Zip Code</label>
    <referenceTo>Zip_Code__c</referenceTo>
    <relationshipLabel>Office-Zip Code Maps</relationshipLabel>
    <relationshipName>Office_Zip_Code_Maps</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/Related_Party__c.object-meta.xml
<CustomObject>
    <label>Related Party</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Related Party  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Party__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>true</active>
    <label>Employee</label>
</RecordType>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the zip code is within</description>
    <inlineHelpText>Enter the city that this zip code is in.</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>Amador</fullName>
            </value>
            <value>
                <fullName>Butte</fullName>
            </value>
            <value>
                <fullName>Calaveras</fullName>
            </value>
            <value>
                <fullName>Colusa</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
            <value>
                <fullName>Del Norte</fullName>
            </value>
            <value>
                <fullName>El Dorado</fullName>
            </value>
            <value>
                <fullName>Fresno</fullName>
            </value>
            <value>
                <fullName>Glenn</fullName>
            </value>
            <value>
                <fullName>Humboldt</fullName>
            </value>
            <value>
                <fullName>Imperial</fullName>
            </value>
            <value>
                <fullName>Inyo</fullName>
            </value>
            <value>
                <fullName>Kern</fullName>
            </value>
            <value>
                <fullName>Kings</fullName>
            </value>
            <value>
                <fullName>Lake</fullName>
            </value>
            <value>
                <fullName>Lassen</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Madera</fullName>
            </value>
            <value>
                <fullName>Marin</fullName>
            </value>
            <value>
                <fullName>Mariposa</fullName>
            </value>
            <value>
                <fullName>Mendocino</fullName>
            </value>
            <value>
                <fullName>Merced</fullName>
            </value>
            <value>
                <fullName>Modoc</fullName>
            </value>
            <value>
                <fullName>Mono</fullName>
            </value>
            <value>
                <fullName>Monterey</fullName>
            </value>
            <value>
                <fullName>Napa</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_OWCServiceUtility.cls
@isTest
public class Test_OWCServiceUtility {
    @isTest
    public static void getDuplicateAccountTest(){
        
        Account ob=new Account();
        ob.PersonEmail='abc@gmail.com';
        ob.firstName='abc';
        ob.lastName='xyz';
        ob.Name='abc xyz';
        ob.Email__c='abcxyz@gmail.com';
        String typeId =[SELECT Id FROM RecordType WHERE Name = 'Person Account'].Id;
        ob.RecordTypeId=typeId; 
        
        Zip_Code__c zipCodeObj = new Zip_Code__c();
        zipCodeObj.City__c = 'New York';
        zipCodeObj.County__c = 'Alameda';
        zipCodeObj.Name = 'test';
        insert zipCodeObj;
        
        Office__c officeObj = new Office__c();
        officeObj.City__c = 'New York';
        insert officeObj;
        
        Office_Zip_Code_Map__c officeZipObj = new Office_Zip_Code_Map__c();
        officeZipObj.Office__c = officeObj.Id;
        officeZipObj.Zip_Code__c = zipCodeObj.Id;
        insert officeZipObj;
        
        Account ob1=new Account();
        ob1.PersonEmail='abc@gmail.com';
        ob1.firstName='abc';
        ob1.lastName='xyz';
        ob1.Name='abc xyz';
        ob1.Email__c='abcxyz@gmail.com';
        ob1.RecordTypeId=null; 
        
        
        
        Test.startTest();
        try{
            Account ob3=new Account();
            System.debug('ob3:::'+ob3);
            insert ob3;
        }catch(Exception ex){
            System.debug('ex:::'+ex);
            new OWCServiceUtility().log(ex);  
        }
        OWCServiceUtility.getDuplicateAccount(ob);  
        OWCServiceUtility.getDuplicateAccount(ob1);
        // OWCServiceUtility.getOfficeLocationByZIPCode('test');
        OWCServiceUtility.getdeserializeUntypedMap('{"name":"John", "Email":"qwer@gmail.com", "lastName":null}');
        OWCServiceUtility.generateJSON('Open','test','fail to update');
        //OWCServiceUtility.populateOfficeOnCM(cse);
        Test.stopTest();
        
        
    }
    
    @isTest static void getPopulateofficeByCm(){
        Trigger_Settings__c setting = new Trigger_Settings__c();
        setting.Name = 'GenerateFieldHistoryAction';
        setting.Is_Active__c = TRUE;
        insert setting;
        
        StaticResource srs = [SELECT Id, Body FROM StaticResource WHERE Name = 'OWCPDFJsonTestData' LIMIT 1];
        Zip_Code__c zip=new Zip_Code__c();
        zip.City__c='Santa Clara Ave';
        zip.County__c='Alameda';
        zip.Region__c='North';
        zip.Name='94501';
        insert zip;
        
        Office__c ofc=new Office__c();
        ofc.Name='WCA - OUT OF STATE';
        ofc.Address_1__c='243 Santa Clara Blvd';
        ofc.City__c='Santa Clara Ave';
        ofc.County__c='Alameda';
        ofc.RecordTypeId= Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        insert ofc;
        
        Office_Zip_Code_Map__c ofczip =new Office_Zip_Code_Map__c();
        ofczip.Zip_Code__c=zip.Id;
        ofczip.Office__c=ofc.Id;
        insert ofczip;
        
        
        DIR_Case__c cse = new DIR_Case__c();
        cse.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
        cse.Related_Party_Employee_Email__c = 'dsyadav@cloudsciencelabs.com';
        cse.Status__c = 'New';
        cse.Advocate_Name_in_Text__c = 'Rajat12345678';
        cse.Employer_Name_in_Text__c = 'Amit';
        cse.Claimant_Name_in_Text__c = 'Abhay';
        cse.Case_Number__c = 'testnumber';
        cse.Intake_Origin__c='Online';
        cse.Office__c=ofc.Id;
        insert cse;
        
        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = cse.Id,
                                                       Role__c = 'Defendant',
                                                       Street_Address__c = '123 Praire City Drive, Apt B',
                                                       City__c = 'Whittier',
                                                       State__c = 'CA',
                                                       Zip_Code__c = '90607',
                                                       RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                      );
        
        
        insert new List<Related_Party__c> {objRL1};
            
            
  		List<DIR_Case__c> cseList = [SELECT Id,Name,Claimant_Name_in_Text__c,Advocate_Name_in_Text__c,Related_Party_Employer_Name__c,Case_Number__c,Office__r.Name  
                                         FROM DIR_Case__c WHERE Advocate_Name_in_Text__c='Rajat12345678' ];
        
        System.debug('cseList::::'+cseList);
        System.debug('cse:::::'+cse);
        
        
        Test.startTest();
        OWCServiceUtility.populateOfficeOnCM(cse);
        OWCServiceUtility.getOfficeNameByZipCode('94501');
        OWCServiceUtility.validateOfficeAssignment('94501','94501','94501');
        OWCServiceUtility.validateOfficeAssignment('94501','' ,'');
        Test.stopTest();
    }
    
    @isTest static void getPopulateofficeByCm1(){
        Trigger_Settings__c setting = new Trigger_Settings__c();
        setting.Name = 'GenerateFieldHistoryAction';
        setting.Is_Active__c = TRUE;
        insert setting;
        
        StaticResource srs = [SELECT Id, Body FROM StaticResource WHERE Name = 'OWCPDFJsonTestData' LIMIT 1];
        Zip_Code__c zip=new Zip_Code__c();
        zip.City__c='Santa Clara Ave';
        zip.County__c='Alameda';
        zip.Region__c='North';
        zip.Name='94501';
        insert zip;
        
        Office__c ofc=new Office__c();
        ofc.Name='WCA - OUT OF STATE';
        ofc.Address_1__c='243 Santa Clara Blvd';
        ofc.City__c='Santa Clara Ave';
        ofc.County__c='Alameda';
        ofc.RecordTypeId= Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        insert ofc;
        
        Office_Zip_Code_Map__c ofczip =new Office_Zip_Code_Map__c();
        ofczip.Zip_Code__c=zip.Id;
        ofczip.Office__c=ofc.Id;
        insert ofczip;
        
        
        DIR_Case__c cse = new DIR_Case__c();
        cse.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
        cse.Related_Party_Employee_Email__c = 'dsyadav@cloudsciencelabs.com';
        cse.Status__c = 'New';
        cse.Advocate_Name_in_Text__c = 'Rajat12345678';
        cse.Employer_Name_in_Text__c = 'Amit';
        cse.Claimant_Name_in_Text__c = 'Abhay';
        cse.Case_Number__c = 'testnumber';
        cse.Intake_Origin__c='Online';
        
        insert cse;
        
        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = cse.Id,
                                                       Role__c = 'Defendant',
                                                       Street_Address__c = '123 Praire City Drive, Apt B',
                                                       City__c = 'Whittier',
                                                       State__c = 'CA',
                                                       Zip_Code__c = '90607',
                                                       RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                      );
        
        
        insert new List<Related_Party__c> {objRL1};
            
            
            List<DIR_Case__c> cseList = [SELECT Id,Name,Claimant_Name_in_Text__c,Advocate_Name_in_Text__c,Related_Party_Employer_Name__c,Case_Number__c,Office__r.Name  
                                         FROM DIR_Case__c WHERE Advocate_Name_in_Text__c='Rajat12345678' ];
        
        System.debug('cseList::::'+cseList);
        System.debug('cse:::::'+cse);
        
        
        Test.startTest();
        OWCServiceUtility.populateOfficeOnCM(cse);
        Test.stopTest();
    }
    
    @isTest static void getPopulateofficeByCm2(){
        Trigger_Settings__c setting = new Trigger_Settings__c();
        setting.Name = 'GenerateFieldHistoryAction';
        setting.Is_Active__c = TRUE;
        insert setting;
        
        StaticResource srs = [SELECT Id, Body FROM StaticResource WHERE Name = 'OWCPDFJsonTestData' LIMIT 1];
        Zip_Code__c zip=new Zip_Code__c();
        zip.City__c='Santa Clara Ave';
        zip.County__c='Alameda';
        zip.Region__c='North';
        zip.Name='94501';
        insert zip;
        
        Office__c ofc=new Office__c();
        ofc.Name='WCA - OUT OF STATE';
        ofc.Address_1__c='243 Santa Clara Blvd';
        ofc.City__c='Santa Clara Ave';
        ofc.County__c='Alameda';
        ofc.RecordTypeId= Schema.SObjectType.Office__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        insert ofc;
        
        Office_Zip_Code_Map__c ofczip =new Office_Zip_Code_Map__c();
        ofczip.Zip_Code__c=zip.Id;
        ofczip.Office__c=ofc.Id;
        insert ofczip;
        
        
        DIR_Case__c cse = new DIR_Case__c();
        cse.recordTypeId = OWCConstants.PRE_DOCKETING_CASE_RECORD_TYPE_ID;
        cse.Related_Party_Employee_Email__c = 'dsyadav@cloudsciencelabs.com';
        cse.Status__c = 'New';
        cse.Advocate_Name_in_Text__c = 'Rajat12345678';
        cse.Employer_Name_in_Text__c = 'Amit';
        cse.Claimant_Name_in_Text__c = 'Abhay';
        cse.Case_Number__c = 'testnumber';
        cse.Intake_Origin__c='Online';
        
        insert cse;
        
        Related_Party__c objRL1 = new Related_Party__c(Case_Management__c = cse.Id,
                                                       Role__c = 'Defendant',
                                                       Street_Address__c = '123 Praire City Drive, Apt B',
                                                       City__c = 'Whittier',
                                                       State__c = 'CA',
                                                       Zip_Code__c = '12345',
                                                       RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByName().get('Employee').getRecordTypeId()
                                                      );
        
        
        insert new List<Related_Party__c> {objRL1};
            
            
            List<DIR_Case__c> cseList = [SELECT Id,Name,Claimant_Name_in_Text__c,Advocate_Name_in_Text__c,Related_Party_Employer_Name__c,Case_Number__c,Office__r.Name  
                                         FROM DIR_Case__c WHERE Advocate_Name_in_Text__c='Rajat12345678' ];
        
        System.debug('cseList::::'+cseList);
        System.debug('cse:::::'+cse);
        
        
        Test.startTest();
        OWCServiceUtility.populateOfficeOnCM(cse);
        Test.stopTest();
    }
    
}