force-app/main/default/objects/Account/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Effective Date of the Entity Registration</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Entity Registration</description>
    <inlineHelpText>Expiration Date of the Entity Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>Official registered legal entity name</description>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Account__c</fullName>
    <label>Registration Account</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <description>Populated via DLRS from Fee Summary</description>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Amount_Paid_Manually__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid_Manually__c</fullName>
    <description>Total amount paid by physical check/money order. Populated via DLRS rollup.</description>
    <label>Amount Paid Manually</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Amount_Paid_Online__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid_Online__c</fullName>
    <description>Total Amount paid via Chargent. Populated via DLRS rollup.</description>
    <label>Amount Paid Online</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Deputy that is going to process this registration.</inlineHelpText>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DIR_Employee__c.Position__c</field>
            <operation>equals</operation>
            <value>Registration Services</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>calculates the balance due with zero being the lowest it can be.</description>
    <formula>MAX(Amount_Due__c -   Amount_Paid_Manually__c -  Amount_Paid_Online__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <inlineHelpText>Please enter name registered with CA Secretary of State.  For Sole Proprietor enter full legal name.</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Registration_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the registration account that became the account on this registration. Used for matching during renewal</description>
    <label>Registration Account</label>
    <referenceTo>Registration_Account__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations_Key_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Registration_Duration__c.field-meta.xml
<CustomField>
    <fullName>Registration_Duration__c</fullName>
    <label>Registration Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 Days - Temporary Permit</fullName>
            </value>
            <value>
                <fullName>6 Months - Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Residential_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Residential_Address_Line_1__c</fullName>
    <inlineHelpText>P.O. Box address is not allowed.</inlineHelpText>
    <label>Residential Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Residential_City__c.field-meta.xml
<CustomField>
    <fullName>Residential_City__c</fullName>
    <label>Residential City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Payment__c</fullName>
    <description>Sets the payment status for display on community page based on the amount due and the balance due.</description>
    <formula>IF(
 Amount_Due__c &lt;= 0, '',
 IF( Balance__c &gt; 0, "Not Paid", "Paid / No Balance Due") )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status of Payment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Submission_Type__c</fullName>
    <label>Submission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
                <default>true</default>
                <label>Online</label>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/Registration_Account__c.object-meta.xml
<CustomObject>
    <description>Staging object used to collect Company/Account information on Registration forms.</description>
    <label>Registration Account</label>
    <nameField>
        <displayFormat>RA-{000000000}</displayFormat>
        <label>Registration Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>Mapped to Legal_Entity_Name__c Account field.</description>
    <inlineHelpText>Employer</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Residential_City__c.field-meta.xml
<CustomField>
    <fullName>Residential_City__c</fullName>
    <label>Residential City / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Residential_State__c.field-meta.xml
<CustomField>
    <fullName>Residential_State__c</fullName>
    <label>Residential State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Submission_Type__c</fullName>
    <formula>TEXT(Registration__r.Submission_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Submission Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegistrationEWPResultsControllerTest.cls
@istest
public class RegistrationEWPResultsControllerTest {
    
    RegistrationEWPResultsControllerTest(){
        
    }
    
    public static testMethod void testRegistrationResults3(){
         Id personRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Id indivRecordTypeId = Schema.SObjectType.Registration_Account__c .getRecordTypeInfosByName().get('Individual Permit').getRecordTypeId();
        Id parentRecordTypeId = Schema.SObjectType.Registration_Account__c .getRecordTypeInfosByName().get('Parent Guardian').getRecordTypeId();
        //Id devRecordTypeId = Schema.getGlobalDescribe().get('License_Registration__c').getDescribe().getRecordTypeInfosByName().get('Entertainment Work').getRecordTypeId();
        Id RecordTypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Entertainment Work').getRecordTypeId();

        
        Account acc2 = new Account(
            FirstName = 'ewp',
            LastName = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212',
            PersonEmail = 'lralltestusers@test.com',
            RecordTypeId = personRecordTypeId
        );
        insert acc2;
        
        Contact con2 = new Contact();
        con2.FirstName = 'Test';
        con2.LastName = 'Test';
        con2.Email = 'testLNRDEV@testdir.com';
        insert con2;
        
        License_Registration__c lreg = new License_Registration__c();
        lreg.RecordTypeId = RecordTypeId;
        lreg.Account__c = acc2.Id;
        lreg.Applicant__c = con2.Id;
        lreg.License_Registration_Number__c = 'xxxxx';
        lreg.Status__c = 'Renewed';
        //lreg.Assigned_Deputy__c = deputy.Id;
        lreg.Legal_Entity_Name__c = 'name';
        lreg.Registration_Duration__c  = '10 Days - Temporary Permit';
        //lreg.Registration_Duration__c  = '6 Months - Permit';
        lreg.Submission_Type__c = 'Online';
        //lreg.Status_of_Payment__c = 'Paid / No Balance Due';
        //lreg.Balance__c = 0;
        lreg.Amount_Due__c = 50;
        lreg.Amount_Paid_Online__c  = 50;
        lreg.Amount_Paid_Manually__c = 0;
        lreg.Status__c = 'Pending Payment';
        lreg.Effective_Date__c = Date.today() - 5;
        lreg.Expiration_Date__c = Date.today() + 90;
        lreg.Residential_Address_Line_1__c = 'test street';
        lreg.Residential_City__c = 'oak';
        lreg.Residential_State__c = 'ca';
        lreg.Residential_Postal_Code__c = '94612';
        lreg.Mailing_Address_Line_1__c = 'Street ';
        lreg.Mailing_City__c = 'San Francisco';
        lreg.Mailing_State__c = 'CA';
        lreg.Mailing_Postal_Code__c = '94612';
        lreg.First_Name__c = 'FirstName';
        lreg.Last_Name__c = 'LastName';
        lreg.Birth_Date__c = Date.today() - 40;
        insert lreg; 
        
        License_Registration__c lreg2 = new License_Registration__c();
        lreg2.RecordTypeId = RecordTypeId;
        lreg2.Account__c = acc2.Id;
        lreg2.Applicant__c = con2.Id;
        lreg2.License_Registration_Number__c = 'xxxxx';
        lreg2.Status__c = 'Incomplete';
        //lreg.Assigned_Deputy__c = deputy.Id;
        lreg2.Legal_Entity_Name__c = 'name';
        //lreg.Registration_Duration__c  = '10 Days - Temporary Permit';
        lreg2.Registration_Duration__c  = '6 Months - Permit';
        lreg2.Submission_Type__c = 'Online';
        //lreg.Status_of_Payment__c = 'Paid / No Balance Due';
        //lreg.Balance__c = 0;
        //lreg2.Amount_Due__c = 50;
        //lreg2.Amount_Paid_Online__c  = 50;
        //lreg2.Amount_Paid_Manually__c = 0;
        lreg2.Status__c = 'Incomplete';
        lreg2.Effective_Date__c = Date.today() - 5;
        lreg2.Expiration_Date__c = Date.today() + 90;
        lreg2.First_Name__c = 'FirstName';
        lreg2.Last_Name__c = 'LastName';
        lreg2.Residential_Address_Line_1__c = 'test street';
        lreg2.Residential_City__c = 'oak';
        lreg2.Residential_State__c = 'ca';
        lreg2.Residential_Postal_Code__c = '94612';
        lreg2.Mailing_Address_Line_1__c = 'Street ';
        lreg2.Mailing_City__c = 'San Francisco';
        lreg2.Mailing_State__c = 'CA';
        lreg2.Mailing_Postal_Code__c = '94612';
        lreg2.Mobile_Phone__c = '5445445555';
        lreg2.Birth_Date__c = Date.today() - 40;
        insert lreg2; 
 /*       
        Registration_Account__c racc1 = new Registration_Account__c();
        racc1.RecordTypeId = indivRecordTypeId;
        racc1.First_Name__c = 'FirstName';
        racc1.Last_Name__c = 'LastName';
        racc1.Residential_Street__c = 'test street';
        racc1.Residential_City__c = 'oak';
        racc1.Residential_State__c = 'ca';
        racc1.Residential_Zip_Code__c = '94612';
        racc1.Email_Address__c = 'test@asdadad.com';
        racc1.Mailing_City__c = 'San Francisco';
        racc1.Mailing_State__c = 'CA';
        racc1.Mailing_City__c = 'San Francisco';
        racc1.Mailing_Street__c = 'Street ';
        racc1.Mailing_Zip_Code__c = '94612';
        racc1.Business_Phone__c = '4445553434';
        racc1.Mobile_Phone__c = '5445445555';
        racc1.Birth_Date__c = Date.today() - 40;
        racc1.Registration__c = lreg.Id;
        insert racc1;
  */      
        Registration_Account__c racc2 = new Registration_Account__c();
        racc2.RecordTypeId = parentRecordTypeId;
        racc2.First_Name__c = 'FirstName';
        racc2.Last_Name__c = 'LastName';
        racc2.Email_Address__c = 'test@asdadad.com';
        racc2.Mailing_City__c = 'San Francisco';
        racc2.Mailing_State__c = 'CA';
        racc2.Mailing_City__c = 'San Francisco';
        racc2.Mailing_Street__c = 'Street ';
        racc2.Mailing_Zip_Code__c = '94612';
        racc2.Business_Phone__c = '4445553434';
        racc2.Mobile_Phone__c = '5445445555';
        racc2.Birth_Date__c = Date.today() - 40;
        racc2.Registration__c = lreg.Id;
        insert racc2;
        
        //List<License_Registration__c> newList = new List<License_Registration__c>();
        //newList.add(lreg);
        
        License_Registration__c lr = [SELECT Id
                                      , License_Registration_Number__c
                                      , Record_Type_Name__c
                                      , Status_of_Payment__c
                                      , Status__c
                                      , Registration_Duration__c
                                      , Submission_Type__c
                                      FROM License_Registration__c WHERE Id=:lreg.Id Limit 1];
        
        lr.Status__c = 'Approved';
        lr.Submission_Type__c = 'Online';
        //lr.Status__c = 'Submitted';
        //lr.Ready_to_Submit__c = 'Yes';
        update lr;
                
        //List<License_Registration__c> newList2 = new List<License_Registration__c>();
        //newList2.add(lr);

        RegistrationEWPResultsController RegistrationResults = new RegistrationEWPResultsController();
        
        String registrationNumberStr = '12345';
        String locationZipStr = '54434';
        String selectedRecordType = 'Entertainment Work';
        
        String RegistrationNum = '12345';
        String Status = 'Active';
        //String ParentNm = 'Parent Test';
        String MinorNm = 'Minor Test';
        String StageNm = 'the artist formerly known as princess';
        Date EffectiveDate = NULL;
        Date ExpirationDate = NULL;
        
        
        test.startTest();
        RegistrationEWPResultsController.getAllRegistrations(lr.License_Registration_Number__c, selectedRecordType, lreg2.Residential_Postal_Code__c);
        RegistrationResults.BackToSearch();
        RegistrationEWPResultsController.wrapRegistrationLicenses wrapper = new RegistrationEWPResultsController.wrapRegistrationLicenses(RegistrationNum, Status, MinorNm, StageNm, EffectiveDate, ExpirationDate);
        
        test.stopTest();
    }
    
}