force-app/main/default/objects/Account/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Effective Date of the Entity Registration</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Entity Registration</description>
    <inlineHelpText>Expiration Date of the Entity Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>Official registered legal entity name</description>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Ownership__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Ownership</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Business_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Address_Line_1__c</fullName>
    <label>Physical Business Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Business_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Address_Line_2__c</fullName>
    <label>Physical Business Address Line 2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Business_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Postal_Code__c</fullName>
    <label>Physical Business Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Physical_Business_State__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_State__c</fullName>
    <label>Physical Business State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bond__c/Bond__c.object-meta.xml
<CustomObject>
    <description>Object to allow deputies and other users to record the details of appeal bonds, surety bonds related to a citation, appeal, and party record.</description>
    <label>Bond</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bond Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bond__c/fields/Bond_Amount__c.field-meta.xml
<CustomField>
    <fullName>Bond_Amount__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Value of the bond.</description>
    <label>Bond Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bond__c/fields/Bond_Status__c.field-meta.xml
<CustomField>
    <fullName>Bond_Status__c</fullName>
    <description>For users (external and internal) to select status of Bond.</description>
    <label>Bond Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reinstated</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bond__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <inlineHelpText>Date format: mm/dd/yyyy or select the downward arrow to choose a date from the calendar view.</inlineHelpText>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bond__c/fields/Posted_By__c.field-meta.xml
<CustomField>
    <fullName>Posted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Account object to relate a bond to an Employer/Entity</description>
    <label>Posted By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bonds</relationshipLabel>
    <relationshipName>Bonds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bond__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Bonds</relationshipLabel>
    <relationshipName>Bonds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DBA__c/DBA__c.object-meta.xml
<CustomObject>
    <label>DBA</label>
    <nameField>
        <label>DBA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DBAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DBA__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DBAs</relationshipLabel>
    <relationshipName>DBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DBA__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <inlineHelpText>Is this DBA currently active or in use?</inlineHelpText>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Huato</fullName>
                <isActive>false</isActive>
                <label>Huato</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DBA__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>DBAs</relationshipLabel>
    <relationshipName>DBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <inlineHelpText>Please enter name registered with CA Secretary of State.  For Sole Proprietor enter full legal name.</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <label>Middle Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Address_Line_1__c</fullName>
    <inlineHelpText>P.O. Box address is not allowed.</inlineHelpText>
    <label>Physical Business Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Address_Line_2__c</fullName>
    <label>Physical Business Address Line 2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_City__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_City__c</fullName>
    <label>Physical Business City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Postal_Code__c</fullName>
    <label>Physical Business Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_State__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_State__c</fullName>
    <label>Physical Business State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ownership__c/Ownership__c.object-meta.xml
<CustomObject>
    <description>Junction object used to denote what percentage of a business an individual owns.</description>
    <label>Ownership</label>
    <nameField>
        <displayFormat>OWN-{00000000}</displayFormat>
        <label>Ownership Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ownership__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Mapped to Account First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Mapped to Person Account Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <description>Mapped to standard Middle Name on Accounts.</description>
    <label>Middle Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Ownership</relationshipLabel>
    <relationshipName>Ownership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Request_FLC_Card__c.field-meta.xml
<CustomField>
    <fullName>Request_FLC_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to request for a FLC Card for a owner.</description>
    <inlineHelpText>Check to request a card</inlineHelpText>
    <label>Request FLC Card</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FLCResultsExportController.cls
global class FLCResultsExportController{
    
    public List<String> regIdList {get;set;}
    public List<License_Registration__c> regList {get;set;}
    public List<wrapLRClass> wrapLRLists {get;set;}
    
    public FLCResultsExportController() 
    {
        wrapLRLists = new List<wrapLRClass>() ;
        regIdList = new List<String>();
        String listReg = apexpages.currentpage().getparameters().get('myList');
        system.debug('reg list is '+listReg);
        if(String.isNotBlank(listReg) && listReg.contains(','))
            regIdList =  listReg.split(',');
        else{
            list<String> lis=new List<String>();
            lis.add(listReg);
            regIdList=lis;
        }
        
        for(Integer i = 0; i < regIdList.size(); i++)
        {
            //System.debug('*****regIdList[i1]'+regIdList[i]);
            if(regIdList[i] == 'undefined')
            {
                //System.debug('*****regIdList[i2]'+regIdList[i]);
                regIdList.remove(i);
            }
        }
        
        //System.debug('*****regIdList--'+regIdList);
        if(regIdList!=null && regIdList.size()>0){
            regList = [SELECT Id
                       , Legal_Entity_Name__c
                       , License_Registration_Number__c
                       , Physical_Business_Address_Line_1__c
                       , Physical_Business_Address_Line_2__c
                       , Physical_Business_City__c
                       , Physical_Business_State__c
                       , Physical_Business_Postal_Code__c
                       , Effective_Date__c
                       , Expiration_Date__c
                       , (SELECT Id, First_Name__c, Middle_Name__c, Last_Name__c FROM Ownership__r WHERE Request_FLC_Card__c = TRUE)
                       , (SELECT Id, Registration__c, Bond_Amount__c FROM Bonds__r WHERE Bond_Status__c = 'Active')
                       , (SELECT Id, Registration__c, Name, Active__c FROM DBAS__r WHERE Active__c = 'Yes')
                       from License_Registration__c where id in : regIdList];
            
             //System.debug('*************regList'+regList);
             //System.debug('*************regList.dbas__r.name'+regList[0].dbas__r[0].name);
        }
        

        
        for(License_Registration__c eachReg : regList)
        {
            String DBA1 = '';
            String DBA2 = '';
            String DBA3 = '';
            
            //for(Integer i = 0; i < eachReg.DBAS__r.size(); i++)
            if(eachReg.DBAS__r.size() < 1){
                DBA1 = eachReg.Legal_Entity_Name__c;
            }
            else{
                for(Integer i = 0; i < eachReg.DBAS__r.size(); i++)
                {
                    if(eachReg.DBAS__r[i].Registration__c == eachReg.id){
                        if(i == 0){
                            DBA1 = eachReg.DBAS__r[i].Name;
                        }
                        if(i == 1){
                            DBA2 = eachReg.DBAS__r[i].Name;
                        }
                        if(i == 2){
                            DBA3 = eachReg.DBAS__r[i].Name;
                        }
                    }
                }
            }
                
            Decimal BondAmount = 0;
            for(Bond__c eachBond : eachReg.Bonds__r){
                BondAmount = BondAmount + eachBond.Bond_Amount__c;
            }
            
            if(eachReg.Ownership__r != Null && eachReg.Ownership__r.size() > 0){
                for(Ownership__c eachOwner : eachReg.Ownership__r)
                {
                    eachOwner.First_Name__c = eachOwner.First_Name__c == NULL ? '' : eachOwner.First_Name__c;
                    eachOwner.Middle_Name__c = eachOwner.Middle_Name__c == NULL ? '' : eachOwner.Middle_Name__c;
                    eachOwner.Last_Name__c = eachOwner.Last_Name__c == NULL ? '' : eachOwner.Last_Name__c;
                    eachReg.Physical_Business_Address_Line_1__c = eachReg.Physical_Business_Address_Line_1__c == NULL ? '' : eachReg.Physical_Business_Address_Line_1__c;                
                    eachReg.Physical_Business_Address_Line_2__c = eachReg.Physical_Business_Address_Line_2__c == NULL ? '' : eachReg.Physical_Business_Address_Line_2__c;
                    eachReg.Physical_Business_City__c = eachReg.Physical_Business_City__c == NULL ? '' : eachReg.Physical_Business_City__c;
                    eachReg.Physical_Business_State__c = eachReg.Physical_Business_State__c == NULL ? '' : eachReg.Physical_Business_State__c;
                    eachReg.Physical_Business_Postal_Code__c = eachReg.Physical_Business_Postal_Code__c == NULL ? '' : eachReg.Physical_Business_Postal_Code__c;
                    //eachReg.Effective_Date__c = eachReg.Effective_Date__c == NULL ? '' : eachReg.Effective_Date__c;
                    //eachReg.Expiration_Date__c = eachReg.Expiration_Date__c == NULL ? '' : eachReg.Expiration_Date__c;
                   //DBAnames = DBAnames == NULL ? '' : DBAnames;
                    DBA1 = DBA1 == NULL ? '' : DBA1;
                    DBA2 = DBA2 == NULL ? '' : DBA2;
                    DBA3 = DBA3 == NULL ? '' : DBA3;
                        
                    wrapLRLists.add(new wrapLRClass( String.valueOf(eachReg.Id)
                                                    , eachReg.License_Registration_Number__c
                                                    , eachOwner.First_Name__c
                                                    , eachOwner.Middle_Name__c
                                                    , eachOwner.Last_Name__c
                                                    , eachReg.Physical_Business_Address_Line_1__c
                                                    , eachReg.Physical_Business_Address_Line_2__c
                                                    , eachReg.Physical_Business_City__c
                                                    , eachReg.Physical_Business_State__c
                                                    , eachReg.Physical_Business_Postal_Code__c
                                                    , eachReg.Effective_Date__c
                                                    , eachReg.Expiration_Date__c
                                                    , BondAmount
                                                    , DBA1
                                                    , DBA2
                                                    , DBA3
                                                   ));                 
                }
            }
        }
    } 
    
    global class wrapLRClass{
        public String SystemId {get;set;}
        public String RegistrationNum {get;set;}
        public String FirstName {get;set;}
        public String MiddleName {get;set;}
        public String LastName {get;set;}
        public String AddressLine1 {get;set;}
        public String AddressLine2 {get;set;}
        public String City {get;set;}
        public String State {get;set;}
        public String Zip {get;set;}        
        public Date EffectiveDte {get;set;}
        public Date ExpirationDte {get;set;}
        public Decimal BondAmount {get;set;}
        public String DBA1 {get;set;}
        public String DBA2 {get;set;}
        public String DBA3 {get;set;}
        
        public wrapLRClass(String sSystemId
                           , String sRegistrationNum
                           , String sFirstName
                           , String sMiddleName
                           , String sLastName
                           , String sAddressLine1
                           , String sAddressLine2
                           , String sCity
                           , String sState
                           , String sZip
                           , Date sEffectiveDte
                           , Date sExpirationDte
                           , Decimal sBondAmount
                           , String sDBA1
                          , String sDBA2
                          , String sDBA3)
        {
            RegistrationNum = sRegistrationNum;
            SystemId = sSystemId;
            FirstName = sFirstName;
            MiddleName = sMiddleName;
            LastName = sLastName;
            AddressLine1 = sAddressLine1;
            AddressLine2 = sAddressLine2;
            City = sCity;
            State = sState;
            Zip = sZip;                       
            EffectiveDte = sEffectiveDte;
            ExpirationDte = sExpirationDte;
            BondAmount = sBondAmount;
            DBA1 = sDBA1;
            DBA2 = sDBA2;
            DBA3 = sDBA3;
        }
    }
}