force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Ownership__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Ownership</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Type__c</fullName>
    <label>License/Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>Agricultural Employers of Minors</fullName>
            </value>
            <value>
                <fullName>Agricultural Produce Unloaders</fullName>
            </value>
            <value>
                <fullName>BOE/Seller’s Permit</fullName>
            </value>
            <value>
                <fullName>Bureau of Automotive Repair</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Car Wash</fullName>
            </value>
            <value>
                <fullName>Child Performer Services</fullName>
            </value>
            <value>
                <fullName>CSLB</fullName>
            </value>
            <value>
                <fullName>DOL</fullName>
            </value>
            <value>
                <fullName>DSS Facility</fullName>
            </value>
            <value>
                <fullName>Electricians and electrician trainees</fullName>
            </value>
            <value>
                <fullName>FBNS</fullName>
            </value>
            <value>
                <fullName>Farm Labor Contractor</fullName>
            </value>
            <value>
                <fullName>Garment Manufacturers and Contractors</fullName>
            </value>
            <value>
                <fullName>Health Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworker Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworkers</fullName>
            </value>
            <value>
                <fullName>Industrial Homework License</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Secretary of State Number</fullName>
            </value>
            <value>
                <fullName>SEIN</fullName>
            </value>
            <value>
                <fullName>Sheltered Workshops (non‐profit)</fullName>
            </value>
            <value>
                <fullName>Special Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Studio Teacher Certification</fullName>
            </value>
            <value>
                <fullName>Talent Agency</fullName>
            </value>
            <value>
                <fullName>Work Permits for Child Performers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>BSIS</fullName>
            </value>
            <value>
                <fullName>Entertainment Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Address_Same_as_Residential__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Same_as_Residential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if the mailing address is the same as the residential address.</inlineHelpText>
    <label>Mailing Address Same as Residential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Ownership_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage__c</fullName>
    <label>Ownership Percentage</label>
    <summarizedField>Ownership__c.Ownership_Percentage__c</summarizedField>
    <summaryForeignKey>Ownership__c.Registration__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <inlineHelpText>Date this Registration was first Submitted. VIP Date/Time Submitted shows most recent submission time.</inlineHelpText>
    <label>Original Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ownership__c/Ownership__c.object-meta.xml
<CustomObject>
    <description>Junction object used to denote what percentage of a business an individual owns.</description>
    <label>Ownership</label>
    <nameField>
        <displayFormat>OWN-{00000000}</displayFormat>
        <label>Ownership Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ownership__c/fields/ATI_Number__c.field-meta.xml
<CustomField>
    <fullName>ATI_Number__c</fullName>
    <description>Enter ATI Number</description>
    <label>ATI Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Mapped to Person Account city</description>
    <label>Residential City / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Date_Completed__c.field-meta.xml
<CustomField>
    <fullName>Date_Completed__c</fullName>
    <description>Enter Date</description>
    <label>Date Completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Birth date of Owner</description>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Mapped to Account First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Mapped to Person Account Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Live_Scan_Operator_Name__c.field-meta.xml
<CustomField>
    <fullName>Live_Scan_Operator_Name__c</fullName>
    <description>Enter Live Scan Operator Name</description>
    <label>Live Scan Operator Name</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/LSID_Number__c.field-meta.xml
<CustomField>
    <fullName>LSID_Number__c</fullName>
    <description>Enter LSID Number</description>
    <label>LSID Number</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Mailing_Address_Same_as_Residential__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Same_as_Residential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mailing Address Same as Residential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Ownership_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage__c</fullName>
    <label>Ownership Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Ownership</relationshipLabel>
    <relationshipName>Ownership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <inlineHelpText>Enter 9 digits with no spaces or dashes.</inlineHelpText>
    <label>SSN or ITIN</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Mapped to Person Account street</description>
    <inlineHelpText>P.O. Box address is not allowed.</inlineHelpText>
    <label>Residential Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FLCClassControllerTest.cls
@isTest
public class FLCClassControllerTest {
    
    public static testMethod void testFLCClass(){
        
       Id p = [SELECT id FROM profile WHERE Name='Community Registrations User'].id;
        Id personAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
       
        account a = new Account(
          RecordTypeID=personAccountRTId,
          FirstName='Test FName',
          LastName='Test LName',
          PersonMailingStreet='test@yahoo.com',
          PersonMailingPostalCode='12345',
          PersonMailingCity='SFO',
          PersonEmail='test@yahoo.com',
          PersonHomePhone='1234567',
          PersonMobilePhone='12345678' 
        );
        insert a;
               
        system.debug('##### A: ' + a);
        Account acc = [Select PersonContactId From Account Where Id = :a.Id];
        
        User u = new User(contactId = acc.PersonContactId, Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p, isActive = true,
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        insert u;
        system.debug('##### u: ' + u);
        
        List<User> communityUser = [SELECT Id, ContactId, Contact.AccountId FROM User WHERE ProfileId =: p AND isActive = true LIMIT 1];
        system.debug('##### CommunityUser: ' + communityUser);
        
        
        Id RecordTypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Farm Labor Contractor').getRecordTypeId();
        
        License_Registration__c lReg1 = new License_Registration__c ();
        lReg1.Account__c = acc.Id;
        lReg1.RecordTypeId = RecordTypeId;
        lReg1.License_Registration_Number__c = acc.Id;
        lReg1.License_Registration_Type__c = '3333';
        lReg1.Submitted_Date__c = Date.today() - 3;
        lReg1.Mailing_City__c = 'Denver';
        lReg1.Applicant__c = communityUser[0].ContactId;
        insert lReg1;
        
        Ownership__c owners = new Ownership__c();
        owners.First_Name__c = 'test owner';
        owners.Registration__c = lReg1.Id;
        /// Added below in RSS sprint 5 to adjust for new validation rule: Required_fields_on_FLC_owner_records.
        owners.Email__c = 'aaaaa@aaaaaa.aaa';
        owners.Last_Name__c = 'aaaaaa';
        Date startDate = Date.newInstance(2008, 1, 1);
        owners.Ownership_Percentage__c = 100;
        owners.Date_of_Birth__c = startDate;
        owners.SSN__c = '123456789';
        owners.Live_Scan_Operator_Name__c = 'OperatorName';
        owners.ATI_Number__c = '123456789';
        owners.LSID_Number__c = '12345678';
        owners.Date_Completed__c = startDate;
        owners.Street__c = '6401 Sunflower Ct';
        owners.City__c = 'Oakland';
        owners.Residential_Zip_Code__c = '90012';
        owners.Mailing_Address_Same_as_Residential__c = true;        
        insert owners;
        
        PageReference myVfPage = Page.FLCClass;
        Test.setCurrentPage(myVfPage);
        
        // Put Id into the current page Parameters
        ApexPages.currentPage().getParameters().put('id',owners.Id);
        

        FLCClassController FLCClass = new FLCClassController();
        
        //FLCCLass.Course_Name = 'test class';
        FLCCLass.Hours_Completed = '9';
        FLCCLass.Language = 'English';
        FLCCLass.Other_Language = 'Spanish';
        FLCCLass.Notes = 'my notes';
        FLCCLass.Completion_Date = Date.today();
        
        test.startTest();
        FLCClass.LinkClass();
        FLCClass.getLanguageList();
        
        test.stopTest();
        
    }
}