force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Defines if a role is currently active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee's email address</description>
    <inlineHelpText>Email address for Salesforce users will be set automatically.
If the employee is NOT a Salesforce user, please enter their email address here.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee's manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The office the user is associated to. Related fields are used on output documents</description>
    <inlineHelpText>The office to which the employee is associated.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Internal Employees</relationshipLabel>
    <relationshipName>Internal_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deputy Labor Commissioner</fullName>
            </value>
            <value>
                <fullName>Deputy Labor Commissioner II</fullName>
            </value>
            <value>
                <fullName>Deputy Labor Commissioner III</fullName>
            </value>
            <value>
                <fullName>Industrial Relations Representative</fullName>
            </value>
            <value>
                <fullName>Management Services Technician</fullName>
            </value>
            <value>
                <fullName>Office Assistant</fullName>
            </value>
            <value>
                <fullName>Office Technician</fullName>
            </value>
            <value>
                <fullName>Payroll Auditor</fullName>
            </value>
            <value>
                <fullName>Regional Manager</fullName>
            </value>
            <value>
                <fullName>Senior Deputy Labor Commissioner</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Staff Service Analyst</fullName>
            </value>
            <value>
                <fullName>Assistant Chief</fullName>
            </value>
            <value>
                <fullName>Registration Approver</fullName>
            </value>
            <value>
                <fullName>Labor Compliance Analyst</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>Referrals for action by other business units related to cases within case management system.</description>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent case for which there is a referral</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Referring_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Referring_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referring Deputy</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Assignment__c/Referral_Assignment__c.object-meta.xml
<CustomObject>
    <description>Persons to which a referral has been assigned</description>
    <label>Referral Assignment</label>
    <nameField>
        <displayFormat>AID-{000000}</displayFormat>
        <label>Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Assignment__c/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <description>Parent referral - Referral may be assigned to multiple individuals.</description>
    <inlineHelpText>Referral to which this person is being assigned. Click this field to access the parent referral</inlineHelpText>
    <label>Referral</label>
    <referenceTo>Referral__c</referenceTo>
    <relationshipLabel>Referral Assignments</relationshipLabel>
    <relationshipName>Referral_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/referralAssignmentAllTest.cls
@istest
public class referralAssignmentAllTest {

    public static testMethod void referralAssignmentTest(){
        
          test.startTest();
        String rtid = [Select Id From RecordType  Where SobjectType = 'Account' and Name = 'Business Account'].id;
        
        Account acc = new Account();
        acc.Name = 'name';
        acc.RecordTypeId = rtid;
        acc.ShippingPostalCode = '234889';
        insert acc;
        
        Office__c off = new Office__c();
        off.Name = 'Test Office';
        insert off;
        
        DIR_Employee__c emp1 = new DIR_Employee__c();
        emp1.Active__c = true;
        //emp1.Deputy_Number__c = '1122';
        emp1.Title__c = 'Deputy Labor Commissioner';
        emp1.Position__c = 'Senior Deputy';
        emp1.Office__c = off.Id;
        emp1.Email__c = 'test_emp@email.com';
        emp1.User__c = UserInfo.getUserId();
        insert emp1;

        DIR_Employee__c emp = new DIR_Employee__c();
        emp.Active__c = true;
        //emp.Deputy_Number__c = '1122';
        emp.Title__c = 'Deputy Labor Commissioner';
        emp.Position__c = 'Deputy';
        emp.Office__c = off.Id;
        emp.Email__c = 'test_emp@email.com';
        emp.Manager__c = emp1.Id;
        emp.User__c = userInfo.getUserId();
        insert emp;
        
        DIR_Employee__c emp2 = new DIR_Employee__c();
        emp2.Active__c = true;
        //emp.Deputy_Number__c = '1122';
        emp2.Title__c = 'Attorney';
        emp2.Position__c = 'Legal';
        emp2.Office__c = off.Id;
        emp2.Email__c = 'test_emp@email.com';
        emp2.Manager__c = emp1.Id;
        emp2.User__c = userInfo.getUserId();
        insert emp2;
        
        DIR_Case__c c = new DIR_Case__c();
        c.Assigned_Deputy__c = emp.Id;
        c.Employer__c = acc.Id;
        insert c;
        
       
        RecordType rtReffid = [Select Id From RecordType Where SobjectType = 'Referral__c' and Name = 'BOFE Request for Legal Services'];
        
        Referral__c r = new Referral__c();
        r.Case__c = c.Id;
        r.Referring_Deputy__c=emp2.id;
        r.RecordTypeId = rtReffid.Id;
        r.Type_of_Request__c = 'Consultation - Citation';
        r.Request_Description__c = 'test';
        r.Request_Status__c = 'Request Approved';
        
        insert r;
        
        Referral_Assignment__c ra = new Referral_assignment__c();
        ra.Referral__c = r.Id;
        ra.Assigned_Employee__c = emp2.id;
        ra.Currently_Assigned__c = true;
     	ra.Employee_Email__c = 'test@xyz.com';
        ra.Deputy_Email__c='test1@xyz.com';
      
        insert ra;
        test.stopTest();
        
        
    }
}