force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</description>
    <inlineHelpText>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Roles</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>Entity__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>BOFE Roles</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Case_Role__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>If you have already created a meeting and wish this case role to be a Meeting Participant, you must also add it to the Meeting as a Meeting Participant.</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/DLSE_Program__c.field-meta.xml
<CustomField>
    <fullName>DLSE_Program__c</fullName>
    <description>Selection list of DLSE Programs</description>
    <label>DLSE Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BOFE</fullName>
            </value>
            <value>
                <fullName>EEEC</fullName>
            </value>
            <value>
                <fullName>EETF</fullName>
                <label>JESF</label>
            </value>
            <value>
                <fullName>FLC</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>LETF</fullName>
            </value>
            <value>
                <fullName>PAGA</fullName>
            </value>
            <value>
                <fullName>PASS THRU</fullName>
            </value>
            <value>
                <fullName>PW</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>JANITORIAL</fullName>
            </value>
            <value>
                <fullName>TALENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/e_Sign_Documents__c.field-meta.xml
<CustomField>
    <fullName>e_Sign_Documents__c</fullName>
    <description>This field will be used to store the selected Documents Name for Electronic Signature via AssureSign.</description>
    <label>e-Sign Documents</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SETTLEMENT- WCA 026A</fullName>
            </value>
            <value>
                <fullName>RELEASE- WCA 023</fullName>
            </value>
            <value>
                <fullName>DIRCase- WCA 055</fullName>
            </value>
            <value>
                <fullName>DIRCase- 633 055</fullName>
            </value>
            <value>
                <fullName>SETTLEMENT- WCA 026C-1</fullName>
            </value>
            <value>
                <fullName>SETTLEMENT- WCA 026B-1</fullName>
            </value>
            <value>
                <fullName>SETTLEMENT- WCA 026A-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Defines if a role is currently active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee's email address</description>
    <inlineHelpText>Email address for Salesforce users will be set automatically.
If the employee is NOT a Salesforce user, please enter their email address here.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee's manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Employees phone number</description>
    <inlineHelpText>Phone number for Salesforce users will be set automatically.
If the employee is NOT a Salesforce user, please enter their phone number here.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OWCEsignFlowActionToGetDefErrorTest.cls
@isTest
public class OWCEsignFlowActionToGetDefErrorTest {
    
    @testSetup
    public static void setupData(){
        Id RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE').getRecordTypeId();
        
        Account employerAccount = new Account();
        employerAccount.Name = 'Big Mega General Corp';
        employerAccount.ShippingStreet = '123 Sesame Street';
        employerAccount.ShippingCity = 'New York';
        employerAccount.ShippingState = 'NY';
        employerAccount.ShippingPostalCode = '01234';
        insert employerAccount;
        
        Trigger_Settings__c customSettingObj = new Trigger_Settings__c();
        customSettingObj.Name = 'GenerateFieldHistoryAction';
        customSettingObj.Is_Active__c = true;
        Insert customSettingObj;
        
        DIR_Employee__c mgr = new DIR_Employee__c();
        mgr.User__c = userinfo.getuserid();
        mgr.Active__c = true;
        mgr.Email__c = 'mgr@test.com';
        mgr.Phone__c = '2223335555';
        insert mgr;
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.User__c = userinfo.getuserid();
        de.Active__c = true;
        de.Email__c = 'dep@test.com';
        de.Phone__c = '2223335555';
        de.Manager__c = mgr.id;
        insert de;
        
        DIR_Case__c dc = new DIR_Case__c();
        dc.Employer__c = employerAccount.Id;
        dc.RecordTypeId = RecordTypeId;
        dc.Status__c = 'Under Investigation';
        dc.Assigned_Deputy__c = de.Id;
        dc.DLSE_Program__c = 'BOFE';
        dc.e_Sign_Documents__c = 'SETTLEMENT- WCA 026A,SETTLEMENT- WCA 026B,SETTLEMENT- WCA 026C,DIRCase- 633 055,WCA 055 - Complaint,RELEASE- WCA 023';
        Insert dc;
        
        Case_Role__c crObj = new Case_Role__c();
        crObj.Entity__c = employerAccount.Id;
        crObj.Case__c = dc.Id;
        Insert crObj;
    }
    
    @isTest
    public static void getDefendantsWithErrorTest() {
        List<Case_Role__c> crList = [SELECT Id FROM Case_Role__c LIMIT 1];
        Test.startTest();
        OWCEsignFlowActionToGetDefendantsError.getDefendantsWithError(new List<String>{crList[0].Id});
        Test.stopTest();
    }
}