force-app/main/default/objects/Account/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the Entity Registration</description>
    <inlineHelpText>Expiration Date of the Entity Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Boilermaker_Blacksmith__c.field-meta.xml
<CustomField>
    <fullName>Boilermaker_Blacksmith__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Boilermaker-Blacksmith</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Bricklayer_Brick_Tender__c.field-meta.xml
<CustomField>
    <fullName>Bricklayer_Brick_Tender__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Bricklayer/Brick Tender</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Carpet_Linoleum_Resilient_Tile_Layer__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Linoleum_Resilient_Tile_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Carpet, Linoleum, Resilient Tile Layer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Drywall_Installer_Lather_Finisher__c.field-meta.xml
<CustomField>
    <fullName>Drywall_Installer_Lather_Finisher__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Drywall Installer/Lather/Finisher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Electrical_Utility__c.field-meta.xml
<CustomField>
    <fullName>Electrical_Utility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Electrical Utility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Electrician__c.field-meta.xml
<CustomField>
    <fullName>Electrician__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Electrician</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Field_Surveyor__c.field-meta.xml
<CustomField>
    <fullName>Field_Surveyor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Field Surveyor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Glazier__c.field-meta.xml
<CustomField>
    <fullName>Glazier__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Glazier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Iron_Worker__c.field-meta.xml
<CustomField>
    <fullName>Iron_Worker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Iron Worker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Landscape__c.field-meta.xml
<CustomField>
    <fullName>Landscape__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Landscape</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Type__c</fullName>
    <label>License/Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>Agricultural Employers of Minors</fullName>
            </value>
            <value>
                <fullName>Agricultural Produce Unloaders</fullName>
            </value>
            <value>
                <fullName>BOE/Seller’s Permit</fullName>
            </value>
            <value>
                <fullName>Bureau of Automotive Repair</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Car Wash</fullName>
            </value>
            <value>
                <fullName>Child Performer Services</fullName>
            </value>
            <value>
                <fullName>CSLB</fullName>
            </value>
            <value>
                <fullName>DOL</fullName>
            </value>
            <value>
                <fullName>DSS Facility</fullName>
            </value>
            <value>
                <fullName>Electricians and electrician trainees</fullName>
            </value>
            <value>
                <fullName>FBNS</fullName>
            </value>
            <value>
                <fullName>Farm Labor Contractor</fullName>
            </value>
            <value>
                <fullName>Garment Manufacturers and Contractors</fullName>
            </value>
            <value>
                <fullName>Health Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworker Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworkers</fullName>
            </value>
            <value>
                <fullName>Industrial Homework License</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Secretary of State Number</fullName>
            </value>
            <value>
                <fullName>SEIN</fullName>
            </value>
            <value>
                <fullName>Sheltered Workshops (non‐profit)</fullName>
            </value>
            <value>
                <fullName>Special Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Studio Teacher Certification</fullName>
            </value>
            <value>
                <fullName>Talent Agency</fullName>
            </value>
            <value>
                <fullName>Work Permits for Child Performers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>BSIS</fullName>
            </value>
            <value>
                <fullName>Entertainment Work</fullName>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>Public Works &amp; Prevailing Wage Contractor Registration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Marble_Mason_Finisher__c.field-meta.xml
<CustomField>
    <fullName>Marble_Mason_Finisher__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Marble Mason/Finisher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Painter__c.field-meta.xml
<CustomField>
    <fullName>Painter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Painter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Plasterer_Tender__c.field-meta.xml
<CustomField>
    <fullName>Plasterer_Tender__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Plasterer/Tender</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Plumber__c.field-meta.xml
<CustomField>
    <fullName>Plumber__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Plumber</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Roofing__c.field-meta.xml
<CustomField>
    <fullName>Roofing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Roofing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Sheet_Metal_Worker__c.field-meta.xml
<CustomField>
    <fullName>Sheet_Metal_Worker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Sheet Metal Worker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Stator_Rewinder__c.field-meta.xml
<CustomField>
    <fullName>Stator_Rewinder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Stator Rewinder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Terrazzo_Worker_Finisher__c.field-meta.xml
<CustomField>
    <fullName>Terrazzo_Worker_Finisher__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Terrazzo Worker/Finisher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Tile_Setter_Finisher__c.field-meta.xml
<CustomField>
    <fullName>Tile_Setter_Finisher__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Tile Setter/Finisher</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Water_Well_Drinker__c.field-meta.xml
<CustomField>
    <fullName>Water_Well_Drinker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PW craft</description>
    <label>Water Well Driller</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/exportRegDetailsControllerTest.cls
@istest (SeeAllData=true)
public class exportRegDetailsControllerTest {

    public static testMethod void testExportRegDetailsController(){

        Id p = [SELECT id FROM profile WHERE Name='Community Registrations User'].id;
        Id personAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
       
        account a = new Account(
          RecordTypeID=personAccountRTId,
          FirstName='Test FName',
          LastName='Test LName',
          PersonMailingStreet='test@yahoo.com',
          PersonMailingPostalCode='12345',
          PersonMailingCity='SFO',
          PersonEmail='test@yahoo.com',
          PersonHomePhone='1234567',
          PersonMobilePhone='12345678'
        );
        insert a;
               
        system.debug('##### A: ' + a);
        Account acc = [Select PersonContactId From Account Where Id = :a.Id];
        
        User u = new User(contactId = acc.PersonContactId, Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p, isActive = true,
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        insert u;
        system.debug('##### u: ' + u);
        
        List<User> communityUser = [SELECT Id, ContactId, Contact.AccountId FROM User WHERE ProfileId =: p AND isActive = true LIMIT 1];
        system.debug('##### CommunityUser: ' + communityUser);
        
        Id publicWorksRecordTypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Public Works').getRecordTypeId();
        
        License_Registration__c  newLR2 = new License_Registration__c();
        newLR2.Account__c = communityUser[0].Contact.AccountId;
        newLR2.RecordTypeId = publicWorksRecordTypeId;
        newLR2.License_Registration_Number__c = '222';
        newLR2.License_Registration_Type__c = 'Public Works';
        newLR2.Status__c = 'Incomplete'; 
        newLR2.Expiration_Date__c = Date.today() - 365; 
        newLR2.Amount_Paid__c = 100; 
        newLR2.Applicant__c = communityUser[0].ContactId;
        newLR2.License_Registration_Type__c = 'Public Works';
        newLR2.Boilermaker_Blacksmith__c = true;
        newLR2.Bricklayer_Brick_Tender__c = true;
        newLR2.Carpet_Linoleum_Resilient_Tile_Layer__c = true;
        newLR2.Drywall_Installer_Lather_Finisher__c = true;
        newLR2.Electrician__c = true;
        newLR2.Field_Surveyor__c = true;
        newLR2.Glazier__c = true;
        newLR2.Marble_Mason_Finisher__c = true;
        newLR2.Painter__c = true;
        newLR2.Plasterer_Tender__c = true;
        
        newLR2.Plumber__c = true;
        newLR2.Roofing__c = true;
        newLR2.Sheet_Metal_Worker__c = true;
        newLR2.Terrazzo_Worker_Finisher__c = true;
        newLR2.Tile_Setter_Finisher__c = true;  
        newLR2.Water_Well_Drinker__c = true;
        newLR2.Iron_Worker__c = true;
        newLR2.Electrical_Utility__c = true;
        newLR2.Landscape__c = true;
        newLR2.Stator_Rewinder__c = true;   
        newLR2.Driver_On_Off_Hauling__c = true;
        newLR2.Teamster__c = true;
        newLR2.Abestos__c = true;
        newLR2.Inspector_Field_Soils_Material_Tester__c = true;
        newLR2.Carpenter__c = true;      
        
        newLR2.Cement_Mason__c = true;   
        newLR2.Elevator_Constructor__c = true;
        newLR2.Laborer__c = true;
        newLR2.Parking_Highway_Improvement__c = true;
        newLR2.Operating_Engineer__c= true;
        
        newLR2.General_Engineering__c = true;
        newLR2.General_Building__c = true;
        
        insert newLR2;
        system.debug('##### newLR2: ' + newLR2);  

        
        apexpages.currentpage().getparameters().put('myList',newLR2.id);
        exportRegDetailsController reg =  new exportRegDetailsController();

    }
    
}