force-app/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>Official registered legal entity name</description>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>This object is to store a One-To-Many relationship between Accounts and the Addresses they may have</description>
    <label>Location</label>
    <nameField>
        <displayFormat>ADDR-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
                <default>true</default>
                <label>CA</label>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DBA__c/DBA__c.object-meta.xml
<CustomObject>
    <label>DBA</label>
    <nameField>
        <label>DBA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DBAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DBA__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DBAs</relationshipLabel>
    <relationshipName>DBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DBA__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>DBAs</relationshipLabel>
    <relationshipName>DBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <inlineHelpText>Please enter name registered with CA Secretary of State.  For Sole Proprietor enter full legal name.</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Type__c</fullName>
    <label>License/Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>Agricultural Employers of Minors</fullName>
            </value>
            <value>
                <fullName>Agricultural Produce Unloaders</fullName>
            </value>
            <value>
                <fullName>BOE/Seller’s Permit</fullName>
            </value>
            <value>
                <fullName>Bureau of Automotive Repair</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Car Wash</fullName>
            </value>
            <value>
                <fullName>Child Performer Services</fullName>
            </value>
            <value>
                <fullName>CSLB</fullName>
            </value>
            <value>
                <fullName>DOL</fullName>
            </value>
            <value>
                <fullName>DSS Facility</fullName>
            </value>
            <value>
                <fullName>Electricians and electrician trainees</fullName>
            </value>
            <value>
                <fullName>FBNS</fullName>
            </value>
            <value>
                <fullName>Farm Labor Contractor</fullName>
            </value>
            <value>
                <fullName>Garment Manufacturers and Contractors</fullName>
            </value>
            <value>
                <fullName>Health Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworker Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworkers</fullName>
            </value>
            <value>
                <fullName>Industrial Homework License</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Secretary of State Number</fullName>
            </value>
            <value>
                <fullName>SEIN</fullName>
            </value>
            <value>
                <fullName>Sheltered Workshops (non‐profit)</fullName>
            </value>
            <value>
                <fullName>Special Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Studio Teacher Certification</fullName>
            </value>
            <value>
                <fullName>Talent Agency</fullName>
            </value>
            <value>
                <fullName>Work Permits for Child Performers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>BSIS</fullName>
            </value>
            <value>
                <fullName>Entertainment Work</fullName>
            </value>
            <value>
                <fullName>Permit to Employ Minors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Line_1__c</fullName>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Postal_Code__c</fullName>
    <label>Mailing Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Received_Date__c</fullName>
    <inlineHelpText>Date a physical application was received by DIR.</inlineHelpText>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <inlineHelpText>Date this Registration was first Submitted. VIP Date/Time Submitted shows most recent submission time.</inlineHelpText>
    <label>Original Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/Registration_Location__c.object-meta.xml
<CustomObject>
    <description>Junction object between Locations, Accounts, and Registrations</description>
    <label>Registration Location</label>
    <nameField>
        <displayFormat>RLN-{0000000}</displayFormat>
        <label>Registration Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registration Locations</relationshipLabel>
    <relationshipName>Registration_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Mapped to City__c Location field.</description>
    <label>City / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Locations</relationshipLabel>
    <relationshipName>Registration_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Mapped to State__c Location field.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the zip code is within</description>
    <inlineHelpText>Enter the city that this zip code is in.</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FLCSearchResultsController.cls
global class FLCSearchResultsController {
    
    
    public String searchString {get; set;}
    
    public License_Registration__c dummyLicenseRegistration {get; set;}
    public Map<String, Boolean> filtersMap {get; set;}
    
    public FLCSearchController.searchClass searchClassObj {get; set;}
    
    public String effectiveDateStart {get; set;}
    public String effectiveDateEnd {get; set;}
    
    public String expirationDateStart {get; set;}
    public String expirationDateEnd {get; set;}
    
    public String bondEffectiveStart {get; set;}
    public String bondEffectiveEnd {get; set;}
    
    public String selectedRecordType {get; set;}
    public String selectedStatus {get; set;}
    public String serviceType {get; set;}
    
    // class constructor, executes first, as soon as the class is invoked
    global FLCSearchResultsController() {      
        
        filtersMap = new Map<String, Boolean>();
        filtersMap.put('searchString', false);
        filtersMap.put('License_Registration_Number', false);
        filtersMap.put('Service_Type__c', false);
        filtersMap.put('License_Registration_Type', false);
        filtersMap.put('Submitted_Date__c', false);
        filtersMap.put('Received_Date__c', false);
        filtersMap.put('Mailing_City__c', false);
        
        
        
        searchClassObj = new FLCSearchController.searchClass();
        searchClassObj.serviceType = ApexPages.currentPage().getParameters().get('serviceType');
        searchClassObj.selectedRecordType = ApexPages.currentPage().getParameters().get('selectedRecordType');
        searchClassObj.selectedStatus = ApexPages.currentPage().getParameters().get('selectedStatus');
        searchClassObj.registrationNumberStr = ApexPages.currentPage().getParameters().get('registrationNumberStr');
        searchClassObj.legalEntityStr = ApexPages.currentPage().getParameters().get('legalEntityStr');
        effectiveDateStart = ApexPages.currentPage().getParameters().get('effectiveDateStart');
        effectiveDateEnd = ApexPages.currentPage().getParameters().get('effectiveDateEnd');
        expirationDateStart = ApexPages.currentPage().getParameters().get('expirationDateStart');
        expirationDateEnd = ApexPages.currentPage().getParameters().get('expirationDateEnd');
        /* if(!String.isEmpty(expirationDateStr)) {
            List<String> endStringDate = effectiveDateStr.split('-');
            String eD = endStringDate[0] + '-' + endStringDate[1] + '-' + endStringDate[2];
            searchClassObj.expirationDate = Date.valueOf(eD);
        }   */  

        searchClassObj.dbaNameStr = ApexPages.currentPage().getParameters().get('dbaNameStr');
        searchClassObj.locationAddressStr = ApexPages.currentPage().getParameters().get('locationAddressStr');
        searchClassObj.locationCityStr = ApexPages.currentPage().getParameters().get('locationCityStr');
        searchClassObj.locationStateStr = ApexPages.currentPage().getParameters().get('locationStateStr');
        searchClassObj.locationZipStr  = ApexPages.currentPage().getParameters().get('locationZipStr');
        searchClassObj.workersCompTypeStr = ApexPages.currentPage().getParameters().get('workersCompTypeStr');
        searchClassObj.workersCompInsurerStr = ApexPages.currentPage().getParameters().get('workersCompInsurerStr');
        searchClassObj.bondIssuerStr = ApexPages.currentPage().getParameters().get('bondIssuerStr');
        bondEffectiveStart = ApexPages.currentPage().getParameters().get('bondEffectiveStart');
        bondEffectiveEnd = ApexPages.currentPage().getParameters().get('bondEffectiveEnd');
        /* if(!String.isEmpty(bondEffectiveDateStr)) {
            List<String> endStringDate = effectiveDateStr.split('-');
            String eD = endStringDate[0] + '-' + endStringDate[1] + '-' + endStringDate[2];
            searchClassObj.bondEffectiveDate = Date.valueOf(eD);
        }   */  

        
    }
    
    // Remote action called from RegistrationSearchResults.page via javascript function getRemoteRegistrations()
    @RemoteAction
    global static List<License_Registration__c> getAllRegistrations(String registrationNumberStr, String serviceType, String selectedRecordType, String selectedStatus, String legalEntityStr, String effectiveDateStart, String effectiveDateEnd,
    String expirationDateStart, String expirationDateEnd, String dbaNameStr, String locationAddressStr, String locationCityStr, 
    String locationStateStr, String locationZipStr, String workersCompTypeStr, String workersCompInsurerStr, 
    String bondIssuerStr, String bondEffectiveStart, String bondEffectiveEnd
    ) {
        List<License_Registration__c> allReg = new List<License_Registration__c>();
        
        
        if(String.isEmpty(registrationNumberStr) && String.isEmpty(legalEntityStr)  && String.isEmpty(legalEntityStr) && String.isEmpty(effectiveDateStart) && String.isEmpty(effectiveDateEnd)  && String.isEmpty(expirationDateStart) && String.isEmpty(expirationDateEnd) 
                        && String.isEmpty(dbaNameStr) && String.isEmpty(locationAddressStr) && String.isEmpty(locationCityStr)  && String.isEmpty(locationStateStr)
                         && String.isEmpty(locationZipStr) && String.isEmpty(workersCompTypeStr) && String.isEmpty(workersCompInsurerStr) && String.isEmpty(bondIssuerStr) && String.isEmpty(bondEffectiveStart) ) {
        
        } else {
            Date todaydate = Date.Today();
            String query = '';
            if(selectedStatus == 'Approved')
            {
                query = 'SELECT Id, Name, Account__c, Account__r.Name, Account__r.Legal_Entity_Name__c, License_Registration_Number__c, License_Registration_Type__c, Mailing_Address_Line_1__c, Mailing_City__c, Mailing_State__c, Mailing_Postal_Code__c, Submitted_Date__c, Status__c, Expiration_Date__c, Effective_Date__c, Payment_Status__c, Amount_Paid__c, Legal_Entity_Name__c, Workers_Compensation_Carrier__c, WCI_Expiration_Date__c, Workers_Comp_Selection__c, Service_Type__c FROM License_Registration__c WHERE (Status__c = \'Approved\'  OR ( Status__c = \'Renewed\' AND Expiration_Date__c >= :todaydate ) ) ';
            }
            else{   
                query = 'SELECT Id, Name, Account__c, Account__r.Name, Account__r.Legal_Entity_Name__c, License_Registration_Number__c, License_Registration_Type__c, Mailing_Address_Line_1__c, Mailing_City__c, Mailing_State__c, Mailing_Postal_Code__c, Submitted_Date__c, Status__c, Expiration_Date__c, Effective_Date__c, Payment_Status__c, Amount_Paid__c, Legal_Entity_Name__c, Workers_Compensation_Carrier__c, WCI_Expiration_Date__c, Workers_Comp_Selection__c, Service_Type__c FROM License_Registration__c WHERE Status__c = \'Closed - Revoked\' ';
            }
            
            if(!String.isEmpty(legalEntityStr)) {
                legalEntityStr = string.escapeSingleQuotes(legalEntityStr);
                String sn = '%'+legalEntityStr.replace('\'','\'')+'%';
                query += ' AND ((Legal_Entity_Name__c LIKE  \'' + sn + '\') OR (Account__r.LastName LIKE \'' + sn + '\') ) ';
            }
            
            if(!String.isEmpty(registrationNumberStr)) {
                String ln = '%' + registrationNumberStr + '%'; 
                query += ' AND License_Registration_Number__c LIKE \'' + ln + '\' ';
            }
            Date eDate = null;
            Date sDate = null;
            Date mysDate = null;
            Date myeDate = null;
            Date effsDate = null;
            Date effeDate = null;
            
            
            
            if(!String.isEmpty(effectiveDateStart) && String.isEmpty(effectiveDateEnd)) {
                effsDate = Date.valueOf(effectiveDateStart);
                query += ' AND ( Effective_Date__c >= :effsDate AND Effective_Date__c <> NULL ) ';
            } 
            
            if(!String.isEmpty(effectiveDateEnd) && String.isEmpty(effectiveDateStart)) {
                effeDate = Date.valueOf(effectiveDateEnd);
                query += ' AND ( Effective_Date__c <= :effeDate AND Effective_Date__c <> NULL ) ';
            }
            
            if(!String.isEmpty(effectiveDateEnd) && !String.isEmpty(effectiveDateStart)) {
                effsDate = Date.valueOf(effectiveDateStart);
                effeDate = Date.valueOf(effectiveDateEnd);
                
                query += ' AND ( Effective_Date__c >= :effsDate AND Effective_Date__c <= :effeDate AND Effective_Date__c <> NULL ) ';
            }     

            if(!String.isEmpty(expirationDateStart) && String.isEmpty(expirationDateEnd)) {
                sDate = Date.valueOf(expirationDateStart);
                mysDate = date.newinstance(sDate.year(), sDate.month(), sDate.day());
                query += ' AND ( Expiration_Date__c >= :mysDate AND Expiration_Date__c <> NULL ) ';
            } 
            
            if(!String.isEmpty(expirationDateEnd) && String.isEmpty(expirationDateStart)) {
                eDate = Date.valueOf(expirationDateEnd);
                myeDate = date.newinstance(eDate.year(), eDate.month(), eDate.day());
                query += ' AND ( Expiration_Date__c <= :myeDate AND Expiration_Date__c <> NULL ) ';
            }
            
            if(!String.isEmpty(expirationDateEnd) && !String.isEmpty(expirationDateStart)) {
                sDate = Date.valueOf(expirationDateStart);
                eDate = Date.valueOf(expirationDateEnd);
                mysDate = date.newinstance(sDate.year(), sDate.month(), sDate.day());
                myeDate = date.newinstance(eDate.year(), eDate.month(), eDate.day());
                
                query += ' AND ( Expiration_Date__c >= :mysDate AND Expiration_Date__c <= :myeDate AND Expiration_Date__c <> NULL ) ';
            }    
            // Commented by Jag 5/14/20 
           /* Set<Id> RegIds = new Set<Id>();
            if(!String.isEmpty(dbaNameStr)) {
                String locln = '%' + dbaNameStr + '%'; 
                String locationQuery = 'SELECT Id, Registration__c FROM Registration_Location__c WHERE DBA_Name__c LIKE \'' + locln + '\' ';
                List<Registration_Location__c> allLocationReg = Database.query(locationQuery);
                RegIds = new Set<Id>();
                for(Registration_Location__c rl: allLocationReg) {
                    if(rl.Registration__c != null) 
                        RegIds.add(rl.Registration__c);
                }
                    
                query += ' AND Id IN :RegIds ';
            }  */
            Set<Id> RegIds = new Set<Id>();
            if(!String.isEmpty(dbaNameStr)) {
                // jk 5/14/2020 - B-000579
                   if( (selectedRecordType == 'Talent Agency') || (selectedRecordType == 'Permit to Employ Minors') ){
                    String dbaName = '%' + dbaNameStr + '%'; 
                    String dbaQuery = 'SELECT Id, Name, Active__c, Registration__c FROM DBA__c WHERE Name LIKE \'' + dbaName + '\' AND Record_Type_Name__c = ' +  '\'' + selectedRecordType + '\'';
                    //System.debug('******'+dbaQuery);
                    List<DBA__c> allDBAs = Database.query(dbaQuery);
                    RegIds = new Set<Id>();
                    for(DBA__c eachDBA: allDBAs) {
                        if(eachDBA.Registration__c != null) 
                            RegIds.add(eachDBA.Registration__c);
                    }
                    query += ' AND Id IN :RegIds ';
                } 
                else {
                    String locln = '%' + dbaNameStr + '%'; 
                    String locationQuery = 'SELECT Id, Registration__c FROM Registration_Location__c WHERE DBA_Name__c LIKE \'' + locln + '\' ';
                    List<Registration_Location__c> allLocationReg = Database.query(locationQuery);
                    RegIds = new Set<Id>();
                    for(Registration_Location__c rl: allLocationReg) {
                        if(rl.Registration__c != null) 
                            RegIds.add(rl.Registration__c);
                    }
                    query += ' AND Id IN :RegIds ';
                } 
            } 

            if(!String.isEmpty(locationAddressStr)) {
                String locln = '%' + locationAddressStr + '%'; 
                String locationQuery = 'SELECT Id, Registration__c FROM Registration_Location__c WHERE Address__c LIKE \'' + locln + '\' OR Address_Line_2__c LIKE \'' + locln + '\' OR Address_Line_3__c LIKE \'' + locln + '\' ';
                List<Registration_Location__c> allLocationReg = Database.query(locationQuery);
                RegIds = new Set<Id>();
                for(Registration_Location__c rl: allLocationReg) {
                    if(rl.Registration__c != null) 
                        RegIds.add(rl.Registration__c);
                }
                
                if(allLocationReg.size() > 0)
                    query += ' AND (Mailing_Address_Line_1__c LIKE \'' + locln + '\' OR Id IN :RegIds) ';
                else
                    query += ' AND Mailing_Address_Line_1__c LIKE \'' + locln + '\' ';
                
            }

            if(!String.isEmpty(locationCityStr)) {
                String locln = '%' + locationCityStr + '%'; 
                String locationQuery = 'SELECT Id, Registration__c FROM Registration_Location__c WHERE City__c LIKE \'' + locln + '\'  ';
                List<Registration_Location__c> allLocationReg = Database.query(locationQuery);
                RegIds = new Set<Id>();
                for(Registration_Location__c rl: allLocationReg) {
                    if(rl.Registration__c != null) 
                        RegIds.add(rl.Registration__c);
                }
                
                if(allLocationReg.size() > 0)
                    query += ' AND (Mailing_City__c LIKE \'' + locln + '\' OR Id IN :RegIds) ';
                else
                    query += ' AND Mailing_City__c LIKE \'' + locln + '\' ';
            }

            if(!String.isEmpty(locationStateStr)) {
                String locln = '%' + locationStateStr + '%'; 
                String locationQuery = 'SELECT Id, Registration__c FROM Registration_Location__c WHERE State__c LIKE \'' + locln + '\'  ';
                List<Registration_Location__c> allLocationReg = Database.query(locationQuery);
                RegIds = new Set<Id>();
                for(Registration_Location__c rl: allLocationReg) {
                    if(rl.Registration__c != null) 
                        RegIds.add(rl.Registration__c);
                }
                
                if(allLocationReg.size() > 0)
                    query += ' AND (Mailing_State__c LIKE \'' + locln + '\' OR Id IN :RegIds) ';
                else
                    query += ' AND Mailing_State__c LIKE \'' + locln + '\' ';
            }

            if(!String.isEmpty(locationZipStr)) {
                String locln = '%' + locationZipStr + '%'; 
                String locationQuery = 'SELECT Id, Registration__c FROM Registration_Location__c WHERE Zip_Code__c LIKE \'' + locln + '\'  ';
                List<Registration_Location__c> allLocationReg = Database.query(locationQuery);
                RegIds = new Set<Id>();
                for(Registration_Location__c rl: allLocationReg) {
                    if(rl.Registration__c != null) 
                        RegIds.add(rl.Registration__c);
                }
                
                if(allLocationReg.size() > 0)
                    query += ' AND (Mailing_Postal_Code__c LIKE \'' + locln + '\' OR Id IN :RegIds) ';
                else
                    query += ' AND Mailing_Postal_Code__c LIKE \'' + locln + '\' '; 
            }
           
            System.debug('*********selectedRecordType:' + selectedRecordType);
            if(!String.isEmpty(selectedRecordType)) {
                System.debug('*********selectedRecordType:' + selectedRecordType);
               query += ' AND License_Registration_Type__c = \'' + selectedRecordType + '\' ';
            }
            
            System.debug('*********serviceType:' + serviceType);
            if(!String.isEmpty(serviceType)) {
                if(serviceType == 'Temporary'){
                    query += ' AND Service_Type__c = \'' + serviceType + '\' ';
                }
                if(serviceType == 'All-NonTemporary'){
                    query += ' AND Service_Type__c != \'Temporary\'';
                }
            }
 
            query += ' ORDER BY Name DESC';
            System.debug('Query=======>'+query);
            if( !Test.isRunningTest()){
                allReg = Database.query(query);
            }
        }
        return allReg;
    }
    
    public PageReference BackToSearch() {
        PageReference searchPage = new PageReference('/apex/FLCSearch');
        searchPage.setRedirect(true);
        return searchPage;
    }
    
   
}