force-app/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>Official registered legal entity name</description>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defect__c/Defect__c.object-meta.xml
<CustomObject>
    <description>Used to indicate defects on submitted Registrations.</description>
    <label>Defect</label>
    <nameField>
        <displayFormat>DID-{0000}</displayFormat>
        <label>Defect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Defect__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Describe the Defect</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Person Account</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>DBA</fullName>
            </value>
            <value>
                <fullName>Bond</fullName>
            </value>
            <value>
                <fullName>Attachments Plus</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Fee Summary</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Registration_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent Authorization</fullName>
            </value>
            <value>
                <fullName>Agreements</fullName>
            </value>
            <value>
                <fullName>Branch Locations</fullName>
            </value>
            <value>
                <fullName>Company Address Information</fullName>
            </value>
            <value>
                <fullName>Company Address Information - JS</fullName>
            </value>
            <value>
                <fullName>Company Contact</fullName>
            </value>
            <value>
                <fullName>Company Entity</fullName>
            </value>
            <value>
                <fullName>Company Finances</fullName>
            </value>
            <value>
                <fullName>Company Information</fullName>
            </value>
            <value>
                <fullName>Company Information -TA</fullName>
            </value>
            <value>
                <fullName>Company Locations</fullName>
            </value>
            <value>
                <fullName>Company Managers</fullName>
            </value>
            <value>
                <fullName>Company Managers Documentation - TA</fullName>
            </value>
            <value>
                <fullName>Company Type</fullName>
                <label>Company Name &amp; Type</label>
            </value>
            <value>
                <fullName>Company Owners</fullName>
            </value>
            <value>
                <fullName>Company Owners Documentation</fullName>
            </value>
            <value>
                <fullName>Company People</fullName>
            </value>
            <value>
                <fullName>Disclaimer</fullName>
            </value>
            <value>
                <fullName>Download Documents To Be Completed</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Exam</fullName>
            </value>
            <value>
                <fullName>Fees</fullName>
            </value>
            <value>
                <fullName>Follow up Questions</fullName>
            </value>
            <value>
                <fullName>Live Scan</fullName>
            </value>
            <value>
                <fullName>Location Documentation</fullName>
            </value>
            <value>
                <fullName>Medical Information</fullName>
            </value>
            <value>
                <fullName>Minor Information</fullName>
            </value>
            <value>
                <fullName>Owners &amp; Management</fullName>
            </value>
            <value>
                <fullName>Parent/Guardian Information</fullName>
            </value>
            <value>
                <fullName>Permit Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect__c/fields/Sub_Section__c.field-meta.xml
<CustomField>
    <fullName>Sub_Section__c</fullName>
    <label>Sub-Section</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporation and LLC Questions</fullName>
            </value>
            <value>
                <fullName>Locations</fullName>
            </value>
            <value>
                <fullName>DBAs</fullName>
            </value>
            <value>
                <fullName>Bonds</fullName>
            </value>
            <value>
                <fullName>CBA</fullName>
            </value>
            <value>
                <fullName>Company Owners</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Questions</fullName>
            </value>
            <value>
                <fullName>Exam/Course</fullName>
            </value>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>Fee Summary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/accAlreadyCreated__c.field-meta.xml
<CustomField>
    <fullName>accAlreadyCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>accAlreadyCreated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Audit_Number__c.field-meta.xml
<CustomField>
    <fullName>Audit_Number__c</fullName>
    <label>Audit Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <inlineHelpText>Please enter name registered with CA Secretary of State.  For Sole Proprietor enter full legal name.</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduledDispatcherTest.cls
@isTest
private class ScheduledDispatcherTest {
    @testSetup
    static void setup() {
        Account acc = new Account(
                Name = 'test acct 123',
                ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
                ShippingCity = 'Denver',
                ShippingState = 'CO',
                ShippingPostalCode = '80212'
        );
        insert acc;

        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Test';
        con.Email = 'testLNRDEV@testdir.com';
        insert con;

        Defect__c de = new Defect__c();
        de.Active__c = true;
        de.Description__c = 'Description test';
        de.Registration_Type__c = 'Car Wash';
        de.Section__c = 'Company Information';
        de.Sub_Section__c = 'Documents';
        de.Object__c = 'Business Account';
        insert de;

        Id devRecordTypeId = Schema.getGlobalDescribe().get('License_Registration__c').getDescribe().getRecordTypeInfosByName().get('Public Works').getRecordTypeId();

        License_Registration__c lreg = new License_Registration__c();
        lreg.RecordTypeId = devRecordTypeId;
        lreg.Account__c = acc.Id;
        lreg.Applicant__c = con.Id;
        lreg.Status__c = 'Incomplete';
        lreg.License_Registration_Number__c = '00023568500';
        lreg.Audit_Number__c = null;
        lreg.accAlreadyCreated__c = false;
        lreg.Status__c = 'Active';
        lreg.Legal_Entity_Name__c = 'name';

        insert lreg;
    }

    @isTest static void testClass() {
        String CRON_EXP = '0 0 0 3 9 ? 2022';

        Test.startTest();

        String jobId = System.schedule('ScheduledDispatcher', CRON_EXP, new ScheduledDispatcher());

        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                          FROM CronTrigger
                          WHERE id = :jobId];

        System.debug('HHH');
        System.debug(ct);
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, ct.CronExpression);

        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);

        // Verify the next time the job will run
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));

        Test.stopTest();
    }
}