force-app/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>Official registered legal entity name</description>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Court_Name__c.field-meta.xml
<CustomField>
    <fullName>Court_Name__c</fullName>
    <inlineHelpText>If selecting Other / Specify, please enter the court name in the Court Name for PAGA Case field.</inlineHelpText>
    <label>Court Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Court_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alameda County Superior Court</fullName>
            </value>
            <value>
                <fullName>Alpine County Superior Court</fullName>
            </value>
            <value>
                <fullName>Amador County Superior Court</fullName>
            </value>
            <value>
                <fullName>Butte County Superior Court</fullName>
            </value>
            <value>
                <fullName>Calaveras County Superior Court</fullName>
            </value>
            <value>
                <fullName>Colusa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Contra Costa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Del Norte County Superior Court</fullName>
            </value>
            <value>
                <fullName>El Dorado County Superior Court</fullName>
            </value>
            <value>
                <fullName>Fresno County Superior Court</fullName>
            </value>
            <value>
                <fullName>Glenn County Superior Court</fullName>
            </value>
            <value>
                <fullName>Humboldt County Superior Court</fullName>
            </value>
            <value>
                <fullName>Imperial County Superior Court</fullName>
            </value>
            <value>
                <fullName>Inyo County Superior Court</fullName>
            </value>
            <value>
                <fullName>Kern County Superior Court</fullName>
            </value>
            <value>
                <fullName>Kings County Superior Court</fullName>
            </value>
            <value>
                <fullName>Lake County Superior Court</fullName>
            </value>
            <value>
                <fullName>Lassen County Superior Court</fullName>
            </value>
            <value>
                <fullName>Los Angeles County Superior Court</fullName>
            </value>
            <value>
                <fullName>Madera County Superior Court</fullName>
            </value>
            <value>
                <fullName>Marin County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mariposa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mendocino County Superior Court</fullName>
            </value>
            <value>
                <fullName>Merced County Superior Court</fullName>
            </value>
            <value>
                <fullName>Modoc County Superior Court</fullName>
            </value>
            <value>
                <fullName>Mono County Superior Court</fullName>
            </value>
            <value>
                <fullName>Monterey County Superior Court</fullName>
            </value>
            <value>
                <fullName>Napa County Superior Court</fullName>
            </value>
            <value>
                <fullName>Nevada County Superior Court</fullName>
            </value>
            <value>
                <fullName>Orange County Superior Court</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Court_Name_Other_Specify__c.field-meta.xml
<CustomField>
    <fullName>Court_Name_Other_Specify__c</fullName>
    <label>Other/Specify</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Date_Case_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Case_Received__c</fullName>
    <description>Date Case Received</description>
    <label>Date Case Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/PAGA_Court_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>PAGA_Court_Case_Number__c</fullName>
    <description>PAGA Court Case Number</description>
    <inlineHelpText>This is the court case number of the Private Attorney's civil case under the PAGA L.C. 2698.</inlineHelpText>
    <label>PAGA Court Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Registration for business / owner / or other individual related to this case.</description>
    <inlineHelpText>Registration for business / owner / or other individual related to this case.</inlineHelpText>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>FEE-{0000}</displayFormat>
        <label>Fee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Registration to which this fee applies</description>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee_Summary__c/Fee_Summary__c.object-meta.xml
<CustomObject>
    <label>Fee Summary</label>
    <nameField>
        <displayFormat>FSUM-{00000}</displayFormat>
        <label>Fee Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Summary__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Fee Summaries</relationshipLabel>
    <relationshipName>Fee_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <inlineHelpText>Please enter name registered with CA Secretary of State.  For Sole Proprietor enter full legal name.</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Type__c</fullName>
    <label>License/Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>Agricultural Employers of Minors</fullName>
            </value>
            <value>
                <fullName>Agricultural Produce Unloaders</fullName>
            </value>
            <value>
                <fullName>BOE/Seller’s Permit</fullName>
            </value>
            <value>
                <fullName>Bureau of Automotive Repair</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Car Wash</fullName>
            </value>
            <value>
                <fullName>Child Performer Services</fullName>
            </value>
            <value>
                <fullName>CSLB</fullName>
            </value>
            <value>
                <fullName>DOL</fullName>
            </value>
            <value>
                <fullName>DSS Facility</fullName>
            </value>
            <value>
                <fullName>Electricians and electrician trainees</fullName>
            </value>
            <value>
                <fullName>FBNS</fullName>
            </value>
            <value>
                <fullName>Farm Labor Contractor</fullName>
            </value>
            <value>
                <fullName>Garment Manufacturers and Contractors</fullName>
            </value>
            <value>
                <fullName>Health Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworker Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworkers</fullName>
            </value>
            <value>
                <fullName>Industrial Homework License</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Secretary of State Number</fullName>
            </value>
            <value>
                <fullName>SEIN</fullName>
            </value>
            <value>
                <fullName>Sheltered Workshops (non‐profit)</fullName>
            </value>
            <value>
                <fullName>Special Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Studio Teacher Certification</fullName>
            </value>
            <value>
                <fullName>Talent Agency</fullName>
            </value>
            <value>
                <fullName>Work Permits for Child Performers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>BSIS</fullName>
            </value>
            <value>
                <fullName>Entertainment Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Placeholder for develoment. Do not deploy this record type</description>
    <label>Other</label>
</RecordType>

force-app/main/default/classes/CommunityPayCheckTest.cls
@istest
public class CommunityPayCheckTest {

    public static testMethod void testCommunityPayCheck(){
        
        
        Id p = [SELECT id FROM profile WHERE Name='Community Registrations User'].id;
       
        Account acc = new Account(
            Name = 'test acct 123',
            Legal_Entity_Name__c = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert acc;
       
        Contact con = new Contact(LastName ='testCon',AccountId = acc.Id, Email='testdirlnr.test@dirlnr.com');
        insert con;  
                  
        /*User communityuser = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                ContactId = con.Id, PortalRole = 'Car Wash User',
                timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
       
        insert communityuser ;*/
        
        Id RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('PAGA Case').getRecordTypeId();
        id lrRecordTypeId = Schema.sObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeID();
        
        DIR_Case__c dirCase1  = new DIR_Case__c();
        dirCase1.RecordTypeId = RecordTypeId;
        dirCase1.Employer__c = acc.Id;
        dirCase1.PAGA_Court_Case_Number__c = '333';
        dirCase1.Court_Type__c = 'Other';
        dirCase1.Court_Name__c = 'Other';
        //dirCase1.Court_Name_Other_Specify__c = 'test';
        dirCase1.Date_Case_Received__c = Date.Today();
        insert dirCase1;
        
        License_Registration__c  newLR = new License_Registration__c();
        newLR.Account__c = acc.Id;
        newLR.License_Registration_Number__c = '222';
        newLR.License_Registration_Type__c = 'Car Wash';
        newLR.Status__c = 'Incomplete'; 
        newLR.Expiration_Date__c = Date.today() + 10; 
        newLR.Amount_Paid__c = 100; 
        newLR.Applicant__c = con.Id;
        newLR.recordTypeID = lrRecordTypeID;
        insert newLR;
        
        Fee_Summary__c feeSummary = new Fee_Summary__c();
        feeSummary.Registration__c = newLR.Id;
        insert feeSummary;
        
        Fee__c newFee = new Fee__c();
        newFee.Fee__c = 100;
        newFee.Registration__c = newLR.Id;
        newFee.Fee_Summary__c = feeSummary.Id;
        newFee.Description__c = 'Fee description';
        insert newFee;
        
        ChargentOrders__ChargentOrder__c newChargentOrder = new ChargentOrders__ChargentOrder__c();
        newChargentOrder.ChargentOrders__Payment_Method__c = 'Check';
        newChargentOrder.Registration__c  = newLR.Id;
        newChargentOrder.Fee_Summary__c = feeSummary.Id;
        newChargentOrder.ChargentOrders__Billing_Email__c = newLR.Applicant__r.Email;
        newChargentOrder.ChargentOrders__Subtotal__c = 0;
        insert newChargentOrder;
        
        test.startTest();
            ApexPages.CurrentPage().getParameters().put('id', newChargentOrder.Id);
            CommunityPayCheck CCACH = new CommunityPayCheck();  
            
            CCACH.NextPayment();
            CCACH.CancelPayment();
        test.stopTest();
    }
    
    public static testMethod void testCommunityPayCheckConfirm(){
        
        
        Id p = [SELECT id FROM profile WHERE Name='Community Registrations User'].id;
       
        Account acc = new Account(
            Name = 'test acct 123',
            Legal_Entity_Name__c = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert acc;
       
        Contact con = new Contact(LastName ='testCon',AccountId = acc.Id, Email='testdirlnr.test@dirlnr.com');
        insert con;  
        /*User communityuser = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                ContactId = con.Id, PortalRole = 'Car Wash User',
                timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
       
        insert communityuser ;*/
        
        Id RecordTypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('PAGA Case').getRecordTypeId();
        id lrRecordTypeId = Schema.sObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeID();
        
        DIR_Case__c dirCase1  = new DIR_Case__c();
        dirCase1.RecordTypeId = RecordTypeId;
        dirCase1.Employer__c = acc.Id;
        dirCase1.PAGA_Court_Case_Number__c = '333';
        dirCase1.Court_Type__c = 'Other';
        dirCase1.Court_Name__c = 'Other';
        //dirCase1.Court_Name_Other_Specify__c = 'test';
        dirCase1.Date_Case_Received__c = Date.Today();
        insert dirCase1;
        
        License_Registration__c  newLR = new License_Registration__c();
        newLR.Account__c = acc.Id;
        newLR.License_Registration_Number__c = '222';
        newLR.License_Registration_Type__c = 'Car Wash';
        newLR.Status__c = 'Incomplete'; 
        newLR.Expiration_Date__c = Date.today() + 10; 
        newLR.Amount_Paid__c = 100; 
        newLR.Applicant__c = con.Id;
        newLR.RecordTypeId = lrRecordTypeID;
        insert newLR;
        
        Fee_Summary__c feeSummary = new Fee_Summary__c();
        feeSummary.Registration__c = newLR.Id;
        insert feeSummary;
        
        Fee__c newFee = new Fee__c();
        newFee.Fee__c = 100;
        newFee.Registration__c = newLR.Id;
        newFee.Fee_Summary__c = feeSummary.Id;
        newFee.Description__c = 'Fee description';
        insert newFee;
        
        ChargentOrders__ChargentOrder__c newChargentOrder = new ChargentOrders__ChargentOrder__c();
        newChargentOrder.ChargentOrders__Payment_Method__c = 'Check';
        newChargentOrder.Registration__c  = newLR.Id;
        newChargentOrder.Fee_Summary__c = feeSummary.Id;
        newChargentOrder.ChargentOrders__Billing_Email__c = newLR.Applicant__r.Email;
        newChargentOrder.ChargentOrders__Subtotal__c = 0;
        insert newChargentOrder;
        
        test.startTest();
            ApexPages.CurrentPage().getParameters().put('id', newChargentOrder.Id);
            CommunityPayCheckConfirm CCACH = new CommunityPayCheckConfirm();  
            
            CCACH.ConfirmSubmitPayment();
            CCACH.CancelPayment();
        test.stopTest();
    }
}