force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAICS Code</label>
    <referenceTo>NAICS_Code__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Phone1__c.field-meta.xml
<CustomField>
    <fullName>Phone1__c</fullName>
    <description>Custom Telephone Field</description>
    <inlineHelpText>Custom Telephone Field</inlineHelpText>
    <label>Phone 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Affiliation__c/Affiliation__c.object-meta.xml
<CustomObject>
    <description>Defines the relationship between two accounts, person accounts or business accounts either one, or between accounts and contacts.</description>
    <label>Affiliation</label>
    <nameField>
        <label>Affiliation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliation__c/fields/Affiliated_Account__c.field-meta.xml
<CustomField>
    <fullName>Affiliated_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account that is chosen to be related to an account when creating an affiliation.</description>
    <label>Affiliated Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations (Affiliated Business/Person)</relationshipLabel>
    <relationshipName>Additional_Affiliations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliation__c/fields/Main_Account__c.field-meta.xml
<CustomField>
    <fullName>Main_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The "source" account that an affiliation is created FROM</description>
    <inlineHelpText>The "source" account that an affiliation is created FROM. When reading the affiliation, the relationship should read:
[Affiliated Account/contact] is a [Affiliation Type] of [Main Account/contact].</inlineHelpText>
    <label>Main Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations (Main Account)</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/Appeal__c.object-meta.xml
<CustomObject>
    <description>This is used for a Request for Citation Appeal Hearing associated with a DIR BOFE Case.  This may be repurposed for specific purposes.</description>
    <label>Appeal</label>
    <nameField>
        <displayFormat>APL-{000000}</displayFormat>
        <label>Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appeals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appeal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Appeals</relationshipLabel>
    <relationshipName>Appeals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Used for BOFE Appeals</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Appeal__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessments__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>BOFE Roles</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Case_Role__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>NAICS code selected on the related employer</description>
    <formula>Employer__r.NAICS_Code__r.Name</formula>
    <inlineHelpText>Employer's NAICS Code.</inlineHelpText>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <description>Vertiba</description>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Defines if a role is currently active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee's manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/DIR_Employee__c.field-meta.xml
<CustomField>
    <fullName>DIR_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issuing Deputy</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipName>DIR_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Liable_Party__c/Liable_Party__c.object-meta.xml
<CustomObject>
    <label>Liable Party</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Liable Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liable Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liable_Party__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The liable party is related to a case role on the record. This field holds the value of that case role and is used for generating output document based on the party.</description>
    <inlineHelpText>Case role of the liable party</inlineHelpText>
    <label>Case Role</label>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Liable Parties</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/recordTypes/BOFE.recordType-meta.xml
<RecordType>
    <fullName>BOFE</fullName>
    <active>true</active>
    <description>Used for BOFE Liable Parties</description>
    <label>BOFE</label>
</RecordType>

force-app/main/default/objects/Liable_Party__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/NAICS_Code__c/NAICS_Code__c.object-meta.xml
<CustomObject>
    <description>WCA - 2012 North American Industry Classification System</description>
    <label>NAICS Code</label>
    <nameField>
        <label>NAICS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAICS Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NAICS_Code__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
            <value>
                <fullName>Level 4</fullName>
            </value>
            <value>
                <fullName>Level 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAICS_Code__c/fields/NAICS_Title__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Title__c</fullName>
    <label>NAICS Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AddAppealTest.cls
@isTest
public with sharing class AddAppealTest {
    
    public static testMethod void TestAddAppeal1() {
        
        List<Trigger_Settings__c> triggerSettings = new List<Trigger_Settings__c>();

        Trigger_Settings__c receiptTriggerSetting = new Trigger_Settings__c(
            Name = 'Receipt Trigger',
            Is_Active__c = false
        );
        triggerSettings.add(receiptTriggerSetting);

        Trigger_Settings__c casePaymentAllTriggerSetting = new Trigger_Settings__c(
            Name = 'CasePaymentAll',
            Is_Active__c = false
        );
        triggerSettings.add(casePaymentAllTriggerSetting); 

         Trigger_Settings__c dlrs_DIR_ViolationTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_DIR_ViolationTrigger',
            Is_Active__c = true
        );

        triggerSettings.add(dlrs_DIR_ViolationTriggerSetting);

        Trigger_Settings__c lpTriggerSetting = new Trigger_Settings__c(
            Name = 'liabilityPaymentTrigger',
            Is_Active__c = true
        );
 
        triggerSettings.add(lpTriggerSetting);

        Trigger_Settings__c GenerateFieldHistoryActionTriggerSetting = new Trigger_Settings__c(
            Name = 'GenerateFieldHistoryAction',
            Is_Active__c = false
        );

        triggerSettings.add(GenerateFieldHistoryActionTriggerSetting);

        Trigger_Settings__c DIREmployeeTrigger = new Trigger_Settings__c(
            Name = 'DIR_EmployeeTrigger',
            Is_Active__c = false
        );        
        
        triggerSettings.add(DIREmployeeTrigger);

        Trigger_Settings__c CaseRoleAllTrigger = new Trigger_Settings__c(
            Name = 'CaseRoleAll',
            Is_Active__c = false
        );        
        
        triggerSettings.add(CaseRoleAllTrigger);
        
        insert triggerSettings;
        
        NAICS_Code__c nc = new NAICS_Code__c();
        nc.Name = '11';
        nc.NAICS_Title__c = 'Agriculture, Forestry, Fishing and Hunting';
        nc.Level__c = 'Level 1';
        
        Account acc = new Account();
        acc.Name = 'Emplpoyer name';
        acc.ShippingPostalCode = '234889';
        acc.Phone1__c = '5103334444';
        acc.NAICS_Code__c = nc.Id;
        insert acc;

        User user1 = new User();
        //profile p = [SELECT Id FROM profile WHERE name='RCI User'];
        profile p = [SELECT Id FROM profile WHERE name='BOFE User'];
        user1.ProfileId = p.Id;
        user1.Phone = '5103334444';
        user1.FirstName = 'firstname';
        user1.LastName = 'lastname';
        user1.Username = 'firstname.lastname@dir.ca.gov.test';
        user1.Email = 'firstname.lastname@dir.ca.gov.test';
        user1.Alias = 'flname';
        user1.TimeZoneSidKey = 'America/Denver';
        user1.LocaleSidKey = 'en_US';
        user1.EmailEncodingKey = 'UTF-8';
        user1.LanguageLocaleKey = 'en_US';
        insert user1;

        User user2 = new User();
        user2.ProfileId = p.Id;
        user2.Phone = '5103334444';
        user2.FirstName = 'firstname';
        user2.LastName = 'lastname';
        user2.Username = 'firstname2.lastname2@dir.ca.gov.test';
        user2.Email = 'firstname2.lastname2@dir.ca.gov.test';
        user2.Alias = 'flname';
        user2.TimeZoneSidKey = 'America/Denver';
        user2.LocaleSidKey = 'en_US';
        user2.EmailEncodingKey = 'UTF-8';
        user2.LanguageLocaleKey = 'en_US';
        insert user2;        
 
        DIR_Employee__c assignedDep2 = new DIR_Employee__c(User__c = user2.Id);
        assignedDep2.Active__c = True;
        insert assignedDep2;
        
        DIR_Employee__c assignedDep = new DIR_Employee__c(User__c = user1.Id);
        assignedDep.Active__c = True;
        assignedDep.Manager__c = assignedDep2.Id;
        insert assignedDep;   
        
        Affiliation__c aff = new Affiliation__c();
        aff.Affiliated_Account__c = acc.Id;
        aff.Main_Account__c = acc.Id;
        insert aff;
        
        DIR_Case__c c = new DIR_Case__c();
        //Id caseRecTypeId_RCI = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId();
        Id caseRecTypeId_BOFE = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('BOFE').getRecordTypeId();
        //c.RecordTypeId = caseRecTypeId_RCI;
        c.RecordTypeId = caseRecTypeId_BOFE;
        c.Employer__c = acc.Id;
        c.Assigned_Deputy__c = assignedDep.Id;
        insert c;
                 
		Case_Role__c crEmplyr = new Case_Role__c();
        crEmplyr.Entity__c = acc.Id;
        crEmplyr.Case__c = c.Id;
        crEmplyr.Case_Role_Status__c = 'Active';
        crEmplyr.Role__c = 'Case Employer';
        insert crEmplyr;
        
        Test.startTest();
            
        Appeal__c appeal1 = new Appeal__c();
        appeal1.Status__c = 'New';
        //Id RCIRecordTypeId = Schema.SObjectType.Appeal__c.getRecordTypeInfosByName().get('RCI').getRecordTypeId();
        Id BOFEAppealRecTypeId = Schema.SObjectType.Appeal__c.getRecordTypeInfosByName().get('BOFE').getRecordTypeId();
        //appeal1.recordtypeID = RCIRecordTypeID;
        appeal1.recordtypeID = BOFEAppealRecTypeID;
        appeal1.Case__c = c.Id;
        appeal1.Estimated_Length_of_Hearing_In_Minutes__c = 30;
        appeal1.Citation_Selected__c = True;
        appeal1.Unavailable_dates__c = 'February 10, 2019';
        //date newDate = date.newInstance(2001, 3, 21);
        appeal1.Request_Receipt_Date__c = Date.today()+1;
        appeal1.X2810_3_Case__c = 'No';
        insert appeal1;
        
        
        Assessments__c assesment = new Assessments__c();
        assesment.Appeal_Deadline_Selector__c = 'Business Days';
        assesment.Appeal_Deadline_Days__c = 15;
        assesment.Case_Management__c = c.Id;
        insert assesment;

        Violation_Type__c vt1 = new Violation_Type__c();
        //Id RCIVTRecordTypeId = Schema.SObjectType.Violation_Type__c.getRecordTypeInfosByName().get('RCI Violations').getRecordTypeId();
        Id BOFEVTRecordTypeId = Schema.SObjectType.Violation_Type__c.getRecordTypeInfosByName().get('BOFE Violations').getRecordTypeId();
        //vt1.RecordTypeId = RCIVTRecordTypeId;
        vt1.RecordTypeId = BOFEVTRecordTypeId;
        vt1.Name = 'L.C. 1030';
        vt1.Active__c = True;
        vt1.Assessment_Formula__c = '100';
        vt1.Appeal_Deadline_Selector__c = 'Business Days';
        vt1.Appeal_Deadline_Days__c = 15;
        vt1.Accounting_Payment_Type__c = 'Penalty';
        insert vt1;
                
        
        //Case Issue
        DIR_Violation__c dv = new DIR_Violation__c();
        dv.Case__c = c.Id;
        dv.Assessment__c = assesment.Id;
        dv.Violation_Type__c = vt1.Id;
        insert dv;
     
        Liability__c liability1 = new Liability__c();
        liability1.Assessment__c = assesment.Id;
        liability1.Case_Management__c = c.Id;
        liability1.Status__c = 'new';
        liability1.Appeal_Deadline__c = Date.today();
        insert liability1;

        
        Liable_Party__c lp = new Liable_Party__c();
        lp.Liability__c = liability1.Id;
        lp.Entity__c = acc.id;
        
        Appeal__c app = [SELECT Id, Status__c FROM Appeal__c WHERE Id =: appeal1.Id];
        //app.Status__c = 'Withdrawn';
        //update app;
        
        
        DIR_Case__c  dir = [SELECT Id, Employer__c, Employer__r.Name, Employer__r.Phone FROM DIR_Case__c WHERE Id =: c.Id LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(dir);
        AddAppeal aa = new AddAppeal(sc);
        
        //system.assertequals(aa.Citations.size(),0);
        PageReference pageRef = Page.AddAppeal;
        pageRef.getParameters().put('id', String.valueOf(dir.Id));
        Test.setCurrentPage(pageRef);
        
        aa.appeal.recordtypeID = BOFEAppealRecTypeID;
        //aa.appeal.recordtypeID = RCIRecordTypeID;
        aa.appeal.Case__c = c.Id;
        aa.appeal.X2810_3_Case__c = 'No';
        aa.appeal.Estimated_Length_of_Hearing_In_Minutes__c = 30;
        aa.appeal.Citation_Selected__c = True;
        aa.appeal.Request_Receipt_Date__c = Date.today()+1;
        aa.appeal.Unavailable_dates__c = 'No Mondays';
        aa.SaveAppeal();

        List<AddAppeal.CitationWrapper> localList = new List<AddAppeal.CitationWrapper>();
        aa.Citations = new List<AddAppeal.CitationWrapper>();
        (aa.Citations).add(new AddAppeal.CitationWrapper(liability1, true));
        aa.SaveAppeal();
        
        Test.stopTest();
        
    }
    

}