force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAICS Code</label>
    <referenceTo>NAICS_Code__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code_Title__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code_Title__c</fullName>
    <description>This field is used to display the Title of the NAICS Code associated with the Account</description>
    <formula>NAICS_Code__r.NAICS_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAICS Code Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Labor Code requires that an owner submit the application or have knowledge of the application. If you are not the owner, then a Power of Attorney must be provided with the certification.</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Bookkeeper</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Formula field to migrate the Case Number from the Case to the Case Role object for use in an email template (auto response to Claim Form being submitted).</description>
    <formula>Case__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Case_Role_Entity_Full_Output__c.field-meta.xml
<CustomField>
    <fullName>Case_Role_Entity_Full_Output__c</fullName>
    <description>Formula field used to dynamically concatenate the Name, Entity Type Descriptor, and DBA of the Account associated with a Case Role.</description>
    <formula>IF ( NOT (ISBLANK(Location__r.Law_Firm__c)),Location__r.Law_Firm__r.Name + ", Attn: " + Entity__r.Name_UsedInTemplates__c, Entity__r.Name_UsedInTemplates__c 	+ IF(ISBLANK (Entity__r.Entity_Type_Other__c), 	", " + TEXT( Entity__r.Legal_Entity_Descriptor__c ),", " + Entity__r.Entity_Type_Other__c) + IF (ISBLANK ( Location__r.DBA__c ), "", " dba " + Location__r.DBA__c ) + IF (ISBLANK(Entity__r.PersonContact.AKA_Alias_or_other_special_circumstance__c), "", ", a.k.a. " + Entity__r.PersonContact.AKA_Alias_or_other_special_circumstance__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Role Entity Full Output</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</description>
    <inlineHelpText>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Roles</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Roles that related accounts have on a case</description>
    <inlineHelpText>Select the role played by this related account</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Agent for Service of Process</fullName>
            </value>
            <value>
                <fullName>Aggrieved</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Attorney for Defendant</fullName>
            </value>
            <value>
                <fullName>Attorney for Plaintiff</fullName>
            </value>
            <value>
                <fullName>Attorney Representative</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Brand Guarantor</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Case Employer</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Claimant Advocate</fullName>
            </value>
            <value>
                <fullName>Claimant Assignee</fullName>
            </value>
            <value>
                <fullName>Claimant Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Guardian</fullName>
            </value>
            <value>
                <fullName>Claimant Minor</fullName>
            </value>
            <value>
                <fullName>Claimant Other</fullName>
            </value>
            <value>
                <fullName>Claimant Representative</fullName>
            </value>
            <value>
                <fullName>Client Employer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Contractor Successor</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Date_of_Docket__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Docket__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date of Docket</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>NAICS code selected on the related employer</description>
    <formula>Employer__r.NAICS_Code__r.Name</formula>
    <inlineHelpText>Employer's NAICS Code.</inlineHelpText>
    <label>NAICS Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/NAICS_Code_Title__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code_Title__c</fullName>
    <formula>Employer__r.NAICS_Code_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAICS Code Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WageClaimSearchResultPageCtrl.cls
public class WageClaimSearchResultPageCtrl {
    public List<WageClaimSearchResultPageWrapperCtrl> wageClaimList{get;set;}
    public String accountName{get;set;}
    public String caseNumber{get;set;}
    public Date docketFromDate{get;set;}
    public Date docketToDate{get;set;}
    public Date closedFromDate{get;set;}
    public Date closedToDate{get;set;}
    public String naicsCode{get;set;}
    public String naicsIndustry{get;set;}
    public String lowWageIndustry{get;set;}
    public String dirOffice{get;set;}
    public String sortedHeader;
    public String sortedOrder;
    public WageClaimSearchResultPageCtrl(){
        wageClaimList = new List<WageClaimSearchResultPageWrapperCtrl>();
        if(ApexPages.currentPage().getParameters().get('fromDate') != 'null' && ApexPages.currentPage().getParameters().get('fromDate') != 'undefined'){
            docketFromDate = Date.valueOf(ApexPages.currentPage().getParameters().get('fromDate'));
        }
        if(ApexPages.currentPage().getParameters().get('toDate') != 'null' && ApexPages.currentPage().getParameters().get('toDate') != 'undefined'){
            docketToDate = Date.valueOf(ApexPages.currentPage().getParameters().get('toDate'));
        }
        if(ApexPages.currentPage().getParameters().get('caseclosedfromdate') != 'null' && ApexPages.currentPage().getParameters().get('caseclosedfromdate') != 'undefined'){
            closedFromDate = Date.valueOf(ApexPages.currentPage().getParameters().get('caseclosedfromdate'));
        }
        if(ApexPages.currentPage().getParameters().get('caseclosedtodate') != 'null' && ApexPages.currentPage().getParameters().get('caseclosedtodate') != 'undefined'){
            closedToDate = Date.valueOf(ApexPages.currentPage().getParameters().get('caseclosedtodate'));
        }
        if(ApexPages.currentPage().getParameters().get('dirOffice') != null){
            dirOffice = ApexPages.currentPage().getParameters().get('dirOffice');
        }
        if(ApexPages.currentPage().getParameters().get('accountName') != null){
            accountName = ApexPages.currentPage().getParameters().get('accountName');
        }
        if(ApexPages.currentPage().getParameters().get('naicsCodeTitle') != null){
            naicsIndustry = ApexPages.currentPage().getParameters().get('naicsCodeTitle');
        }
        if(ApexPages.currentPage().getParameters().get('naicsCode') != null){
            naicsCode = ApexPages.currentPage().getParameters().get('naicsCode');
        }
        if(ApexPages.currentPage().getParameters().get('caseNumber') != null){
            caseNumber = ApexPages.currentPage().getParameters().get('caseNumber');
        }
        if(ApexPages.currentPage().getParameters().get('lowWage') != null){
            lowWageIndustry = ApexPages.currentPage().getParameters().get('lowWage');
        }
        if(ApexPages.currentPage().getParameters().get('sortingOrder') != null){
            sortedOrder = ApexPages.currentPage().getParameters().get('sortingOrder');
        }
        if(ApexPages.currentPage().getParameters().get('selectedHeader') != null){
            sortedHeader = ApexPages.currentPage().getParameters().get('selectedHeader');
        }
        System.debug('docketFromDate ::: '+docketFromDate);
        System.debug('docketToDate ::: '+docketToDate);
        System.debug('closedFromDate ::: '+closedFromDate);
        System.debug('closedToDate ::: '+closedToDate);
        System.debug('dirOffice ::: '+dirOffice);
        System.debug('accountName ::: '+accountName);
        System.debug('naicsIndustry ::: '+naicsIndustry);
        System.debug('naicsCode ::: '+naicsCode);
        System.debug('caseNumber ::: '+caseNumber);
        List<Case_Role__c> caseRoleRecords = WageClaimQuerySelector.getWageClaimRecods(naicsCode , accountName, docketFromDate, docketToDate,closedFromDate,closedToDate, caseNumber, lowWageIndustry , dirOffice);
        System.debug('caseRoleRecords ::: '+caseRoleRecords.size());
        for(Case_Role__c caseRoleObj : caseRoleRecords){
            WageClaimSearchResultPageWrapperCtrl wageClaimObj = new WageClaimSearchResultPageWrapperCtrl();
            if(caseRoleObj.Role__c == 'Claimant' || caseRoleObj.Role__c == 'Defendant'){
                wageClaimObj.accountName = caseRoleObj.Case_Role_Entity_Full_Output__c ;
            }
            else{
                wageClaimObj.accountName = caseRoleObj.Entity__r.Name;
            }
            wageClaimObj.caseRole = caseRoleObj.Role__c;
            wageClaimObj.caseNumber = caseRoleObj.Case__r.Case_Number__c;
            wageClaimObj.naicsCode = caseRoleObj.Case__r.NAICS_Code__c;
            wageClaimObj.naicsTitle = (caseRoleObj.Case__r.NAICS_Code_Title__c != null ? caseRoleObj.Case__r.NAICS_Code_Title__c : '');
            wageClaimObj.dateofDocket = caseRoleObj.Case__r.Date_of_Docket__c;
            wageClaimObj.assignedDeputy = caseRoleObj.Case__r.Assigned_Deputy__r.Name;
            wageClaimObj.caseStatus = caseRoleObj.Case__r.Status__c +' '+(caseRoleObj.Case__r.Closure_Disposition__c != null ? caseRoleObj.Case__r.Closure_Disposition__c : '');
            wageClaimObj.applies = caseRoleObj.Case__r.X2810_4_Applies__c;
            wageClaimObj.dirOffice = caseRoleObj.Case__r.Office__r.Name;
            wageClaimList.add(wageClaimObj);
        }
        System.debug('wageClaimList ::: '+wageClaimList.size());
        WageClaimSearchResultPageWrapperCtrl.sortBy = sortedHeader;
        WageClaimSearchResultPageWrapperCtrl.sortedOrder = sortedOrder;
        wageClaimList.sort();
    }
}