force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_URL__c.field-meta.xml
<CustomField>
    <fullName>Attachment_URL__c</fullName>
    <formula>"/" &amp;  Attachment_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attorney_Client_Privilege__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Client_Privilege__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is subject to attorney-client privilege.</inlineHelpText>
    <label>Attorney-Client Privilege</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is considered confidential</inlineHelpText>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is not subject to PRA requests</inlineHelpText>
    <label>Not Subject to PRA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/VIP_Form_Section__c.field-meta.xml
<CustomField>
    <fullName>VIP_Form_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>VIP Form Section</label>
    <referenceTo>VIPForm__VIP_Category__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Attachment_Widget_Controller_Test.cls
@isTest(SeeAllData=false)
private class Attachment_Widget_Controller_Test {
  
    static testMethod void testAttachment_Widget_Controller() {
        VIPForm__VIP_Category__c section = new VIPForm__VIP_Category__c();
        section.VIPForm__Name_Displayed__c = 'FLC Card Photo';
        section.VIPForm__Object_API__c = 'License_Registration__c';
        section.VIPForm__Order__c = 300;
        section.RecordtypeId = Schema.SObjectType.VIPForm__VIP_Category__c.getRecordTypeInfosByName().get('VIP Form Section').getRecordTypeId();
        insert section;
        
        Account a = new Account();
        a.Name = 'test account'+system.now();
        insert a;
        
        Contact con = new Contact();
        con.AccountId = a.id;
        con.LastName = 'lastName';
        insert con;
        
        License_Registration__c lr = new License_Registration__c();
        lr.Account__c = a.id;
        lr.Applicant__c = con.id;
        lr.RecordtypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();
        insert lr;
        
        Attachments_Plus__c attPlus = new Attachments_Plus__c(
        Attachment_Name__c = 'test att name.jpg', 
        Registration__c = lr.id,
        //Attachment_URL__c, 
        Description__c = 'test desc', 
        //Object__c, 
        //Record_ID__c = cm.Id, 
        Type__c = '', 
        Attorney_Client_Privilege__c = true, 
        Confidential__c = true, 
        Not_Subject_to_PRA__c = true,
        VIP_Form_Section__c = section.id
        );
        insert attPlus;
        
        ContentVersion conVer = new ContentVersion();
        conVer.ContentLocation = 'S';
        conVer.PathOnClient = 'file_name.jpg';
        conVer.Title = 'file_name.pdf';
        conVer.VersionData = blob.valueOf('text file');
        conVer.Origin = 'C';
        insert conVer;
        
        ContentDocumentLink cDe = new ContentDocumentLink();
        cDe.ContentDocumentId = [select id, ContentDocumentId from ContentVersion where id = :conVer.id].ContentDocumentId;
        cDe.LinkedEntityId = attPlus.id;
        cDe.ShareType = 'I';
        cDe.Visibility = 'AllUsers';
        insert cDe;
        
        Attachments_Plus__c attPlus1 = new Attachments_Plus__c(
        Attachment_Name__c = 'test att name.jpg', 
        Registration__c = lr.id,
        //Attachment_URL__c, 
        Description__c = 'test desc', 
        //Object__c, 
        //Record_ID__c = cm.Id, 
        Type__c = 'Unknown', 
        Attorney_Client_Privilege__c = true, 
        Confidential__c = true, 
        Not_Subject_to_PRA__c = true,
        VIP_Form_Section__c = section.id
        );
        insert attPlus1;
        
        
        Attachments_Plus__c attPlus2 = new Attachments_Plus__c(
        Attachment_Name__c = 'test att name.jpg', 
        Registration__c = lr.id,
        //Attachment_URL__c, 
        Description__c = 'test desc', 
        //Object__c, 
        //Record_ID__c = cm.Id, 
        Type__c = 'Subpoena', 
        Attorney_Client_Privilege__c = true, 
        Confidential__c = true, 
        Not_Subject_to_PRA__c = true,
        VIP_Form_Section__c = section.id
        );
        insert attPlus2;
        
        test.startTest();
        
        pageReference pageRef = Page.Attachment_Widget;
        pageRef.getParameters().put('id',lr.id);
        pageRef.getParameters().put('sectionId',section.id);
        pageRef.getParameters().put('attPId',attPlus2.id);
        system.Test.setCurrentPage(pageRef);
        
        Attachment att = new Attachment(
            Body = blob.valueOf('test body'),
            Name = 'testname.jpg',
            isPrivate = false
        );
        
        Attachment att1 = new Attachment(
            Body = blob.valueOf('test body'),
            Name = 'testname.jpg',
            isPrivate = false
        );
        
        Attachment_Widget_Controller controller = new Attachment_Widget_Controller();
        //controller.attTable = new List<Attachment_Widget_Controller.AttachmentTable>();
        
        controller.attTable.add(new Attachment_Widget_Controller.AttachmentTable(false,attPlus1,null,null));
        controller.attTable[1].att = att;
        controller.attTable.add(new Attachment_Widget_Controller.AttachmentTable(false,attPlus2,null,null));
        controller.attTable[2].att = att1;
        controller.attachPDF2();
        //controller.updateAttTable();
        
        pageRef.getParameters().put('delID',attPlus.id);
        controller.deleteAttachment();
        
        test.stopTest();
    
    }  
    
    static testMethod void testAttachment_Widget_Controller1() {
        VIPForm__VIP_Category__c section = new VIPForm__VIP_Category__c();
        section.VIPForm__Name_Displayed__c = 'FLC Card Photo';
        section.VIPForm__Object_API__c = 'License_Registration__c';
        section.VIPForm__Order__c = 300;
        section.RecordtypeId = Schema.SObjectType.VIPForm__VIP_Category__c.getRecordTypeInfosByName().get('VIP Form Section').getRecordTypeId();
        insert section;
        
        Account a = new Account();
        a.Name = 'test account'+system.now();
        insert a;
        
        Contact con = new Contact();
        con.AccountId = a.id;
        con.LastName = 'lastName';
        insert con;
        
        License_Registration__c lr = new License_Registration__c();
        lr.Account__c = a.id;
        lr.Applicant__c = con.id;
        lr.RecordtypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();
        insert lr;
        
        Attachments_Plus__c attPlus = new Attachments_Plus__c(
        Attachment_Name__c = 'test att name', 
        Registration__c = lr.id,
        //Attachment_URL__c, 
        Description__c = 'test desc', 
        //Object__c, 
        //Record_ID__c = cm.Id, 
        Type__c = '', 
        Attorney_Client_Privilege__c = true, 
        Confidential__c = true, 
        Not_Subject_to_PRA__c = true,
        VIP_Form_Section__c = section.id
        );
        insert attPlus;
        
        ContentVersion conVer = new ContentVersion();
        conVer.ContentLocation = 'S';
        conVer.PathOnClient = 'file_name.pdf';
        conVer.Title = 'file_name.pdf';
        conVer.VersionData = blob.valueOf('text file');
        conVer.Origin = 'C';
        insert conVer;
        
        ContentDocumentLink cDe = new ContentDocumentLink();
        cDe.ContentDocumentId = [select id, ContentDocumentId from ContentVersion where id = :conVer.id].ContentDocumentId;
        cDe.LinkedEntityId = attPlus.id;
        cDe.ShareType = 'I';
        cDe.Visibility = 'AllUsers';
        insert cDe;
        
        Attachments_Plus__c attPlus1 = new Attachments_Plus__c(
        Attachment_Name__c = 'test att name', 
        Registration__c = lr.id,
        //Attachment_URL__c, 
        Description__c = 'test desc', 
        //Object__c, 
        //Record_ID__c = cm.Id, 
        Type__c = 'Unknown', 
        Attorney_Client_Privilege__c = true, 
        Confidential__c = true, 
        Not_Subject_to_PRA__c = true,
        VIP_Form_Section__c = section.id
        );
        insert attPlus1;
        
        
        Attachments_Plus__c attPlus2 = new Attachments_Plus__c(
        Attachment_Name__c = 'test att name', 
        Registration__c = lr.id,
        //Attachment_URL__c, 
        Description__c = 'test desc', 
        //Object__c, 
        //Record_ID__c = cm.Id, 
        Type__c = 'Subpoena', 
        Attorney_Client_Privilege__c = true, 
        Confidential__c = true, 
        Not_Subject_to_PRA__c = true,
        VIP_Form_Section__c = section.id
        );
        insert attPlus2;
        
        test.startTest();
        
        pageReference pageRef = Page.Attachment_Widget;
        pageRef.getParameters().put('id',lr.id);
        pageRef.getParameters().put('sectionId',section.id);
        pageRef.getParameters().put('attPId',attPlus.id);
        system.Test.setCurrentPage(pageRef);
        
        Attachment att = new Attachment(
            Body = blob.valueOf('test body'),
            Name = 'testname.pdf',
            isPrivate = false
        );
        
        Attachment att1 = new Attachment(
            Body = blob.valueOf('test body'),
            Name = 'testname.txt',
            isPrivate = false
        );
        
        Attachment_Widget_Controller controller = new Attachment_Widget_Controller();
        //controller.attTable = new List<Attachment_Widget_Controller.AttachmentTable>();
        controller.updateAttTable();
        controller.attTable.add(new Attachment_Widget_Controller.AttachmentTable(false,attPlus1,null,null));
        controller.attTable[1].att = att;
        controller.attTable.add(new Attachment_Widget_Controller.AttachmentTable(false,attPlus2,null,null));
        controller.attTable[2].att = att1;
        controller.attachPDF2();
        //controller.updateAttTable();
        
        pageRef.getParameters().put('delID',attPlus.id);
        controller.deleteAttachment();
        
        test.stopTest();
    
    }  
}