force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <formula>Case_Management__r.Employer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Registration for business / owner / or other individual related to this case.</description>
    <inlineHelpText>Registration for business / owner / or other individual related to this case.</inlineHelpText>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee's manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RegistrationAttachmentTest.cls
@istest
public class RegistrationAttachmentTest {

    public static testMethod void testRegistrationAttachment1(){
    
        Account a = new Account();
        a.Name = 'test account'+system.now();
        insert a;
        
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Test';
        con.Email = 'testLNRDEV@testdir.com';
        insert con;
        
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma;
        
        Id devRecordTypeId = Schema.getGlobalDescribe().get('License_Registration__c').getDescribe().getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();

        License_Registration__c lreg = new License_Registration__c();
        lreg.RecordTypeId = devRecordTypeId;
        lreg.Account__c = a.Id;
        lreg.Applicant__c = con.Id;
        lreg.License_Registration_Number__c = '00023568500';
        insert lreg; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.User__c = UserInfo.getUserId();
        de.Position__c = 'Deputy';
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Case__c cm = new DIR_Case__c();
        cm.Employer__c = a.Id;
        cm.Status__c = 'Open';
        cm.Assigned_Deputy__c = de.Id;
        cm.RecordtypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        insert cm;

        Attachment att = new Attachment(
          Body = blob.valueOf('test body'),
          Name = 'test name',
          isPrivate = false,
          ParentId = cm.Id
        );
        insert att;
    
        Attachments_Plus__c attPlus = new Attachments_Plus__c(
          Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id,
          Registration__c = lreg.Id,
          Registration_Document_Category__c = 'Education', 
          Type__c = '', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );
        insert attPlus;

        

        Attachments_Plus__c attPlus1 = new Attachments_Plus__c(
          Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id, 
          Registration__c = lreg.Id,
          Registration_Document_Category__c = 'Education', 
          Type__c = 'Unknown', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );
        insert attPlus1;
         
       
        Attachments_Plus__c attPlus2 = new Attachments_Plus__c(
          Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id,
          Registration__c = lreg.Id,
          Registration_Document_Category__c = 'Education',  
          Type__c = 'Subpoena', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );

        test.startTest();

        pageReference pageRef = Page.RegistrationAttachment;
        system.Test.setCurrentPage(pageRef);

        ApexPages.currentPage().getParameters().put('category', 'Education');
        
        ApexPages.StandardController sc = new ApexPages.StandardController(lreg);
        RegistrationAttachmentController controller = new RegistrationAttachmentController(sc);
        controller.currentAttRecord = attPlus.Id;
        controller.DummyAttachment.Name = 'test name';
        controller.DummyAttachment.Body = blob.valueOf('test body');
        controller.AttToUpdate.Name = 'test name';
        controller.AttToUpdate.Body = blob.valueOf('test body');
        controller.getAttPlus();
        controller.DisplayAttachment();
        controller.EditAttachment();
        controller.UploadAttachment();
        controller.UpdateRecord();
        
        controller.UploadUpdateAttachment();
        controller.Cancel();
        controller.CancelUpload();
        //controller.fname = att.Name;
        //controller.body = att.Body;
        //controller.newAttPlus = attPlus2;
    }
    
    public static testMethod void testRegistrationAttachment2(){
    
        Account a = new Account();
        a.Name = 'test account'+system.now();
        insert a;
        
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Test';
        con.Email = 'testLNRDEV@testdir.com';
        insert con;
        
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma;
        
        Id devRecordTypeId = Schema.getGlobalDescribe().get('License_Registration__c').getDescribe().getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();

        License_Registration__c lreg = new License_Registration__c();
        lreg.RecordTypeId = devRecordTypeId;
        lreg.Account__c = a.Id;
        lreg.Applicant__c = con.Id;
        lreg.License_Registration_Number__c = '00023568500';
        insert lreg; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.User__c = UserInfo.getUserId();
        de.Position__c = 'Deputy';
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Case__c cm = new DIR_Case__c();
        cm.Employer__c = a.Id;
        cm.Status__c = 'Open';
        cm.Assigned_Deputy__c = de.Id;
        cm.RecordtypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        insert cm;

        
    
        Attachments_Plus__c attPlus = new Attachments_Plus__c(
          //Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id,
          Registration__c = lreg.Id,
          Registration_Document_Category__c = 'Education', 
          Type__c = '', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );
        insert attPlus;

        Attachment att = new Attachment(
          Body = blob.valueOf('test body'),
          Name = 'test name',
          isPrivate = false,
          ParentId = attPlus.Id
        );
        insert att;

        Attachments_Plus__c aplus = [SELECT Id, Attachment_ID__c FROM Attachments_Plus__c WHERE Id=:attPlus.Id];

        Attachments_Plus__c attPlus1 = new Attachments_Plus__c(
          Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id, 
          Registration__c = lreg.Id,
          Registration_Document_Category__c = 'Education', 
          Type__c = 'Unknown', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );
        insert attPlus1;
         
       
        Attachments_Plus__c attPlus2 = new Attachments_Plus__c(
          Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id,
          Registration__c = lreg.Id,
          Registration_Document_Category__c = 'Education',  
          Type__c = 'Subpoena', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );

        test.startTest();

        pageReference pageRef = Page.RegistrationAttachment;
        system.Test.setCurrentPage(pageRef);

        ApexPages.currentPage().getParameters().put('category', 'Education');
        
        ApexPages.StandardController sc = new ApexPages.StandardController(lreg);
        RegistrationAttachmentController controller = new RegistrationAttachmentController(sc);
        controller.currentAttRecord = attPlus.Id;
        
        controller.getAttPlus();
        controller.DisplayAttachment();
        controller.EditAttachment();
        controller.DummyAttachment.Name = 'test name';
        controller.DummyAttachment.Body = blob.valueOf('test body');
        controller.AttToUpdate.Name = 'test name';
        controller.AttToUpdate.Body = blob.valueOf('test body');
        controller.UploadAttachment();
        controller.UpdateRecord();
        
        controller.UploadUpdateAttachment();
        controller.Cancel();
        controller.CancelUpload();
        //controller.fname = att.Name;
        //controller.body = att.Body;
        //controller.newAttPlus = attPlus2;
    }
}