force-app/main/default/objects/Account/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Labor Code requires that an owner submit the application or have knowledge of the application. If you are not the owner, then a Power of Attorney must be provided with the certification.</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Bookkeeper</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Formula field to migrate the Case Number from the Case to the Case Role object for use in an email template (auto response to Claim Form being submitted).</description>
    <formula>Case__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</description>
    <inlineHelpText>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Roles</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Roles that related accounts have on a case</description>
    <inlineHelpText>Select the role played by this related account</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Agent for Service of Process</fullName>
            </value>
            <value>
                <fullName>Aggrieved</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Attorney for Defendant</fullName>
            </value>
            <value>
                <fullName>Attorney for Plaintiff</fullName>
            </value>
            <value>
                <fullName>Attorney Representative</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Brand Guarantor</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Case Employer</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Claimant Advocate</fullName>
            </value>
            <value>
                <fullName>Claimant Assignee</fullName>
            </value>
            <value>
                <fullName>Claimant Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Guardian</fullName>
            </value>
            <value>
                <fullName>Claimant Minor</fullName>
            </value>
            <value>
                <fullName>Claimant Other</fullName>
            </value>
            <value>
                <fullName>Claimant Representative</fullName>
            </value>
            <value>
                <fullName>Client Employer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Contractor Successor</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Online_Claim_Account__c.field-meta.xml
<CustomField>
    <fullName>Online_Claim_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Online Claim Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Online Claim Account)</relationshipLabel>
    <relationshipName>Online_Claim_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Bookkeeper</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OWCThirdPartyValidationCheckerController.cls
public class OWCThirdPartyValidationCheckerController {
    public static void validateMeetingAPIResponse(String caseNumber, String claimantLastName, String communityUserId){
        if(String.isNotBlank(caseNumber) && String.isNotBlank(communityUserId)){
            List<User> userObj = [SELECT Id, accountId FROM User WHERE Id =: communityUserId];
            List<DIR_Case__c> caseObj = [SELECT Id, Name, Case_Number__c, Online_Claim_Account__c FROM DIR_Case__c
                                   WHERE Case_Number__c =: caseNumber LIMIT 1];
            System.debug('userObj:::'+userObj);
            System.debug('caseObj::::'+caseObj);
            if(caseObj != null && caseObj.size() > 0){
                OWCThirdPartyFileUploadWebService.fieldValidationError = ThirdPartyErrorMsgConstants.caseNumberErrorMsg(caseNumber);
                return;
            }
            else if(userObj != null && userObj.size() > 0 && caseObj.size() > 0 && caseObj[0].Online_Claim_Account__c != userObj[0].accountId){
                OWCThirdPartyFileUploadWebService.fieldValidationError = ThirdPartyErrorMsgConstants.COMMUNITY_USER_ID_MSG;
                return;
            }
        }
        if(String.isBlank(communityUserId)){
            ThirdPartyMeetingDetailsWebService.fieldValidationError = ThirdPartyErrorMsgConstants.COMMUNITY_USER_ID_MSG;
            return;
        }
        else if(String.isNotBlank(communityUserId)){
            List<User> userObj = [SELECT Id, accountId FROM User WHERE Id =: communityUserId];
            if(userObj == null || userObj.size() == 0){
                ThirdPartyMeetingDetailsWebService.fieldValidationError = ThirdPartyErrorMsgConstants.COMMUNITY_USER_ID_MSG;
                return;
            }
        }
        if(String.isNotBlank(caseNumber)){
            List<DIR_Case__c> cases = [SELECT Id, Case_Number__c FROM DIR_Case__c WHERE Case_Number__c =: caseNumber];
            if(cases == null || cases.size() == 0){
                ThirdPartyMeetingDetailsWebService.fieldValidationError = ThirdPartyErrorMsgConstants.caseNumberErrorMsg(caseNumber);
                return;
            }
        }
        if(String.isNotBlank(claimantLastName)){
            List<Case_Role__c> caseRoles = [SELECT Id, Name, Case__c, Entity__c, Role__c FROM Case_Role__c 
                                            WHERE Role__c = 'Claimant' AND Entity__r.LastName =: claimantLastName];
            if(caseRoles == null || caseRoles.size() == 0){ 
                ThirdPartyMeetingDetailsWebService.fieldValidationError = ThirdPartyErrorMsgConstants.claimantLastNameErrorMsg(caseNumber, claimantLastName);
                return;
            }
        }
    }
    
    public static void validateCCAPIResponse(String caseNumber, String communityUserId){
        /**if( 1 == 1){
            return;
        }**/
        
        System.debug('caseNumber:::'+caseNumber);
        System.debug('Query:::'+ [SELECT Id, Name, Case_Number__c, Online_Claim_Account__c FROM DIR_Case__c ]);
        
        if(String.isNotBlank(caseNumber) && String.isNotBlank(communityUserId)){
            List<User> userObj = [SELECT Id, accountId FROM User WHERE Id =: communityUserId];
            DIR_Case__c caseObj = [SELECT Id, Name, Case_Number__c, Online_Claim_Account__c FROM DIR_Case__c
                                   WHERE Case_Number__c =: caseNumber LIMIT 1];
            if(userObj != null && userObj.size() > 0 && caseObj.Online_Claim_Account__c != userObj[0].accountId){
                OWCThirdPartyFileUploadWebService.fieldValidationError = ThirdPartyErrorMsgConstants.COMMUNITY_USER_ID_MSG;
                return;
            }
        }
        //Check whether community user id is valid or not
        if(String.isBlank(communityUserId)){
            OWCThirdPartyFileUploadWebService.fieldValidationError = ThirdPartyErrorMsgConstants.COMMUNITY_USER_ID_MSG;
            return;
        }
        else if(String.isNotBlank(communityUserId)){
            List<User> userObj = [SELECT Id, accountId FROM User WHERE Id =: communityUserId];
            if(userObj == null || userObj.size() == 0){
                OWCThirdPartyFileUploadWebService.fieldValidationError = ThirdPartyErrorMsgConstants.COMMUNITY_USER_ID_MSG;
                return;
            }
        }
        if(String.isNotBlank(caseNumber)){
            List<DIR_Case__c> cases = [SELECT Id, Case_Number__c FROM DIR_Case__c WHERE Case_Number__c =: caseNumber];
            System.debug('cases:::'+cases);
            if(cases == null || cases.size() == 0){
                OWCThirdPartyFileUploadWebService.fieldValidationError = ThirdPartyErrorMsgConstants.caseNumberErrorMsg(caseNumber);
                return;
            }
        }
    }
    
    public static void dateFormatChecker(String dateValue, String errorMsg){
        try{
            Date d = Date.valueOf(dateValue);            
        }
        catch(TypeException ex){
            OnlineWageClaimThirdPartyAPIController.fieldMissingMsg = errorMsg;
        }
    }
}