force-app/main/default/objects/Account/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Labor Code requires that an owner submit the application or have knowledge of the application. If you are not the owner, then a Power of Attorney must be provided with the certification.</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Bookkeeper</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Associated_Agents__c/Associated_Agents__c.object-meta.xml
<CustomObject>
    <label>Associated Agents</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Associated Agents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Agents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Agents</relationshipLabel>
    <relationshipName>Associated_Agents1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Agents__c/fields/Associated_Account__c.field-meta.xml
<CustomField>
    <fullName>Associated_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Agents (Associated Account)</relationshipLabel>
    <relationshipName>Associated_Agents2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Agents__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Check this field if relationship occurs. Otherwise, uncheck this field and provide the Inactive relationship reason.</inlineHelpText>
    <label>Relationship Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Associated_Agents__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent for Service</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Employer Representative</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Associated_Agents_Type_Inverse__mdt/Associated_Agents_Type_Inverse__mdt.object-meta.xml
<CustomObject>
    <label>Associated Agents Type Inverse</label>
    <pluralLabel>Associated Agents Type Inverse</pluralLabel>
</CustomObject>

force-app/main/default/objects/Associated_Agents_Type_Inverse__mdt/fields/Current_Type__c.field-meta.xml
<CustomField>
    <fullName>Current_Type__c</fullName>
    <label>Current Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Agents_Type_Inverse__mdt/fields/Inverse_Type__c.field-meta.xml
<CustomField>
    <fullName>Inverse_Type__c</fullName>
    <label>Inverse Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Case_Role_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Role_Status__c</fullName>
    <description>For requirement 33146; allows users to quickly view the status of related case roles to a given case record.</description>
    <label>Case Role Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>ODA - Defendant</fullName>
            </value>
            <value>
                <fullName>ODA - Plaintiff</fullName>
            </value>
            <value>
                <fullName>ODA by Settlement</fullName>
            </value>
            <value>
                <fullName>Dismissal - Claimant</fullName>
            </value>
            <value>
                <fullName>Dismissal - Deputy</fullName>
            </value>
            <value>
                <fullName>Dismissal - Ineffective service</fullName>
            </value>
            <value>
                <fullName>No Longer Active On Case</fullName>
            </value>
            <value>
                <fullName>De Novo Appeal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</description>
    <inlineHelpText>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Roles</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Roles that related accounts have on a case</description>
    <inlineHelpText>Select the role played by this related account</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Agent for Service of Process</fullName>
            </value>
            <value>
                <fullName>Aggrieved</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Attorney for Defendant</fullName>
            </value>
            <value>
                <fullName>Attorney for Plaintiff</fullName>
            </value>
            <value>
                <fullName>Attorney Representative</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Brand Guarantor</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Case Employer</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Claimant Advocate</fullName>
            </value>
            <value>
                <fullName>Claimant Assignee</fullName>
            </value>
            <value>
                <fullName>Claimant Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Guardian</fullName>
            </value>
            <value>
                <fullName>Claimant Minor</fullName>
            </value>
            <value>
                <fullName>Claimant Other</fullName>
            </value>
            <value>
                <fullName>Claimant Representative</fullName>
            </value>
            <value>
                <fullName>Client Employer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Contractor Successor</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Defendant Attorney</fullName>
            </value>
            <value>
                <fullName>Defendant Representative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssociatedAgentsTriggerHandler.cls
public class AssociatedAgentsTriggerHandler {
    Public static Boolean isFirstTime = true;
    public static void beforeInsertOperation(List<Associated_Agents__c> newRecords){
        Set<Id> accountIsSet = new Set<Id>();
        //pupulate the description on the new records
        for(Associated_Agents__c agent: newRecords){
            if(agent.Account__c != null && agent.Associated_Account__c != null){
                accountIsSet.add(agent.Account__c);
                accountIsSet.add(agent.Associated_Account__c);
                
            }
        }
       	Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Name FROM Account WHERE Id IN: accountIsSet]);
        //pupulate the description on the new records
        for(Associated_Agents__c agent: newRecords){
            if(agent.Account__c != null && agent.Associated_Account__c != null){
                agent.Description__c = accountMap.get(agent.Associated_Account__c ).Name + ' is the '+agent.Type__c +' for '+accountMap.get(agent.Account__c).Name;
            }
        }
    }
    
    public static void afterInsertOperation(List<Associated_Agents__c> newRecords){
        List<Associated_Agents__c> AssociatedAgentsList = new List<Associated_Agents__c>();
        Set<Id> accountIds = new Set<Id>();
        Set<Id> associatedAccountIds = new Set<Id>();
        Map<Id, Set<Id>> associatedAccountWithAccountId = new Map<Id, Set<Id>>();
        createInverseAssociatedAgents(newRecords);
        for(Associated_Agents__c agent: newRecords){
            if(agent.Relationship_Status__c && (agent.Type__c == 'Agent for Service' || agent.Type__c == 'Attorney' || agent.Type__c == 'Employer Representative')){
                AssociatedAgentsList.add(agent);
                accountIds.add(agent.Account__c);
                if(associatedAccountWithAccountId.containsKey(agent.Associated_Account__c)){
                    associatedAccountWithAccountId.get(agent.Associated_Account__c).add(agent.Account__c);
                }else{
                    associatedAccountWithAccountId.put(agent.Associated_Account__c, new Set<Id>{agent.Account__c});
                }
                associatedAccountIds.add(agent.Associated_Account__c);
            }
        }
        if(AssociatedAgentsList.size() >0)	{
            creteCaseRoleForAssociatedAccount(AssociatedAgentsList, accountIds,associatedAccountWithAccountId, associatedAccountIds);
        }		
    }
    /**********************************************************
    *Method Name : createInverseAssociatedAgents
    *Description : it would create the inverse RBO whenever the rbo is created.
    **/
    public static void createInverseAssociatedAgents(List<Associated_Agents__c> associatedAgentsList){
        List<Associated_Agents__c> inverseAssociatedAgentsList = new List<Associated_Agents__c>();
        for(Associated_Agents__c associatedAgents : associatedAgentsList){
            inverseAssociatedAgentsList.add(createInverseAssociatedAgentsRecord(associatedAgents));
        }
        if(inverseAssociatedAgentsList.size() > 0){
            insert inverseAssociatedAgentsList;
        }
    }
    
    /***********************************************************
	*Method Name : createInverseAssociatedAgentsRecord
	*Description : calling from the 'createInverseAssociatedAgents' which will create the individual inverse relationship. 
	**/
    public static Associated_Agents__c createInverseAssociatedAgentsRecord(Associated_Agents__c associatedAgents){
        Map<String,String> associatedAgentsInverseMap = new Map<String,String>();
       
        for(Associated_Agents_Type_Inverse__mdt inverseMap : Associated_Agents_Type_Inverse__mdt.getall().values()){
            associatedAgentsInverseMap.put(inverseMap.Current_Type__c,inverseMap.Inverse_Type__c);
        }
        Associated_Agents__c aa = new Associated_Agents__c();
        //aa.Name__c = associatedAgents.Name__c;
        aa.Associated_Account__c = associatedAgents.Account__c;
        aa.Account__c = associatedAgents.Associated_Account__c;
        //aa.Additional_information__c = associatedAgents.Additional_information__c;
        if(associatedAgentsInverseMap.containskey(associatedAgents.Type__c)){
            aa.Type__c = associatedAgentsInverseMap.get(associatedAgents.Type__c);
        } 
        return aa;
    }
    //creteCaseRoleForAssociatedAccount
    private static void creteCaseRoleForAssociatedAccount(List<Associated_Agents__c> AssociatedAgentsList,Set<Id> accountIds, Map<Id, Set<Id>> associatedAccountWithAccountId, set<Id> associatedAccountIds){
        List<Case_Role__c> caseRolesToInsert = new List<Case_Role__c>();
        List<Case_Note__c> caseNotesToInsert = new List<Case_Note__c>(); 
        Set<String> CasewithAccountId = new Set<String>();
        Set<String> agentsToIgnore = new Set<String>();
        Map<Id, Set<Id>> CaseWithAccountMap = new Map<Id, Set<Id>>();
        Map<Id, Set<Id>> caseWithAssociatedMap = new Map<Id, Set<Id>>();
        
        for(Case_Role__c  caseRole : [select Id,Case__c ,Entity__c from Case_Role__c  
                                      where Role__c != null
                                      and Entity__c In:accountIds 
                                      and (Case__r.Status__c != 'Closed' and Case_Role_Status__c != 'No Longer Active On Case')])
        {	
            CasewithAccountId.add(caseRole.Case__c+''+caseRole.Entity__c);
            if(CaseWithAccountMap.containsKey(caseRole.Entity__c)){
                CaseWithAccountMap.get(caseRole.Entity__c).add(caseRole.Case__c);
            }else{
                CaseWithAccountMap.put(caseRole.Entity__c, new Set<Id>{caseRole.Case__c});
            } 
        }
        system.debug('CaseWithAccountMap: '+CaseWithAccountMap);
        //identify the case where the Associated Account is already added as Case Role
        for(Case_Role__c  caseRole : [select Id,Case__c ,Entity__c from Case_Role__c  
                                      where Case__c Not IN: CaseWithAccountMap.keySet()
                                      and Entity__c In:associatedAccountIds 
                                      and (Case__r.Status__c != 'Closed' and Case_Role_Status__c != 'No Longer Active On Case')])
        {
            for(String accountId: associatedAccountWithAccountId.get(caseRole.Entity__c))
            {
                if(CasewithAccountId.contains(caseRole.Case__c+accountId)){
                    agentsToIgnore.add(accountId+''+caseRole.Entity__c+''+caseRole.Case__c);
                }
            }                             
        }
        system.debug('agentsToIgnore: '+agentsToIgnore);
        for(Associated_Agents__c agent: AssociatedAgentsList){
            if(CaseWithAccountMap.containsKey(agent.Account__c)){
                for(String caseId: CaseWithAccountMap.get(agent.Account__c)){
                    if(!agentsToIgnore.contains(agent.Account__c+''+agent.Associated_Account__c+''+caseId)){
                        //create the Case Role and Case Note for the Associated Account
                        caseRolesToInsert.add(createCaseRole(caseId, agent));
                        //String notes = 'caseId';
                        //caseNotesToInsert.add(createCaseNote(caseId, notes));
                    }
                }
            }
        }
        system.debug('caseRolesToInsert: '+caseRolesToInsert);
        if(caseRolesToInsert.size() >0) 	insert caseRolesToInsert;
    }
    
    private static Case_Role__c createCaseRole(String CaseId, Associated_Agents__c agent){
        Map<String, String> roleValuesMap = new Map<String, String>{'Agent for Service'=>'Agent for Service of Process','Attorney'=> 'Defendant Attorney','Employer Representative'=> 'Defendant Representative'};          
        Case_Role__c caseRole = new Case_Role__c();
        caseRole.Entity__c = agent.Associated_Account__c;
        caseRole.Case__c = CaseId;
        caseRole.Role__c  = roleValuesMap.get(agent.Type__c);
        caseRole.Also_Related_To__c = agent.Account__c;
        caseRole.Relationship_to_Claimant__c = roleValuesMap.get(agent.Type__c) + ' for';
        caserole.RecordTypeId = OWCConstants.WCA_CASE_ROLE_RECORD_TYPE_ID;
        return caseRole;
    }
    /*
	*   Method Name : createCaseNotes
	*   Description : 
	**/
    public static Case_Note__c createCaseNote(Id CaseId, string caseNote){
        Case_Note__c caseNoteObj = new Case_Note__c();
        caseNoteObj.Event_Note__c = caseNote;
        caseNoteObj.Case_Management__c = CaseId;
        caseNoteObj.Event_Date_Time__c = datetime.now();
        return caseNoteObj;
    }
}