force-app/main/default/objects/Account/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Labor Code requires that an owner submit the application or have knowledge of the application. If you are not the owner, then a Power of Attorney must be provided with the certification.</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Bookkeeper</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Note__c/Case_Note__c.object-meta.xml
<CustomObject>
    <description>Case Notes and Events that correspond to Case Management.</description>
    <label>Case Note</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Case Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Note__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Notes</relationshipLabel>
    <relationshipName>Case_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Note__c/fields/Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_Time__c</fullName>
    <defaultValue>DATETIMEVALUE(NOW())</defaultValue>
    <label>Event Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Note__c/fields/Event_Note__c.field-meta.xml
<CustomField>
    <fullName>Event_Note__c</fullName>
    <label>Event Note</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Related_Business_Type_Inverse__c/Related_Business_Type_Inverse__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Related Business Type Inverse</label>
</CustomObject>

force-app/main/default/objects/Related_Business_Type_Inverse__c/fields/Current_Type__c.field-meta.xml
<CustomField>
    <fullName>Current_Type__c</fullName>
    <label>Current Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Business_Type_Inverse__c/fields/Inverse_Type__c.field-meta.xml
<CustomField>
    <fullName>Inverse_Type__c</fullName>
    <label>Inverse Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/Related_Businesses__c.object-meta.xml
<CustomObject>
    <label>Related Business</label>
    <nameField>
        <displayFormat>RBO-{00000000}</displayFormat>
        <label>Related Businesses Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Businesses__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>Used to track the additional notes related to the Related business</description>
    <label>Additional Information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to store business Account for the Rbo record</description>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Business)</relationshipLabel>
    <relationshipName>Related_Businessess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Related Business)</relationshipLabel>
    <relationshipName>Related_Businessess1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alter Ego</fullName>
            </value>
            <value>
                <fullName>LC 238 (Related Business)</fullName>
            </value>
            <value>
                <fullName>Parent Company</fullName>
            </value>
            <value>
                <fullName>Predecessor</fullName>
            </value>
            <value>
                <fullName>Single Enterprise</fullName>
            </value>
            <value>
                <fullName>Subsidiary</fullName>
            </value>
            <value>
                <fullName>Successor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>Used for the read only access for business, Related Business and Related Business Name.</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Related_Party__c/Related_Party__c.object-meta.xml
<CustomObject>
    <label>Related Party</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Related Party  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Parties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Party__c/fields/Business_account__c.field-meta.xml
<CustomField>
    <fullName>Business_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>used to store the business account</description>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Parties</relationshipLabel>
    <relationshipName>Related_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Related Parties</relationshipLabel>
    <relationshipName>Related_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Party__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Agent for Service of Process</fullName>
            </value>
            <value>
                <fullName>Aggrieved</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Attorney for Defendant</fullName>
            </value>
            <value>
                <fullName>Attorney for Plaintiff</fullName>
            </value>
            <value>
                <fullName>Attorney Representative</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Case Employer</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Claimant Advocate</fullName>
            </value>
            <value>
                <fullName>Claimant Attorney</fullName>
            </value>
            <value>
                <fullName>Claimant Guardian</fullName>
            </value>
            <value>
                <fullName>Claimant Minor</fullName>
            </value>
            <value>
                <fullName>Claimant Representative</fullName>
            </value>
            <value>
                <fullName>Client Employer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Contractor Successor</fullName>
            </value>
            <value>
                <fullName>Corporate Officer</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Defendant - (Restitution)</fullName>
            </value>
            <value>
                <fullName>Defendant - Agent for Service</fullName>
            </value>
            <value>
                <fullName>Defendant Attorney</fullName>
            </value>
            <value>
                <fullName>Potentially Liable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Party__c/recordTypes/Potential_Defendant.recordType-meta.xml
<RecordType>
    <fullName>Potential_Defendant</fullName>
    <active>true</active>
    <label>Potential Defendant</label>
</RecordType>

force-app/main/default/classes/RelatedBusinessTriggerHelper.cls
/*
* Class Name :- RelatedBusinessTriggerHelper
* Description :- This class is used to check the duplicacy of Related Business record, used to assign addition notes and to create related party object when a new record is created.
**/
public class RelatedBusinessTriggerHelper {
    public static void beforeInsert(List<Related_Businesses__c> relatedBusinessesList){
        checkDuplicateRelatedBusinesses(relatedBusinessesList);
    }
    public static void afterInsert(List<Related_Businesses__c> relatedBusinessesList){
        System.debug('relatedBusinessesList::'+relatedBusinessesList);
        if(DirUtils.isFirstTime){
            DirUtils.isFirstTime = false;
            createInverseRelatedBusinesses(relatedBusinessesList);
        }
        createRelatedParty(relatedBusinessesList);
    }
    /*
*   Method Name : afterUpdate
*   Description : it would update the type or corresponding Related business record(inverse)
**/
    public static void afterUpdate(List<Related_Businesses__c> newRelatedBusinessesList, Map<Id,Related_Businesses__c> oldRelatedBusinessMap){
        if(DirUtils.isFirstTime){
                DirUtils.isFirstTime = false;
            updateRelatedBusinessRecords(newRelatedBusinessesList, oldRelatedBusinessMap);
        }
    }
    public static void updateRelatedBusinessRecords(List<Related_Businesses__c> newRelatedBusinessesList, Map<Id,Related_Businesses__c> oldRelatedBusinessMap){
        Set<Id> businessIdSet = new Set<Id>();
        Set<Id> relatedBusinessIdSet = new Set<Id>();
        for(Related_Businesses__c relatedBusinessObj : newRelatedBusinessesList){
            if(relatedBusinessObj.Type__c != oldRelatedBusinessMap.get(relatedBusinessObj.Id).Type__c){
                businessIdSet.add(relatedBusinessObj.Business__c);
                relatedBusinessIdSet.add(relatedBusinessObj.Related_Business__c);
            }
        }
        if(businessIdSet.size() > 0 || relatedBusinessIdSet.size() > 0 ){
            Map<Id,Related_Businesses__c> relatedBusinessesMap = new Map<Id,Related_Businesses__c>([SELECT Business__c, Related_Business__c, Type__c FROM Related_Businesses__c
                                                                                                    WHERE Business__c =: relatedBusinessIdSet AND Related_Business__c =: businessIdSet]);
            if(relatedBusinessesMap.size() > 0){
                Map<String,String> relatedBusinessInverseMap = new Map<String,String>();
                for(Related_Business_Type_Inverse__c inverseMap : Related_Business_Type_Inverse__c.getall().values()){
                    relatedBusinessInverseMap.put(inverseMap.Current_Type__c,inverseMap.Inverse_Type__c);
                }
                for(Related_Businesses__c relatedBusiness : newRelatedBusinessesList){
                    if(relatedBusiness.Type__c != oldRelatedBusinessMap.get(relatedBusiness.Id).Type__c){
                        for(Id rbMap : relatedBusinessesMap.keySet()){
                            if(relatedBusinessesMap.get(rbMap).Business__c == relatedBusiness.Related_Business__c && relatedBusinessesMap.get(rbMap).Related_Business__c == relatedBusiness.Business__c){
                                relatedBusinessesMap.get(rbMap).Type__c = relatedBusinessInverseMap.get(relatedBusiness.Type__c);
                            }
                        }
                    }
                }
                update relatedBusinessesMap.values();
            }
        }
    }
    
    
    /*
*   Method Name : checkDuplicateRelatedBusinesses
*   Description : it would check for the duplicate related business record and update the name and additionalInformation field on newly created RBO
**/
    public static void checkDuplicateRelatedBusinesses(List<Related_Businesses__c> relatedBusinessesList){
        Set<Id> businessIdsSet = new Set<Id>();
        Set<Id> relatedBusinessIdsSet = new Set<Id>();
        Set<Id> allAccountIdsSet = new Set<Id>();
        Map<Id,Id> businessWithRelatedBusinessMap = new Map<Id,Id>();
        for(Related_Businesses__c relatedBusiness : relatedBusinessesList){
            if(relatedBusiness.Business__c != null && relatedBusiness.Related_Business__c != null){
                businessIdsSet.add(relatedBusiness.Business__c);
                relatedBusinessIdsSet.add(relatedBusiness.Related_Business__c);
                allAccountIdsSet.add(relatedBusiness.Business__c);
                allAccountIdsSet.add(relatedBusiness.Related_Business__c);
            }
        }
        
        //checking for duplicate RBO
        List<Related_Businesses__c> relatedBusinessDuplicateList = DirQuerySelector.getDuplicateRelatedBusinessRecord(businessIdsSet,relatedBusinessIdsSet);
        for(Related_Businesses__c relatedBusiness : relatedBusinessesList){
            for(Related_Businesses__c duplicateRelatedBusiness : relatedBusinessDuplicateList){
                if(duplicateRelatedBusiness.Business__c == relatedBusiness.Business__c && duplicateRelatedBusiness.Related_Business__c == relatedBusiness.Related_Business__c){
                    relatedBusiness.addError('Related Business Record Already Exists');
                }
            }
        }
        
        // updating the Name 
        Map<Id,Account> accountNameMap = DirQuerySelector.getAccountNames(allAccountIdsSet);
        for(Related_Businesses__c relatedBusiness : relatedBusinessesList){
            relatedBusiness.Name__c = accountNameMap.get(relatedBusiness.Business__c).Name +' - '+ accountNameMap.get(relatedBusiness.Related_Business__c).Name;
        } 
    }
    
    /*
*   Method Name : createInverseRelatedBusinesses
*   Description : it would create the inverse RBO whenever the rbo is created.
**/
    public static void createInverseRelatedBusinesses(List<Related_Businesses__c> relatedBusinessesList){
        List<Related_Businesses__c> inverseRelatedBusinessesList = new List<Related_Businesses__c>();
        for(Related_Businesses__c relatedBusiness : relatedBusinessesList){
            inverseRelatedBusinessesList.add(createInverseRelatedBusinessRecord(relatedBusiness));
        }
        if(inverseRelatedBusinessesList.size() > 0){
            insert inverseRelatedBusinessesList;
        }
    }
    
    /*
*   Method Name : createInverseRelatedBusinessRecord
*   Description : calling from the 'createInverseRelatedBusinesses' which will create the individual inverse relationship. 
**/
    public static Related_Businesses__c createInverseRelatedBusinessRecord(Related_Businesses__c relatedBusiness){
        Map<String,String> relatedBusinessInverseMap = new Map<String,String>();
        for(Related_Business_Type_Inverse__c inverseMap : Related_Business_Type_Inverse__c.getall().values()){
            relatedBusinessInverseMap.put(inverseMap.Current_Type__c,inverseMap.Inverse_Type__c);
        }
        Related_Businesses__c rbo = new Related_Businesses__c();
        rbo.Name__c = relatedBusiness.Name__c;
        rbo.Related_Business__c = relatedBusiness.Business__c;
        rbo.Business__c = relatedBusiness.Related_Business__c;
        rbo.Additional_information__c = relatedBusiness.Additional_information__c;
        if(relatedBusinessInverseMap.containskey(relatedBusiness.Type__c)){
            rbo.Type__c = relatedBusinessInverseMap.get(relatedBusiness.Type__c);
        } 
        return rbo;
    }
    
    /*
*   Method Name : createRelatedParty
*   Description : it would create the Relaed party once any of account having case role,then it would create related party with 
case management id of the case role account that has role and business name of that account that doesn't have case role
and with the type potentialy liable and record type potential defendant.
**/
    public static void createRelatedParty(List<Related_Businesses__c> relatedBusinessesList){
        Set<Id> allAccountIdsSet = new Set<Id>();
        Set<Id> businessIdsSet = new Set<Id>();
        Set<Id> relatedBusinessIdSet = new Set<Id>();
        Map<string,Set<string>> businessWithRbMap = new Map<string,Set<string>>();
        for(Related_Businesses__c relatedBusiness : relatedBusinessesList){
            relatedBusinessIdSet.add(relatedBusiness.Related_Business__c);
            //businessWithRbMap.put(relatedBusiness.Business__c+'+'+relatedBusiness.Related_Business__c,relatedBusiness.Related_Business__c);
            if(businessWithRbMap.containsKey(relatedBusiness.Related_Business__c)){
                businessWithRbMap.get(relatedBusiness.Related_Business__c).add(relatedBusiness.Business__c);
            }else{
                businessWithRbMap.put(relatedBusiness.Related_Business__c,new Set<String>{relatedBusiness.Business__c});
            }
            allAccountIdsSet.add(relatedBusiness.Related_Business__c);
            allAccountIdsSet.add(relatedBusiness.Business__c);
        }
        //used to store the Account name(Business and related Business)
        Map<Id,Account> accountNameMap = DirQuerySelector.getAccountNames(allAccountIdsSet);
        //used to store the caseid related to case role acccount
        Map<ID,Set<ID>> caseRoleMap = DirQuerySelector.checkCaseRoleForRelatedParty(businessWithRbMap);
        // system.debug('relatedPartyMap:::'+relatedPartyMap);
        List<Related_Party__c> relatedPartyList = new List<Related_Party__c>();
        List<Case_Note__c> caseNoteList = new List<Case_Note__c>();
        
        for(Related_Businesses__c relatedBusiness : relatedBusinessesList){
            Related_Party__c relatedParty = new Related_Party__c();
            //checking if related business is created from case management then created related party against it.
            if(caseRoleMap.size() > 0 && caseRoleMap.containsKey(relatedBusiness.Related_Business__c)){
                for(Id accId : caseRoleMap.keySet()){
                    for(Id caseId : caseRoleMap.get(accId)){
                        relatedPartyList.add(createRelatedPartyRecord(caseId ,accountNameMap.get(relatedBusiness.Related_Business__c).Name , relatedBusiness.Related_Business__c));
                        //creating case notes
                        String caseNote = 'A potential related business has been identified: '+accountNameMap.get(relatedBusiness.Business__c).Name+'  may be related to '+accountNameMap.get(relatedBusiness.Related_Business__c).Name+' as a '+relatedBusiness.Type__c+'. (See Related Parties list.) You may wish to add '+accountNameMap.get(relatedBusiness.Related_Business__c).Name+' as a defendant in this case.';
                        caseNoteList.add(createCaseNote(caseId, caseNote));
                    }
                    
                }
            }
            if(relatedPartyList.size() > 0){
                insert relatedPartyList;
            }
            if(caseNoteList.size() > 0){
                insert caseNoteList;
            }
        }
    }
    
    /*
*   Method Name : createRelatedPartyRecord
*   Description : calling from 'createRelatedParty' this method used for creating individual related party
**/
    public static Related_Party__c createRelatedPartyRecord(Id CaseId, String BusinessName,Id relatedBusinessId ){
        Related_Party__c relatedParty = new Related_Party__c();
        relatedParty.Case_Management__c = CaseId; //case management id
        relatedParty.Business_Name__c = BusinessName; // account name
        relatedParty.Business_account__c = relatedBusinessId;
        relatedParty.Found_Account_ID__c  = relatedBusinessId;
        relatedParty.Role__c = 'Potentially Liable';
        // assigning potential defendant record type
        relatedParty.RecordTypeId = Schema.SObjectType.Related_Party__c.getRecordTypeInfosByDeveloperName().get('Potential_Defendant').getRecordTypeId();
        return relatedParty;
        
    }
    /*
*   Method Name : createCaseNotes
*   Description : 
**/
    public static Case_Note__c createCaseNote(Id CaseId, string caseNote){
        Case_Note__c caseNoteObj = new Case_Note__c();
        caseNoteObj.Event_Note__c = caseNote;
        caseNoteObj.Case_Management__c = CaseId;
        caseNoteObj.Event_Date_Time__c = datetime.now();
        return caseNoteObj;
    }
    
}