force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Number_of_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attachments__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Populated via dlrs</description>
    <label>Number of Attachments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/updateExistingRegForCheckBox.cls
global class updateExistingRegForCheckBox implements Database.Batchable<sObject> {
    
        global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id FROM Attachments_Plus__c WHERE Attachment_Required__c =TRUE AND (Number_of_Attachments__c = 0 OR Number_of_Attachments__c = NULL)' 
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Attachments_Plus__c> scope){
        
        update scope;
           
    }
    
    global void finish(Database.BatchableContext bc){
        
    }    

}