force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Reg_Related_Rec_Id__c.field-meta.xml
<CustomField>
    <fullName>Reg_Related_Rec_Id__c</fullName>
    <description>Registration Related Record Id. This field is used by Registration Services to store the related Registration record.</description>
    <externalId>true</externalId>
    <label>Reg Related Rec Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DBA__c/DBA__c.object-meta.xml
<CustomObject>
    <label>DBA</label>
    <nameField>
        <label>DBA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DBAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DBA__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>DBAs</relationshipLabel>
    <relationshipName>DBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DBA__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <formula>TEXT( Registration__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DbaAllHandler.cls
public class DbaAllHandler {
    
/********************************************************************************************************
Name:  DbaAllHandler.cls

Trigger: DbaTrigger.trigger
Test class: LicenseRegistrationAllTest.cls

Behavior: 
updateDbaName() 
When the user updates the dba name, update the attachment, Attachments_Plus__c, as well.

deleteDBA()
When the user deletes the dba, the attachment, Attachments_Plus__c, should also be deleted.  

********************************************************************************************************/
    
    private static DbaAllHandler classInstance = null;
    public Boolean stopRecursion {get; set;}
    
    private dbaAllHandler() {
        stopRecursion = FALSE;
    }
    
    public static DbaAllHandler getInstance(){
        if (null == classInstance) {
            classInstance = new dbaAllHandler();
        }
        return classInstance;
    }
    
    public void onBeforeInsert(List<DBA__c> newList){ 
    }
    
    public void onAfterInsert(List<DBA__c> newList , Map<id, DBA__c> newMap){  
    }
    
    public void onBeforeUpdate(List<DBA__c> newList, Map<id, DBA__c> newMap, Map<id, DBA__c> oldMap){
        if(stopRecursion == null || !stopRecursion)
        {
            stopRecursion = TRUE;
            updateDbaName(newList); 
            stopRecursion = FALSE;
        }
    }
    
    public void onAfterUpdate(List<DBA__c> newList, Map<id, DBA__c> newMap, Map<id, DBA__c> oldMap){  
    }
    
    public void onBeforeDelete(List<DBA__c> oldList, Map<id, DBA__c> oldMap){
        
        if(stopRecursion == null || !stopRecursion)
        {
            stopRecursion = TRUE;
            deleteDBA(oldList);
            stopRecursion = FALSE;
        }
    }
    
    public void onAfterDelete(list<DBA__c> oldList, Map<id, DBA__c> oldMap){   
    }
    
    
    //////////////////////////////////////////////////////////////////////////////////////
    private void updateDbaName(List<DBA__c> newList){
        // Get current user's profile name
        //Profile prof = [select Name from Profile where Id = :UserInfo.getProfileId() ];
        //List<DBA__c> dbarec = [Select Id, Registration__c from DBA__c where Id in : Trigger.old];
        //if (!prof.Name.contains('System Administrator') || !prof.Name.contains('System Administrator LTD') ) {
        
        
        for(DBA__c dbaUpdate: newList){
            DBA__c dbaName = [SELECT Name FROM DBA__c WHERE Id =: dbaUpdate.Id];
            List<Attachments_Plus__c> attplus = [SELECT Id, Attachment_Name__c, Type__c, Instructions__c FROM Attachments_Plus__c WHERE Reg_Related_Rec_Id__c =:dbaUpdate.Id];
            if(attplus.size() > 0){
                for(Attachments_Plus__c eachAttPlus: attplus){
                    eachAttPlus.Attachment_Name__c = eachAttPlus.Attachment_Name__c.replace(dbaName.Name,  dbaUpdate.Name);
                    eachAttPlus.Type__c = eachAttPlus.Type__c.replace(dbaName.Name,  dbaUpdate.Name);
                    eachAttPlus.Instructions__c = eachAttPlus.Instructions__c.replace(dbaName.Name,  dbaUpdate.Name);
                    //System.debug('*************** eachAttPlus.Attachment_Name__c:' + eachAttPlus.Attachment_Name__c);
                }
            }
            update attplus;
        }
    }
    
    private void deleteDBA(List<DBA__c> oldDbaList){
        for(DBA__c dbarec : oldDbaList){
            //System.debug('dbarec '+dbarec);
            //System.debug('Reg status '+dbarec.Registration_Status__c );
            
            if (dbarec.Registration_Status__c != null){  
                if (dbarec.Registration_Status__c != 'Incomplete') {
                    dbarec.addError('This Record can not be deleted because it is associated with a Registration that is not Incomplete');
                }
            }
            else
            {
                List<Attachments_Plus__c> attplus = [SELECT Id FROM Attachments_Plus__c WHERE Reg_Related_Rec_Id__c =:dbarec.Id];
                // System.debug('attplus.size():' + attplus.size());
                if(attplus.size() > 0){
                    delete attplus;
                }
            }
        }
    }
}