force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_URL__c.field-meta.xml
<CustomField>
    <fullName>Attachment_URL__c</fullName>
    <formula>"/" &amp;  Attachment_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attorney_Client_Privilege__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Client_Privilege__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is subject to attorney-client privilege.</inlineHelpText>
    <label>Attorney-Client Privilege</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <formula>Case_Management__r.Employer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Wage Cases</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee's manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Position on Loan</fullName>
            </value>
            <value>
                <fullName>Temporarily Vacant</fullName>
            </value>
            <value>
                <fullName>Abolished</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>607 Pending Finance Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - Civil Service</fullName>
            </value>
            <value>
                <fullName>4 - Exempt</fullName>
            </value>
            <value>
                <fullName>7 - Salary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Attachment_Widget_ControllerTest.cls
@isTest(SeeAllData=false)
private class Attachment_Widget_ControllerTest {
  
  static testMethod void testAttachment_Widget_Controller() {
    Account a = new Account();
        a.Name = 'test account'+system.now();
        insert a;
        
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c();
        de.User__c = UserInfo.getUserId();
        de.Position__c = 'Deputy';
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Case__c cm = new DIR_Case__c();
        cm.Employer__c = a.Id;
        cm.Status__c = 'Open';
        cm.Assigned_Deputy__c = de.Id;
        cm.RecordtypeId = Schema.SObjectType.DIR_Case__c.getRecordTypeInfosByName().get('WCA').getRecordTypeId();
        insert cm;

        Attachment att = new Attachment(
          Body = blob.valueOf('test body'),
          Name = 'test name',
          isPrivate = false,
          ParentId = cm.Id
        );
        insert att;
    
        Attachments_Plus__c attPlus = new Attachments_Plus__c(
          Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id, 
          Type__c = '', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );
        insert attPlus;
    
        Attachments_Plus__c attPlus1 = new Attachments_Plus__c(
          Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id, 
          Type__c = 'Unknown', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );
        insert attPlus1;
    
        Attachments_Plus__c attPlus2 = new Attachments_Plus__c(
          Attachment_ID__c = att.Id, 
          Attachment_Name__c = 'test att name', 
          //Attachment_URL__c, 
          Description__c = 'test desc', 
          //Object__c, 
          Record_ID__c = cm.Id, 
          Type__c = 'Subpoena', 
          Attorney_Client_Privilege__c = true, 
          Confidential__c = true, 
          Not_Subject_to_PRA__c = true
        );
    
        test.startTest();
    
        Attachment_Widget_Controller controller = new Attachment_Widget_Controller();
        pageReference pageRef = Page.Attachment_Widget;
        system.Test.setCurrentPage(pageRef);
    
        
        test.stopTest();
    
      }

  
  
}