force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_URL__c.field-meta.xml
<CustomField>
    <fullName>Attachment_URL__c</fullName>
    <formula>"/" &amp;  Attachment_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <formula>Case_Management__r.Employer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/File_ID__c.field-meta.xml
<CustomField>
    <fullName>File_ID__c</fullName>
    <label>File ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/File_URL__c.field-meta.xml
<CustomField>
    <fullName>File_URL__c</fullName>
    <description>URL of file attached to the record.</description>
    <label>File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Notice_Filer_Name__c.field-meta.xml
<CustomField>
    <fullName>Notice_Filer_Name__c</fullName>
    <label>Submitter Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Publicly_Accessible__c.field-meta.xml
<CustomField>
    <fullName>Publicly_Accessible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Accessible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PAGACaseDetailsController.cls
/********************************************************************************************************
Name:  PAGACaseDetailsController.cls
Author:  Mirela Chituc (mirela.chituc@vertiba.com)
Date:  08/08/2017
VF Page: PAGACaseDetails.page
Test class: PAGACaseDetailsControllerTest.cls

Behavior:
    takes the current DIR_Case__c record & displays case details fields from the field set specified in the VF page
       
********************************************************************************************************/

public class PAGACaseDetailsController {

    private final DIR_Case__c cCase;
    public DIR_Case__c currentCase {get; set;}
    // The extension constructor initializes the private member
    // variable cCase by using the getRecord method from the standard
    // controller.
    public PAGACaseDetailsController(ApexPages.StandardController stdController) {
        this.cCase = (DIR_Case__c)stdController.getRecord();
        currentCase = [SELECT Id FROM DIR_Case__c WHERE Id =: cCase.Id];
    }
    
    // get the attachments list to be displayed in the table
    public List<Attachments_Plus__c> getAttachments() {
        String thisObjId = cCase.Id;
        String thisObjIdShort = thisObjId.subString(0, thisObjId.length() - 3);
        List<Attachments_Plus__c> allAttPlus = [SELECT Id, File_ID__c, Attachment_ID__c FROM Attachments_Plus__c WHERE (Case_Management__c =: thisObjId OR Record_ID__c =: thisObjId OR Record_ID__c =: thisObjIdShort) AND File_URL__c != null];
        Set<String> attSet = new Set<String>();
        for(Attachments_Plus__c ap: allAttPlus) {
            attSet.add(ap.Id);
        }
 /*       Map<Id, ContentDocument> allAttMap = new Map<Id, ContentDocument>([SELECT Id FROM ContentDocument WHERE Id IN: attSet]);
       // Map<Id, Attachment> allAttMap = new Map<Id, Attachment>([SELECT Id FROM Attachment WHERE Id IN: attSet]);

        Set<String> attPlusSet = new Set<String>();
        for(Attachments_Plus__c ap: allAttPlus) {
            if(allAttMap.containsKey(ap.File_ID__c))
                attPlusSet.add(ap.Id);
        }
  */    //return statement modified to include the field Publicly_Accessible__c for Paga Search 2 project user story PS-006 All Documents Listed on Case Details.
        return [SELECT Id, Name, File_ID__c,File_URL__c, Attachment_ID__c, Attachment_Name__c, CreatedDate, Description__c, Notice_Filer_Name__c, Attachment_URL__c, Employer__c, Type__c, Publicly_Accessible__c FROM Attachments_Plus__c WHERE Id IN: attSet ORDER BY Attachment_Name__c];     
    }
}