force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Reg_Related_Rec_Id__c.field-meta.xml
<CustomField>
    <fullName>Reg_Related_Rec_Id__c</fullName>
    <description>Registration Related Record Id. This field is used by Registration Services to store the related Registration record.</description>
    <externalId>true</externalId>
    <label>Reg Related Rec Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Account</label>
    <referenceTo>Registration_Account__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/Registration_Account__c.object-meta.xml
<CustomObject>
    <description>Staging object used to collect Company/Account information on Registration forms.</description>
    <label>Registration Account</label>
    <nameField>
        <displayFormat>RA-{000000000}</displayFormat>
        <label>Registration Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Account__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegistrationAccountAllHandler.cls
public class RegistrationAccountAllHandler {
    private static registrationAccountAllHandler classInstance = null;
    public Boolean stopRecursion {get; set;}
    
    private registrationAccountAllHandler() {
        stopRecursion = FALSE;
    }
    
    public static RegistrationAccountAllHandler getInstance(){
        if (null == classInstance) {
            classInstance = new registrationAccountAllHandler();
        }
        return classInstance;
    }
    
    public void onBeforeInsert(List<Registration_Account__c> newList){ 
    }
    
    public void onAfterInsert(List<Registration_Account__c> newList , Map<id, Registration_Account__c> newMap){  
    }
    
    public void onBeforeUpdate(List<Registration_Account__c> newList, Map<id, Registration_Account__c> newMap, Map<id, Registration_Account__c> oldMap){
        if(stopRecursion == null || !stopRecursion)
        {
            stopRecursion = TRUE;
            updateRA(newList); 
            stopRecursion = FALSE;
        }
    }
    
    public void onAfterUpdate(List<Registration_Account__c> newList, Map<id, Registration_Account__c> newMap, Map<id, Registration_Account__c> oldMap){  
    }
    
    public void onBeforeDelete(List<Registration_Account__c> oldList, Map<id, Registration_Account__c> oldMap){
        
        if(stopRecursion == null || !stopRecursion)
        {
            stopRecursion = TRUE;
            deleteRA(oldList);
            stopRecursion = FALSE;
        }
    }
    
    public void onAfterDelete(list<Registration_Account__c> oldList, Map<id, Registration_Account__c> oldMap){   
    }
    
    /// String s2 = s1.replace(target, replacement);
    //////////////////////////////////////////////////////////////////////////////////////  Old one
/*    private void updateRA(List<Registration_Account__c> newList){
        
        Map<Id, Registration_Account__c> raNameOld=new Map<id, Registration_Account__c>([SELECT Id, Name, Registration__c, First_Name__c, Last_Name__c FROM Registration_Account__c WHERE Id IN: newList AND Registration__c =: newList[0].Registration__c]);
        if(!raNameOld.isEmpty()){
            for(Registration_Account__c raNameNew: newList){
                List<Attachments_Plus__c> attplus = [SELECT Id, Attachment_Name__c, Type__c, Instructions__c, Reg_Related_Rec_Id__c FROM Attachments_Plus__c WHERE Reg_Related_Rec_Id__c =: raNameOld.keySet() AND Registration__c =: raNameNew.Registration__c ];        
                if (raNameNew.First_Name__c == null && raNameNew.Last_Name__c == null)
                {
                    raNameNew.First_Name__c='';
                    raNameNew.Last_Name__c='';
                }    
                Else
                    if (raNameNew.First_Name__c == Null)
                {
                    raNameNew.First_Name__c='';
                }
                Else{
                    if (raNameNew.Last_Name__c == Null)
                    {
                        raNameNew.Last_Name__c='';
                    }
                }
                if(attplus.size() > 0){
                    for(Attachments_Plus__c eachAttPlus: attplus){
                        String attName = eachAttPlus.Attachment_Name__c;
                        String attType =  eachAttPlus.Type__c;
                        String attInstruction = eachAttPlus.Instructions__c;  
                        //eachAttPlus.Attachment_Name__c = 
                        //eachAttPlus.Attachment_Name__c.replace(raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).First_Name__c + ' ' + raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).Last_Name__c, raNameNew.First_Name__c + ' ' + raNameNew.Last_Name__c );
                        eachAttPlus.Attachment_Name__c = attName.substringBefore('-')+' - '+raNameNew.First_Name__c+' '+raNameNew.Last_Name__c;
                        eachAttPlus.Type__c = attType.substringBefore('-')+' - '+raNameNew.First_Name__c+' '+raNameNew.Last_Name__c;
                        eachAttPlus.Instructions__c = attInstruction.substringBefore('-')+' - '+raNameNew.First_Name__c+' '+raNameNew.Last_Name__c;

                        //eachAttPlus.Type__c = eachAttPlus.Type__c.replace(raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).First_Name__c + ' ' + raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).Last_Name__c, raNameNew.First_Name__c + ' ' + raNameNew.Last_Name__c );
                        //eachAttPlus.Instructions__c = eachAttPlus.Instructions__c.replace(raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).First_Name__c + ' ' + raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).Last_Name__c, raNameNew.First_Name__c + ' ' + raNameNew.Last_Name__c );
                        System.debug('*************** eachAttPlus.Attachment_Name__c:' + eachAttPlus.Attachment_Name__c);
                    }
                }
                update attplus;
            }
        }
    } */

    private void updateRA(List<Registration_Account__c> newList){
        
        Map<Id, Registration_Account__c> raNameOld=new Map<id, Registration_Account__c>([SELECT Id, Name, Registration__c, First_Name__c, Last_Name__c FROM Registration_Account__c WHERE Id IN: newList AND Registration__c =: newList[0].Registration__c]);
        if(!raNameOld.isEmpty()){
            for(Registration_Account__c raNameNew: newList){
                List<Attachments_Plus__c> attplus = [SELECT Id, Attachment_Name__c, Type__c, Instructions__c, Reg_Related_Rec_Id__c FROM Attachments_Plus__c WHERE Reg_Related_Rec_Id__c =: raNameOld.keySet() AND Registration__c =: raNameNew.Registration__c ];        
/*                if (raNameNew.First_Name__c == null && raNameNew.Last_Name__c == null)
                {
                    raNameNew.First_Name__c='';
                    raNameNew.Last_Name__c='';
                }    
                Else
                    if (raNameNew.First_Name__c == Null)
                {
                    raNameNew.First_Name__c='';
                }
                Else{
                    if (raNameNew.Last_Name__c == Null)
                    {
                        raNameNew.Last_Name__c='';
                    }
                } */
                if(attplus.size() > 0){
                    for(Attachments_Plus__c eachAttPlus: attplus){
                        String attName = eachAttPlus.Attachment_Name__c;
                        String attType =  eachAttPlus.Type__c;
                        String attInstruction = eachAttPlus.Instructions__c;  
                        //eachAttPlus.Attachment_Name__c = 
                        //eachAttPlus.Attachment_Name__c.replace(raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).First_Name__c + ' ' + raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).Last_Name__c, raNameNew.First_Name__c + ' ' + raNameNew.Last_Name__c );
                        eachAttPlus.Attachment_Name__c = attName.substringBefore('-')+' - '+raNameNew.First_Name__c+' '+raNameNew.Last_Name__c;
                        eachAttPlus.Type__c = attType.substringBefore('-')+' - '+raNameNew.First_Name__c+' '+raNameNew.Last_Name__c;
                        eachAttPlus.Instructions__c = attInstruction.substringBefore('-')+' - '+raNameNew.First_Name__c+' '+raNameNew.Last_Name__c;

                        //eachAttPlus.Type__c = eachAttPlus.Type__c.replace(raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).First_Name__c + ' ' + raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).Last_Name__c, raNameNew.First_Name__c + ' ' + raNameNew.Last_Name__c );
                        //eachAttPlus.Instructions__c = eachAttPlus.Instructions__c.replace(raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).First_Name__c + ' ' + raNameOld.get(eachAttPlus.Reg_Related_Rec_Id__c).Last_Name__c, raNameNew.First_Name__c + ' ' + raNameNew.Last_Name__c );
                        System.debug('*************** eachAttPlus.Attachment_Name__c:' + eachAttPlus.Attachment_Name__c);
                    }
                }
                update attplus;
            }
        }
    }    
    
    
    private void deleteRA(List<Registration_Account__c> oldRAList){
        // Get current user's profile name
        // Profile prof = [select Name from Profile where Id = :UserInfo.getProfileId() ];
        // List<Registration_Account__c> regacc = [Select Id, Registration__c from Registration_Account__c where Id in : Trigger.old];
        // Delete Submission Detail 1st
        // Delete Registration Acconunts 2nd
        // if (!prof.Name.contains('System Administrator')) {
        
        for(Registration_Account__c regacc : oldRAList){
            // System.debug('regacc '+regacc);
            
            if (regacc.Registration_Status__c != 'Incomplete') {
                regacc.addError('This Record can not be deleted');
            }
            else
            {
                List<Attachments_Plus__c> attplus = [SELECT Id FROM Attachments_Plus__c WHERE Reg_Related_Rec_Id__c =:regacc.Id AND Registration__c =: regacc.Registration__c];
                // System.debug('attplus.size():' + attplus.size());
                if(attplus.size() > 0){
                    delete attplus;
                }
            }
        } 
    }
}