force-app/main/default/objects/Affiliation__c/Affiliation__c.object-meta.xml
<CustomObject>
    <description>Defines the relationship between two accounts, person accounts or business accounts either one, or between accounts and contacts.</description>
    <label>Affiliation</label>
    <nameField>
        <label>Affiliation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliation__c/fields/Affiliated_Account__c.field-meta.xml
<CustomField>
    <fullName>Affiliated_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account that is chosen to be related to an account when creating an affiliation.</description>
    <label>Affiliated Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations (Affiliated Business/Person)</relationshipLabel>
    <relationshipName>Additional_Affiliations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliation__c/fields/Main_Account__c.field-meta.xml
<CustomField>
    <fullName>Main_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The "source" account that an affiliation is created FROM</description>
    <inlineHelpText>The "source" account that an affiliation is created FROM. When reading the affiliation, the relationship should read:
[Affiliated Account/contact] is a [Affiliation Type] of [Main Account/contact].</inlineHelpText>
    <label>Main Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations (Main Account)</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/Appeal__c.object-meta.xml
<CustomObject>
    <description>This is used for a Request for Citation Appeal Hearing associated with a DIR BOFE Case.  This may be repurposed for specific purposes.</description>
    <label>Appeal</label>
    <nameField>
        <displayFormat>APL-{000000}</displayFormat>
        <label>Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appeals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appeal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Appeals</relationshipLabel>
    <relationshipName>Appeals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liability</label>
    <referenceTo>Liability__c</referenceTo>
    <relationshipLabel>Appeals</relationshipLabel>
    <relationshipName>Appeals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessments__c/fields/Appeal_Deadline_Selector__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Selector__c</fullName>
    <label>Appeal Deadline Selector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Days</fullName>
            </value>
            <value>
                <fullName>Calendar Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</description>
    <inlineHelpText>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</inlineHelpText>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <description>Vertiba</description>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Violations are tied together as an assessment.</description>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Hearing__c/Hearing__c.object-meta.xml
<CustomObject>
    <description>This stores all of the hearings/conferences related to an Appeal, which gets information from the Assessment, Liability Appeal, Case, and Account from a relationship level.</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Meeting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hearing__c/fields/Appeal__c.field-meta.xml
<CustomField>
    <fullName>Appeal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Appeal this Hearing is related to.</description>
    <inlineHelpText>This is the Appeal this Hearing is related to.</inlineHelpText>
    <label>Appeal</label>
    <referenceTo>Appeal__c</referenceTo>
    <relationshipName>Hearings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Lookup to parent case. Used for easy identification and for rules related to referrals that deal with hearing dates.</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Hearings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability__c/Liability__c.object-meta.xml
<CustomObject>
    <description>This objects contains the Liability against an Assessment.</description>
    <label>Liability</label>
    <nameField>
        <displayFormat>LIA-{000000}</displayFormat>
        <label>Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>This creates a lookup relationship between a Liability and an Assessment.  This field is required.</description>
    <inlineHelpText>This creates a lookup relationship between a Liability and an Assessment.  This field is required.</inlineHelpText>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipLabel>Liabilities</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related case to the liability</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Liability</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability__c/recordTypes/RCI.recordType-meta.xml
<RecordType>
    <fullName>RCI</fullName>
    <active>true</active>
    <label>RCI</label>
</RecordType>

force-app/main/default/objects/Liability_Appeal__c/Liability_Appeal__c.object-meta.xml
<CustomObject>
    <description>Junction object between liablities and appeals. Allows a liability to have multiple appeals where necessary.</description>
    <label>Liability Appeal</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>Liability Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability Appeals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Appeal__c/fields/Appeal__c.field-meta.xml
<CustomField>
    <fullName>Appeal__c</fullName>
    <inlineHelpText>Relationship to the appeal for this liability</inlineHelpText>
    <label>Appeal</label>
    <referenceTo>Appeal__c</referenceTo>
    <relationshipLabel>Liability Appeals</relationshipLabel>
    <relationshipName>Liability_Appeals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability_Appeal__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <inlineHelpText>Relationship to the Liability for this appeal</inlineHelpText>
    <label>Liability</label>
    <referenceTo>Liability__c</referenceTo>
    <relationshipLabel>Liability Appeals</relationshipLabel>
    <relationshipName>Liability_Appeals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HearingResultsTest.cls
@isTest
public with sharing class HearingResultsTest {
    public static testMethod void TestHearingResults1() {
        
        List<Trigger_Settings__c> triggerSettings = new List<Trigger_Settings__c>();
        
        Trigger_Settings__c casePaymentAllTriggerSetting = new Trigger_Settings__c(
            Name = 'CasePaymentAll',
            Is_Active__c = false
        );
        triggerSettings.add(casePaymentAllTriggerSetting);
        
        Trigger_Settings__c dlrsDirViolationTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_DIR_ViolationTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(dlrsDirViolationTriggerSetting);
        
        Trigger_Settings__c dlrsJudgementTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_JudgementTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(dlrsJudgementTriggerSetting);
        
        Trigger_Settings__c dlrsPaymentRecordTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_Payment_RecordTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(dlrsPaymentRecordTriggerSetting);
            
        Trigger_Settings__c generateFieldHistoryActionTriggerSetting = new Trigger_Settings__c(
            Name = 'GenerateFieldHistoryAction',
            Is_Active__c = false
        );
        triggerSettings.add(generateFieldHistoryActionTriggerSetting);        
            
        Trigger_Settings__c liabilityPaymentTriggerSetting = new Trigger_Settings__c(
            Name = 'liabilityPaymentTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(liabilityPaymentTriggerSetting);
                
        Trigger_Settings__c rctTriggerSetting = new Trigger_Settings__c(
            Name = 'Receipt Trigger',
            Is_Active__c = false
        );
        triggerSettings.add(rctTriggerSetting);

        insert triggerSettings;


        Account acc = new Account();
        acc.Name = 'name';
        acc.ShippingPostalCode = '234889';
        insert acc;
        
        Affiliation__c aff = new Affiliation__c();
        aff.Affiliated_Account__c = acc.Id;
        aff.Main_Account__c = acc.Id;
        insert aff;

        DIR_Case__c c = new DIR_Case__c();
        c.Employer__c = acc.Id;
        insert c;
        
        Assessments__c assess = new Assessments__c();
        assess.Case_Management__c = c.Id;
        assess.Appeal_Deadline_Selector__c = 'Business Days';
        insert assess;
        
        DIR_Violation__c dv = new DIR_Violation__c();
        dv.Case__c = c.Id;
        dv.Assessment__c = assess.Id;
        insert dv;

        Liability__c lia = new Liability__c();
        lia.Assessment__c = assess.Id;
        insert lia;
        
        Appeal__c appeal1 = new Appeal__c();
        appeal1.Status__c = 'New';
        appeal1.Case__c = c.Id;
        appeal1.X2810_3_Case__c = 'Yes';
        appeal1.Citation_Selected__c = true;
        appeal1.Estimated_Length_of_Hearing_In_Minutes__c = 60;
        insert appeal1;
        
        Liability_Appeal__c la = new Liability_Appeal__c();
        la.Appeal__c = appeal1.Id;
        la.Liability__c = lia.Id;
        insert la;
        
        Hearing__c h = new Hearing__c();
        h.Appeal__c = appeal1.Id;
        h.Case__c = c.Id;
        h.Status__c = 'New';
        insert h;

        Hearing_Liability__c hl = new Hearing_Liability__c();
        hl.Hearing__c = h.Id;
        hl.Liability_Appeal__c = la.Id;
        insert hl;
        
        Hearing_Liability__c hl1 = new Hearing_Liability__c();
        hl1.Hearing__c = h.Id;
        hl1.Liability_Appeal__c = la.Id;
        insert hl1;

        ApexPages.StandardController sc = new ApexPages.StandardController(h);
        HearingResults hr = new HearingResults(sc);
        
        PageReference pageRef = Page.HearingResults;
        pageRef.getParameters().put('id', String.valueOf(h.Id));
        Test.setCurrentPage(pageRef);
        
        hr.SaveHearing();
    }
    
    public static testMethod void TestHearingResults2() {

        List<Trigger_Settings__c> triggerSettings = new List<Trigger_Settings__c>();
        
        Trigger_Settings__c casePaymentAllTriggerSetting = new Trigger_Settings__c(
            Name = 'CasePaymentAll',
            Is_Active__c = false
        );
        triggerSettings.add(casePaymentAllTriggerSetting);
        
        Trigger_Settings__c dlrsDirViolationTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_DIR_ViolationTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(dlrsDirViolationTriggerSetting);
        
        Trigger_Settings__c dlrsJudgementTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_JudgementTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(dlrsJudgementTriggerSetting);
        
        Trigger_Settings__c dlrsPaymentRecordTriggerSetting = new Trigger_Settings__c(
            Name = 'dlrs_Payment_RecordTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(dlrsPaymentRecordTriggerSetting);
            
        Trigger_Settings__c generateFieldHistoryActionTriggerSetting = new Trigger_Settings__c(
            Name = 'GenerateFieldHistoryAction',
            Is_Active__c = false
        );
        triggerSettings.add(generateFieldHistoryActionTriggerSetting);        
            
        Trigger_Settings__c liabilityPaymentTriggerSetting = new Trigger_Settings__c(
            Name = 'liabilityPaymentTrigger',
            Is_Active__c = false
        );
        triggerSettings.add(liabilityPaymentTriggerSetting);
                
        Trigger_Settings__c rctTriggerSetting = new Trigger_Settings__c(
            Name = 'Receipt Trigger',
            Is_Active__c = false
        );
        triggerSettings.add(rctTriggerSetting);

        insert triggerSettings;


        Account acc = new Account();
        acc.Name = 'name';
        acc.ShippingPostalCode = '234889';
        insert acc;
        
        Affiliation__c aff = new Affiliation__c();
        aff.Affiliated_Account__c = acc.Id;
        aff.Main_Account__c = acc.Id;
        insert aff;
    
        Profile p = [select id from profile where name='RCI User'];
        User u = new User(alias = 'standt', email='alex@vertiba.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p.Id,
                timezonesidkey='America/Los_Angeles', username='testuser1@ca-dir.com');
        insert u;
    
        //manager
        DIR_Employee__c ma = new DIR_Employee__c();
        ma.User__c = UserInfo.getUserId();
        insert ma; 
        
        
        //internal employee
        DIR_Employee__c de = new DIR_Employee__c();
        de.Name = 'name';
        de.Position__c = 'Deputy';
        de.User__c = u.Id;
        de.Manager__c = ma.Id;
        insert de;
        
        DIR_Case__c c = new DIR_Case__c();
        c.Employer__c = acc.Id;
        c.Assigned_Deputy__c = de.id;
        insert c;
        
        Assessments__c assess = new Assessments__c();
        assess.Case_Management__c = c.Id;
        assess.Appeal_Deadline_Selector__c = 'Business Days';
        insert assess;
        
        DIR_Violation__c dv = new DIR_Violation__c();
        dv.Case__c = c.Id;
        dv.Assessment__c = assess.Id;
        insert dv;

        Liability__c lia = new Liability__c();
        lia.Assessment__c = assess.Id;
        insert lia;
        
        Appeal__c appeal1 = new Appeal__c();
        appeal1.Status__c = 'New';
        appeal1.Case__c = c.Id;
        appeal1.X2810_3_Case__c = 'Yes';
        appeal1.Citation_Selected__c = true;
        appeal1.Estimated_Length_of_Hearing_In_Minutes__c = 60;
        insert appeal1;
        
        Liability_Appeal__c la = new Liability_Appeal__c();
        la.Appeal__c = appeal1.Id;
        la.Liability__c = lia.Id;
        insert la;
        
        Hearing__c h = new Hearing__c();
        h.Appeal__c = appeal1.Id;
        h.Case__c = c.Id;
        h.Status__c = 'Scheduled';
        h.Meeting_Start_Date_Time__c = Date.today();
        h.Meeting_End_Date_Time__c = Date.today() + 1;
        h.Meeting_Type__c = 'Conference';
        h.Length_of_Hearing__c = 30;
        h.Meeting_Scheduled_For__c = de.id;
        h.In_Person_Remote_Meeting__c = 'In Person';
        insert h;

        Hearing_Liability__c hl = new Hearing_Liability__c();
        hl.Hearing__c = h.Id;
        hl.Liability_Appeal__c = la.Id;
        insert hl;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(h);
        HearingResults hr = new HearingResults(sc);
        
        test.startTest();
        
        PageReference pageRef = Page.HearingResults;
        pageRef.getParameters().put('id', String.valueOf(h.Id));
        Test.setCurrentPage(pageRef);
       
        hr.SaveHearing();
        
        test.stopTest();
    }
    
}