force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>This object is to store a One-To-Many relationship between Accounts and the Addresses they may have</description>
    <label>Location</label>
    <nameField>
        <displayFormat>ADDR-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address Line 1</description>
    <inlineHelpText>Address Line 1</inlineHelpText>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Registration_Location__c.field-meta.xml
<CustomField>
    <fullName>Registration_Location__c</fullName>
    <label>Registration Location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Select the type of location at this address</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Business Location</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Job Site</fullName>
            </value>
            <value>
                <fullName>Location of Records</fullName>
            </value>
            <value>
                <fullName>PO Box</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Reg_Related_Rec_Id__c.field-meta.xml
<CustomField>
    <fullName>Reg_Related_Rec_Id__c</fullName>
    <description>Registration Related Record Id. This field is used by Registration Services to store the related Registration record.</description>
    <externalId>true</externalId>
    <label>Reg Related Rec Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <formula>Registration__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Litter</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Subpoena</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>L&amp;R/RCI/CIU</fullName>
            </value>
            <value>
                <fullName>Cure Dispute</fullName>
            </value>
            <value>
                <fullName>Court Complaint</fullName>
            </value>
            <value>
                <fullName>Proposed Settlement</fullName>
            </value>
            <value>
                <fullName>PAGA Notice</fullName>
            </value>
            <value>
                <fullName>Other PAGA Document</fullName>
            </value>
            <value>
                <fullName>Employer Response/Cure</fullName>
            </value>
            <value>
                <fullName>Amended Notice</fullName>
            </value>
            <value>
                <fullName>In Forma Pauperis</fullName>
            </value>
            <value>
                <fullName>Court Order/Judgment</fullName>
            </value>
            <value>
                <fullName>Workers Compensation Insurance (WCI)</fullName>
            </value>
            <value>
                <fullName>Bond Collective Bargaining Agreement (CBA)</fullName>
            </value>
            <value>
                <fullName>Sample Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Signed Employee Leasing Contract</fullName>
            </value>
            <value>
                <fullName>Employee Leasing WCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Location__c/Registration_Location__c.object-meta.xml
<CustomObject>
    <description>Junction object between Locations, Accounts, and Registrations</description>
    <label>Registration Location</label>
    <nameField>
        <displayFormat>RLN-{0000000}</displayFormat>
        <label>Registration Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Mapped to Address__c Location field.</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>DBA_Name__c</fullName>
    <description>Mapped to DBA__c Location field.</description>
    <inlineHelpText>If there is no DBA Name, enter N/A for not applicable</inlineHelpText>
    <label>DBA Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Locations</relationshipLabel>
    <relationshipName>Registration_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <formula>TEXT(Registration__r.License_Registration_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegistrationLocationAllHandler.cls
public class RegistrationLocationAllHandler {
    
    private static registrationLocationAllHandler classInstance = null;
    public Boolean stopRecursion {get; set;}
    
    private registrationLocationAllHandler() {
        stopRecursion = FALSE;
    }
    
    public static RegistrationLocationAllHandler getInstance(){
        if (null == classInstance) {
            classInstance = new registrationLocationAllHandler();
        }
        return classInstance;
    }
    
    public void onBeforeInsert(List<Registration_Location__c> newList){ 
    }
    
    public void onAfterInsert(List<Registration_Location__c> newList , Map<id, Registration_Location__c> newMap){  
    }
    
    public void onBeforeUpdate(List<Registration_Location__c> newList, Map<id, Registration_Location__c> newMap, Map<id, Registration_Location__c> oldMap){
        if(stopRecursion == null || !stopRecursion)
        {
            stopRecursion = TRUE;
            updateLoc(newList); 
            stopRecursion = FALSE;
        }
    }
    
    public void onAfterUpdate(List<Registration_Location__c> newList, Map<id, Registration_Location__c> newMap, Map<id, Registration_Location__c> oldMap){  
    }
    
    public void onBeforeDelete(List<Registration_Location__c> oldList, Map<id, Registration_Location__c> oldMap){
        
        if(stopRecursion == null || !stopRecursion)
        {
            stopRecursion = TRUE;
            deleteLoc(oldList);
            stopRecursion = FALSE;
        }
    }
    
    public void onAfterDelete(list<Registration_Location__c> oldList, Map<id, Registration_Location__c> oldMap){   
    }
    
    private void updateLoc(List<Registration_Location__c> newList){
        Map<Id, Registration_Location__c> locNameOld=new Map<id, Registration_Location__c>([SELECT Id, DBA_Name__c,	Address__c
                      FROM Registration_Location__c WHERE Id IN: newList AND Registration__c =: newList[0].Registration__c]);
        
        if(!locNameOld.isEmpty()){
        for(Registration_Location__c locNameNew: newList){
         
            List<Attachments_Plus__c> attplus = [SELECT Id, Attachment_Name__c, Type__c,Reg_Related_Rec_Id__c, Instructions__c, Registration_Type__c FROM Attachments_Plus__c WHERE Reg_Related_Rec_Id__c =: locNameNew.Id];
             if (locNameNew.DBA_Name__c == Null)
                {
                   locNameNew.DBA_Name__c='';
                }
            if(attplus.size() > 0){
                for(Attachments_Plus__c eachAttPlus: attplus){
                        String attName = eachAttPlus.Attachment_Name__c;
                        String attType =  eachAttPlus.Type__c;
                        String attInstruction = eachAttPlus.Instructions__c;                    
                    if(eachAttPlus.Registration_Type__c == 'Car_Wash'){

                        eachAttPlus.Attachment_Name__c = attName.substringBefore('-')+' - '+locNameNew.DBA_Name__c;
                        eachAttPlus.Type__c = attType.substringBefore('-') +' - '+ locNameNew.DBA_Name__c;
                        eachAttPlus.Instructions__c = attInstruction.substringBefore('-') +' - '+ locNameNew.DBA_Name__c;
                        
                        System.debug('*************** eachAttPlus.Attachment_Name__c:' + eachAttPlus.Attachment_Name__c);
                    }
                    else {
                        //if(eachAttPlus.Registration_Type__c == 'Garment_Manufacturers_and_Contractors')
                        eachAttPlus.Attachment_Name__c = attName.substringBefore('-')+' - '+locNameNew.Address__c;
                        eachAttPlus.Type__c = attType.substringBefore('-') +' - '+ locNameNew.Address__c;
                        eachAttPlus.Instructions__c = attInstruction.substringBefore('-') +' - '+ locNameNew.Address__c;
                        System.debug('*******I am here if not Carwash');
                            }
                }
               
            }
            update attplus;
        }
       }
    }
    
    
    private void deleteLoc(List<Registration_Location__c> oldLocList){
                // Get current user's profile name
                // Profile prof = [select Name from Profile where Id = :UserInfo.getProfileId() ];
                // List<Registration_Location__c> regloc = [Select Id, Registration__c from Registration_Location__c where Id in : Trigger.old];
                // Delete Submission Detail 1st
                // Delete Registration location 2nd
                // if (!prof.Name.contains('System Administrator')) {
                
                for(Registration_Location__c regloc : oldLocList){
                    // System.debug('regloc '+regloc);
                    
                    if (regloc.Registration_Status__c != 'Incomplete') {
                        regloc.addError('This Record can not be deleted');
                    }
                    else
                    {
                        List<Attachments_Plus__c> attplus = [SELECT Id FROM Attachments_Plus__c WHERE Reg_Related_Rec_Id__c =:regloc.Id AND Registration__c =: regloc.Registration__c];
                        // System.debug('attplus.size():' + attplus.size());
                        if(attplus.size() > 0){
                            delete attplus;
                        }
                    }
                } 
    }

}