force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>This object is to store a One-To-Many relationship between Accounts and the Addresses they may have</description>
    <label>Location</label>
    <nameField>
        <displayFormat>ADDR-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
                <default>true</default>
                <label>CA</label>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <label>Attachment ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attachment_URL__c.field-meta.xml
<CustomField>
    <fullName>Attachment_URL__c</fullName>
    <formula>"/" &amp;  Attachment_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <formula>Case_Management__r.Employer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Notice_Filer_Name__c.field-meta.xml
<CustomField>
    <fullName>Notice_Filer_Name__c</fullName>
    <label>Submitter Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Publicly_Accessible__c.field-meta.xml
<CustomField>
    <fullName>Publicly_Accessible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Accessible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Submission Detail</relationshipLabel>
    <relationshipName>Submission_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bond__c/Bond__c.object-meta.xml
<CustomObject>
    <description>Object to allow deputies and other users to record the details of appeal bonds, surety bonds related to a citation, appeal, and party record.</description>
    <label>Bond</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bond Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bond__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Bonds</relationshipLabel>
    <relationshipName>Bonds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DBA__c/DBA__c.object-meta.xml
<CustomObject>
    <label>DBA</label>
    <nameField>
        <label>DBA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DBAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DBA__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>Registration__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DBA__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>DBAs</relationshipLabel>
    <relationshipName>DBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Line_1__c</fullName>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address_Line_2__c</fullName>
    <label>Mailing Address Line 2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Postal_Code__c</fullName>
    <label>Mailing Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Address_Line_1__c</fullName>
    <inlineHelpText>P.O. Box address is not allowed.</inlineHelpText>
    <label>Physical Business Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Address_Line_2__c</fullName>
    <label>Physical Business Address Line 2</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_City__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_City__c</fullName>
    <label>Physical Business City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_Country__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Country__c</fullName>
    <label>Physical Business Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_Postal_Code__c</fullName>
    <label>Physical Business Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Physical_Business_State__c.field-meta.xml
<CustomField>
    <fullName>Physical_Business_State__c</fullName>
    <label>Physical Business State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Location__c/Registration_Location__c.object-meta.xml
<CustomObject>
    <description>Junction object between Locations, Accounts, and Registrations</description>
    <label>Registration Location</label>
    <nameField>
        <displayFormat>RLN-{0000000}</displayFormat>
        <label>Registration Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Location__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Mapped to City__c Location field.</description>
    <label>City / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Locations</relationshipLabel>
    <relationshipName>Registration_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Mapped to State__c Location field.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <description>Holds the zip codes and cities in which a zip code is located and supports the assigning records based on zip codes.</description>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the zip code is within</description>
    <inlineHelpText>Enter the city that this zip code is in.</inlineHelpText>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegistrationDetailsController.cls
/********************************************************************************************************
Name:  RegistrationDetailsController.cls
Author:  Mirela Chituc (mirela.chituc@vertiba.com)
Date:  11/01/2017
VF Page: RegistrationDetails.page
Test class: RegistrationDetailsControllerTest.cls

Behavior:
    takes the current Registration record & displays Registration details fields from the field set specified in the VF page
       
********************************************************************************************************/

public class RegistrationDetailsController {

    // public License_Registration__c cRegistration{get; set;}
    public License_Registration__c currentRegistration {get; set;}
     public Id regId {get;set;}

    // variable cRegistration by using the getRecord method from the standard
    // controller.
    public RegistrationDetailsController() {
        //this.cRegistration = (License_Registration__c)stdController.getRecord();
        regId = apexpages.currentpage().getparameters().get('id');
        
        currentRegistration = [SELECT Id, Name, Mailing_Address_Line_1__c, Mailing_Address_Line_2__c, Mailing_City__c, Mailing_State__c, Mailing_Postal_Code__c, Mailing_Country__c,Physical_Business_Address_Line_1__c, Physical_Business_Address_Line_2__c, Physical_Business_City__c, 
               Physical_Business_State__c, Physical_Business_Postal_Code__c, Physical_Business_Country__c,Record_Type_Name__c FROM License_Registration__c WHERE id =: regId];
       
    }
    
    // get the attachments list to be displayed in the table
    /*public List<Attachments_Plus__c> getAttachments() {
        String thisObjId = cRegistration.Id;
        String thisObjIdShort = thisObjId.subString(0, thisObjId.length() - 3);
        List<Attachments_Plus__c> allAttPlus = [SELECT Id, Attachment_ID__c FROM Attachments_Plus__c WHERE (Registration__c  =: thisObjId OR Record_ID__c =: thisObjId OR Record_ID__c =: thisObjIdShort) AND Attachment_ID__c != null AND Publicly_Accessible__c = true];
        Set<String> attSet = new Set<String>();
        for(Attachments_Plus__c ap: allAttPlus) {
            attSet.add(ap.Attachment_ID__c);
        }
        Map<Id, Attachment> allAttMap = new Map<Id, Attachment>([SELECT Id FROM Attachment WHERE Id IN: attSet]);
        
        Set<String> attPlusSet = new Set<String>();
        for(Attachments_Plus__c ap: allAttPlus) {
            if(allAttMap.containsKey(ap.Attachment_ID__c))
                attPlusSet.add(ap.Id);
        }
        
        
        return [SELECT Id, Name, Attachment_ID__c, Attachment_Name__c, CreatedDate, Description__c, Notice_Filer_Name__c, Attachment_URL__c, Employer__c, Type__c FROM Attachments_Plus__c WHERE Id IN: attPlusSet ORDER BY Attachment_Name__c]; 
    
    }*/
    
    
    // get the Bond list to be displayed in the table
    public List<Bond__c> getBonds() {
        return [SELECT Id, Effective_Date__c, Applicant_Email__c, Name_of_Surety_Company__c FROM Bond__c WHERE Registration__c =: currentRegistration.Id]; 
    }
      
    	   
    // get the Registration Location list to be displayed in the table 
    public List<Registration_Location__c> getRegistrationLocation() {
         return [SELECT Id, Address__c, Address_Line_2__c, City__c, State__c, Zip_Code__c, DBA_Name__c FROM Registration_Location__c WHERE Registration__c =: currentRegistration.Id AND Date_Deactivated__c = NULL]; 
        
	}
        
     // get the Registration Registration DBAs list to be displayed in the table - added by Jag
    public List<DBA__c> getRegistrationDBAs() {
        return [SELECT Id,Name,Active__c FROM DBA__c WHERE Registration__c =: currentRegistration.Id]; 
    }

}