force-app/main/default/objects/Interest__c/Interest__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains settings for calculating interest. Yearly interest rate is 10% and daily interest is 10% divided by 365 = .000273972603... Since FM used the first 7 places after decimal (0.0002739) for the daily interest, yearly rate calculates at exactly: 9.99735%.</description>
    <label>Interest</label>
</CustomObject>

force-app/main/default/objects/Interest__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <inlineHelpText>Annual interest rate</inlineHelpText>
    <label>Interest Rate</label>
    <precision>15</precision>
    <scale>12</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Interest__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <inlineHelpText>Developer name of the rec type to which this interest applies</inlineHelpText>
    <label>Record Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status value to which this interest applies</inlineHelpText>
    <label>Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Judgement__c/Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment</label>
    <nameField>
        <displayFormat>J-{0}</displayFormat>
        <label>Judgment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgement__c/fields/Attorney_Fees__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Fees__c</fullName>
    <label>Attorney Fees</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Attorney_Fees_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Fees_Balance_Due__c</fullName>
    <formula>Attorney_Fees__c - Attorney_Fee_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attorney Fees Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean field set automatically when the judgment is considered complete and no further actions are expected on it. Field is not displayed on the page layouts, but is set by wfr, process, or flow and is used in code or other automation functionality.</description>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Filing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Filing_Fee__c</fullName>
    <inlineHelpText>Filing fee for the court for filing the judgment</inlineHelpText>
    <label>Filing Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Filing_Fees_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Filing_Fees_Balance_Due__c</fullName>
    <formula>Filing_Fee__c - Filing_Fee_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filing Fees Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest rate of the post judgment interest. Populated when the decision date is entered.</description>
    <inlineHelpText>Interest rate being charged on this judgment</inlineHelpText>
    <label>Interest Rate</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Judgement_Date__c.field-meta.xml
<CustomField>
    <fullName>Judgement_Date__c</fullName>
    <inlineHelpText>Date the clerk entered the judgement</inlineHelpText>
    <label>Judgment Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Judgment_Balance__c.field-meta.xml
<CustomField>
    <fullName>Judgment_Balance__c</fullName>
    <formula>Judgement_Amount__c - Judgment_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Judgment amount minus any payments received against the violations on the judgment.</inlineHelpText>
    <label>Judgment Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Post_hearing_Interest_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Post_hearing_Interest_Balance_Due__c</fullName>
    <formula>Interest_Due__c - Post_Hearing_Interest_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Post-Hearing Interest Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Post_Judgement_Interest__c.field-meta.xml
<CustomField>
    <fullName>Post_Judgement_Interest__c</fullName>
    <description>Interest on the judgement following the filing date</description>
    <inlineHelpText>Interest on the judgement following the filing date</inlineHelpText>
    <label>Post-Judgment Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Settlement_Amounts_that_Accrue_Interest__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Amounts_that_Accrue_Interest__c</fullName>
    <formula>IF ( !ISBLANK( Settlement__c ) , Settlement__r.Amounts_Due_that_Accrue_Interest__c,
     IF ( !ISBLANK (  ODA__c ) ,  ODA__r.ODA_Amount_that_accrues_interest__c , NULL )
   )</formula>
    <label>Amounts That Accrue Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending/Open</fullName>
            </value>
            <value>
                <fullName>Open/Unpaid</fullName>
            </value>
            <value>
                <fullName>Open - Partial Payment/Satisfaction</fullName>
            </value>
            <value>
                <fullName>Open - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Closed - Satisfied</fullName>
            </value>
            <value>
                <fullName>Closed - Discharged in Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Stayed - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Stayed - Other</fullName>
            </value>
            <value>
                <fullName>Vacated</fullName>
            </value>
            <value>
                <fullName>Closed-Claimant Judgment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleCalculateInterest.cls
global class ScheduleCalculateInterest implements Schedulable, Database.Batchable<sObject>, Database.Stateful{
	// Seconds  Minutes  Hours  Day_of_month  Month  Day_of_week  optional_year
	// Runs each day at 00:00:38
	public static final String CRON_SCHEDULE = '38 0 0 * * ?';
	private static final Integer DEFAULT_BATCH_SIZE = 200;
	private static Interest__c csInterest = Interest__c.getInstance('Judgement Open');
	private String baseURL;
	
	private Integer batchSize;
	
	public ScheduleCalculateInterest() {
		this(DEFAULT_BATCH_SIZE);
	}
	
	public ScheduleCalculateInterest(Integer batchSize) {
		this.batchSize = batchSize;
	}

	public static Id schedule() {
		return schedule(ScheduleCalculateInterest.CRON_SCHEDULE);
	}
	
	public static Id scheduleNow() {
		DateTime Soon = System.now().addSeconds(10);
		String sec = String.valueOf(Soon.second());
		String min = String.valueOf(Soon.minute());
		String hour = String.valueOf(Soon.hour());
		String day = String.valueOf(Soon.day());
		String month = String.valueOf(Soon.month());
		String year = String.valueOf(Soon.year());
		String schedule = sec + ' ' + min + ' ' + hour + ' ' + day + ' ' + month + ' ? ' + year;
		return schedule(schedule);
	}
	
	public static Id schedule(String schedule) {
		ScheduleCalculateInterest scheduler = new ScheduleCalculateInterest();
		String jobId = System.schedule('Schedule Calculate Interest', schedule, scheduler);
		return jobId;
	}
	
	global Database.QueryLocator start(Database.BatchableContext ctx) {
		return Database.getQueryLocator ([SELECT Id, Name, RecordType.Name, RecordTypeId, Settlement_Amounts_that_Accrue_Interest__c, Judgment_Balance__c, Post_Judgement_Interest__c, 
												 Post_hearing_Interest_Balance_Due__c, Filing_Fee__c, Attorney_Fees__c, Status__c, Judgement_Date__c, 	Filing_Fees_Balance_Due__c, Attorney_Fees_Balance_Due__c 
										  FROM Judgement__c 
										  WHERE Closed__c = false AND Judgement_Date__c != null]);
	}
	
	global void execute(Database.BatchableContext ctx, List<Judgement__c> jList) {
		List<Judgement__c> updateList = new List<Judgement__c>();
		for(Judgement__c j : jList){
			if((j.Status__c != null && j.RecordTypeId != null) && (csInterest.Status__c.contains(j.Status__c) && csInterest.Record_Type__c.contains(j.RecordType.Name))){
				Decimal jBal = j.Judgment_Balance__c == null ? 0 : j.Judgment_Balance__c;
                Decimal iAmt = j.Settlement_Amounts_that_Accrue_Interest__c == null ? 0 : j.Settlement_Amounts_that_Accrue_Interest__c;
				Decimal phIntBal = j.Post_hearing_Interest_Balance_Due__c == null ? 0 : j.Post_hearing_Interest_Balance_Due__c;
                Decimal fileFee = j.Filing_Fees_Balance_Due__c == null ? 0 : j.Filing_Fees_Balance_Due__c;
                Decimal attFee = j.Attorney_Fees_Balance_Due__c == null ? 0 : j.Attorney_Fees_Balance_Due__c;
				Decimal totalBal = jBal + phIntBal + fileFee + attFee;
				Decimal dailyInterest = (csInterest.Interest_Rate__c * .01 / 365) * totalBal;
				j.Post_Judgement_Interest__c = j.Post_Judgement_Interest__c == null ? dailyInterest * math.abs(date.today().daysBetween(j.Judgement_Date__c)) : j.Post_Judgement_Interest__c + dailyInterest;
				updateList.add(j);
			}
		}
		if(!updateList.isEmpty()){
			update updateList;
		}
	}
	
	global void execute(SchedulableContext ctx) {
		Database.executeBatch(new ScheduleCalculateInterest(), DEFAULT_BATCH_SIZE);
	}
	
	global void finish(Database.BatchableContext ctx) {
		//option code to run once job finishes
	}
}