force-app/main/default/objects/Case_Payment__c/Case_Payment__c.object-meta.xml
<CustomObject>
    <description>Receipt applied to a Case. May have zero or more Liability Payments and zero or more Judgment Payments.</description>
    <label>Case Payment</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Payment__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <formula>HYPERLINK("/"+Receipt__r.Payee__r.Id,Receipt__r.Payee__r.Name)</formula>
    <label>Payee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case_Payment__c/recordTypes/Posted.recordType-meta.xml
<RecordType>
    <fullName>Posted</fullName>
    <active>true</active>
    <description>Prevents editing of a Case Payment record that has been Posted.</description>
    <label>Posted</label>
</RecordType>

force-app/main/default/objects/Case_Payment__c/recordTypes/WCA.recordType-meta.xml
<RecordType>
    <fullName>WCA</fullName>
    <active>true</active>
    <description>Payments made on WCA Cases.</description>
    <label>WCA</label>
</RecordType>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/Judgment_Payment__c.object-meta.xml
<CustomObject>
    <description>Records payments made against Judgments and their related interests, filing fees, and attorney fees.</description>
    <label>Judgment Payment</label>
    <nameField>
        <displayFormat>JP-{000000}</displayFormat>
        <label>Judgment Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/fields/Case_Payment__c.field-meta.xml
<CustomField>
    <fullName>Case_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Payment</description>
    <label>Case Payment</label>
    <referenceTo>Case_Payment__c</referenceTo>
    <relationshipLabel>Judgment Payments</relationshipLabel>
    <relationshipName>Judgment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Payment_Applied_To__c.field-meta.xml
<CustomField>
    <fullName>Payment_Applied_To__c</fullName>
    <description>Defines to which Judgment Payment category the funds should be applied.</description>
    <label>Payment Applied To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Post-Hearing Interest</fullName>
            </value>
            <value>
                <fullName>Post-Judgment Interest</fullName>
            </value>
            <value>
                <fullName>Filing Fees</fullName>
            </value>
            <value>
                <fullName>Attorney Fees</fullName>
            </value>
            <value>
                <fullName>Judgment Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Posted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Posted_Amount__c</fullName>
    <description>Formerly Allocated_Amount__c</description>
    <label>Posted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/Liability_Payment__c.object-meta.xml
<CustomObject>
    <description>Case Payments allocated and posted to Case Issues.</description>
    <label>Liability Payment</label>
    <nameField>
        <displayFormat>LP-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Liability Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Payment__c/fields/Case_Issue_RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>Case_Issue_RecordTypeId__c</fullName>
    <inlineHelpText>Populated and used by the PostCasePaymentController and PartyPaymentController apex classes.</inlineHelpText>
    <label>Case Issue RecordTypeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/fields/Case_Payment__c.field-meta.xml
<CustomField>
    <fullName>Case_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Payment</label>
    <referenceTo>Case_Payment__c</referenceTo>
    <relationshipLabel>Liability Payments</relationshipLabel>
    <relationshipName>Liability_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <inlineHelpText>Amount actually posted from the Case Payment to this payment type.</inlineHelpText>
    <label>Payment Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/fields/Payment_Applied_To__c.field-meta.xml
<CustomField>
    <fullName>Payment_Applied_To__c</fullName>
    <description>F0263</description>
    <label>Payment Applied To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wages</fullName>
            </value>
            <value>
                <fullName>Wage Interest</fullName>
            </value>
            <value>
                <fullName>Penalties</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Hold Amount</fullName>
            </value>
            <value>
                <fullName>Refund Amount</fullName>
            </value>
            <value>
                <fullName>Other Amount</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
            <value>
                <fullName>Amounts Due to DIR</fullName>
            </value>
            <value>
                <fullName>DIR Attorney Fees</fullName>
                <isActive>false</isActive>
                <label>DIR Attorney Fees</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/fields/Posted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Posted_Amount__c</fullName>
    <description>Formerly Payment_Amount__c</description>
    <label>Posted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/NetWages__c.field-meta.xml
<CustomField>
    <fullName>NetWages__c</fullName>
    <description>value imported from form 40 import process</description>
    <label>Net Wages Assessed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payee__c/fields/Sum_Of_All_Payment_Records__c.field-meta.xml
<CustomField>
    <fullName>Sum_Of_All_Payment_Records__c</fullName>
    <description>Not on layout. Used in CashCalculatePrAmounts.cls to make sure Payees aren't overpaid.</description>
    <label>Sum Of All Payment Records</label>
    <summarizedField>Payment_Record__c.Payment_Amount__c</summarizedField>
    <summaryForeignKey>Payment_Record__c.Payee__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/Payment_Record__c.object-meta.xml
<CustomObject>
    <label>Payment Record</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Record__c/fields/Judgment_Payment__c.field-meta.xml
<CustomField>
    <fullName>Judgment_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Judgment Payment</label>
    <referenceTo>Judgment_Payment__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Liability_Payment__c.field-meta.xml
<CustomField>
    <fullName>Liability_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liability Payment</label>
    <referenceTo>Liability_Payment__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Payment_Applied_To__c.field-meta.xml
<CustomField>
    <fullName>Payment_Applied_To__c</fullName>
    <description>Usually populated by CashCreatePRs.cls when a Case Payment is Posted. Also populated by ReturnedVoidedReceipt.cls, creating Buybacks when a RCT is Returned.</description>
    <label>Payment Applied To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attorney Fees</fullName>
            </value>
            <value>
                <fullName>Filing Fees</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Judgment Amount</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Penalties</fullName>
            </value>
            <value>
                <fullName>Post-Hearing Interest</fullName>
            </value>
            <value>
                <fullName>Post-Judgment Interest</fullName>
            </value>
            <value>
                <fullName>Refund Amount</fullName>
            </value>
            <value>
                <fullName>Wage Interest</fullName>
            </value>
            <value>
                <fullName>Wages</fullName>
            </value>
            <value>
                <fullName>Buyback</fullName>
            </value>
            <value>
                <fullName>Amounts Due to DIR</fullName>
            </value>
            <value>
                <fullName>DIR Attorney Fees</fullName>
                <isActive>false</isActive>
                <label>DIR Attorney Fees</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CashPrRoundCorrSetupQable.cls
public with sharing class CashPrRoundCorrSetupQable implements Queueable {

    Map<Id, List<Payment_Record__c>> payeeIdToPrListMap;
    List<Payee__c> allPayeeList;
    List<Liability_Payment__c> allLpList; //Does not include CU-1s
    List<Judgment_Payment__c> allJpList;
    Case_Payment__c casePayment;
    Map<String, List<Id>> qableJobIdMap;

    public CashPrRoundCorrSetupQable(Case_Payment__c cp, Map<Id, List<Payment_Record__c>> payeeToPrList, List<Payee__c> allPayees,
                    List<Liability_Payment__c> allLps, List<Judgment_Payment__c> allJps, Map<String, List<Id>> qJobIdMap){
        payeeIdToPrListMap = payeeToPrList;
        allPayeeList = allPayees;
        allLpList = allLps;
        allJpList = allJps;
        casePayment = cp;
        qableJobIdMap = qJobIdMap;
    }

    public void execute(QueueableContext qc){

        try{
            
            //Only Payees with NetWages__c != null get to have their PRs rounding corrected.
            List<Payee__c> allNetWagesPayeeList = new List<Payee__c>();
            while(!allPayeeList.isEmpty()){
                Payee__c payee = allPayeeList.remove(0);
                if(payee.NetWages__c != null){
                    allNetWagesPayeeList.add(payee);
                }
            }
    
            //Determine if any of the PRs created belong to a net wages Payee. If not, we can skip the rounding setup.
            // E.g., a CP is allocated all to the Refund Amount, even though the case has net wages Payees.
            Boolean netWagesPrFound = false;
            Set<Id> prPayeeIds = payeeIdToPrListMap.keySet();
            for(Id prPayeeId : prPayeeIds){
                if(netWagesPrFound){
                    break;
                }
                for(Payee__c netWagesPayee : allNetWagesPayeeList){
                    if(prPayeeId == netWagesPayee.Id){
                        netWagesPrFound = true;
                        break;
                    }
                }
            }
    
            if(!allNetWagesPayeeList.isEmpty() && netWagesPrFound){
    
                //Map of LP, JP, and CU-1 IDs to their Posted Amount (Yea, we're throwing LP and JP Ids together,
                //  but they will still be unique from each other).
                Map<Id, Decimal> lpJpIdToAmountRemainingMap = new Map<Id, Decimal>();
                for(Liability_Payment__c lp : allLpList){
                    lpJpIdToAmountRemainingMap.put(lp.Id, lp.Posted_Amount__c);
                }

                for(Judgment_Payment__c jp : allJpList){
                    if(jp.Payment_Applied_To__c != 'Judgment Amount'){ //Judgment Amount JPs will never have PRs
                        lpJpIdToAmountRemainingMap.put(jp.Id, jp.Posted_Amount__c);
                    }
                }
    
                //Map of Payee IDs and their amounts owed, which is their NetWages__c amount - the sum of all their existing PRs
                //  already in the database (payee.NetWages__c - payee.Sum_Of_All_Payment_Records__c).
                Map<Id, Decimal> payeeIdToExistingAmountOwedMap = new Map<Id, Decimal>();
    
                //This map is similar to payeeIdToExistingAmountOwedMap above, except that it also takes into account
                //  the new PRs we've just created in CashCreatePrsQable and are about to insert.
                //  Used primarily to tell if we've over- or under-paid the Payee.
                Map<Id, Decimal> payeeIdToNewAmountOwedMap = new Map<Id, Decimal>();
    
                // Integer count = 0;
                for(Payee__c payee : allNetWagesPayeeList){
                    payeeIdToExistingAmountOwedMap.put(payee.Id, payee.NetWages__c - payee.Sum_Of_All_Payment_Records__c);
    
                    payeeIdToNewAmountOwedMap.put(payee.Id, payee.NetWages__c - payee.Sum_Of_All_Payment_Records__c);

                }
    
                //Subtract PR amounts from Payee amounts owed and LP/JP amount remaining
                for(Payee__c payee : allNetWagesPayeeList){

                    //For each PR under each Payee
                    for(Payment_Record__c pr : payeeIdToPrListMap.get(payee.Id)){  //******* for all PRs */
    
                        //Subtract the PR.Amount from the amount remaining on the LP or JP...
                        // System.debug('57 lp amount remaining before: ' + lpJpIdToAmountRemainingMap.get(pr.Liability_Payment__c));
                        lpJpIdToAmountRemainingMap.put(getPrParentId(pr), lpJpIdToAmountRemainingMap.get(getPrParentId(pr)) - pr.Payment_Amount__c);
                        // System.debug('59 lp amount remaining after: ' + lpJpIdToAmountRemainingMap.get(pr.Liability_Payment__c));
                        
                        // ...and also subtract it from the amount owed each Payee
                        // System.debug('82 payee amount owed before: ' + payeeIdToNewAmountOwedMap.get(payee.Id));
                        payeeIdToNewAmountOwedMap.put(payee.Id, payeeIdToNewAmountOwedMap.get(payee.Id) - pr.Payment_Amount__c);
                        // System.debug('84 payee amount owed after: ' + payeeIdToNewAmountOwedMap.get(payee.Id));
                    }
                }
    
                //For each LP or JP, if the sum of their PRs != their Posted_Amount__c, add that whole difference (whether it's + or -) to the
                //  1st Payee's PR under that LP or JP. "1st Payee" means the Payee, or one of the Payees, with the highest NetWages__c amount,
                //  as returned by the SOQL query in CashValidatePayees.cls.
    
                List<Id> lpOrJpIdList = new List<Id>(lpJpIdToAmountRemainingMap.keySet());

                for(Id lpOrJpId : lpOrJpIdList){
                    Decimal amountToAdd = lpJpIdToAmountRemainingMap.get(lpOrJpId);
                    // System.debug('82 amountToAdd: ' + amountToAdd);
                    if(amountToAdd != 0){
    
                        //Grab 1st net wages Payee returned by the SOQL query in CashValidatePayees.cls, who should be the, or one of the, Payees with the highest
                        //  NetWages__c amount.
                        Payee__c payee = allNetWagesPayeeList[0];

                        //This next line is for debugging only
                        // Decimal payeeNewAmountOwedOld = payeeIdToNewAmountOwedMap.get(payee.Id);
                        for(Payment_Record__c pr : payeeIdToPrListMap.get(payee.Id)){
                            
                            //Find that Payee's PR under this LP/JP
                            if(getPrParentId(pr) == lpOrJpId){
                                pr.Payment_Amount__c += amountToAdd;
                                lpJpIdToAmountRemainingMap.put(lpOrJpId, lpJpIdToAmountRemainingMap.get(lpOrJpId) - amountToAdd);
                                // System.debug('96 lpAmountRemaining should be 0: ' + lpJpIdToAmountRemainingMap.get(lpOrJpId));
                                payeeIdToNewAmountOwedMap.put(payee.Id, payeeIdToNewAmountOwedMap.get(payee.Id) - amountToAdd);
                                // System.debug('97 payeeNewAmountOwedOld: ' + payeeNewAmountOwedOld + ' should be ' + amountToAdd + '> payeeNewAmountOwedNew: ' + payeeIdToNewAmountOwedMap.get(payee.Id));
                                break;
                            }
                        }
                    }
                }
    
                // System.debug('105 lpJpIdToAmountRemainingMap: ' + lpJpIdToAmountRemainingMap);
    
                //Now that the LPs and JPs are exactly spent, we sum their Posted_Amounts and compare that to the sum
                //  of the existing Payee amounts owed (i.e., owed without these new PRs we're creating).
                /* Any changes to the filtering of the different types of LPs/JPs need to be also reflected in when PRs are generated in CashCreatePrsQable.cls */
                Decimal sumOfNewEmployeeLpsAndJps = 0.00;
                for(Liability_Payment__c lp : allLpList){
                    if(lp.Payment_Applied_To__c == 'Wages' ||
                            lp.Payment_Applied_To__c == 'Wage Interest' ||
                            (lp.Payment_Applied_To__c == 'Interest' && lp.Case_Issue_RecordTypeId__c == Schema.SObjectType.DIR_Violation__c.getRecordTypeInfosByName().get('WCA Violations').getRecordTypeId())){
                        sumOfNewEmployeeLpsAndJps += lp.Posted_Amount__c;
                    }
                }
                for(Judgment_Payment__c jp : allJpList){
                    if(jp.Payment_Applied_To__c == 'Post-Hearing Interest' || jp.Payment_Applied_To__c == 'Post-Judgment Interest'){
                        sumOfNewEmployeeLpsAndJps += jp.Posted_Amount__c;
                    }
                }
                
                Decimal sumOfPayeeExistingAmountsOwed = 0.00;
                List<Id> netWagesPayeeIdList = new List<Id>(); //TODO: no need to declare a new List<Id> here, just call each Payee.Id
                for(Payee__c netWagesPayee : allNetWagesPayeeList){
                    netWagesPayeeIdList.add(netWagesPayee.Id);
                }
                for(Id netWagesPayeeId : netWagesPayeeIdList){
                    sumOfPayeeExistingAmountsOwed += payeeIdToExistingAmountOwedMap.get(netWagesPayeeId);
                }
    
                //Grab Id of the LP or JP with the largest Posted_Amount__c. Assumes at this point that all NetWages payees will have a PR under all LPs/JPs, even if it's $0.
                //  First, grab LP and JP Ids of 1st (largest NewWages__c amount) Payee's PRs.
                List<Id> netWagesLpIdList = new List<Id>();
                List<Id> netWagesJpIdList = new List<Id>();
                for(Payment_Record__c pr : payeeIdToPrListMap.get(allNetWagesPayeeList[0].Id)){
                    if(pr.Liability_Payment__c != null){
                        netWagesLpIdList.add(pr.Liability_Payment__c);
                    }else{
                        netWagesJpIdList.add(pr.Judgment_Payment__c);
                    }
                }
    
                //  Then determine which of these has the largest Posted_Amount__c value.
                Id largestAmountPrParentId;
                Id largestAmountLpId;
                Decimal lpLargestAmount = 0.00;
                for(Liability_Payment__c lp : allLpList){
                    for(Id netWagesLpId : netWagesLpIdList){
                        if(lp.Id == netWagesLpId){
                            if(largestAmountLpId == null){
                                largestAmountLpId = lp.Id;
                                lpLargestAmount = lp.Posted_Amount__c;
                            }else{
                                if(lp.Posted_Amount__c > lpLargestAmount){
                                    largestAmountLpId = lp.Id;
                                    lpLargestAmount = lp.Posted_Amount__c;
                                }
                            }
                        }
                    }
                }
                Id largestAmountJpId;
                Decimal jpLargestAmount = 0.00;
                for(Judgment_Payment__c jp : allJpList){
                    for(Id netWagesJpId : netWagesJpIdList){
                        if(jp.Id == netWagesJpId){
                            if(largestAmountJpId == null){
                                largestAmountJpId = jp.Id;
                                jpLargestAmount = jp.Posted_Amount__c;
                            }else{
                                if(jp.Posted_Amount__c > jpLargestAmount){
                                    largestAmountJpId = jp.Id;
                                    jpLargestAmount = jp.Posted_Amount__c;
                                }
                            }
                        }
                    }
                }
                if(jpLargestAmount > lpLargestAmount){
                    largestAmountPrParentId = largestAmountJpId;
                }else{
                    largestAmountPrParentId = largestAmountLpId;
                }
                // System.debug('207 largestAmountPrParentId ' + largestAmountPrParentId);
    
                qableJobIdMap.put('PR Rounding Correction Setup', new List<Id>{qc.getJobId()});
    
                if(!Test.isRunningTest()){
                    System.enqueueJob(new CashPrRoundCorrBalancingQable(allNetWagesPayeeList, payeeIdToNewAmountOwedMap, payeeIdToPrListMap, lpJpIdToAmountRemainingMap,
                                                                                largestAmountPrParentId, sumOfNewEmployeeLpsAndJps, sumOfPayeeExistingAmountsOwed, casePayment, qableJobIdMap));
                }
    
    
            }else{ //No rounding correction needed, break payeeIdToPrListMap into a list of PRs for insert.
    
                List<Payment_Record__c> prsToInsert = new List<Payment_Record__c>();
                Set<Id> payeeIds = payeeIdToPrListMap.keySet();

                for(Id payeeId : payeeIds){
    
                    for(Payment_Record__c pr : payeeIdToPrListMap.remove(payeeId)){
                        if(pr.Payment_Amount__c > 0.00){
                            prsToInsert.add(pr);
                        }
                    }
                }

                qableJobIdMap.put('PR Rounding Correction Setup', new List<Id>{qc.getJobId()});
                System.enqueueJob(new CashInsertPrsQable(prsToInsert, casePayment, qableJobIdMap));
            }


        }catch(Exception e){

            String errorMessage = e.getTypeName() + ': [' + e.getLineNumber() + '] ' + e.getMessage() + '<br/>Stack trace:<br/>' + e.getStackTraceString();
            qableJobIdMap.put('PR Rounding Correction Setup', new List<Id>{qc.getJobId()});
            System.attachFinalizer(new CashPrFinalizer(casePayment.Id, casePayment.Name, qableJobIdMap, errorMessage));
        }

    }

    private static Id getPrParentId(Payment_Record__c pr){
        if(pr.Liability_Payment__c != null){
            return pr.Liability_Payment__c;
        }else{
            return pr.Judgment_Payment__c;
        }
    }
}