force-app/main/default/objects/Case_Payment__c/Case_Payment__c.object-meta.xml
<CustomObject>
    <description>Receipt applied to a Case. May have zero or more Liability Payments and zero or more Judgment Payments.</description>
    <label>Case Payment</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/Judgment_Payment__c.object-meta.xml
<CustomObject>
    <description>Records payments made against Judgments and their related interests, filing fees, and attorney fees.</description>
    <label>Judgment Payment</label>
    <nameField>
        <displayFormat>JP-{000000}</displayFormat>
        <label>Judgment Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/fields/Case_Payment__c.field-meta.xml
<CustomField>
    <fullName>Case_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Payment</description>
    <label>Case Payment</label>
    <referenceTo>Case_Payment__c</referenceTo>
    <relationshipLabel>Judgment Payments</relationshipLabel>
    <relationshipName>Judgment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Payment_On_Behalf_Of__c.field-meta.xml
<CustomField>
    <fullName>Payment_On_Behalf_Of__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment On Behalf Of</label>
    <referenceTo>Liable_Party__c</referenceTo>
    <relationshipLabel>Judgment Payments</relationshipLabel>
    <relationshipName>Judgment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/Liability_Payment__c.object-meta.xml
<CustomObject>
    <description>Case Payments allocated and posted to Case Issues.</description>
    <label>Liability Payment</label>
    <nameField>
        <displayFormat>LP-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Liability Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Payment__c/fields/Case_Payment__c.field-meta.xml
<CustomField>
    <fullName>Case_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Payment</label>
    <referenceTo>Case_Payment__c</referenceTo>
    <relationshipLabel>Liability Payments</relationshipLabel>
    <relationshipName>Liability_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Payment__c/fields/Payment_On_Behalf_Of__c.field-meta.xml
<CustomField>
    <fullName>Payment_On_Behalf_Of__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When saving a payment through the payment system, this is the party that the payment is on behalf of, if this applies. This rolls into the payments on the liable parties to reduce the balance due by the party.</description>
    <inlineHelpText>Party on whose behalf the payment was made.</inlineHelpText>
    <label>Payment On Behalf Of</label>
    <referenceTo>Liable_Party__c</referenceTo>
    <relationshipLabel>Payments Received</relationshipLabel>
    <relationshipName>Liability_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Util.cls
global with sharing class Util {
    
    global static boolean skipTrigger(){
        Boolean skip = false;
        
        String a;
        String b;
        String c;
        String d;
        String e;
        String f;
        String g;
        String h;
        String i;
        String j;
        String k;
        String l;
        String m;
        String n;
        String o;
        String p;
        String q;
        String r;
        String s;
        String t;
        String u;
        String v;
        String w;
        String x;
        String y;
        String z;
        
        if(test.isRunningTest()) return skip;
        if(ApexPages.currentPage() != null){
            System.debug('ApexPages.currentPage() = '+ApexPages.currentPage());
            String strUrl = ApexPages.currentPage().getUrl();
            strUrl = strUrl.split('apex/')[1];
            skip =  strUrl.containsIgnoreCase('attachmentsplus');
        }

        return skip;
    }
    
    /*

    
    public static List<SObject> selectAllById(String sobjectName, List<String> ids) {
        Set<String> fieldNames = schema.describeSObjects(new String[] {sobjectName})[0].fields.getMap().keyset();
        List<String> iterableFields = new List<String>(fieldNames);
        String adtlParams = '';
        if(sObjectName == 'Case_Payment__c'){
            adtlParams += ''
            +',(SELECT Id, Payment_on_Behalf_of__c FROM Liability_Payments__r)'
            +',(SELECT Id, Payment_on_Behalf_of__c FROM Judgment_Payments__r)';
        }
        String queryString = String.format('SELECT {0} {1} FROM {2}', new String[] {String.join(iterableFields, ','), adtlParams, sobjectName});
        if(ids != null) {
            queryString += ' WHERE ID IN :ids';
        }
        System.debug('@@@queryString: '+queryString);
        return Database.query(queryString);
    }
    
    public static List<sObject> queryStarByObjectNameAndId(String sObjectName, String idType, String idValue, List<String> additionalFields, String OrderBy, Integer recordLimit){

        SObjectType sObjectType = Schema.getGlobalDescribe().get(sObjectName);
        Map<String,Schema.SObjectField> fldObjMap = new Map<String,Schema.SObjectField>();
        
        fldObjMap = sObjectType.getDescribe().fields.getMap();
        
        List<Schema.SObjectField> fldObjMapValues = fldObjMap.values();
        String queryStr = 'SELECT ';
        for(Schema.SObjectField s : fldObjMapValues){
            Schema.DescribeFieldResult fieldResult= s.getDescribe();
           
            String fieldName = fieldResult.getName();
            if (fieldResult.isAccessible()) {
                queryStr += fieldName + ',';
                
            }
        }
        
        if(additionalFields != null && !additionalFields.isEmpty()){
            for(String s : additionalFields){
                queryStr += s+',';
            }
        }
        
        queryStr = queryStr.subString(0, queryStr.length() - 1);
        
        queryStr += ' FROM '+ sObjectName;

        if(!String.isBlank(idType) && !String.isBlank(idValue)){
            queryStr += ' WHERE '+idType+' = \''+idValue+'\'';
        }
        if(!String.isBlank(OrderBy)){
            queryStr += ' ORDER BY '+OrderBy;
        }
        if(recordLimit != null){
            queryStr += ' LIMIT '+string.valueOf(recordLimit);
        }

        System.debug('@@@QueryString: '+queryStr);
        return Database.query(queryStr);
    }*/
}