force-app/main/default/objects/Appeal__c/Appeal__c.object-meta.xml
<CustomObject>
    <description>This is used for a Request for Citation Appeal Hearing associated with a DIR BOFE Case.  This may be repurposed for specific purposes.</description>
    <label>Appeal</label>
    <nameField>
        <displayFormat>APL-{000000}</displayFormat>
        <label>Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appeals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appeal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Appeals</relationshipLabel>
    <relationshipName>Appeals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/fields/Estimated_Length_of_Hearing_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Length_of_Hearing_In_Minutes__c</fullName>
    <inlineHelpText>The estimate length of this hearing in minutes.  i.e. 60 minutes for 1 hour, or 90 minutes for 1 hour 30 minutes.</inlineHelpText>
    <label>Estimated Length of Hearing (In Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appeal__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liability</label>
    <referenceTo>Liability__c</referenceTo>
    <relationshipLabel>Appeals</relationshipLabel>
    <relationshipName>Appeals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Citation_Number__c.field-meta.xml
<CustomField>
    <fullName>Citation_Number__c</fullName>
    <label>Citation Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Hearing_Date__c.field-meta.xml
<CustomField>
    <fullName>Hearing_Date__c</fullName>
    <description>Settlement Hearing Date for PAGA Case</description>
    <inlineHelpText>Settlement Hearing Date for PAGA Case</inlineHelpText>
    <label>Settlement Hearing Date for PAGA Case</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Violations are tied together as an assessment.</description>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hearing__c/Hearing__c.object-meta.xml
<CustomObject>
    <description>This stores all of the hearings/conferences related to an Appeal, which gets information from the Assessment, Liability Appeal, Case, and Account from a relationship level.</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Meeting ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hearing__c/fields/Appeal__c.field-meta.xml
<CustomField>
    <fullName>Appeal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Appeal this Hearing is related to.</description>
    <inlineHelpText>This is the Appeal this Hearing is related to.</inlineHelpText>
    <label>Appeal</label>
    <referenceTo>Appeal__c</referenceTo>
    <relationshipName>Hearings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Lookup to parent case. Used for easy identification and for rules related to referrals that deal with hearing dates.</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Hearings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>When the Hearing Result is entered, the Hearing Officer needs to have an effective date to set. The Hearing Officer can take some time before entering a decision, and the effective date is not necessarily the same as the Hearing Date.</description>
    <inlineHelpText>Date on which the hearing results become effective. May be different from the hearing date or the date the results are entered.</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Failure_to_Appear__c.field-meta.xml
<CustomField>
    <fullName>Failure_to_Appear__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set by vfp when entering hearing results. Also on W CA meetings when applicable to a Plaintiff.</description>
    <inlineHelpText>Appellant / Plaintiff failed to appear at meeting.</inlineHelpText>
    <label>Failure to Appear</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Hearing_Date__c.field-meta.xml
<CustomField>
    <fullName>Hearing_Date__c</fullName>
    <label>Legacy Meeting Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Length_of_Hearing__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Hearing__c</fullName>
    <inlineHelpText>Length of Meeting in minutes</inlineHelpText>
    <label>Length of Meeting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hearing__c/fields/Minutes_to_Write_Findings__c.field-meta.xml
<CustomField>
    <fullName>Minutes_to_Write_Findings__c</fullName>
    <description>Length of minutes to write Findings</description>
    <label>Length of Minutes to Write Findings</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hearing_Liability__c/Hearing_Liability__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between the Hearings related to an Appeal, and the Liabilities on the Appeal.</description>
    <label>Hearing Liability</label>
    <nameField>
        <displayFormat>HL-{000000}</displayFormat>
        <label>Hearing Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hearing Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hearing_Liability__c/fields/Hearing__c.field-meta.xml
<CustomField>
    <fullName>Hearing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a link to the hearing for this liability.</description>
    <inlineHelpText>This is a link to the hearing for this liability.</inlineHelpText>
    <label>Hearing</label>
    <referenceTo>Hearing__c</referenceTo>
    <relationshipLabel>Hearing Liabilities</relationshipLabel>
    <relationshipName>Hearing_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hearing_Liability__c/fields/Liability_Appeal__c.field-meta.xml
<CustomField>
    <fullName>Liability_Appeal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Liability Appeal Record that must exist in order to schedule a Hearing against it.</description>
    <inlineHelpText>This is the Liability Appeal Record that must exist in order to schedule a Hearing against it.</inlineHelpText>
    <label>Liability Appeal</label>
    <referenceTo>Liability_Appeal__c</referenceTo>
    <relationshipLabel>Hearing Liabilities</relationshipLabel>
    <relationshipName>Hearing_Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability__c/Liability__c.object-meta.xml
<CustomObject>
    <description>This objects contains the Liability against an Assessment.</description>
    <label>Liability</label>
    <nameField>
        <displayFormat>LIA-{000000}</displayFormat>
        <label>Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>This creates a lookup relationship between a Liability and an Assessment.  This field is required.</description>
    <inlineHelpText>This creates a lookup relationship between a Liability and an Assessment.  This field is required.</inlineHelpText>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipLabel>Liabilities</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related case to the liability</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Liability</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability__c/fields/Legal_Consult__c.field-meta.xml
<CustomField>
    <fullName>Legal_Consult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Provides a lookup to the Internal Employee who serves as the legal consult on a liability</description>
    <inlineHelpText>Select the person who serves as the legal consult for this liability.</inlineHelpText>
    <label>Legal Consult</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Liability</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links a Meeting record to a Liability record in order to migrate the Hearing Officer/Courthouse information from the Meeting into output documents via Conga.</description>
    <label>Meeting</label>
    <referenceTo>Hearing__c</referenceTo>
    <relationshipLabel>Liability</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability_Appeal__c/Liability_Appeal__c.object-meta.xml
<CustomObject>
    <description>Junction object between liablities and appeals. Allows a liability to have multiple appeals where necessary.</description>
    <label>Liability Appeal</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>Liability Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability Appeals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Appeal__c/fields/Appeal__c.field-meta.xml
<CustomField>
    <fullName>Appeal__c</fullName>
    <inlineHelpText>Relationship to the appeal for this liability</inlineHelpText>
    <label>Appeal</label>
    <referenceTo>Appeal__c</referenceTo>
    <relationshipLabel>Liability Appeals</relationshipLabel>
    <relationshipName>Liability_Appeals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability_Appeal__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <inlineHelpText>Relationship to the Liability for this appeal</inlineHelpText>
    <label>Liability</label>
    <referenceTo>Liability__c</referenceTo>
    <relationshipLabel>Liability Appeals</relationshipLabel>
    <relationshipName>Liability_Appeals</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HearingResults.cls
public with sharing class HearingResults {

    public Hearing__c hearing { get; set; }
    
    public List<HearingLiability> liabilities { get; set; }
    
    public HearingResults(ApexPages.StandardController sc) {
        hearing = [SELECT Id, Name, Failure_to_Appear__c, Appeal__r.Case__r.Case_Number__c, Appeal__r.Name, Hearing_Date__c, Appeal__r.Estimated_Length_of_Hearing_In_Minutes__c, Appeal__r.Case__r.Assigned_Deputy__r.Name, Appeal__r.Case__r.Assigned_Deputy__r.Manager__r.Name, Effective_date__c, Length_Of_Hearing__c, Minutes_to_Write_Findings__c FROM Hearing__c WHERE Id = :sc.getId()];
        
        liabilities = new List<HearingLiability>();
        Set<Id> assessIds = new Set<Id>();
        List<Hearing_Liability__c> liabs = [SELECT Id, Liability_Appeal__r.Liability__r.Assessment__c, Liability_Appeal__r.Liability__r.Citation_Number__c, Results__c, Hearing_Notes__c, Liability_Appeal__r.Liability__c FROM Hearing_Liability__c WHERE Hearing__c = :hearing.Id];
        for (Hearing_Liability__c liab : liabs) {
            liabilities.add(new HearingLiability(liab));
            if (liab.Liability_Appeal__r.Liability__r.Assessment__c != null){
                assessIds.add(liab.Liability_Appeal__r.Liability__r.Assessment__c);
            }
        }
        
        // S. Thornton 2/4/2016 Added Status__c to the SELECT statement.
        List<DIR_Violation__c> allViols = [SELECT Id, Name, Assessment__c, Violation_Type__r.Name, Civil_Penalty_Section_Conga__c, Status__c, Original_Penalty_Assessment_Amount__c, Total_Wage_Interest_Amount__c, Citation_Amount__c, Original_Wage_Assessment_Amount__c, Wages_Due__c, Appeal_Finding_Date__c FROM DIR_Violation__c WHERE Assessment__c IN :assessIds];
        for (DIR_Violation__c viol : allViols) {
            for (HearingLiability hl : liabilities) {
                if (hl.liability.Liability_Appeal__r.Liability__r.Assessment__c == viol.Assessment__c) {
                    hl.violations.add(viol);
                }
            }
        }
    }
    
    public PageReference SaveHearing() {
        
        Savepoint sp = Database.setSavepoint();
        
        try {
            hearing.Status__c = 'Completed';
            update hearing;
            List<Liability__c> liabList = new List<Liability__c>();
            List<Hearing_Liability__c> liabs = new List<Hearing_Liability__c>();
            List<DIR_Violation__c> viols = new List<DIR_Violation__c>();
            Map<Id, String> resultsMap = new Map<Id, String>();
            for (HearingLiability hl : liabilities) {
                liabs.add(hl.liability);
                hl.liab.Status__c = hl.liability.Results__c;
                liabList.add(hl.liab);
                for (DIR_Violation__c viol : hl.violations) {
                    /*
                    if (hl.liability.Results__c == 'Affirmed')
                        viol.Status__c = 'Affirmed';
                    if (hl.liability.Results__c == 'Modified')
                        viol.Status__c = 'Modified';
                    */
                    // S. Thornton 2/4/2016 Commented out the following line to allow the user selected case violations status to be saved.
                    /* viol.Status__c = hl.liability.Results__c; */
                    viol.Appeal_Finding_Date__c = hearing.Effective_Date__c;
                    if(!resultsMap.containsKey(viol.Id)){
                        resultsMap.put(viol.Id, viol.Status__c);
                        viols.add(viol);
                    }
                    else if(resultsMap.containsKey(viol.Id)){
                        String result = resultsMap.get(viol.Id);
                        if(viol.Status__c != result){
                            List<String> tempList = new List<String>();
                            for(HearingLiability h : liabilities){
                                if(h.liability.Liability_Appeal__r.Liability__r.Assessment__c == viol.Assessment__c){
                                    tempList.add(h.liability.Liability_Appeal__r.Liability__r.Citation_Number__c);
                                }
                            }
                            String errorString = 'You are attempting to update Case Violation: ' + viol.Name + ' from Citations: ';
//Next 2 lines below appended to line above. 5/31/19
/*                          errorString += viol.Name;
                            errorString += ' from Citations: '; */
                            for(String s : tempList){
                                errorString += (s+', ');
                            }
                            errorString = errorString.subString(0, errorString.length() - 2);
                            errorString += ' with different Hearing Results. Please ensure that the violation is set to the same Result.';
                            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, errorString));
                            return null;
                        }
                        else{
                            continue;
                        }
                    }
                }
            }
            update liabs;
            update viols;
            update liabList;
            
        } catch (Exception ex) {
            ApexPages.addMessages(ex);
            Database.rollback(sp);
            return null;
        }
        
        return new PageReference('/' + hearing.Id);
        
    }
    
    public class HearingLiability {
        
        public Hearing_Liability__c liability { get; set; }
        public List<DIR_Violation__c> violations { get; set; }
        public Liability__c liab { get; set; }
        
        public HearingLiability(Hearing_Liability__c hl) {
            
            liability = hl;
            violations = new List<DIR_Violation__c>();
            liab = hl.Liability_Appeal__r.Liability__r;         
        }
    }

}