force-app/main/default/objects/Appeal__c/Appeal__c.object-meta.xml
<CustomObject>
    <description>This is used for a Request for Citation Appeal Hearing associated with a DIR BOFE Case.  This may be repurposed for specific purposes.</description>
    <label>Appeal</label>
    <nameField>
        <displayFormat>APL-{000000}</displayFormat>
        <label>Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appeals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appeal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Appeals</relationshipLabel>
    <relationshipName>Appeals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeal__c/fields/Citation_Selected__c.field-meta.xml
<CustomField>
    <fullName>Citation_Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks if a citation has been selected</description>
    <label>Citation Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appeal__c/fields/Estimated_Length_of_Hearing_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Length_of_Hearing_In_Minutes__c</fullName>
    <inlineHelpText>The estimate length of this hearing in minutes.  i.e. 60 minutes for 1 hour, or 90 minutes for 1 hour 30 minutes.</inlineHelpText>
    <label>Estimated Length of Hearing (In Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appeal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received - Timely</fullName>
                <default>true</default>
                <label>Received - Timely</label>
            </value>
            <value>
                <fullName>Received - Untimely</fullName>
            </value>
            <value>
                <fullName>Sent to Calendar Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Accepted Representation</fullName>
            </value>
            <value>
                <fullName>Trial Pending</fullName>
            </value>
            <value>
                <fullName>Court Decision</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Affirmed</fullName>
            </value>
            <value>
                <fullName>Modified - Affirmed</fullName>
            </value>
            <value>
                <fullName>Remanded for Investigation</fullName>
            </value>
            <value>
                <fullName>Reversed and Dismissed</fullName>
            </value>
            <value>
                <fullName>Reversed to Cause</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appeal__c/fields/X2810_3_Case__c.field-meta.xml
<CustomField>
    <fullName>X2810_3_Case__c</fullName>
    <label>2810.3 Case</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessments__c/fields/Appeal_Deadline_Days__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Days__c</fullName>
    <description>Set as max of appeal deadline from child case violation records via trigger on case violation object</description>
    <label>Appeal Deadline (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Appeal_Deadline_Selector__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Selector__c</fullName>
    <label>Appeal Deadline Selector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Days</fullName>
            </value>
            <value>
                <fullName>Calendar Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</description>
    <inlineHelpText>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</inlineHelpText>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability__c/Liability__c.object-meta.xml
<CustomObject>
    <description>This objects contains the Liability against an Assessment.</description>
    <label>Liability</label>
    <nameField>
        <displayFormat>LIA-{000000}</displayFormat>
        <label>Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related case to the liability</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Liability</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>If Status = Admin Dismissed, must decide if associated violations should be Admin Dismissed as well and Penalties zeroed out.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administrative Dismissal</fullName>
            </value>
            <value>
                <fullName>Affirmed</fullName>
            </value>
            <value>
                <fullName>Appeal Withdrawn</fullName>
            </value>
            <value>
                <fullName>Canceled-Invalid</fullName>
            </value>
            <value>
                <fullName>Demand Non-citable</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Hearing Complete</fullName>
            </value>
            <value>
                <fullName>Judgment Accepted</fullName>
            </value>
            <value>
                <fullName>Judgment Rejected</fullName>
            </value>
            <value>
                <fullName>Modified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Out of Statute</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Pending Writ</fullName>
            </value>
            <value>
                <fullName>Referred for Judgment</fullName>
            </value>
            <value>
                <fullName>Request Dismissal</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Stop Order Only</fullName>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Writ Affirmed</fullName>
            </value>
            <value>
                <fullName>Writ Modified</fullName>
            </value>
            <value>
                <fullName>Writ Received</fullName>
            </value>
            <value>
                <fullName>Writ Remanded</fullName>
            </value>
            <value>
                <fullName>Writ Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Appeal__c/Liability_Appeal__c.object-meta.xml
<CustomObject>
    <description>Junction object between liablities and appeals. Allows a liability to have multiple appeals where necessary.</description>
    <label>Liability Appeal</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>Liability Appeal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability Appeals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Appeal__c/fields/Appeal__c.field-meta.xml
<CustomField>
    <fullName>Appeal__c</fullName>
    <inlineHelpText>Relationship to the appeal for this liability</inlineHelpText>
    <label>Appeal</label>
    <referenceTo>Appeal__c</referenceTo>
    <relationshipLabel>Liability Appeals</relationshipLabel>
    <relationshipName>Liability_Appeals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/appealTriggerTest.cls
@isTest
public with sharing class appealTriggerTest {
    
    public static testMethod void TestWithdrawnAppeals1() {
        Account acc = new Account();
        acc.Name = 'name';
        acc.ShippingPostalCode = '234889';
        insert acc;
        
        DIR_Case__c c = new DIR_Case__c();
        c.Employer__c = acc.Id;
        insert c;
        
        Appeal__c appeal1 = new Appeal__c();
        appeal1.Status__c = 'Received - Timely';
        //appeal1.Case__c = c.Id;
        appeal1.X2810_3_Case__c = 'Yes';
        appeal1.Citation_Selected__c = true;
        appeal1.Estimated_Length_of_Hearing_In_Minutes__c = 60;
        insert appeal1;
        
        Assessments__c assesment = new Assessments__c();
        assesment.Appeal_Deadline_Selector__c = 'Business Days';
        assesment.Appeal_Deadline_Days__c = 15;
        assesment.Case_Management__c = c.Id;
        insert assesment;

        Liability__c liability1 = new Liability__c();
        liability1.Assessment__c = assesment.Id;
        liability1.Status__c = 'New';
        liability1.Case_Management__c = c.Id;
        insert liability1;
        
        Liability_Appeal__c la = new Liability_Appeal__c();
        la.Appeal__c = appeal1.Id;
        la.Liability__c = liability1.Id;
        la.Appeal_Status__c = 'Received - Untimely';
        insert la;
        
        test.startTest();
        
        Appeal__c app = [SELECT Id, Status__c FROM Appeal__c WHERE Id =: appeal1.Id];
        app.Status__c = 'Withdrawn';
        update app;
        
        test.stopTest();
    }
    
    public static testMethod void TestWithdrawnAppeals2() {
        Account acc = new Account();
        acc.Name = 'name';
        acc.ShippingPostalCode = '234889';
        insert acc;
        
        DIR_Case__c c = new DIR_Case__c();
        c.Employer__c = acc.Id;
        //c.RecordTypeId = caseRecordType.Id;
        insert c;
        
        Appeal__c appeal1 = new Appeal__c();
        appeal1.Status__c = 'Received - Timely';
        appeal1.Case__c = c.Id;
        appeal1.X2810_3_Case__c = 'Yes';
        appeal1.Citation_Selected__c = true;
        appeal1.Estimated_Length_of_Hearing_In_Minutes__c = 60;
        insert appeal1;
        
        Appeal__c appeal2 = new Appeal__c();
        appeal2.Status__c = 'Received - Timely';
        appeal2.Case__c = c.Id;
        appeal2.X2810_3_Case__c = 'Yes';
        appeal2.Citation_Selected__c = true;
        appeal2.Estimated_Length_of_Hearing_In_Minutes__c = 60;
        insert appeal2;
        
        Assessments__c assesment = new Assessments__c();
        assesment.Appeal_Deadline_Selector__c = 'Business Days';
        assesment.Appeal_Deadline_Days__c = 15;
        assesment.Case_Management__c = c.Id;
        insert assesment;

        Liability__c liability1 = new Liability__c();
        liability1.Assessment__c = assesment.Id;
        liability1.Status__c = 'New';
        liability1.Case_Management__c = c.Id;
        insert liability1;
        
        Liability_Appeal__c la = new Liability_Appeal__c();
        la.Appeal__c = appeal1.Id;
        la.Liability__c = liability1.Id;
        la.Appeal_Status__c = 'Received - Untimely';
        insert la;
        
        Liability_Appeal__c la1 = new Liability_Appeal__c();
        la1.Appeal__c = appeal2.Id;
        la1.Liability__c = liability1.Id;
        la.Appeal_Status__c = 'Received - Untimely';
        insert la1;
        
        test.startTest();
        
        Appeal__c app = [SELECT Id, Status__c FROM Appeal__c WHERE Id =: appeal1.Id];
        app.Status__c = 'Withdrawn';
        update app;
        
        test.stopTest();
    }
}