force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessments__c/fields/Total_Citation_Penalties_Assessed__c.field-meta.xml
<CustomField>
    <fullName>Total_Citation_Penalties_Assessed__c</fullName>
    <label>Total Citation Penalties Assessed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Total_Citations_Penalties_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Citations_Penalties_Paid__c</fullName>
    <label>Total Citations Penalties Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Total_Interest_Assessed__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Assessed__c</fullName>
    <description>Interest assessed on the violations</description>
    <inlineHelpText>Total of interest assessed on the violations</inlineHelpText>
    <label>Total Interest Assessed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Total_Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Paid__c</fullName>
    <inlineHelpText>Total of all payments allocated to interest on violations on this assessment</inlineHelpText>
    <label>Total Interest Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Total_Wages_Assessed__c.field-meta.xml
<CustomField>
    <fullName>Total_Wages_Assessed__c</fullName>
    <label>Total Wages Assessed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Total_Wages_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Wages_Paid__c</fullName>
    <label>Total Wages Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Violations are tied together as an assessment.</description>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Citation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Citation_Amount__c</fullName>
    <description>Previous label: Modified To Penalty Assessment Amount</description>
    <label>Penalty Assessment Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Interest_Payments_Received__c.field-meta.xml
<CustomField>
    <fullName>Interest_Payments_Received__c</fullName>
    <description>Total of Liability Payments under this Case Issue allocated to Interest. Populated by LiabilityPaymentTrigger -&gt; LiabilityPaymentMethods apex classes.</description>
    <inlineHelpText>Total of all funds received allocated to Interest.</inlineHelpText>
    <label>Interest Payments Rec'd</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Penalty_Payments_Received__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Payments_Received__c</fullName>
    <description>Total of Liability Payments under this Case Issue allocated to Penalties. Populated by LiabilityPaymentTrigger -&gt; LiabilityPaymentMethods apex classes.</description>
    <inlineHelpText>Total of all funds received allocated to Penalties.</inlineHelpText>
    <label>Civil Penalty Payments Rec'd</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defaults to "open" but may be set to "affirmed" or "modified" by the hearing process via the hearing results vfp.</description>
    <inlineHelpText>If Sr. administratively dismisses violation, they must also adjust penalties and/or wages due to zero.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>NTD - Full Compliance</fullName>
            </value>
            <value>
                <fullName>NTD - No Compliance</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Affirmed</fullName>
            </value>
            <value>
                <fullName>Modified</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Administrative Dismissal</fullName>
            </value>
            <value>
                <fullName>De Novo Appeal</fullName>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
            </value>
            <value>
                <fullName>Appeal Withdrawn</fullName>
            </value>
            <value>
                <fullName>Request Dismissal</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Referred for Judgment</fullName>
            </value>
            <value>
                <fullName>Judgment Accepted</fullName>
            </value>
            <value>
                <fullName>Judgment Rejected</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Writ Dismissed</fullName>
            </value>
            <value>
                <fullName>Writ Settled by Legal</fullName>
            </value>
            <value>
                <fullName>Writ Affirmed</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Offer in Compromise</fullName>
            </value>
            <value>
                <fullName>Self Audit Discount</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Canceled - Invalid</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Judgment</fullName>
            </value>
            <value>
                <fullName>Claimant Withdrew</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Dismissed at Conference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Total_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount__c</fullName>
    <inlineHelpText>Interest amount due on the violation.</inlineHelpText>
    <label>Total Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Total_Wage_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Wage_Interest_Amount__c</fullName>
    <label>Total Wage Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Wage_Payments_Received__c.field-meta.xml
<CustomField>
    <fullName>Wage_Payments_Received__c</fullName>
    <description>Total of Liability Payments under this Case Issue allocated to regular wages. Populated by LiabilityPaymentTrigger -&gt; LiabilityPaymentMethods apex classes.</description>
    <inlineHelpText>Total of all funds received allocated to regular Wages after claim / citation was issued.</inlineHelpText>
    <label>EE Payments Rec'd</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Wages_Due__c.field-meta.xml
<CustomField>
    <fullName>Wages_Due__c</fullName>
    <description>Regular, non-interest, wages due on this violation. Derived from the Wage Assessment Formula on the violation type and the variable values entered by the user when creating the violation.</description>
    <inlineHelpText>This is the regular wage amount due including the most recent modification (if any).</inlineHelpText>
    <label>EE(s) Amt Assessed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Wages_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Wages_Due_Date__c</fullName>
    <description>Date the wages are considered due the employee. For WCA, this is set by the hearing officer on a violation by violation basis at the hearing. This date factors into the calculation of the interest due on the violation.</description>
    <inlineHelpText>Date the wages are due the employee.</inlineHelpText>
    <label>Amounts Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/caseViolationRollupAmountsAction.cls
public with sharing class caseViolationRollupAmountsAction extends TriggerAction{
    
    public boolean shouldRun;

    set<Id> assessmentIds = new set<Id>();
    set<Id> canceledViols = new set<Id>();

    public caseViolationRollupAmountsAction(Map<Id, sObject> triggerNewMap){ //is insert
        super(triggerNewMap);
        
        for(sObject sObj : triggerNewMap.values()){
            DIR_Violation__c newViol = (DIR_Violation__c)sObj;
            if(newViol.Assessment__c != null){
                assessmentIds.add(newViol.Assessment__c);
            }
        }
    }

    public caseViolationRollupAmountsAction(Map<Id, sObject> triggerNewMap, Map<Id, sObject> triggerOldMap){ //is update
        super(triggerNewMap, triggerOldMap);

        for(sObject sObj : triggerNewMap.values()){
            DIR_Violation__c newViol = (DIR_Violation__c)sObj;
            DIR_Violation__c oldViol = (DIR_Violation__c)triggerOldMap.get(sObj.Id);
            if(newViol.Assessment__c != null 
                &&(newViol.Citation_Amount__c != oldViol.Citation_Amount__c
                    || newViol.Wages_Due__c != oldViol.Wages_Due__c
                    || newViol.Wages_Due_Date__c != oldViol.Wages_Due_Date__c
                    || newViol.Penalty_Payments_Received__c != oldViol.Penalty_Payments_Received__c
                    || newViol.Wage_Payments_Received__c != oldViol.Wage_Payments_Received__c
                    || newViol.Total_Interest_Amount__c != oldViol.Total_Interest_Amount__c
                    || newViol.Total_Wage_Interest_Amount__c != oldViol.Total_Wage_Interest_Amount__c
                    || newViol.Interest_Payments_Received__c != oldViol.Interest_Payments_Received__c
                    || (newViol.Status__c == 'Canceled - Invalid' && oldViol.Status__c != 'Canceled - Invalid')
                    || (newViol.Status__c != 'Canceled - Invalid' && oldViol.Status__c == 'Canceled - Invalid'))) {

                assessmentIds.add(newViol.Assessment__c);
                if(newViol.Status__c != 'Canceled - Invalid'){
                    canceledViols.add(newViol.Id);
                }
            }
        }
    }

    public override boolean shouldRunOnInsert() { 
        shouldRun = assessmentIds.isEmpty() ? false : true;
        return shouldRun; 
    }
     
    public override boolean shouldRunOnDelete() { return false; } 
    
    public override boolean shouldRunOnUpdate() {
        shouldRun = assessmentIds.isEmpty() ? false : true;
        return shouldRun;
    } 
    
    public override void doAction() {

        if(hasBeenAudited()) return;

        List<Assessments__c> updateList = new List<Assessments__c>();

        map<Id, Assessments__c> assessmentMap = new map<Id, Assessments__c>([
                                                                             SELECT Id, Name, Total_Citation_Penalties_Assessed__c, Total_Citations_Penalties_Paid__c, Total_Interest_Assessed__c, Total_Wage_Interest_Amount__c,
                                                                                    Total_Interest_Paid__c, Total_Wages_Assessed__c, Total_Wages_Paid__c,
                                                                                    (
                                                                                     SELECT Citation_Amount__c, Penalty_Payments_Received__c, Total_Interest_Amount__c, Total_Wage_Interest_Amount__c, Interest_Payments_Received__c, 
                                                                                            Wages_Due__c, Wage_Payments_Received__c, Status__c
                                                                                     FROM Case_Violations__r
                                                                                    )
                                                                             FROM Assessments__c
                                                                             WHERE Id IN: assessmentIds
                                                                            ]);

        Map<Id, Map<String, Decimal>> amountsMap = new Map<Id, Map<String, Decimal>> ();
        for(Assessments__c a : assessmentMap.values()){
            if(!a.Case_Violations__r.isEmpty()){
                for(DIR_Violation__c viol : a.Case_Violations__r){
                    Map<String, Decimal> valMap;
                    boolean invalid = Viol.Status__c == 'Canceled - Invalid' ? true : false;
                    if(!amountsMap.containsKey(a.Id)){
                        valMap = new Map<String, Decimal>();
                        valMap.put('Total_Citation_Penalties_Assessed__c', ( (viol.Citation_Amount__c == null || invalid) ? 0 : viol.Citation_Amount__c) );
                        valMap.put('Total_Citations_Penalties_Paid__c', ( (viol.Penalty_Payments_Received__c == null || invalid) ? 0 : viol.Penalty_Payments_Received__c) );
                        valMap.put('Total_Interest_Assessed__c', ( (viol.Total_Interest_Amount__c == null || invalid) ? 0 : viol.Total_Interest_Amount__c) );
                        valMap.put('Total_Wage_Interest_Amount__c', ( (viol.Total_Wage_Interest_Amount__c == null || invalid) ? 0 : viol.Total_Wage_Interest_Amount__c) );
                        valMap.put('Total_Interest_Paid__c', ( (viol.Interest_Payments_Received__c == null || invalid) ? 0 : viol.Interest_Payments_Received__c) );
                        valMap.put('Total_Wages_Assessed__c', ( (viol.Wages_Due__c == null || invalid) ? 0 : viol.Wages_Due__c) );
                        valMap.put('Total_Wages_Paid__c', ( (viol.Wage_Payments_Received__c == null || invalid) ? 0 : viol.Wage_Payments_Received__c) );
                    }
                    else{
                        Decimal amt;
                        valMap = amountsMap.get(a.Id);

                        amt = valMap.get('Total_Citation_Penalties_Assessed__c') + ( (viol.Citation_Amount__c == null || invalid) ? 0 : viol.Citation_Amount__c);
                        valMap.put('Total_Citation_Penalties_Assessed__c', amt);

                        amt = valMap.get('Total_Citations_Penalties_Paid__c') + ( (viol.Penalty_Payments_Received__c == null || invalid) ? 0 : viol.Penalty_Payments_Received__c);
                        valMap.put('Total_Citations_Penalties_Paid__c', amt);

                        amt = valMap.get('Total_Interest_Assessed__c') + ( (viol.Total_Interest_Amount__c == null || invalid) ? 0 : viol.Total_Interest_Amount__c);
                        valMap.put('Total_Interest_Assessed__c', amt);

                        amt = valMap.get('Total_Wage_Interest_Amount__c') + ( (viol.Total_Wage_Interest_Amount__c == null || invalid) ? 0 : viol.Total_Wage_Interest_Amount__c);
                        valMap.put('Total_Wage_Interest_Amount__c', amt);
                        
                        amt = valMap.get('Total_Interest_Paid__c') + ( (viol.Interest_Payments_Received__c == null || invalid) ? 0 : viol.Interest_Payments_Received__c);
                        valMap.put('Total_Interest_Paid__c', amt);

                        amt = valMap.get('Total_Wages_Assessed__c') + ( (viol.Wages_Due__c == null || invalid) ? 0 : viol.Wages_Due__c);
                        valMap.put('Total_Wages_Assessed__c', amt);

                        amt = valMap.get('Total_Wages_Paid__c') + ( (viol.Wage_Payments_Received__c == null || invalid) ? 0 : viol.Wage_Payments_Received__c);
                        valMap.put('Total_Wages_Paid__c', amt);
                    }
                    amountsMap.put(a.Id, valMap);
                }
                Map<String, Decimal> valMap = amountsMap.get(a.Id);

                a.Total_Citation_Penalties_Assessed__c = valMap.get('Total_Citation_Penalties_Assessed__c');
                a.Total_Citations_Penalties_Paid__c = valMap.get('Total_Citations_Penalties_Paid__c');
                a.Total_Interest_Assessed__c = valMap.get('Total_Interest_Assessed__c');
                a.Total_Interest_Paid__c = valMap.get('Total_Interest_Paid__c');
                a.Total_Wages_Assessed__c = valMap.get('Total_Wages_Assessed__c');
                a.Total_Wages_Paid__c = valMap.get('Total_Wages_Paid__c');
                a.Total_Wage_Interest_Amount__c = valMap.get('Total_Wage_Interest_Amount__c');


                updateList.add(a);
            }
        }
        if(!updateList.isEmpty()){
            update updateList;
        }
    }
    
    private static boolean hasBeenAudited() {
        return false;
    }
    
    public static void runHandler() {
        if (trigger.isbefore) {
            return;
        }   
        if(trigger.isInsert){
            caseViolationRollupAmountsAction action = new caseViolationRollupAmountsAction(trigger.newMap);
            if(action.shouldRunOnInsert()){
                action.doAction();
            }
        }
        if (trigger.isUpdate) {
            caseViolationRollupAmountsAction action = new caseViolationRollupAmountsAction(trigger.newMap, trigger.oldMap);
            if(action.shouldRunOnUpdate()){
                action.doAction();
            }
        }
    }
}