force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/Judgment_Payment__c.object-meta.xml
<CustomObject>
    <description>Records payments made against Judgments and their related interests, filing fees, and attorney fees.</description>
    <label>Judgment Payment</label>
    <nameField>
        <displayFormat>JP-{000000}</displayFormat>
        <label>Judgment Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/fields/Payment_On_Behalf_Of__c.field-meta.xml
<CustomField>
    <fullName>Payment_On_Behalf_Of__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment On Behalf Of</label>
    <referenceTo>Liable_Party__c</referenceTo>
    <relationshipLabel>Judgment Payments</relationshipLabel>
    <relationshipName>Judgment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Posted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Posted_Amount__c</fullName>
    <description>Formerly Allocated_Amount__c</description>
    <label>Posted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Recommended_Amount__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Amount__c</fullName>
    <description>amount recommended by the deputy when applying a payment</description>
    <label>Recommended Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Deposited-Returned</fullName>
            </value>
            <value>
                <fullName>Deposited-Returned Deduction</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Corrective Entry</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability__c/Liability__c.object-meta.xml
<CustomObject>
    <description>This objects contains the Liability against an Assessment.</description>
    <label>Liability</label>
    <nameField>
        <displayFormat>LIA-{000000}</displayFormat>
        <label>Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>This creates a lookup relationship between a Liability and an Assessment.  This field is required.</description>
    <inlineHelpText>This creates a lookup relationship between a Liability and an Assessment.  This field is required.</inlineHelpText>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipLabel>Liabilities</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>If Status = Admin Dismissed, must decide if associated violations should be Admin Dismissed as well and Penalties zeroed out.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administrative Dismissal</fullName>
            </value>
            <value>
                <fullName>Affirmed</fullName>
            </value>
            <value>
                <fullName>Appeal Withdrawn</fullName>
            </value>
            <value>
                <fullName>Canceled-Invalid</fullName>
            </value>
            <value>
                <fullName>Demand Non-citable</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Hearing Complete</fullName>
            </value>
            <value>
                <fullName>Judgment Accepted</fullName>
            </value>
            <value>
                <fullName>Judgment Rejected</fullName>
            </value>
            <value>
                <fullName>Modified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Out of Statute</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Pending Writ</fullName>
            </value>
            <value>
                <fullName>Referred for Judgment</fullName>
            </value>
            <value>
                <fullName>Request Dismissal</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Stop Order Only</fullName>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Writ Affirmed</fullName>
            </value>
            <value>
                <fullName>Writ Modified</fullName>
            </value>
            <value>
                <fullName>Writ Received</fullName>
            </value>
            <value>
                <fullName>Writ Remanded</fullName>
            </value>
            <value>
                <fullName>Writ Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liable_Party__c/Liable_Party__c.object-meta.xml
<CustomObject>
    <label>Liable Party</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Liable Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liable Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liable_Party__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The liable party is related to a case role on the record. This field holds the value of that case role and is used for generating output document based on the party.</description>
    <inlineHelpText>Case role of the liable party</inlineHelpText>
    <label>Case Role</label>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Liable Parties</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <description>This ties the Liability to One or Many Liable Parties for a specific Assessment. Not-Reparentable</description>
    <inlineHelpText>This ties the Liability to One or Many Liable Parties for a specific Assessment. Not-Reparentable</inlineHelpText>
    <label>Liability</label>
    <referenceTo>Liability__c</referenceTo>
    <relationshipLabel>Liable Parties</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Proportionate_Share__c.field-meta.xml
<CustomField>
    <fullName>Proportionate_Share__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Defines the share of the liability that the liable party owes relative to the parent liability. Populated from the violation engine.</description>
    <label>Proportionate Share</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Liable</fullName>
            </value>
            <value>
                <fullName>Not Liable</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liable_Party_Case_Issue__c/Liable_Party_Case_Issue__c.object-meta.xml
<CustomObject>
    <description>Junction between liable parties and case issues. Denormalizes data model to allow the application of a liable party's proportionate share to the issue totals</description>
    <label>Liable Party Case Issue</label>
    <nameField>
        <displayFormat>LPCI-{000000}</displayFormat>
        <label>Liable Party Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liable Party Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liable_Party_Case_Issue__c/fields/Case_Issue__c.field-meta.xml
<CustomField>
    <fullName>Case_Issue__c</fullName>
    <description>Parent case issue to which the proportionate share of the liable party needs to be applied</description>
    <label>Case Issue</label>
    <referenceTo>DIR_Violation__c</referenceTo>
    <relationshipLabel>Liable Party Case Issues</relationshipLabel>
    <relationshipName>Liable_Party_Case_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liable_Party_Case_Issue__c/fields/Liable_Party__c.field-meta.xml
<CustomField>
    <fullName>Liable_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liable Party</label>
    <referenceTo>Liable_Party__c</referenceTo>
    <relationshipLabel>Liable Party Case Issues</relationshipLabel>
    <relationshipName>Liable_Party_Case_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party_Case_Issue__c/fields/Proportionate_Share__c.field-meta.xml
<CustomField>
    <fullName>Proportionate_Share__c</fullName>
    <formula>Liable_Party__r.Proportionate_Share__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proportionate Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/CashUpdateMatchedLPs.cls
//Match CIW allocations to existing LPs and their related 'redundant' 'Judgment Amount' JPs, if any.
//   Non-'Judgment Amount' JPs updated in the CashUpdateMatchedJPs class.
//   Essentially the same algorithm as with matching JW allocations to JPs, CashUpdateMatchedJPs class,
//    and matching CU1W allocations to their LPs, CashUpdateMatchedCU1s class, q.v.

public with sharing class CashUpdateMatchedLPs{
    public static void updateMatchedLPs(List<CashCaseIssueWrapper> caseIssueWrapperList, 
                                            List<Liable_Party__c> allLiablePartyList, 
                                            /* String selectedPobo, //Case_Role__c.Id //Commented out because relevantPoboLiablePartyId and relevantLiability should already have been set in JS */
                                            String whichButtonClicked)
        {
        for(CashCaseIssueWrapper ciw : caseIssueWrapperList){
            /* Commented out because relevantPoboLiablePartyId and relevantLiability should already have been set in JS.
             //  Determine correct Liability and Payment_on_Behalf_of__c the LP should look up to.
            //    TODO: Verify this works for CIs with multiple Liable Parties (through LPCIs) and Case Roles with multiple Liable Parties. This may be
            //        where we need to bring in LPCI.Proportionate_Share__c
            for(Liable_Party__c liableParty : allLiablePartyList){
                //for(Liable_Party_Case_Issue__c lpci : liableParty.Liable_Party_Case_Issues__r){ //SR-010949
                    //if(lpci.Case_Issue__c == ciw.thisCaseIssue.Id && lpci.Liable_Party__r.Case_Role__c == selectedPobo){ //SR-010949

                    if(selectedPobo == liableParty.Case_Role__c && ciw.caseIssueAssessment.Id == liableParty.Liability__r.Assessment__r.Id){
                        ciw.relevantLiability = liableParty.Liability__r;
                        ciw.relevantPoboLiablePartyId = liableParty.Id;
                    }
                //}
            } */

            //  If the recommended amounts are different in the CIW than in it's matching LP, update the LP and any 'redundant' JPs,
            //    even if $0 (meaning a previous recommended amount has been removed, but we're still keeping the record for historical purposes).
            if(ciw.matchingWageLP != null){
                ciw.matchingWageLP.Case_Violation__c = ciw.thisCaseIssue.Id; // Updating this field here because a lot of the records in PROD have this field blank
                ciw.matchingWageLP.Liability__c = ciw.relevantLiability.Id; // Updating this field here because a lot of the records in PROD have this field blank
                ciw.matchingWageLP.Payment_on_Behalf_of__c = ciw.relevantPoboLiablePartyId;

                if(whichButtonClicked == 'Recommend'){
                    ciw.matchingWageLP.Recommended_Amount__c = ciw.wageAllocation;
                    ciw.matchingWageLP.Status__c = 'Recommended';

                    for(Judgment_Payment__c jp : ciw.matchingRedundantWageJPsArray){   
                        jp.Recommended_Amount__c = ciw.wageAllocation;
                        jp.Payment_On_Behalf_Of__c = ciw.relevantPoboLiablePartyId;
                        jp.Status__c = 'Recommended';
                    }
                }else{ //whichButtonClicked == 'Post'
                    ciw.matchingWageLP.Posted_Amount__c = ciw.wageAllocation;
                    ciw.matchingWageLP.Status__c = 'Posted';
                    
                    for(Judgment_Payment__c jp : ciw.matchingRedundantWageJPsArray){   
                        jp.Posted_Amount__c = ciw.wageAllocation;
                        jp.Payment_On_Behalf_Of__c = ciw.relevantPoboLiablePartyId;
                        jp.Status__c = 'Posted';
                    }
                }
            }
            if(ciw.matchingWageInterestLP != null){
                ciw.matchingWageInterestLP.Case_Violation__c = ciw.thisCaseIssue.Id; // Updating this field here because a lot of the records in PROD have this field blank
                ciw.matchingWageInterestLP.Liability__c = ciw.relevantLiability.Id; // Updating this field here because a lot of the records in PROD have this field blank
                ciw.matchingWageInterestLP.Payment_on_Behalf_of__c = ciw.relevantPoboLiablePartyId;

                if(whichButtonClicked == 'Recommend'){
                    ciw.matchingWageInterestLP.Recommended_Amount__c = ciw.wageInterestAllocation;
                    ciw.matchingWageInterestLP.Status__c = 'Recommended';

                    for(Judgment_Payment__c jp : ciw.matchingRedundantWageInterestJPsArray){   
                        jp.Recommended_Amount__c = ciw.wageInterestAllocation;
                        jp.Payment_On_Behalf_Of__c = ciw.relevantPoboLiablePartyId;
                        jp.Status__c = 'Recommended';
                    }
                }else{ //whichButtonClicked == 'Post'
                    ciw.matchingWageInterestLP.Posted_Amount__c = ciw.wageInterestAllocation;
                    ciw.matchingWageInterestLP.Status__c = 'Posted';
                    
                    for(Judgment_Payment__c jp : ciw.matchingRedundantWageInterestJPsArray){   
                        jp.Posted_Amount__c = ciw.wageInterestAllocation;
                        jp.Payment_On_Behalf_Of__c = ciw.relevantPoboLiablePartyId;
                        jp.Status__c = 'Posted';
                    }
                }
            }
            if(ciw.matchingInterestLP != null){
                ciw.matchingInterestLP.Case_Violation__c = ciw.thisCaseIssue.Id;
                ciw.matchingInterestLP.Liability__c = ciw.relevantLiability.Id;
                ciw.matchingInterestLP.Payment_on_Behalf_of__c = ciw.relevantPoboLiablePartyId;

                if(whichButtonClicked == 'Recommend'){
                    ciw.matchingInterestLP.Recommended_Amount__c = ciw.interestAllocation;
                    ciw.matchingInterestLP.Status__c = 'Recommended';

                    for(Judgment_Payment__c jp: ciw.matchingRedundantInterestJPsArray){
                        jp.Recommended_Amount__c = ciw.interestAllocation;
                        jp.Payment_On_Behalf_Of__c = ciw.relevantPoboLiablePartyId;
                        jp.Status__c = 'Recommended';
                    }
                }else{ //whichButtonClicked == 'Post'
                    ciw.matchingInterestLP.Posted_Amount__c = ciw.interestAllocation;
                    ciw.matchingInterestLP.Status__c = 'Posted';

                    for(Judgment_Payment__c jp: ciw.matchingRedundantInterestJPsArray){
                        jp.Posted_Amount__c = ciw.interestAllocation;
                        jp.Payment_On_Behalf_Of__c = ciw.relevantPoboLiablePartyId;
                        jp.Status__c = 'Posted';
                    }
                }
            }
            if(ciw.matchingPenaltyLP != null){
                ciw.matchingPenaltyLP.Case_Violation__c = ciw.thisCaseIssue.Id;
                ciw.matchingPenaltyLP.Liability__c = ciw.relevantLiability.Id;
                // System.debug('108 ciw.relevantPoboLiablePartyId: ' + ciw.relevantPoboLiablePartyId);
                ciw.matchingPenaltyLP.Payment_on_Behalf_of__c = ciw.relevantPoboLiablePartyId;

                if(whichButtonClicked == 'Recommend'){
                    ciw.matchingPenaltyLP.Recommended_Amount__c = ciw.penaltyAllocation;
                    ciw.matchingPenaltyLP.Status__c = 'Recommended';

                    for(Judgment_Payment__c jp: ciw.matchingRedundantPenaltyJPsArray){
                        jp.Recommended_Amount__c = ciw.penaltyAllocation;
                        jp.Payment_On_Behalf_Of__c = ciw.relevantPoboLiablePartyId;
                        jp.Status__c = 'Recommended';
                    }
                }else{ //whichButtonClicked == 'Post'
                    ciw.matchingPenaltyLP.Posted_Amount__c = ciw.penaltyAllocation;
                    ciw.matchingPenaltyLP.Status__c = 'Posted';

                    for(Judgment_Payment__c jp: ciw.matchingRedundantPenaltyJPsArray){
                        jp.Posted_Amount__c = ciw.penaltyAllocation;
                        jp.Payment_On_Behalf_Of__c = ciw.relevantPoboLiablePartyId;
                        jp.Status__c = 'Posted';
                    }
                }
            }
        }
    }
}