force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessments__c/fields/Appeal_Deadline_Days__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Days__c</fullName>
    <description>Set as max of appeal deadline from child case violation records via trigger on case violation object</description>
    <label>Appeal Deadline (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Appeal_Deadline_Selector__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Selector__c</fullName>
    <label>Appeal Deadline Selector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Days</fullName>
            </value>
            <value>
                <fullName>Calendar Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</description>
    <inlineHelpText>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</inlineHelpText>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessments__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</description>
    <inlineHelpText>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Roles</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to the DIR Employee object creating a hierarchial relationship between an employee and his or her manager. Used in code to modify the role hierarchy and dynamically build teams</description>
    <inlineHelpText>Select the employee's manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Manages these Employees</relationshipLabel>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position the employee holds</description>
    <inlineHelpText>Select the position the employee holds</inlineHelpText>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Senior Deputy</fullName>
            </value>
            <value>
                <fullName>Deputy</fullName>
            </value>
            <value>
                <fullName>Clerk</fullName>
            </value>
            <value>
                <fullName>Hearing Officer</fullName>
            </value>
            <value>
                <fullName>Cashiering</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>CIU</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Registration_Services</fullName>
                <label>Registration Services</label>
            </value>
            <value>
                <fullName>Public Information Investigator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related user record for the employee. Some employees may not be salesforce users, but when they are, certain automations and activities will use the related user record.</description>
    <inlineHelpText>If the employee is a salesforce user, select the user. If the employee is not a salesforce user, you may leave this field blank.</inlineHelpText>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIR_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Appeal_Deadline_Days__c.field-meta.xml
<CustomField>
    <fullName>Appeal_Deadline_Days__c</fullName>
    <description>Appeal deadline in days from the violation type</description>
    <formula>Violation_Type__r.Appeal_Deadline_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appeal Deadline (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/DIR_Employee__c.field-meta.xml
<CustomField>
    <fullName>DIR_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issuing Deputy</label>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipName>DIR_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liability__c/Liability__c.object-meta.xml
<CustomObject>
    <description>This objects contains the Liability against an Assessment.</description>
    <label>Liability</label>
    <nameField>
        <displayFormat>LIA-{000000}</displayFormat>
        <label>Liability ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related case to the liability</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Liability</relationshipLabel>
    <relationshipName>Liability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/Liable_Party__c.object-meta.xml
<CustomObject>
    <label>Liable Party</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Liable Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liable Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liable_Party__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The liable party is related to a case role on the record. This field holds the value of that case role and is used for generating output document based on the party.</description>
    <inlineHelpText>Case role of the liable party</inlineHelpText>
    <label>Case Role</label>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Liable Parties</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>This is a link to the Entity that is a Liable Party for a Liability.</description>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Liable Party to Assessments</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/createLiablePartyCaseIssueActionTest.cls
@isTest(SeeAllData=false)
private class createLiablePartyCaseIssueActionTest {
    
    static testMethod void testCreateLiablePartyCaseIssueAction() {
        List<Trigger_Settings__c> triggerSettings = new List<Trigger_Settings__c>();
        triggerSettings.add(new Trigger_Settings__c(
            Name = 'CaseRoleAll',
            Is_Active__c = false
        ));
            
        triggerSettings.add(new Trigger_Settings__c(
            Name = 'dlrs_DIR_ViolationTrigger',
            Is_Active__c = false
        ));

        triggerSettings.add(new Trigger_Settings__c(
            Name = 'dlrs_JudgementTrigger',
            Is_Active__c = false
        ));

        triggerSettings.add(new Trigger_Settings__c(
            Name = 'GenerateFieldHistoryAction',
            Is_Active__c = false
        ));

        triggerSettings.add(new Trigger_Settings__c(
            Name = 'LiabilityPaymentTrigger',
            Is_Active__c = false
        ));

        triggerSettings.add(new Trigger_Settings__c(
            Name = 'Receipt Trigger',
            Is_Active__c = true
        ));
        insert triggerSettings;
        
        
        Account a = new Account(
            Name = 'testAcct80211'
        );
        insert a;
        
        DIR_Employee__c ma = new DIR_Employee__c(
            User__c = UserInfo.getUserId()
        );
        insert ma; 
        
        DIR_Employee__c de = new DIR_Employee__c(
            User__c = UserInfo.getUserId(),
            Position__c = 'Deputy',
            Manager__c = ma.Id
        );
        insert de; 
        
        DIR_Case__c cm = new DIR_Case__c(
            Assigned_Deputy__c = de.Id,
            Employer__c = a.Id
        );
        insert cm;
        
        Assessments__c assesment = new Assessments__c(
            Appeal_Deadline_Selector__c = 'Business Days',
            Appeal_Deadline_Days__c = 15,
            Case_Management__c = cm.Id
        );
        insert assesment;

        Case_Role__c cr = new Case_Role__c(
            Case__c = cm.Id,
            Entity__c = a.Id
        );
        insert cr;

        DIR_Violation__c dv = new DIR_Violation__c(
            Case__c = cm.Id,
            Assessment__c = assesment.Id
        );
        insert dv;
        
        Liability__c liability = new Liability__c(
            Assessment__c = assesment.Id,
            Case_Management__c = cm.Id,
            Status__c = 'new',
            Appeal_Deadline__c = Date.today()
        );
        insert liability;
        
        test.startTest();

        Liable_Party__c lp = new Liable_Party__c(
            Liability__c = liability.Id,
            Entity__c = a.id,
            Interest_Amount_Collected__c = -500,
            Case_Role__c = cr.Id
        );
        insert lp;

        test.stopTest();

        List<Liable_Party_Case_Issue__c> lpciList = [
                                                     SELECT Id, Case_Issue__c, Liable_Party__c
                                                     FROM Liable_Party_Case_Issue__c
                                                     WHERE Case_Issue__c =: dv.Id AND Liable_Party__c =: lp.Id
                                                    ];

        system.assertEquals(lpciList.size(), 1);

        Liable_Party_Case_Issue__c newLPCI = lpciList[0];
        
        system.assertEquals(newLPCI.Case_Issue__c, dv.Id);
        system.assertEquals(newLPCI.Liable_Party__c, lp.Id);
    }
}