force-app/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <description>Penalty Assessment, Wage Assessments, Non-Citable Violations, Stop Orders, Notice To Discontinues are all stored in this object, which is tied to a Violation.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AST-{000000}</displayFormat>
        <label>Assessments ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessments__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</description>
    <inlineHelpText>The case is a parent of the assessment. This field specifies the case for which the assessment is a child.</inlineHelpText>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/Attachment_Configuration__c.object-meta.xml
<CustomObject>
    <label>Attachment Configuration</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Attachment Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attachment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Criteria__c</fullName>
    <label>Attachment Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attachment_Operator__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Operator__c</fullName>
    <label>Attachment Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Starts With</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Attorney_Client_Privilege__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Client_Privilege__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attorney Client Privilege</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/History_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>History_Object_Configuration__c</fullName>
    <label>History Object Configuration</label>
    <referenceTo>History_Object_Configuration__c</referenceTo>
    <relationshipLabel>Attachment Configuration</relationshipLabel>
    <relationshipName>History_Field_Configuration1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attachment_Configuration__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Subject to PRA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is considered confidential</inlineHelpText>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Not_Subject_to_PRA__c.field-meta.xml
<CustomField>
    <fullName>Not_Subject_to_PRA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is not subject to PRA requests</inlineHelpText>
    <label>Not Subject to PRA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/DIR_Violation__c.object-meta.xml
<CustomObject>
    <description>This objects contains a Violation tied to a Case.</description>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Case Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Violation__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Violations are tied together as an assessment.</description>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipName>Case_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This creates a master detail relationship between a Violation and the Case that it is against.</description>
    <inlineHelpText>This creates a master detail relationship between a Violation and the Case that it is against.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Issues</relationshipLabel>
    <relationshipName>DIR_Violations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIR_Violation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defaults to "open" but may be set to "affirmed" or "modified" by the hearing process via the hearing results vfp.</description>
    <inlineHelpText>If Sr. administratively dismisses violation, they must also adjust penalties and/or wages due to zero.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>NTD - Full Compliance</fullName>
            </value>
            <value>
                <fullName>NTD - No Compliance</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Affirmed</fullName>
            </value>
            <value>
                <fullName>Modified</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Administrative Dismissal</fullName>
            </value>
            <value>
                <fullName>De Novo Appeal</fullName>
            </value>
            <value>
                <fullName>Under Appeal</fullName>
            </value>
            <value>
                <fullName>Appeal Withdrawn</fullName>
            </value>
            <value>
                <fullName>Request Dismissal</fullName>
            </value>
            <value>
                <fullName>Paid Off</fullName>
            </value>
            <value>
                <fullName>Referred for Judgment</fullName>
            </value>
            <value>
                <fullName>Judgment Accepted</fullName>
            </value>
            <value>
                <fullName>Judgment Rejected</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Writ Dismissed</fullName>
            </value>
            <value>
                <fullName>Writ Settled by Legal</fullName>
            </value>
            <value>
                <fullName>Writ Affirmed</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Offer in Compromise</fullName>
            </value>
            <value>
                <fullName>Self Audit Discount</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Canceled - Invalid</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Judgment</fullName>
            </value>
            <value>
                <fullName>Claimant Withdrew</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Dismissed at Conference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/History_Object_Configuration__c.object-meta.xml
<CustomObject>
    <label>History Object Configuration</label>
    <nameField>
        <displayFormat>HOC-{0}</displayFormat>
        <label>History Object Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Object Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Object_Configuration__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Object_Configuration__c/fields/Path_to_Case__c.field-meta.xml
<CustomField>
    <fullName>Path_to_Case__c</fullName>
    <inlineHelpText>This is the path to get to the Case Management object. .Case__r should be at the end of each string.

Example: If you are going from Meeting Participant object to Case it would be Meeting_Participant__r.Meeting__r.Case__r</inlineHelpText>
    <label>Path to Case</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateAttachmentsPlusActionTEST.cls
@isTest
private class GenerateAttachmentsPlusActionTEST {

    static testMethod void testCreateAttachmentsPlus() {
        History_Object_Configuration__c hoc1 = new History_Object_Configuration__c(
            Object_name__c = 'Case Violation',
            Object_API_Name__c = 'DIR_Violation__c',
            Active__c = true,
            Path_to_Case__c = 'Case__r'
        );
        insert hoc1;
        
        History_Object_Configuration__c hoc2 = new History_Object_Configuration__c(
            Object_name__c = 'Attachment',
            Object_API_Name__c = 'Attachment',
            Active__c = true
        );
        insert hoc2;
        
        RecordType caseRT = [SELECT Id FROM RecordType WHERE sObjectType = 'DIR_Case__c' AND IsActive = true LIMIT 1];
                
        DIR_Case__c dirCase = new DIR_Case__c(
            RecordTypeId = caseRT.Id
        );
        insert dirCase;
        
        RecordType violRT = [SELECT Id FROM RecordType WHERE sObjectType = 'DIR_Violation__c' AND Name LIKE '%BOFE%' AND IsActive = true LIMIT 1];
        
        Assessments__c assess = new Assessments__c(
        Case_Management__c = dirCase.Id
        );
        insert assess;

        DIR_Violation__c viol = new DIR_Violation__c(
            Case__c = dirCase.Id,
            Assessment__c = assess.Id,
            Status__c = 'Open',
            RecordTypeId = violRT.Id
        );
        insert viol;
        
        Attachment_Configuration__c ac = new Attachment_Configuration__c(
            History_Object_Configuration__c = hoc2.Id,
            Active__c = true,
            Attachment_Criteria__c = 'test',
            Attachment_Operator__c = 'Starts With',
            Confidential__c = true,
            Not_Subject_to_PRA__c = true,
            Attorney_Client_Privilege__c = true,
            Type__c = 'test type'
        );
        insert ac;
         
        Attachment att = new Attachment(
            parentId = viol.Id,
            Name = 'test attachment',
            body = blob.valueOf('test')
        );
        insert att;
        
        Attachment_Configuration__c ac1 = new Attachment_Configuration__c(
            History_Object_Configuration__c = hoc2.Id,
            Active__c = true,
            Attachment_Criteria__c = 'test2',
            Attachment_Operator__c = 'Contains',
            Confidential__c = true,
            Not_Subject_to_PRA__c = true,
            Attorney_Client_Privilege__c = true,
            Type__c = 'test type'
        );
        insert ac1;
        
		Attachment_Configuration__c ac3 = new Attachment_Configuration__c(
            History_Object_Configuration__c = hoc2.Id,
            Active__c = true,
            Attachment_Criteria__c = 'test2',
            Attachment_Operator__c = 'Equals',
            Confidential__c = true,
            Not_Subject_to_PRA__c = true,
            Attorney_Client_Privilege__c = true,
            Type__c = 'test type'
        );
        insert ac3;
         
        Attachment att1 = new Attachment(
            parentId = viol.Id,
            Name = 'test attachment',
            body = blob.valueOf('test2')
        );
        insert att1;
        
        Attachments_Plus__c a = [SELECT Id, Confidential__c, Not_Subject_to_PRA__c, Attorney_Client_Privilege__c, Type__c FROM Attachments_Plus__c LIMIT 1];
        
        system.assertEquals(a.Confidential__c, ac.Confidential__c);
        system.assertEquals(a.Not_Subject_to_PRA__c, ac.Not_Subject_to_PRA__c);
        system.assertEquals(a.Attorney_Client_Privilege__c, ac.Attorney_Client_Privilege__c);
        system.assertEquals(a.Type__c, ac.Type__c);
    }
}