force-app/main/default/objects/Judgement__c/Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment</label>
    <nameField>
        <displayFormat>J-{0}</displayFormat>
        <label>Judgment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ODA by Settlement</fullName>
            </value>
            <value>
                <fullName>ODA</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>Tax Lien</fullName>
            </value>
            <value>
                <fullName>Court Judgment</fullName>
            </value>
            <value>
                <fullName>RCI Citation Pre-Hearing</fullName>
            </value>
            <value>
                <fullName>RCI Citation Post-Hearing</fullName>
            </value>
            <value>
                <fullName>Default Clerk Judgment</fullName>
            </value>
            <value>
                <fullName>Citation against subsequent offender  (LC 2810.4(b)(1)(B))</fullName>
            </value>
            <value>
                <fullName>ODA against subsequent offender (LC 2810.4(b)(1)(B))</fullName>
            </value>
            <value>
                <fullName>Other Ruling or award against subsequent offender (LC 2810.4(b)(1)(B))</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/Liability_Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment Party</label>
    <nameField>
        <displayFormat>LJ-{0}</displayFormat>
        <label>Judgment Party</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Judgement__c/fields/EntityAccountId__c.field-meta.xml
<CustomField>
    <fullName>EntityAccountId__c</fullName>
    <formula>IF( NOT( ISBLANK(Liable_Party__c) ),  
Liable_Party__r.Entity__c, 
Related_Business__r.Business__c)</formula>
    <label>EntityAccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Judgement__c.field-meta.xml
<CustomField>
    <fullName>Judgement__c</fullName>
    <label>Judgment</label>
    <referenceTo>Judgement__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Liable_Party_Name__c.field-meta.xml
<CustomField>
    <fullName>Liable_Party_Name__c</fullName>
    <formula>IF(ISBLANK(Liable_Party__c) ,  
IF(ISBLANK(Related_Business__r.Business__r.Name), Related_Business__r.Business__r.FirstName + ' '+Related_Business__r.Business__r.LastName, Related_Business__r.Business__r.Name),
IF(ISBLANK(Liable_Party__r.Entity__r.Name), Liable_Party__r.Entity__r.FirstName + ' '+Liable_Party__r.Entity__r.LastName, Liable_Party__r.Entity__r.Name) )</formula>
    <label>Liable Party Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Related_Businesses__c</referenceTo>
    <relationshipLabel>Judgment Parties</relationshipLabel>
    <relationshipName>Judgment_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/Related_Businesses__c.object-meta.xml
<CustomObject>
    <label>Related Business</label>
    <nameField>
        <displayFormat>RBO-{00000000}</displayFormat>
        <label>Related Businesses Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Businesses__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to store business Account for the Rbo record</description>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Business)</relationshipLabel>
    <relationshipName>Related_Businessess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Related Business)</relationshipLabel>
    <relationshipName>Related_Businessess1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alter Ego</fullName>
            </value>
            <value>
                <fullName>LC 238 (Related Business)</fullName>
            </value>
            <value>
                <fullName>Parent Company</fullName>
            </value>
            <value>
                <fullName>Predecessor</fullName>
            </value>
            <value>
                <fullName>Single Enterprise</fullName>
            </value>
            <value>
                <fullName>Subsidiary</fullName>
            </value>
            <value>
                <fullName>Successor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RelatedBusinessLookupJudgmentPartyCtrl.cls
public class RelatedBusinessLookupJudgmentPartyCtrl {
        public String name{get;set;}
        public String jid{get;set;}
        public String bid{get;set;}
        public String rbname{get;set;}
        Set<Id> accountId = new Set<Id>();
        Set<Id> relatedBusinessId = new Set<Id>();
        public List<Related_Businesses__c> relatedBusinessList{get;set;}
        public RelatedBusinessLookupJudgmentPartyCtrl(){
            try{
                name = '';
                jid = '';
                bid = '';
                rbname = '';
                String relatedBusinessName = ApexPages.currentPage().getParameters().get('rbname');
                if(String.isNotBlank(relatedBusinessName)){
                    rbname = ApexPages.currentPage().getParameters().get('rbname').replaceAll('%',' ');}
                String lookupName = ApexPages.currentPage().getParameters().get('name');
                if(String.isNotBlank(lookupName)){
                    name = ApexPages.currentPage().getParameters().get('name').replaceAll('%',' ');
                }
                String judgmentId = ApexPages.currentPage().getParameters().get('jid');
                if(String.isNotBlank(judgmentId)){
                    jid = ApexPages.currentPage().getParameters().get('jid').replaceAll('%',' ');
                }
                String relatedBusinessIds = ApexPages.currentPage().getParameters().get('bid');
                if(String.isNotBlank(relatedBusinessIds)){
                    bid = ApexPages.currentPage().getParameters().get('bid').replaceAll('%',' ');
                }
                onGo();
            }
            catch(Exception e){
                
            }
        }
        public PageReference onGo(){
            try{
                for(Liability_Judgement__c judgmentParty  : [SELECT Id, EntityAccountId__c,Liable_Party_Name__c,Related_Business__c
                                                             FROM Liability_Judgement__c 
                                                             where Judgement__c =: jid])
                {
                    accountId.add(judgmentParty.EntityAccountId__c);
                    relatedBusinessId.add(judgmentParty.Related_Business__c);  
                }
                List<Related_Businesses__c> relatedBusinessesOnJudgment = new List<Related_Businesses__c>(); 
                List<Related_Businesses__c> inverseRBOList = new List<Related_Businesses__c>();
                    Set<String> RelatedBusinessMappingSet = new Set<String>();
                relatedBusinessList = new List<Related_Businesses__c>(); 
                name = String.isNotBlank(name.trim()) ? String.escapeSingleQuotes(name.trim()) : '';
                String nameStr = '%' + name + '%';
                if(name != '' && name != NULL){
                    relatedBusinessesOnJudgment = [SELECT Name,Id,Business__c, Business__r.Name, Related_Business__c ,Related_Business__r.Name ,Type__c
                                           FROM Related_Businesses__c where Related_Business__r.Name like: nameStr AND Business__c IN :accountId 
                                           And Id NOT IN : relatedBusinessId
                                           AND Related_Business__c NOT IN :accountId];
                }else{
                    relatedBusinessesOnJudgment = [SELECT Name,Id,Business__c, Business__r.Name, Related_Business__c ,Related_Business__r.Name ,Type__c
                                           FROM Related_Businesses__c where Business__c IN :accountId 
                                           And Id NOT IN : relatedBusinessId
                                           AND Related_Business__c NOT IN :accountId];
                }
                Set<Id> rbIds = new Set<Id>(); 
                //get all the RBOs whos are in Related Businesses section on Judgment.
                for(Related_Businesses__c rbo: relatedBusinessesOnJudgment){
                    rbIds.add(rbo.Related_Business__c);
                    RelatedBusinessMappingSet.add(rbo.Related_Business__c+''+rbo.Business__c);
                }
                inverseRBOList = [SELECT Name,Id,Business__c, Business__r.Name, Related_Business__c ,Related_Business__r.Name ,Type__c
                                           FROM Related_Businesses__c where Business__c IN :rbIds ];
                for(Related_Businesses__c rbo: inverseRBOList){
                    if(RelatedBusinessMappingSet.contains(rbo.Business__c+''+rbo.Related_Business__c)){
                       relatedBusinessList.add(rbo); 
                    }
                }
            }
            catch(Exception e){ 
                system.debug('error: '+e.getMessage());
                //Logger.logMessage('CallScriptLookupCtlr', 'onGo', e);
            }
            return null;
        }
    }