force-app/main/default/objects/Judgement__c/Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment</label>
    <nameField>
        <displayFormat>J-{0}</displayFormat>
        <label>Judgment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Judgement__c/Liability_Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment Party</label>
    <nameField>
        <displayFormat>LJ-{0}</displayFormat>
        <label>Judgment Party</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Judgement__c/fields/EntityAccountId__c.field-meta.xml
<CustomField>
    <fullName>EntityAccountId__c</fullName>
    <formula>IF( NOT( ISBLANK(Liable_Party__c) ),  
Liable_Party__r.Entity__c, 
Related_Business__r.Business__c)</formula>
    <label>EntityAccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Judgement__c.field-meta.xml
<CustomField>
    <fullName>Judgement__c</fullName>
    <label>Judgment</label>
    <referenceTo>Judgement__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Judgment_Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Judgment_Party_Type__c</fullName>
    <label>Judgment Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alter Ego</fullName>
            </value>
            <value>
                <fullName>Car Wash Successor (LC 2066)</fullName>
            </value>
            <value>
                <fullName>Equitable Successor</fullName>
            </value>
            <value>
                <fullName>FLC Successor (LC 1698.9)</fullName>
            </value>
            <value>
                <fullName>Garment Successor (LC 2684)</fullName>
            </value>
            <value>
                <fullName>Janitorial Successor (LC 1420)</fullName>
            </value>
            <value>
                <fullName>Judgment Successor (LC 200.3)</fullName>
            </value>
            <value>
                <fullName>Labor Code 238(e) Related Business</fullName>
            </value>
            <value>
                <fullName>Original Judgment Debtor</fullName>
                <default>true</default>
                <label>Original Judgment Debtor</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Port Trucking Successor (LC 2810.4)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Related_Businesses__c</referenceTo>
    <relationshipLabel>Judgment Parties</relationshipLabel>
    <relationshipName>Judgment_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/Related_Businesses__c.object-meta.xml
<CustomObject>
    <label>Related Business</label>
    <nameField>
        <displayFormat>RBO-{00000000}</displayFormat>
        <label>Related Businesses Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Businesses__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to store business Account for the Rbo record</description>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Business)</relationshipLabel>
    <relationshipName>Related_Businessess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Businesses__c/fields/Related_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Businesses (Related Business)</relationshipLabel>
    <relationshipName>Related_Businessess1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewJudgmentPartyWithRelatedBusinessCtrl.cls
public class NewJudgmentPartyWithRelatedBusinessCtrl {
    Public String judgementId{get;set;}
    public string businessName {get; set;}
    Public Liability_Judgement__c judgmentParty{get;set;}
    public Set<Id> setOfLiableJudgmentId;
    public NewJudgmentPartyWithRelatedBusinessCtrl(ApexPages.StandardController controller) { 
        judgementId = (Id)controller.getId();
        setOfLiableJudgmentId = new Set<Id>();
        List<Liability_Judgement__c> liableJudList = [SELECT Id, EntityAccountId__c, Judgement__c, Related_Business__c FROM Liability_Judgement__c WHERE Judgement__c =: judgementId];
        for(Liability_Judgement__c liableObj : liableJudList){
            setOfLiableJudgmentId.add(liableObj.EntityAccountId__c);
        }
        judgmentParty = new Liability_Judgement__c();
        judgmentParty.Judgement__c = judgementId;
        if(Test.isRunningTest()){
            Related_Businesses__c relatedBusinessObj = [SELECT Id, Name, Business__c FROM Related_Businesses__c limit 1];
            judgmentParty.Related_Business__c = relatedBusinessObj.Id;
        }
        judgmentParty.Judgment_Party_Type__c = 'Port Trucking Successor (LC 2810.4)'; 
    }
    public PageReference saveRecord(){
        String redirectId = '';
        try{
            System.debug('RelatedBusiness Id ::: '+judgmentParty.Related_Business__c);
            Related_Businesses__c relatedBusinessObj = [SELECT Id, Name, Business__c FROM Related_Businesses__c WHERE Id =: judgmentParty.Related_Business__c limit 1];
            if(setOfLiableJudgmentId.contains(relatedBusinessObj.Business__c)){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Already Exist...'));
                return null;
            }
            insert judgmentParty;
            redirectId = judgmentParty.Id;
        }catch(Exception ex){redirectId =judgementId;
                             System.debug(ex.getMessage());
                             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage()));return null;
                            }
        PageReference pageRef = new PageReference('/'+redirectId);
        pageRef.setRedirect(true);
        return pageRef;
    }
}