force-app/main/default/objects/Judgement__c/Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment</label>
    <nameField>
        <displayFormat>J-{0}</displayFormat>
        <label>Judgment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Judgement__c/Liability_Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment Party</label>
    <nameField>
        <displayFormat>LJ-{0}</displayFormat>
        <label>Judgment Party</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Judgement__c/fields/Judgement__c.field-meta.xml
<CustomField>
    <fullName>Judgement__c</fullName>
    <label>Judgment</label>
    <referenceTo>Judgement__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PortDrayageSearchResultPageCtrlTest.cls
@IsTest
public class PortDrayageSearchResultPageCtrlTest {
    @IsTest
    static void testPortDrayageSearchResultForNegativeCase(){
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecords();
        Test.setCurrentPage(Page.PortDrayageSearchResultsPage);
        ApexPages.currentPage().getParameters().put('sortingOrder','asc');
        ApexPages.currentPage().getParameters().put('selectedHeader',' Claimant / Plaintiff Name');
        ApexPages.currentPage().getParameters().put('asofdate',String.valueOf(System.today()));
        ApexPages.currentPage().getParameters().put('todate',String.valueOf(System.today()));
        ApexPages.currentPage().getParameters().put('fromdate',String.valueOf(System.today()));
        Test.startTest();
        PortDrayageSearchResultPageCtrl portDrayageResult = new PortDrayageSearchResultPageCtrl();
        Test.stopTest();
    }
    @IsTest
    static void testPortDrayageSearchResultForPositiveCase(){
        List<Judgement__c> judgmentRecordsLists = DIRDataFactory.createJudgmentSearchRecords();
        Test.startTest();
        List<Liability_Judgement__c> liabilityJudgmentList = DIRDataFactory.createLiabilityJudgmentTestRecord();
        Test.setCurrentPage(Page.PortDrayageSearchResultsPage);
        ApexPages.currentPage().getParameters().put('sortingOrder','asc');
        ApexPages.currentPage().getParameters().put('selectedHeader',' Claimant / Plaintiff Name');
        ApexPages.currentPage().getParameters().put('asofdate',String.valueOf(System.today()));
        ApexPages.currentPage().getParameters().put('todate',String.valueOf(System.today()));
        ApexPages.currentPage().getParameters().put('fromdate',String.valueOf(System.today()));
        PortDrayageSearchResultPageCtrl portDrayageResult = new PortDrayageSearchResultPageCtrl();
        Test.stopTest();
    }
}