force-app/main/default/objects/ApexLog__c/ApexLog__c.object-meta.xml
<CustomObject>
    <description>Logs for Actions happening in Apex Code</description>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Apex Logs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApexLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Type of Exception</description>
    <label>Exception Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Debug/Exception Message logged</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApexLog__c/recordTypes/Debug.recordType-meta.xml
<RecordType>
    <fullName>Debug</fullName>
    <active>true</active>
    <description>Debug Log in Apex</description>
    <label>Debug</label>
</RecordType>

force-app/main/default/objects/ApexLog__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <description>Log of Exceptions occurred in Apex</description>
    <label>Exception</label>
</RecordType>

force-app/main/default/objects/ApexLogSetting__c/ApexLogSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Setting to Control Apex Logging</description>
    <label>Apex Log Setting</label>
</CustomObject>

force-app/main/default/objects/ApexLogSetting__c/fields/DebugsEnabled__c.field-meta.xml
<CustomField>
    <fullName>DebugsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if debugs are enabled for the Org</inlineHelpText>
    <label>Debugs Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApexLogSetting__c/fields/ExceptionsEnabled__c.field-meta.xml
<CustomField>
    <fullName>ExceptionsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if exceptions Loggin is enabled for the org</inlineHelpText>
    <label>Exceptions Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/loggerTest.cls
/*******************************************************************************
* @author         Sapient
* @date           December 2018
* @return         
* @description    Test class for testing the class named 
*                 logger
*******************************************************************************/
@isTest
public class loggerTest {

/*******************************************************************************
* @author         Sapient
* @date           December 2018
* @return         
* @description    This test methods creates log exceptions intentionally to check
                  the logger methods of logger class
* @Revision(s) 
*******************************************************************************/

    static testMethod void testlogger() {
        
        list<RecordType> apexLogrts = [SELECT Id, Name from RecordType WHERE SobjectType =: 'apexLog__c'];
             ApexLogSetting__c logconfig = new ApexLogSetting__c ();
             logconfig.ExceptionsEnabled__c=true;
             logconfig.debugsEnabled__c=true;
             insert logconfig;
            Test.startTest(); 
            
            //test push method
            logger.push('createAccount','AccountDML');     
            logger.debug('Test debug message');
            //generate exception
            try 
            {
              insert new Account();
            
            }   
            catch (System.DmlException ex) {
                
              logger.debugException(ex); 
              logger.debugException(ex.getmessage());   
          
            }
            
            //test pop method
            logger.pop();
            logger.setInConstuctor();
            List<apexlog__c> testLog = [Select ExceptionType__c, Message__c from apexlog__c];
            System.assertEquals('Test debug message', testLog[0].Message__c);
            System.assert(testLog[1].Message__c.indexOf('fail') > -1);
            Test.stopTest();
            
        
     
   }
   
}