force-app/main/default/objects/ApexLog__c/ApexLog__c.object-meta.xml
<CustomObject>
    <description>Logs for Actions happening in Apex Code</description>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Apex Logs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApexLog__c/recordTypes/Debug.recordType-meta.xml
<RecordType>
    <fullName>Debug</fullName>
    <active>true</active>
    <description>Debug Log in Apex</description>
    <label>Debug</label>
</RecordType>

force-app/main/default/objects/ApexLog__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <description>Log of Exceptions occurred in Apex</description>
    <label>Exception</label>
</RecordType>

force-app/main/default/objects/ApexLogSetting__c/ApexLogSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Setting to Control Apex Logging</description>
    <label>Apex Log Setting</label>
</CustomObject>

force-app/main/default/objects/ApexLogSetting__c/fields/DebugsEnabled__c.field-meta.xml
<CustomField>
    <fullName>DebugsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if debugs are enabled for the Org</inlineHelpText>
    <label>Debugs Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApexLogSetting__c/fields/ExceptionsEnabled__c.field-meta.xml
<CustomField>
    <fullName>ExceptionsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if exceptions Loggin is enabled for the org</inlineHelpText>
    <label>Exceptions Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LogConfigSettings.cls
/*******************************************************************************
* @author       Cloud Sherpas
* @date         5.19.2014
* @description  Class that is used to retrieve the LogConfig custom settings of 
*               the current user profile. 
*******************************************************************************/
public class LogConfigSettings{
    
    private static ApexLogSetting__c theSetting = ApexLogSetting__c.getInstance().Id != null ? 
    ApexLogSetting__c.getInstance() : apexLogSetting__c.getInstance(userinfo.getprofileid());
    private static List<RecordType> recordTypes = [SELECT Id, DeveloperName from RecordType WHERE SobjectType =: 'apexLog__c'];
    
    public static Id getDebugRecordType(){
        for(RecordType rt : recordTypes){
            if(rt.DeveloperName.tolowercase()  == 'debug'){
                return rt.Id;
            }
        }
        return null;       
    }
    
    
    public static Id getExceptionRecordType(){
        for(RecordType rt : recordTypes){
            if(rt.DeveloperName.tolowercase()  == 'exception'){
                return rt.Id;
            }
        }
        return null;       
    }
    
    public static  Boolean loggingEnabled(){

        return theSetting.DebugsEnabled__c;
    }
    public static  Boolean exceptionEnabled(){

        return theSetting.ExceptionsEnabled__c;
    }
}