force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <description>Represents a receivable: an incoming payment, or an advice of incoming funds.</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCT-{0000000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Hold_Date__c.field-meta.xml
<CustomField>
    <fullName>Hold_Date__c</fullName>
    <description>Updated by TransactionTrigger -&gt; TransactionMethods -&gt; AccountingDepositBatch.
Once this Receipt is deposited, this field is updated to TRN.Deposit_Date__c + Receipt_Hold_Date__mdt.Number_of_Days__c.</description>
    <label>Hold Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CalculateBusinessDays.cls
/*********************************************************************
Usage   : This class is used to calculate a date based on number of days from a given start date and the BusinessHours object.
            Currently only called by AccountingDepositBatch to set the Receipt__c.Hold_Date__c when depositing.
*********************************************************************/

public with sharing class CalculateBusinessDays {
    
    BusinessHours businessHoursInstance;
    public CalculatebusinessDays(){
        businessHoursInstance = [SELECT Id, IsActive, IsDefault FROM BusinessHours WHERE IsActive = true AND IsDefault = true
                                    WITH SECURITY_ENFORCED];        
    }
    
    public Date addBusinessDays(Date startDate, Integer days){        
        
        Datetime newDatetime = Datetime.newInstance(startDate.year(), startDate.month(),startDate.day());
        system.debug('newDatetime: ' + newDatetime);
        system.debug('days: ' + days);

        Integer hours = 24;
        Integer minutes = 60;
        Integer seconds = 60;
        Integer milliseconds = 1000;
        Integer millisecondsInADay = hours * minutes * seconds * milliseconds;
        
        newDatetime = BusinessHours.add(businessHoursInstance.Id, newDatetime, days * millisecondsInADay);

        // If newDatetime falls on a holiday, advance a day or until newDatetime is within working hours (i.e., not Saturday nor Sunday).
        // ** As of Sept 2021, no holidays have been configured for our Org. Until there are holidays, this while loop will do nothing.
        while(!BusinessHours.isWithin(businessHoursInstance.Id, newDatetime)){            
            newDatetime = newDatetime.addDays(1);
            system.debug(newDatetime);
            
        }
        
        return newDatetime.date();
    }
}