force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/Share_Point_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Share_Point_Item_Id__c</fullName>
    <label>Share Point Item Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Sharepoint_File_Status__c.field-meta.xml
<CustomField>
    <fullName>Sharepoint_File_Status__c</fullName>
    <label>Sharepoint File Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Sharepoint_File_Upload_Error__c.field-meta.xml
<CustomField>
    <fullName>Sharepoint_File_Upload_Error__c</fullName>
    <label>Sharepoint File Upload Error</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OWCUploadDocumentDeleteBatch.cls
global class OWCUploadDocumentDeleteBatch implements Database.Batchable<sObject>{
    public String success = 'success';
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Share_Point_Item_Id__c,Sharepoint_File_Status__c,Sharepoint_File_Upload_Error__c FROM Attachments_New__c WHERE Share_Point_Item_Id__c != null AND Sharepoint_File_Status__c = '+ '\'' + success+ '\'' ;
        return Database.getQueryLocator(query);
    } 
    global void execute(Database.BatchableContext BC, List<Attachments_New__c> attachPlusRecords){
        
        Set<Id> attachIdSet = new Set<Id>();
        for(Attachments_New__c attachObj : attachPlusRecords){
            attachIdSet.add(attachObj.Id);
        } 
        //get all contentDocumentIds to delete
        List<ContentDocumentLink> conDocIds = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN: attachIdSet];
        //List of ContentDocumentId
        List<Id> contentDocIdToDelete = new List<Id>();
        for(ContentDocumentLink conDocLinkObj : conDocIds){
            contentDocIdToDelete.add(conDocLinkObj.ContentDocumentId);
        }
        
        Database.delete(contentDocIdToDelete) ;
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('finish');
    }
}