force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Id__c</fullName>
    <label>Related Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Release_to_Public__c.field-meta.xml
<CustomField>
    <fullName>Release_to_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Release to Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Address_Primary_Zip__c.field-meta.xml
<CustomField>
    <fullName>Address_Primary_Zip__c</fullName>
    <description>Formula feild to display the Primary Address of the Employer/Business Account on this object. This field is also being used to merge to Conga documents and also to pre-populate on it on the Inspection Questions.</description>
    <formula>Employer__r.ShippingPostalCode</formula>
    <label>Primary Address Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>DIR_Employee__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>DIR_Employee__c.User__r.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Case Management (Assigned Deputy)</relationshipLabel>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>Case Number</description>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Claimant__c.field-meta.xml
<CustomField>
    <fullName>Claimant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Automatically Creates Case role record. Also used to set the Case Name</inlineHelpText>
    <label>Claimant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Clamant)</relationshipLabel>
    <relationshipName>Case_Management4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Claimant_Name_in_Text__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Name_in_Text__c</fullName>
    <label>Claimant Name in Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer_Name_in_Text__c.field-meta.xml
<CustomField>
    <fullName>Employer_Name_in_Text__c</fullName>
    <description>Hidden field for Form Assembly Employer Name lookups</description>
    <inlineHelpText>Do not enter a name in this box if it is blank. Later if you need to make a change to the Case Name, then edit the name in this box. Note: Editing the name in this box does not change the Account Name.</inlineHelpText>
    <label>Employer Name in Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the office that services this case</description>
    <inlineHelpText>Defines the office that will process this case.</inlineHelpText>
    <label>DIR Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office__c.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Courthouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Case Management</relationshipLabel>
    <relationshipName>Case_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Online_Claim_Account__c.field-meta.xml
<CustomField>
    <fullName>Online_Claim_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Online Claim Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Management (Online Claim Account)</relationshipLabel>
    <relationshipName>Online_Claim_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Related_Party_Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Party_Employer_Name__c</fullName>
    <label>Related Party Employer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Case - Open/Closed</description>
    <label>Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pre-Investigation</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Conf. Scheduled</fullName>
            </value>
            <value>
                <fullName>Conf. Held</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Hearing Approved</fullName>
            </value>
            <value>
                <fullName>Hearing Scheduled</fullName>
            </value>
            <value>
                <fullName>NOF Issued</fullName>
            </value>
            <value>
                <fullName>Under Writ</fullName>
            </value>
            <value>
                <fullName>Referred to DA</fullName>
            </value>
            <value>
                <fullName>Eligible for Closure</fullName>
            </value>
            <value>
                <fullName>Administrative Closure</fullName>
            </value>
            <value>
                <fullName>Ready to Assign</fullName>
            </value>
            <value>
                <fullName>Pending Settlement</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Hearing Held</fullName>
            </value>
            <value>
                <fullName>ODA Issued</fullName>
            </value>
            <value>
                <fullName>Judgment Issued</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Settled - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Inactive - Intake</fullName>
            </value>
            <value>
                <fullName>Wage Pass Through</fullName>
            </value>
            <value>
                <fullName>Pending - Incomplete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Not Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIR_Employee__c/DIR_Employee__c.object-meta.xml
<CustomObject>
    <description>This object store employee information in order to determine who may be currently responsible for a record.</description>
    <label>Internal Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Employee__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The office the user is associated to. Related fields are used on output documents</description>
    <inlineHelpText>The office to which the employee is associated.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Internal Employees</relationshipLabel>
    <relationshipName>Internal_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <description>Holds internal office location information</description>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Office_Email__c.field-meta.xml
<CustomField>
    <fullName>Office_Email__c</fullName>
    <description>For "LaborComm...: office email in Conga docs.</description>
    <label>Office Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Office__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <description>Used for a Flow in order to Map the BOFE Office for WCA Wage Referrals</description>
    <inlineHelpText>Used for a Flow in order to Map the BOFE Office for WCA Wage Referrals</inlineHelpText>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bakersfield</fullName>
            </value>
            <value>
                <fullName>El Centro</fullName>
            </value>
            <value>
                <fullName>Fresno</fullName>
            </value>
            <value>
                <fullName>Long Beach</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Oakland</fullName>
            </value>
            <value>
                <fullName>Redding</fullName>
            </value>
            <value>
                <fullName>Sacramento</fullName>
            </value>
            <value>
                <fullName>Salinas</fullName>
            </value>
            <value>
                <fullName>San Bernardino</fullName>
            </value>
            <value>
                <fullName>San Diego</fullName>
            </value>
            <value>
                <fullName>San Francisco</fullName>
            </value>
            <value>
                <fullName>San Jose</fullName>
            </value>
            <value>
                <fullName>Santa Ana</fullName>
            </value>
            <value>
                <fullName>Santa Barbara</fullName>
            </value>
            <value>
                <fullName>Santa Rosa</fullName>
            </value>
            <value>
                <fullName>Stockton</fullName>
            </value>
            <value>
                <fullName>Van Nuys</fullName>
            </value>
            <value>
                <fullName>Riverside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lists the offices and their addresses for use in creating output documents and other functions</description>
    <label>Office Location</label>
</CustomObject>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OWCCaseManagementController.cls
/*Name: OWCCaseManagementController
* Description: This class is used to get all the submitted case management records for the current community login user.
* Primary Record: Case Management
*/
public without sharing class OWCCaseManagementController {
    @AuraEnabled
    public static List<caseWrapperObj> getSubmittedCaseRecords(){
        
        List<caseWrapperObj> wrapperList = new List<caseWrapperObj>();
        String communityAccountId;
        try {
            System.debug('OWCConstants.ONLINE_CLAIM_COMMUNITY_USER_PROFILE_ID ::: '+OWCConstants.ONLINE_CLAIM_COMMUNITY_USER_PROFILE_ID);
            System.debug('userInfo.getProfileId() ::: '+userInfo.getProfileId());
            if(OWCConstants.ONLINE_CLAIM_COMMUNITY_USER_PROFILE_ID != null && userInfo.getProfileId() == OWCConstants.ONLINE_CLAIM_COMMUNITY_USER_PROFILE_ID){
                communityAccountId = [SELECT Id, ContactId, AccountId, Profile.Name FROM User 
                                      WHERE Id =: userInfo.getUserId() LIMIT 1].AccountId;
            }
            List<DIR_Case__c> caseObjList;
            if(String.isNotBlank(communityAccountId)){
                caseObjList = [SELECT Case_Number__c,Related_Party_Employer_Name__c, Claimant__r.Name, Claimant_Name_in_Text__c, Id,
                                                 Name, Employer_Name_in_Text__c, Employer__r.Name, CreatedDate, Status__c FROM DIR_Case__c 
                                                 WHERE Online_Claim_Account__c =: communityAccountId ORDER BY CreatedDate DESC];
            }
            
            if(caseObjList.size() > 0){
                for(DIR_Case__c caseObj : caseObjList){
                    caseWrapperObj wrapperObj = new caseWrapperObj();
                    wrapperObj.caseName = caseObj.Name;
                    wrapperObj.recordId = caseObj.Id;
                    wrapperObj.claimantName = caseObj.Claimant__r.Name != null ? caseObj.Claimant__r.Name : caseObj.Claimant_Name_in_Text__c;
                    wrapperObj.status = caseObj.Status__c;
                    wrapperObj.employerName = caseObj.Employer__r.Name != null ? caseObj.Employer__r.Name : caseObj.Related_Party_Employer_Name__c;
                    wrapperObj.CaseNumber = (caseObj.Status__c == 'Not Confirmed') ? '' : caseObj.Case_Number__c;
                    wrapperObj.submittedDate = (caseObj.createdDate).format('MM/dd/yyyy');
                    wrapperObj.submitDate = caseObj.createdDate.Date();
                    if(wrapperObj.submitDate.daysBetween(Date.today()) >=60 && caseObj.Status__c == 'Not Confirmed'){//&& caseObj.Status__c == 'Not Confirmed'
                        wrapperObj.is60DayOld = true;
                    }
                    wrapperList.add(wrapperObj);
                }
            }
            return wrapperList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        } 
    }
    // This method is used to get the current case management details.
    @AuraEnabled
    public static caseWrapperObj getCaseDetails(String recordId){
        try{
            List<ContentDocumentLink> contentDocLinks;
            List<ContentDistribution> contentDistributionObj;
            System.debug('recordId ::: '+recordId);
            if(String.isNotBlank(recordId)){
                /*Set<Id> contentIds = new Set<Id>();
                List<ContentDocument> contDocs = [SELECT Id, Title, ParentId FROM ContentDocument WHERE Title = 'Wage Claim Summary Report'];
                if(contDocs.size() > 0){
                    for(ContentDocument contDocObj : contDocs){
                        contentIds.add(contDocObj.Id);
                    }
                }*/
                
                    contentDocLinks = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink
                                       WHERE LinkedEntityId =: recordId AND ContentDocument.Title = 'Wage Claim Summary Report'];
                
                //Get the attachment record
                List<Attachments_New__c> aPlusData = [SELECT Id,Name,File_Type__c,Related_Id__c,File_Name__c, Release_To_Public__c FROM Attachments_New__c 
                                              WHERE Related_Id__c =: recordId AND File_Name__c = 'Wage Claim Summary Report' LIMIT 1];
                
                System.debug('aPlusData ::: '+aPlusData);
                
                String fileURL;
                if(aPlusData != null && aPlusData.size() > 0){
                    if(aPlusData[0].Release_To_Public__c){
                        if(contentDocLinks.size() > 0){
                            contentDistributionObj = [SELECT Id, ContentDownloadUrl, PdfDownloadUrl, DistributionPublicUrl, ContentDocumentId FROM ContentDistribution
                                                      WHERE ContentDocumentId =: contentDocLinks[0].ContentDocumentId];
                            
                            fileURL = contentDistributionObj != null && contentDistributionObj.size() > 0 ? contentDistributionObj[0] != null ? contentDistributionObj[0].DistributionPublicUrl : null : null;
                        }
                    }
                    else{
                        fileURL = OWCSharepointAPIService.getFilesFromSharePoint(new List<String>{aPlusData[0].Id})[0];//A_Plus_Controller.viewSharepointFile(aPlusData[0].Id);
                    }
                }
                system.debug('fileURL: '+fileURL);
                
                System.debug('contentDocLinks ::: '+contentDocLinks);
                
                caseWrapperObj caseWrapObj = new caseWrapperObj();
                DIR_Case__c caseObj = [SELECT Id, Name, Address_Primary_Zip__c, Case_Number__c, Assigned_Deputy__r.Name, Office__r.Office_Location__c, 
                                       Office__r.Office_Email__c, CreatedDate, Status__c FROM DIR_Case__c WHERE Id =: recordId];
                if(caseObj != null){
                    caseWrapObj.assignedDeputy = caseObj.Assigned_Deputy__r.Name;
                    caseWrapObj.officeLocation = caseObj.Office__r.Office_Location__c;
                    caseWrapObj.CaseNumber = caseObj.Case_Number__c;
                    caseWrapObj.caseName = caseObj.Name;
                    caseWrapObj.status = caseObj.Status__c;
                    //caseWrapObj.contentDocuments = contentIds;
                    caseWrapObj.officeEmail = caseObj.Office__r.Office_Email__c;
                    caseWrapObj.pdfLink = fileURL;
                    caseWrapObj.isPDFAvailable = caseWrapObj.pdfLink != null ? true : false;
                }
                Date createdDate = caseObj.createdDate.Date();
                if(createdDate.daysBetween(Date.today()) >=30 && caseObj.Status__c == 'Not Confirmed'){// && caseObj.Status__c == 'Not Confirmed'
                    caseWrapObj.is60DayOld = true;
                }
                if(caseWrapObj != null){
                    return caseWrapObj;
                }
            }
            return null;
        }catch (Exception e) {
            throw new AuraHandledException(e.getStackTraceString());
        }
    }
    public class caseWrapperObj{
        @AuraEnabled
        public Set<Id> contentDocuments{get;set;}
        @AuraEnabled
        public String caseName{get;set;}
        @AuraEnabled
        public String recordId{get;set;}
        @AuraEnabled
        public String claimantName{get;set;}
        @AuraEnabled
        public String CaseNumber{get;set;}
        @AuraEnabled
        public String status{get;set;}
        @AuraEnabled
        public String employerName{get;set;}
        @AuraEnabled
        public Date submitDate {get;set;}
        @AuraEnabled
        public String submittedDate {get;set;}
        @AuraEnabled
        public String errorMsg{get;set;}
        @AuraEnabled
        public String assignedDeputy{get;set;}
        @AuraEnabled
        public String officeLocation{get;set;}
        @AuraEnabled
        public String officeEmail{get;set;}
        @AuraEnabled
        public String pdfLink{get;set;}
        @AuraEnabled
        public Boolean is60DayOld{get;set;}
        @AuraEnabled
        public Boolean isPDFAvailable{get;set;}
    }
}