force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Id__c</fullName>
    <label>Related Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DIR_PreventHistoricDataDelete_Test.cls
@isTest
private class DIR_PreventHistoricDataDelete_Test {

    private static testMethod void testPreventHistoricDataDelete() {
         
        Account objAccount = new Account(Name = 'Test');
        insert objAccount;
        
        DIR_Case__c objCase = new DIR_Case__c(Employer__c = objAccount.Id);
        insert objCase;
         

        Attachments_New__c objAttachment = new Attachments_New__c(File_Name__c = 'Test',
                                                                  File_Type__c = 'Test',
                                                                  Related_Id__c = objCase.Id);
        insert  objAttachment;
        
        ContentVersion conVer = new ContentVersion( ContentLocation = 'S',
                                                    PathOnClient = 'Test',
                                                    Title = 'test',
                                                    VersionData = EncodingUtil.base64Decode('Test'),
                                                    Origin = 'C');
       insert conVer;
       
       String cdId = [SELECT id, ContentDocumentId 
                      FROM ContentVersion 
                      WHERE id = :conVer.id].ContentDocumentId;
                      
       ContentDocumentLink objCDL = new ContentDocumentLink( ContentDocumentId = cdId,
                                                              ShareType = 'I',
                                                              LinkedEntityId = objAttachment.id);
        
        insert objCDL;
        
        try{
            delete objCase;
        }
        catch(Exception ex){
            
        }
        
        try{
            delete objAttachment;
        }
        catch(Exception ex){
            system.assertEquals(ex.getMessage().contains('Only system administrators can delete historical attachments.'),true);
        }
        
        try{
            delete objCDL;
        }
        catch(Exception ex){
            
        }
        
        try{
            delete new ContentDocument(Id = cdId);
        }
        catch(Exception ex){
            
        }
        
        

    }

}