force-app/main/default/objects/Attachments_New__c/Attachments_New__c.object-meta.xml
<CustomObject>
    <label>Attachments +</label>
    <nameField>
        <displayFormat>A+-{000000}</displayFormat>
        <label>Attachments Plus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments +</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_New__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Attachments +</relationshipLabel>
    <relationshipName>CaseAttachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_New__c/fields/Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Id__c</fullName>
    <label>Related Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/Attachments_Plus__c.object-meta.xml
<CustomObject>
    <label>Attachments Plus</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Attachments Plus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Detail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachments_Plus__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Attorney_Client_Privilege__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Client_Privilege__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is subject to attorney-client privilege.</inlineHelpText>
    <label>Attorney-Client Privilege</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to indicate that this document is considered confidential</inlineHelpText>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attachments_Plus__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <formula>Case_Management__r.Employer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/DIR_Case__c.object-meta.xml
<CustomObject>
    <description>This object contains the BOFE DIR Case.  Temporary name will be DIR Case in order to differentiate between Standard Object Case and this case.  Vertiba August 20 from ERD</description>
    <label>Case Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>DIR Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIR_Case__c/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</description>
    <inlineHelpText>This is the Legal Entity. If there is a DBA, this can be added on the Employer/Account page.</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DIR_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIR_Case__c/recordTypes/PAGA_Case.recordType-meta.xml
<RecordType>
    <fullName>PAGA_Case</fullName>
    <active>true</active>
    <label>PAGA Case</label>
</RecordType>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/classes/OWCUpdateAPlusSubDetailTest.cls
@IsTest
public class OWCUpdateAPlusSubDetailTest {
    @IsTest
    public static void testAPlusSubDetail(){
        RecordType caseRT = [SELECT Id FROM RecordType WHERE sObjectType = 'DIR_Case__c' AND DeveloperName = 'PAGA_Case' AND IsActive = true LIMIT 1];
        List<Trigger_Settings__c> triggerSetting = OWCTestDataFactory.createTriggerCustomSettingRecord();
        Account objAccount = new Account(Name = 'Test');
        insert objAccount;
        
        DIR_Case__c objCase = new DIR_Case__c(Employer__c = objAccount.Id, RecordTypeId = caseRT.Id);
        insert objCase;
        
        
        Attachments_New__c objAttachment = new Attachments_New__c(File_Name__c = 'Test',
                                                                  File_Type__c = 'Other PAGA Document',
                                                                  Related_Id__c = objCase.Id);
        insert  objAttachment;
        
        ContentVersion conVer = new ContentVersion( ContentLocation = 'S',
                                                   PathOnClient = 'Test',
                                                   Title = 'test',
                                                   VersionData = EncodingUtil.base64Decode('Test'),
                                                   Origin = 'C');
        insert conVer;
        
        String cdId = [SELECT id, ContentDocumentId 
                       FROM ContentVersion 
                       WHERE id = :conVer.id].ContentDocumentId;
        
        ContentDocumentLink objCDL = new ContentDocumentLink( ContentDocumentId = cdId,
                                                             ShareType = 'I',
                                                             LinkedEntityId = objAttachment.id);
        
        insert objCDL;
        
        List<Attachments_Plus__c> attachPlusList = new List<Attachments_Plus__c>();
        Attachments_Plus__c attachPlusObj = new Attachments_Plus__c();
        attachPlusObj.Account__c = objAccount.Id;
        attachPlusObj.Case_Management__c = objCase.Id;
        attachPlusObj.Confidential__c = true;
        attachPlusObj.Attorney_Client_Privilege__c = true;
        attachPlusObj.Confidential__c = true;
        attachPlusList.add(attachPlusObj);
        
        if(attachPlusList.size() > 0){
            insert attachPlusList;
        }
        
        ContentDocumentLink objCDLs = new ContentDocumentLink( ContentDocumentId = cdId,
                                                             ShareType = 'I',
                                                             LinkedEntityId = [SELECT Id FROM Attachments_Plus__c LIMIT 1].Id);
        insert objCDLs;
        
        Test.startTest();
        OWCUpdateAPlusSubDetail.updateAPlusSubDetail(attachPlusList);
        Test.stopTest();
    }
}