force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>HR - An employee in a position at a point in time.</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>Position__r.Division_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>American Canyon</fullName>
            </value>
            <value>
                <fullName>Anaheim</fullName>
            </value>
            <value>
                <fullName>Bakersfield</fullName>
            </value>
            <value>
                <fullName>Concord</fullName>
            </value>
            <value>
                <fullName>El Centro</fullName>
            </value>
            <value>
                <fullName>Eureka</fullName>
            </value>
            <value>
                <fullName>Foster City</fullName>
            </value>
            <value>
                <fullName>Fremont</fullName>
            </value>
            <value>
                <fullName>Fresno</fullName>
            </value>
            <value>
                <fullName>Glendale</fullName>
            </value>
            <value>
                <fullName>Goleta</fullName>
            </value>
            <value>
                <fullName>La Palma</fullName>
            </value>
            <value>
                <fullName>Lodi</fullName>
            </value>
            <value>
                <fullName>Long Beach</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Marina del Rey</fullName>
            </value>
            <value>
                <fullName>Modesto</fullName>
            </value>
            <value>
                <fullName>Monrovia</fullName>
            </value>
            <value>
                <fullName>Oakland</fullName>
            </value>
            <value>
                <fullName>Oxnard</fullName>
            </value>
            <value>
                <fullName>Pomona</fullName>
            </value>
            <value>
                <fullName>Redding</fullName>
            </value>
            <value>
                <fullName>Riverside</fullName>
            </value>
            <value>
                <fullName>Sacramento</fullName>
            </value>
            <value>
                <fullName>Salinas</fullName>
            </value>
            <value>
                <fullName>San Bernardino</fullName>
            </value>
            <value>
                <fullName>San Diego</fullName>
            </value>
            <value>
                <fullName>San Francisco</fullName>
            </value>
            <value>
                <fullName>San Jose</fullName>
            </value>
            <value>
                <fullName>San Leandro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>The Position an Employee occupies</description>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Division</description>
    <inlineHelpText>Select the Division</inlineHelpText>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin-Accounting</fullName>
            </value>
            <value>
                <fullName>Admin-Admin Services</fullName>
            </value>
            <value>
                <fullName>Admin-Budgets</fullName>
            </value>
            <value>
                <fullName>Admin-Business Serv</fullName>
            </value>
            <value>
                <fullName>Admin-Human Resources</fullName>
            </value>
            <value>
                <fullName>Admin-OIS</fullName>
            </value>
            <value>
                <fullName>Admin-RTWS</fullName>
            </value>
            <value>
                <fullName>CHSWC</fullName>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
            <value>
                <fullName>DLSE</fullName>
            </value>
            <value>
                <fullName>DLSE-IWC</fullName>
            </value>
            <value>
                <fullName>DLSE/PIU</fullName>
            </value>
            <value>
                <fullName>DLSE-PWD/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH</fullName>
            </value>
            <value>
                <fullName>DOSH-CFOI/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH-OIIS/OD-Research</fullName>
            </value>
            <value>
                <fullName>DWC</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/Claims Mgmt</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/SELSP</fullName>
            </value>
            <value>
                <fullName>Fast Food Council</fullName>
            </value>
            <value>
                <fullName>OD-Drug Formulary</fullName>
            </value>
            <value>
                <fullName>OD-Legal N</fullName>
            </value>
            <value>
                <fullName>OD-Legal S</fullName>
            </value>
            <value>
                <fullName>OD-PAGA</fullName>
            </value>
            <value>
                <fullName>OD-PIO/Communications</fullName>
            </value>
            <value>
                <fullName>Office of The Director</fullName>
            </value>
            <value>
                <fullName>OIS</fullName>
            </value>
            <value>
                <fullName>OSHAB</fullName>
            </value>
            <value>
                <fullName>OSHSB</fullName>
            </value>
            <value>
                <fullName>SIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Division_Name__c</fullName>
    <description>Changed label from Division to Unit Name per CR SR-013912. HR requested to have this field to reference Unit's field Unit Name.</description>
    <label>Unit Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Manual_Entry__c.field-meta.xml
<CustomField>
    <fullName>Manual_Entry__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/PY__c.field-meta.xml
<CustomField>
    <fullName>PY__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Person Years</description>
    <inlineHelpText>Enter the number of PYs for this position.</inlineHelpText>
    <label>PY</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Reporting_Unit_CodeNo__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Unit_CodeNo__c</fullName>
    <label>Reporting Unit CodeNo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial #</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>HR - Lookup to HR unit names</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin-Accounting</fullName>
            </value>
            <value>
                <fullName>Admin-Admin Services</fullName>
            </value>
            <value>
                <fullName>Admin-Budgets</fullName>
            </value>
            <value>
                <fullName>Admin-Business Serv</fullName>
            </value>
            <value>
                <fullName>Admin-Human Resources</fullName>
            </value>
            <value>
                <fullName>Admin-OIS</fullName>
            </value>
            <value>
                <fullName>Admin-RTWS</fullName>
            </value>
            <value>
                <fullName>Admin-TPSP</fullName>
            </value>
            <value>
                <fullName>CHSWC</fullName>
            </value>
            <value>
                <fullName>DAS</fullName>
            </value>
            <value>
                <fullName>DLSE</fullName>
            </value>
            <value>
                <fullName>DLSE-IWC</fullName>
            </value>
            <value>
                <fullName>DLSE-PWD/OD-Research</fullName>
            </value>
            <value>
                <fullName>DLSR</fullName>
            </value>
            <value>
                <fullName>DOSH</fullName>
            </value>
            <value>
                <fullName>DOSH-CFOI/OD-Research</fullName>
            </value>
            <value>
                <fullName>DOSH-OIIS/OD-Research</fullName>
            </value>
            <value>
                <fullName>DWC</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/Claims Mgmt</fullName>
            </value>
            <value>
                <fullName>DWC-RTW/SELSP</fullName>
            </value>
            <value>
                <fullName>Fast Food Council</fullName>
            </value>
            <value>
                <fullName>OD-Drug Formulary</fullName>
            </value>
            <value>
                <fullName>OD-Legal N</fullName>
            </value>
            <value>
                <fullName>OD-Legal S</fullName>
            </value>
            <value>
                <fullName>OD-PAGA</fullName>
            </value>
            <value>
                <fullName>OD-PIO/Communications</fullName>
            </value>
            <value>
                <fullName>OD/Anti-Fraud Unit</fullName>
            </value>
            <value>
                <fullName>Office of The Director</fullName>
            </value>
            <value>
                <fullName>OSHAB</fullName>
            </value>
            <value>
                <fullName>OSHSB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Unit_Name__c</fullName>
    <label>Unit Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/position_Methods.cls
public with sharing class position_Methods {
    public static void beforeInsert(List<Position__c> newlist){
        Set<String> unitNumbers = new Set<String>();
        for(Position__c p : newlist) {
            if(!p.Serial_Number__c.isNumeric()) {
                p.addError('Serial Number must be numeric');
                continue;
            }
            if(Integer.valueOf(p.Serial_Number__c) >= 900) {
                p.Manual_Entry__c = false;
                p.PY__c = null;
            }
            if(p.Manual_Entry__c == true) {
                p.addError('Cannot create Position without a 607 if serial number is less than 900');
            }
            if(p.Reporting_Unit_CodeNo__c != null && p.Reporting_Unit_CodeNo__c != '') {
                unitNumbers.add(p.Reporting_Unit_CodeNo__c);
            }
        }
        
        Map<String, String> unitNumberToDivision = new Map<String, String>();
        //10/19/2022 Removed Division__c and replaced it with Unit_Name__c in query (per HR CR SR-013912 )
        for(Unit__c unit : [select Id, Name, Unit_Name__c from Unit__c where Name in :unitNumbers]) {
            unitNumberToDivision.put(unit.Name, unit.Unit_Name__c);
        }
        
        for(Position__c p : newlist) {
            if(unitNumberToDivision.containsKey(p.Reporting_Unit_CodeNo__c)) {
                p.Division_Name__c = unitNumberToDivision.get(p.Reporting_Unit_CodeNo__c);
            }
        }
        
        Map<String, String> unitNumberToDivision1 = new Map<String, String>();
        for(Unit__c unit : [select Id, Name, Location__c from Unit__c where Name in :unitNumbers]) {
            unitNumberToDivision1.put(unit.Name, unit.Location__c);
        } 

        for(Position__c p : newlist) {
            if(unitNumberToDivision1.containsKey(p.Reporting_Unit_CodeNo__c)) {
                p.Location__c = unitNumberToDivision1.get(p.Reporting_Unit_CodeNo__c);
            }
        }
        
        
        
        Map<String, String> unitNumberToDivision2 = new Map<String, String>();
        for(Unit__c unit : [select Id, Name, Division_Unit__c from Unit__c where Name in :unitNumbers]) {
            unitNumberToDivision1.put(unit.Name, unit.Division_Unit__c);
        } 

        for(Position__c p : newlist) {
            if(unitNumberToDivision1.containsKey(p.Reporting_Unit_CodeNo__c)) {
                p.Division_Unit__c = unitNumberToDivision1.get(p.Reporting_Unit_CodeNo__c);
            }
        }
        
        
        
    }
    
    public static void beforeUpdate(List<Position__c> oldlist, List<Position__c> newlist){
        Set<String> unitNumbers = new Set<String>();
        for(Position__c p : newlist) {
            if(p.Reporting_Unit_CodeNo__c != null && p.Reporting_Unit_CodeNo__c != '') {
                unitNumbers.add(p.Reporting_Unit_CodeNo__c);
            }
        }
        
        Map<String, String> unitNumberToDivision = new Map<String, String>();
         //10/19/2022 Removed Division__c and replaced it with Unit_Name__c in query (per HR CR SR-013912 )
         for(Unit__c unit : [select Id, Name, Unit_Name__c from Unit__c where Name in :unitNumbers]) {
            unitNumberToDivision.put(unit.Name, unit.Unit_Name__c);
        }
        
        for(Position__c p : newlist) {
            if(unitNumberToDivision.containsKey(p.Reporting_Unit_CodeNo__c)) {
                p.Division_Name__c = unitNumberToDivision.get(p.Reporting_Unit_CodeNo__c);
            }
            if(p.Status__c =='Closed' || p.Status__c =='Abolished')
            {
                p.Position_Closed_Abolished__c = True;
            }
            else
                p.Position_Closed_Abolished__c = False;
        }
        
        
        
        Map<String, String> unitNumberToDivision2 = new Map<String, String>();
        for(Unit__c unit : [select Id, Name, Division_Unit__c from Unit__c where Name in :unitNumbers]) {
            unitNumberToDivision2.put(unit.Name, unit.Division_Unit__c);
        }
        
        for(Position__c p : newlist) {
            if(unitNumberToDivision.containsKey(p.Reporting_Unit_CodeNo__c)) {
                p.Division_Unit__c = unitNumberToDivision2.get(p.Reporting_Unit_CodeNo__c);
            }
        }
        
        
        
    }
    /*
    @isTest
    public static void position_Methods_UnitTest() {
        Unit__c unit = new Unit__c();
        unit.Division__c = 'TEST';
        unit.Name = '999';
        insert unit;
        
        Position__c p = new Position__c();
        p.Reporting_Unit_CodeNo__c = unit.Name;
        try {
            p.Serial_Number__c = 'asdf';
            insert p;
            p = new Position__c();
            p.Reporting_Unit_CodeNo__c = unit.Name;
        }
        catch (Exception e) {}
        try {
            p.Serial_Number__c = '123';
            insert p;
            p = new Position__c();
            p.Reporting_Unit_CodeNo__c = unit.Name;
        }
        catch (Exception e) {}
        p.Serial_Number__c = '909';
        p.Reporting_Unit_CodeNo__c = unit.Name;
        insert p;
        
        update p;
    } */
    /*public static void updatePositionVacancy() {
        List<Position__c> positionsToUpdate = new List<Position__c>();
        for(Position__c p : [select Id, Status__c, Serial_Number__c, Separation_Date__c, (select Temporarily_Vacant__c, Start_Date__c, End_Date__c from Appointments__r) from Position__c where isActive__c = true]) {
            if(p.Appointments__r.size() == 0 && p.Status__c == 'Filled') {
                p.Status__c = 'Vacant';
            }
            if(p.Appointments__r.size() > 0) {
                Appointment__c lastAppointment = p.Appointments__r.get(p.Appointments__r.size() - 1);
                if(lastAppointment.End_Date__c != null && lastAppointment.End_Date__c <= system.today()) {
                    p.Status__c = 'Vacant';
                }
            }
            
            positionsToUpdate.add(p);
        }
        update positionsToUpdate;
    }*/
}