force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>HR - An employee in a position at a point in time.</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An Employee in a Position</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Employee_Contact__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments Held</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Form_1__c.field-meta.xml
<CustomField>
    <fullName>Form_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form 1</label>
    <referenceTo>Form_1__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Hiring_Type__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Type__c</fullName>
    <description>This picklist is required to identify hiring type whether within DIR, Other Department or from outside.</description>
    <label>Hiring Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New to State</fullName>
            </value>
            <value>
                <fullName>Previous State EE</fullName>
            </value>
            <value>
                <fullName>Current DIR EE</fullName>
            </value>
            <value>
                <fullName>Transfer from other Dept</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>The Position an Employee occupies</description>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Supervisor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supervised Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>120-Position Number Change</fullName>
            </value>
            <value>
                <fullName>405-Time Base Change</fullName>
            </value>
            <value>
                <fullName>565-Reinstatement from IDL/TD</fullName>
            </value>
            <value>
                <fullName>A01-CEA appointment from list</fullName>
            </value>
            <value>
                <fullName>A01-Graduate Student Assistant</fullName>
            </value>
            <value>
                <fullName>A01-Limited Term from List</fullName>
            </value>
            <value>
                <fullName>A01-Permanent Appointment from List</fullName>
            </value>
            <value>
                <fullName>A01-Student Assistant</fullName>
            </value>
            <value>
                <fullName>A01-TAU in Lieu of Limited Term</fullName>
            </value>
            <value>
                <fullName>A01-TAU in Lieu of Permanent Appointment</fullName>
            </value>
            <value>
                <fullName>A01-Youth Aid</fullName>
            </value>
            <value>
                <fullName>A02-Emergency</fullName>
            </value>
            <value>
                <fullName>A02-Reinstatement (permissive)</fullName>
            </value>
            <value>
                <fullName>A02-Retired Annuitant</fullName>
            </value>
            <value>
                <fullName>A02-Transfer</fullName>
            </value>
            <value>
                <fullName>A03-Reinstatement (mandatory)</fullName>
            </value>
            <value>
                <fullName>A03-Reinstatement from LOA</fullName>
            </value>
            <value>
                <fullName>A03-Reinstatement from NDI</fullName>
            </value>
            <value>
                <fullName>A03-Reinstatement from SDI</fullName>
            </value>
            <value>
                <fullName>A04-Training &amp; Development</fullName>
            </value>
            <value>
                <fullName>A11-Involuntary Reassignment</fullName>
            </value>
            <value>
                <fullName>A14 - Adverse Demotion</fullName>
            </value>
            <value>
                <fullName>A20-Reallocation</fullName>
            </value>
            <value>
                <fullName>A22-In Lieu of Appt through Cert Process</fullName>
            </value>
            <value>
                <fullName>A30/A31-Exempt</fullName>
            </value>
            <value>
                <fullName>SPC-Special Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Type_of_Separation__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Separation__c</fullName>
    <label>Type of Separation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>120 Position # change</fullName>
            </value>
            <value>
                <fullName>405 Time Base Change</fullName>
            </value>
            <value>
                <fullName>565-IDL</fullName>
            </value>
            <value>
                <fullName>565-TD</fullName>
            </value>
            <value>
                <fullName>Reallocation-(A20)</fullName>
                <label>Reallocation (A20)</label>
            </value>
            <value>
                <fullName>S01-Resignation</fullName>
            </value>
            <value>
                <fullName>S05-Resignation Without Fault</fullName>
            </value>
            <value>
                <fullName>S21-AWOL</fullName>
            </value>
            <value>
                <fullName>S31-No Layoff</fullName>
            </value>
            <value>
                <fullName>S40-Termination with fault</fullName>
            </value>
            <value>
                <fullName>S41-Dismissal</fullName>
            </value>
            <value>
                <fullName>S49-NDI</fullName>
            </value>
            <value>
                <fullName>S50-Leave of Absence</fullName>
            </value>
            <value>
                <fullName>S50-SDI Leave of Absence</fullName>
            </value>
            <value>
                <fullName>S51-Military</fullName>
            </value>
            <value>
                <fullName>S57 Pending Disability</fullName>
            </value>
            <value>
                <fullName>S70-Service Retirement</fullName>
            </value>
            <value>
                <fullName>S71-Disability Retirement</fullName>
            </value>
            <value>
                <fullName>S80 Termination-Illegal Appointment</fullName>
            </value>
            <value>
                <fullName>S85-Adverse Suspension</fullName>
            </value>
            <value>
                <fullName>S90-Probe Rejection</fullName>
            </value>
            <value>
                <fullName>S95-Death</fullName>
            </value>
            <value>
                <fullName>SPC-Special Change</fullName>
            </value>
            <value>
                <fullName>Transfer/Promotion within DIR</fullName>
            </value>
            <value>
                <fullName>Transfer to another Agency/Department</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>HR - DIR Employees (contacts)</description>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter First Name</inlineHelpText>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_1__c/Form_1__c.object-meta.xml
<CustomObject>
    <description>HR - Form to advertise an open position</description>
    <label>Form 1</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Form 1 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form 1s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>HR - All positions and their status within DIR.</description>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Position</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Manual_Entry__c.field-meta.xml
<CustomField>
    <fullName>Manual_Entry__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial #</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - Civil Service</fullName>
            </value>
            <value>
                <fullName>4 - Exempt</fullName>
            </value>
            <value>
                <fullName>7 - Salary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/appointment_Tests.cls
@isTest
(SeeAllData = true)
public class appointment_Tests {

    static testMethod void appointment_Methods_UnitTest() {
        test.startTest();
        Employee__c emp = new Employee__c();
        emp.First_Name__c = 'Test';
        emp.Last_Name__c = 'Last';
        insert emp;
        
        Position__c p1 = new Position__c();
        p1.Serial_Number__c = '111';
        p1.Manual_Entry__c = false;
        insert p1;
        Contact c1 = new Contact();
        c1.LastName = 'Test';
        insert c1;
        
        Appointment__c a1 = new Appointment__c();
        a1.Position__c = p1.Id;
        a1.Employee_Contact__c = c1.Id;
        a1.Supervisor_Contact__c = c1.Id;
        a1.Start_Date__c = System.today().addDays(-3);
        a1.Employee__c = emp.Id;
        a1.Type__c = 'xyz';
        a1.Hiring_Type__c = 'zyz';
        insert a1;
        
        a1.End_Date__c = System.today();
        a1.Type_of_Separation__c = 'a';
        update a1;
        
        Appointment__c a2 = new Appointment__c();
        a2.Position__c = p1.Id;
        a2.Employee_Contact__c = c1.Id;
        a2.Start_Date__c = System.today().addDays(1);
        a2.End_Date__c = System.today().addDays(2);
        a2.Employee__c = emp.Id;
        a2.Type__c = 'xyz';
        a2.Hiring_Type__c = 'zyz';
        a2.Type_of_Separation__c = 'x';
        insert a2;
        
        Appointment__c a3 = new Appointment__c();
        a3.Position__c = p1.Id;
        a3.Employee_Contact__c = c1.Id;
        a3.Supervisor_Contact__c = c1.Id;
        a3.Start_Date__c = System.today().addDays(3);
        a3.Employee__c = emp.Id;
        a3.Type__c = 'xyz';
        a3.Hiring_Type__c = 'zyz';
        insert a3;
        
        delete new List<Appointment__c>{a1, a2};
        delete a3;
        
        Form_1__c f1 = new Form_1__c();
        insert f1;
        
        Appointment__c a4 = new Appointment__c();
        a4.Form_1__c = f1.Id;
        a4.Position__c = p1.Id;
        a4.Employee_Contact__c = c1.Id;
        a4.Supervisor_Contact__c = c1.Id;
        a4.Start_Date__c = System.today().addDays(5);
        a4.Employee__c = emp.Id;
        a4.Type__c = 'xyz';
        a4.Hiring_Type__c = 'zyz';
        insert a4;
        
        test.stopTest();
    }
}