force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/AgentAuthorizationDA__c.field-meta.xml
<CustomField>
    <fullName>AgentAuthorizationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agent Authorization DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/AgreementsDA__c.field-meta.xml
<CustomField>
    <fullName>AgreementsDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agreements DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyAddressInformationDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyAddressInformationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Address Information DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyContactDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyContactDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Contact DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyFinancesDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyFinancesDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Finances DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyInformationDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyInformationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Information DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyLocationsDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyLocationsDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Locations DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyManagersDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyManagersDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Managers DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyNameTypeDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyNameTypeDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Name &amp; Type DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyOwnersDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyOwnersDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Owners DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/CompanyTypeRenewalDA__c.field-meta.xml
<CustomField>
    <fullName>CompanyTypeRenewalDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Type - Renewal DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/DisclaimerDA__c.field-meta.xml
<CustomField>
    <fullName>DisclaimerDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disclaimer DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Documentation_III_DA__c.field-meta.xml
<CustomField>
    <fullName>Documentation_III_DA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Documentation III DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/DocumentationIDA__c.field-meta.xml
<CustomField>
    <fullName>DocumentationIDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Documentation I DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/DocumentationIIDA__c.field-meta.xml
<CustomField>
    <fullName>DocumentationIIDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Documentation II DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/EducationDA__c.field-meta.xml
<CustomField>
    <fullName>EducationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Education DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/FeesDA__c.field-meta.xml
<CustomField>
    <fullName>FeesDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fees DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/FollowupQuestionsDA__c.field-meta.xml
<CustomField>
    <fullName>FollowupQuestionsDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Follow up Questions DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Information_II_DA__c.field-meta.xml
<CustomField>
    <fullName>Information_II_DA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in FLC for Information section II on vipform tool for External to check mark defect reviewed for the section</description>
    <inlineHelpText>Please check if Defects are corrected</inlineHelpText>
    <label>Information II DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Information_III_DA__c.field-meta.xml
<CustomField>
    <fullName>Information_III_DA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in FLC for Information section III on vipform tool for External to check mark defect reviewed for the section</description>
    <inlineHelpText>Please check if Defects are corrected</inlineHelpText>
    <label>Information III DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/InformationIDA__c.field-meta.xml
<CustomField>
    <fullName>InformationIDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Information I DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/LiveScanDA__c.field-meta.xml
<CustomField>
    <fullName>LiveScanDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live Scan DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/LocationDocumentationDA__c.field-meta.xml
<CustomField>
    <fullName>LocationDocumentationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Documentation DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/MedicalInformationDA__c.field-meta.xml
<CustomField>
    <fullName>MedicalInformationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Information DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/MinorInformationDA__c.field-meta.xml
<CustomField>
    <fullName>MinorInformationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Minor Information DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/ParentGuardianInformationDA__c.field-meta.xml
<CustomField>
    <fullName>ParentGuardianInformationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parent/Guardian Information DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/PermitApplicantDA__c.field-meta.xml
<CustomField>
    <fullName>PermitApplicantDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit Applicant DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/QualifyingQuestionDA__c.field-meta.xml
<CustomField>
    <fullName>QualifyingQuestionDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Qualifying Question DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/QuestionnaireDA__c.field-meta.xml
<CustomField>
    <fullName>QuestionnaireDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Questionnaire DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/RegistrationDurationDA__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDurationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Registration Duration DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/SchoolInformationDA__c.field-meta.xml
<CustomField>
    <fullName>SchoolInformationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>School Information DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Sexual_Harassment_Prevention_TrainingDA__c.field-meta.xml
<CustomField>
    <fullName>Sexual_Harassment_Prevention_TrainingDA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in FLC for Sexual Harassment Prevention on vipform tool to check mark defect reviewed for the section</description>
    <inlineHelpText>Please check if Defects are corrected</inlineHelpText>
    <label>Sexual Harassment Prevention Training DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/UploadDocumentDA__c.field-meta.xml
<CustomField>
    <fullName>UploadDocumentDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upload Document DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/VIP_Template_Status__c.field-meta.xml
<CustomField>
    <fullName>VIP_Template_Status__c</fullName>
    <label>VIP Template Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/WCI_and_Bond_DocumentationDA__c.field-meta.xml
<CustomField>
    <fullName>WCI_and_Bond_DocumentationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in FLC for WCI and Bond Documentation Section on vipform tool for to check mark defect reviewed for the section</description>
    <inlineHelpText>Please check if Defects are corrected</inlineHelpText>
    <label>WCI and Bond Documentation DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/WCI_and_BondDA__c.field-meta.xml
<CustomField>
    <fullName>WCI_and_BondDA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in FLC for WCI and Bond section on vipform tool for External to check mark defect reviewed for the section</description>
    <inlineHelpText>Please check if Defects are corrected</inlineHelpText>
    <label>WCI and Bond DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/WCIDocumentationDA__c.field-meta.xml
<CustomField>
    <fullName>WCIDocumentationDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WCI Documentation DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/WorkersCompDA__c.field-meta.xml
<CustomField>
    <fullName>WorkersCompDA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Workers Comp DA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration_Defects_Mapping__mdt/Registration_Defects_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Registration Defects Mapping</label>
    <pluralLabel>Registration Defects Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Registration_Defects_Mapping__mdt/fields/Field_API__c.field-meta.xml
<CustomField>
    <fullName>Field_API__c</fullName>
    <label>Field API</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/Rejection_Defect__c.object-meta.xml
<CustomObject>
    <description>Junction object between Rejections and Defects.</description>
    <label>Rejection Defect</label>
    <nameField>
        <displayFormat>RJD-{0000000}</displayFormat>
        <label>Rejection Defect Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rejection Defects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rejection_Defect__c/fields/Applies__c.field-meta.xml
<CustomField>
    <fullName>Applies__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Applies?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Rejection Defects</relationshipLabel>
    <relationshipName>Rejection_Defects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/fields/Resolved__c.field-meta.xml
<CustomField>
    <fullName>Resolved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Values from this field roll up to Registration via DLRS</description>
    <inlineHelpText>Has this defect been resolved?</inlineHelpText>
    <label>Resolved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <label>Test</label>
</RecordType>

force-app/main/default/classes/RejectionDefectTriggerHandler.cls
/********************************************************************************************************
Name:  RejectionDefectTriggerHandler.cls
Author:  vertiba
Date:  11/26/2018
Modified by: 
Date:
Test class: 

Behavior: 170016,170017
********************************************************************************************************/
public without sharing class RejectionDefectTriggerHandler{
    
    List<License_Registration__c> regToUpdate = new List<License_Registration__c>();

    
    public void afterInsert(List<Rejection_Defect__c> newList){
        //if(checkRecursive.runOnce())
       // UpdateRegistration(newList);
    }
    public void afterUpdate(List<Rejection_Defect__c> newList, Map<Id,Rejection_Defect__c > oldMap){
        //if(checkRecursive.runOnce())
        UpdateRegistration(newList);
    }
    public void afterDelete(List<Rejection_Defect__c> oldList){
        //if(checkRecursive.runOnce())
        UpdateRegistration(oldList);
    }
    
    public void UpdateRegistration(List<Rejection_Defect__c> newList){
        System.debug('in update regi');
        Logger.push('UpdateRegistration','RejectionDefectTriggerHandler');
        Set<Id> regids = new Set<Id>();
        Map<Id,Set<String>> regRejDefMap = new Map<Id,Set<String>>();
        Set<String> sectionLst = new Set<String>();
        Map<String,String> secFeildMap = new Map<String,String>();
        
        for(Rejection_Defect__c rd: newList){
            regIds.add(rd.Registration__c);  
            if(trigger.isDelete)
                sectionLst.add(rd.Section__c);
        }
     
         //fetch metadata
         for(Registration_Defects_Mapping__mdt rdm: [Select MasterLabel,Field_API__c FROM Registration_Defects_Mapping__mdt])
             secFeildMap.put(rdm.MasterLabel,rdm.Field_API__c);

         if(!secFeildMap.isEmpty()){
         Logger.debug('secFeildMap***'+secFeildMap);
         
        string query = 'Select ID,VIP_Template_Status__c, AgentAuthorizationDA__c,AgreementsDA__c,CompanyContactDA__c,CompanyFinancesDA__c,CompanyInformationDA__c,CompanyLocationsDA__c,CompanyManagersDA__c,CompanyNameTypeDA__c,CompanyOwnersDA__c, CompanyTypeRenewalDA__c,DisclaimerDA__c,EducationDA__c, FeesDA__c,FollowupQuestionsDA__c,QuestionnaireDA__c,WCIDocumentationDA__c,CompanyAddressInformationDA__c,WorkersCompDA__c,LocationDocumentationDA__c,PermitApplicantDA__c,LiveScanDA__c,QualifyingQuestionDA__c, ParentGuardianInformationDA__c, UploadDocumentDA__c, MedicalInformationDA__c, MinorInformationDA__c, RegistrationDurationDA__c, SchoolInformationDA__c, InformationIDA__c, Information_II_DA__c,Information_III_DA__c, DocumentationIDA__c, DocumentationIIDA__c,Documentation_III_DA__c, WCI_and_BondDA__c,WCI_and_Bond_DocumentationDA__c,Sexual_Harassment_Prevention_TrainingDA__c, ';
        if(trigger.isInsert)
            query += '(SELECT ID,Applies__c, Resolved__c,Registration__c,Section__c FROM Rejection_Defects__r WHERE ID IN:newList )';
        if(trigger.isUpdate)
            query += '(SELECT ID,Applies__c, Resolved__c,Registration__c,Section__c FROM Rejection_Defects__r)';
        if(trigger.isDelete)
            query += '(SELECT ID,Applies__c, Resolved__c,Registration__c,Section__c FROM Rejection_Defects__r WHERE Section__c IN: sectionLst)';
        query += 'FROM License_Registration__c WHERE Id IN: regIds';
        
            //fetch all the related registrations
            Map <Id, License_Registration__c> regLst = new Map<Id, License_Registration__c>(
                (List<License_Registration__c>)Database.query(query)
            );
            
                                               
            for(License_Registration__c reg : regLst.Values()){
                if(!reg.Rejection_Defects__r.isEmpty()){
                    
                    for(Rejection_Defect__c rd:reg.Rejection_Defects__r){
                        //collect all those rejection defects which applies and not resolved
                        
                        if(rd.Applies__c && !rd.Resolved__c){
                            if(!regRejDefMap.ContainsKey(rd.Registration__c)){
                                Set<String> secLst = new Set<String>{rd.Section__c};
                                regRejDefMap.put(rd.Registration__c,secLst); 
                            }else{              
                                Set<String> secLst = regRejDefMap.get(rd.Registration__c);
                                secLst.add(rd.Section__c);
                                regRejDefMap.put(rd.Registration__c,secLst); 
                            }
                        }
                        
                    }
                }                
            }
            System.debug('regRejDefMap--'+regRejDefMap);
        if(trigger.isInsert || trigger.isUpdate){
            for(License_Registration__c reg : regLst.Values()){
                
                if(!reg.Rejection_Defects__r.isEmpty()){
                    for(Rejection_Defect__c rd:reg.Rejection_Defects__r){
                        if(regRejDefMap.containsKey(reg.Id)){
                            if(regRejDefMap.get(reg.Id).Contains(rd.Section__c)){
                             //make it true
                                updateCheckbox(reg, secFeildMap.get(rd.Section__c), TRUE);
                            }else{
                                //make it false   
                                updateCheckbox(reg, secFeildMap.get(rd.Section__c), FALSE);
                            }
                        }
                        else{
                         //make it false
                             //system.debug(Logginglevel.INFO,'rd.Section__c***'+rd.Section__c);
                            updateCheckbox(reg, secFeildMap.get(rd.Section__c), FALSE);
                        }
                         
                    }
                }
                
            }
        }else if(trigger.isDelete){
            
            for(Rejection_Defect__c rd: newList){
                if(regRejDefMap.ContainsKey(rd.Registration__c)){
                    if(regRejDefMap.get(rd.Registration__c).Contains(rd.Section__c)){
                        //make it true
                        updateCheckbox(regLst.get(rd.Registration__c), secFeildMap.get(rd.Section__c), TRUE);
                    }else{
                        //make it false
                        updateCheckbox(regLst.get(rd.Registration__c), secFeildMap.get(rd.Section__c), FALSE);
                    }
                }else{
                    //make it false
                    updateCheckbox(regLst.get(rd.Registration__c), secFeildMap.get(rd.Section__c), FALSE);
                    
                }
            }
        }
        //If list not empty, update the registrations
      }      
      system.debug('regToUpdate--'+regToUpdate);
            if(!regToUpdate.isEmpty()){
                update regToUpdate;
            }
      Logger.pop();
    }
    public void updateCheckbox(License_Registration__c reg, String Section, Boolean defectIdentified){
      Logger.push('updateCheckbox','RejectionDefectTriggerHandler');
        System.debug('updateCheckbox');
        System.debug(Section);
        System.debug(defectIdentified);
        //make it true/false
        try {
            if(Section != null && reg.get(Section) != defectIdentified){
                reg.put(Section,defectIdentified);

                if(!regToUpdate.Contains(reg))
                    regToUpdate.add(reg);
            }
        } catch(DmlException de) {
            System.debug(de.getMessage());
        }

    Logger.pop();
    }
}