force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Bank__c/Question_Bank__c.object-meta.xml
<CustomObject>
    <description>The Question Bank Object will store all questions used in the form tool for registrations.  The Registration Question Object and Follow-Up Question Object will pull questions from the bank.</description>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QID-{0000}</displayFormat>
        <label>Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Bank__c/fields/Answer_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Type__c</fullName>
    <label>Answer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YesNo</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Long Text</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Bank__c/fields/Controlling_Question__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Allows for defining a followup question based on a previously answered question</description>
    <inlineHelpText>Lookup the question that will be the "master" or "preceding" question to this question.</inlineHelpText>
    <label>Controlling Question</label>
    <referenceTo>Question_Bank__c</referenceTo>
    <relationshipLabel>Follow-up Question Configs</relationshipLabel>
    <relationshipName>Question_Bank</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Bank__c/fields/Follow_up_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Criteria__c</fullName>
    <inlineHelpText>Define the criteria for the answer from the controlling question that triggers this follow-up question to be relevant. e.g. Yes, NOT NULL</inlineHelpText>
    <label>Follow-up Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Bank__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Rule__c/Question_Rule__c.object-meta.xml
<CustomObject>
    <description>The Question Rule object determines the sort order for registration questions and is only accessible to system admins.</description>
    <label>Question Rule</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Rule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Rule__c/fields/Question_ID__c.field-meta.xml
<CustomField>
    <fullName>Question_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question ID</label>
    <referenceTo>Question_Bank__c</referenceTo>
    <relationshipLabel>Question Rules</relationshipLabel>
    <relationshipName>Question_Rules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Rule__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <formula>Question_ID__r.Short_Text__c</formula>
    <label>Question Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Rule__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Registration_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Rule__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>Define the order in which you want the questions to appear. Blank values will show last on the questionnaire section of the application</inlineHelpText>
    <label>Sort Order</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration_Question__c/Registration_Question__c.object-meta.xml
<CustomObject>
    <description>Registration Questions for the Q1 Tab in the Form Tool.  These will be controlling questions that decide what appears in Q2 tab of the Form tool.</description>
    <label>Registration Questions</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Question__c/fields/Question_ID__c.field-meta.xml
<CustomField>
    <fullName>Question_ID__c</fullName>
    <label>Question ID</label>
    <referenceTo>Question_Bank__c</referenceTo>
    <relationshipLabel>Registration Questions</relationshipLabel>
    <relationshipName>Registration_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <description>test of question populated when the question is created from the question bank on creation of the registration</description>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Question__c/fields/Reg_Answer__c.field-meta.xml
<CustomField>
    <fullName>Reg_Answer__c</fullName>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Question__c/fields/Registration_ID__c.field-meta.xml
<CustomField>
    <fullName>Registration_ID__c</fullName>
    <label>Registration ID</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Questions</relationshipLabel>
    <relationshipName>Registration_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Question__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>order in which questions are presented to the user. this value comes from the question rule that resulted in creating this question</description>
    <label>Sort Order</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration_Question__c/recordTypes/YesNo.recordType-meta.xml
<RecordType>
    <fullName>YesNo</fullName>
    <active>true</active>
    <label>YesNo</label>
</RecordType>

force-app/main/default/classes/RegistrationQuestionAllTest.cls
@istest
public class RegistrationQuestionAllTest {

    public static testMethod void testRegistrationQuestionAll1(){
        Account acc = new Account(
            Name = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert acc;
        
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Test';
        con.Email = 'testLNRDEV@testdir.com';
        insert con;
        
        Question_Bank__c qb = new Question_Bank__c();
        qb.Answer_Type__c = 'YesNo'; 
        qb.Question_Text__c = 'Is this a test question?';
        insert qb;
        
        Question_Bank__c qb1 = new Question_Bank__c();
        qb1.Answer_Type__c = 'YesNo'; 
        qb1.Question_Text__c = 'Is this a test question?';
        qb1.Follow_up_Criteria__c = 'Yes';
        qb1.Controlling_Question__c = qb.Id;
        insert qb1;
        
        Question_Rule__c qr = new Question_Rule__c();
        qr.Active__c = true;
        qr.Question_ID__c = qb.Id;
        qr.Registration_Type__c = 'Car Wash';
        qr.Sort_Order__c = 1;
        insert qr;
        
        Id devRecordTypeId = Schema.getGlobalDescribe().get('License_Registration__c').getDescribe().getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();

        License_Registration__c lreg = new License_Registration__c();
        lreg.RecordTypeId = devRecordTypeId;
        lreg.Account__c = acc.Id;
        lreg.Applicant__c = con.Id;
        lreg.License_Registration_Number__c = '00023568500';
        insert lreg;
        
        Registration_Question__c rq = [SELECT Id, Reg_Answer__c FROM Registration_Question__c WHERE Question_ID__c =: qb.Id AND Registration_ID__c =:lreg.Id];
        rq.Reg_Answer__c = 'Yes';
        
        test.startTest();
            update rq;
            Registration_Question__c rq1 = [SELECT Id, Reg_Answer__c FROM Registration_Question__c WHERE Question_ID__c =: qb.Id AND Registration_ID__c =:lreg.Id];
            rq1.Reg_Answer__c = '';
            update rq1;
        test.stopTest();
    }
    
    
    public static testMethod void testRegistrationQuestionAll2(){
        Account acc = new Account(
            Name = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert acc;
        
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Test';
        con.Email = 'testLNRDEV@testdir.com';
        insert con;
        
        Question_Bank__c qb = new Question_Bank__c();
        qb.Answer_Type__c = 'YesNo'; 
        qb.Question_Text__c = 'Is this a test question?';
        insert qb;
        
        Question_Bank__c qb1 = new Question_Bank__c();
        qb1.Answer_Type__c = 'YesNo'; 
        qb1.Question_Text__c = 'Is this a test question?';
        qb1.Follow_up_Criteria__c = 'Yes';
        qb1.Controlling_Question__c = qb.Id;
        insert qb1;
        
        Question_Rule__c qr = new Question_Rule__c();
        qr.Active__c = true;
        qr.Question_ID__c = qb.Id;
        qr.Registration_Type__c = 'Car Wash';
        qr.Sort_Order__c = 1;
        insert qr;
        
        Id devRecordTypeId = Schema.getGlobalDescribe().get('License_Registration__c').getDescribe().getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();

        License_Registration__c lreg = new License_Registration__c();
        lreg.RecordTypeId = devRecordTypeId;
        lreg.Account__c = acc.Id;
        lreg.Applicant__c = con.Id;
        lreg.License_Registration_Number__c = '00023568500';
        insert lreg;
        
        Registration_Question__c rq = [SELECT Id, Reg_Answer__c FROM Registration_Question__c WHERE Question_ID__c =: qb.Id AND Registration_ID__c =:lreg.Id];
        rq.Reg_Answer__c = 'Yes';
        
        test.startTest();
            update rq;
            Registration_Question__c rq1 = [SELECT Id, Reg_Answer__c FROM Registration_Question__c WHERE Question_ID__c =: qb.Id AND Registration_ID__c =:lreg.Id];
            rq1.Reg_Answer__c = 'No';
            update rq1;
        test.stopTest();
    }
   
}