force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <inlineHelpText>Please enter name registered with CA Secretary of State.  For Sole Proprietor enter full legal name.</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <label>Middle Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/License.recordType-meta.xml
<RecordType>
    <fullName>License</fullName>
    <active>true</active>
    <description>Public Works lookup back to Registration</description>
    <label>License</label>
</RecordType>

force-app/main/default/objects/Ownership__c/Ownership__c.object-meta.xml
<CustomObject>
    <description>Junction object used to denote what percentage of a business an individual owns.</description>
    <label>Ownership</label>
    <nameField>
        <displayFormat>OWN-{00000000}</displayFormat>
        <label>Ownership Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ownership__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Mapped to Account First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Mapped to Person Account Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <description>Mapped to standard Middle Name on Accounts.</description>
    <label>Middle Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Ownership</relationshipLabel>
    <relationshipName>Ownership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ownership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Template_Mapping__mdt/Registration_Template_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Maps registration record types to their corresponding  form wizard templates</description>
    <label>Registration Template Mapping</label>
    <pluralLabel>Registration Template Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Registration_Template_Mapping__mdt/fields/Record_Type_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Developer_Name__c</fullName>
    <inlineHelpText>Enter the developer name of the record type for the registration you want to map</inlineHelpText>
    <label>Record Type Developer Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Template_Mapping__mdt/fields/Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Template_ID__c</fullName>
    <inlineHelpText>Enter the ID of the form template to map to the corresponding record type</inlineHelpText>
    <label>Template ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FLCClassAdminController.cls
public class FLCClassAdminController { // without sharing if instructor cannot view registration #, otherwise use sharing rules/sets
    
    public License_Registration__c currentRegistration {get;set;}
    public List<License_Registration__c> AllRegistrations {get;set;}
    public Ownership__c owners {get;set;}
    public List<Ownership__c> allOwners {get;set;}
    
    public String errormessage {get; set;}
    public String errortype {get; set;}
    public String errorDisplay {get; set;}
    private User currentUser;
  //  public String currentRecordType {get; set;}
    private List<RecordType> registrationRecordTypes;
    
    public FLCClassAdminController(){
        
        currentRegistration = new License_Registration__c();
        AllRegistrations = new List<License_Registration__c>();
        owners = new Ownership__c();
        allOwners = new List<Ownership__c>();
        
        errortype = '';
        errorDisplay = 'none'; 
        errormessage = '';
        
        currentUser = [SELECT Id, ContactId, Contact.AccountId FROM User WHERE Id =: UserInfo.getUserId()];
        
         Map<String,String> devNames = new Map<String,String>();
        for(Registration_Template_Mapping__mdt mdt : [select id,DeveloperName,Record_Type_Developer_Name__c,Template_ID__c from Registration_Template_Mapping__mdt]){
            devNames.put(mdt.Record_Type_Developer_Name__c, mdt.Template_ID__c);
        }       
        registrationRecordTypes = new List<RecordType>();
        for(RecordType rt : [SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType='License_Registration__c' AND DeveloperName IN :devNames.keySet() AND IsActive = true ORDER BY Name ASC]){
            registrationRecordTypes.add(rt);
        }        
    }
    
    
    
    public void SearchRegistration() {
    
        System.debug('License entered '+currentRegistration.License_Registration_Number__c);
        
        String query = 'SELECT Id ' 
                 +', Registration__r.Legal_Entity_Name__c'
                 +', Registration__r.License_Registration_Number__c'
                 +', Registration__r.Effective_Date__c'
                 +', Registration__r.Expiration_Date__c'
            	 +', Registration__r.Status__c'
            	+', Registration__r.CreatedDate'
           		 +', First_Name__c, Middle_Name__c'
                 +', Last_Name__c'
             +' FROM Ownership__c'
             +' WHERE  Registration__r.Status__c IN (\'Approved\', \'Incomplete\', \'Pending Payment\', \'Pending / Defect\', \'Transmitted\', \'Submitted\', \'Resubmitted\') AND Registration__r.RecordType.Name = \'Farm Labor Contractor\'';
        
        // Add additional search criteria here
        if (currentRegistration.License_Registration_Number__c != NULL) {query += ' AND Registration__r.License_Registration_Number__c LIKE \''+ currentRegistration.License_Registration_Number__c+'\'';}
        if (currentRegistration.Legal_Entity_Name__c != NULL) {query += ' AND Registration__r.Legal_Entity_Name__c LIKE \''+ currentRegistration.Legal_Entity_Name__c +'%\'';}
        if (owners.First_Name__c != NULL) {query += ' AND First_Name__c LIKE \''+ owners.First_Name__c + '%\'';}
        if (owners.Middle_Name__c != NULL) {query += ' AND Middle_Name__c LIKE \''+ owners.Middle_Name__c + '%\'';} 
        if (owners.Last_Name__c != NULL) {query += ' AND Last_Name__c LIKE \''+ owners.Last_Name__c+'%\'';}


        
        
            
            System.debug('Query=======>'+query);
            if( !Test.isRunningTest()){
                allOwners = Database.query(query);
            }

            System.debug('ALL Owners: '+ AllOwners);
   
            if(AllOwners.size() < 1) {
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.WARNING,'No results found.Please create a new Application.');
                ApexPages.addMessage(msg);  
            }  
        }
    

 public PageReference CancelBack() {
currentRegistration.License_Registration_Number__c = NULL;
        return null;
    } 
    
    // clears all the fields on Search page
    public void ClearFields() {
        currentRegistration.License_Registration_Number__c = NULL;
        currentRegistration.Legal_Entity_Name__c = NULL;
        owners.First_Name__c = NULL;
        owners.Middle_Name__c = NULL;
        owners.Last_Name__c = NULL;
        
    } 
    
    
}