force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/accAlreadyCreated__c.field-meta.xml
<CustomField>
    <fullName>accAlreadyCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>accAlreadyCreated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/Public_Works.recordType-meta.xml
<RecordType>
    <fullName>Public_Works</fullName>
    <active>true</active>
    <label>Public Works</label>
</RecordType>

force-app/main/default/objects/Public_Works_Account_Scheduler__c/Public_Works_Account_Scheduler__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Public Works Account Scheduler</label>
</CustomObject>

force-app/main/default/objects/Public_Works_Account_Scheduler__c/fields/BatchId__c.field-meta.xml
<CustomField>
    <fullName>BatchId__c</fullName>
    <label>BatchId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createAccountForPublicWorksBatchSchedule.cls
public class createAccountForPublicWorksBatchSchedule implements ScheduledDispatcher.IScheduleDispatched {
    public void execute(SchedulableContext ctx) {
        Public_Works_Account_Scheduler__c scheduler;

        if ([SELECT COUNT()
             FROM License_Registration__c
             WHERE RecordType.DeveloperName = 'Public_Works'
             AND accAlreadyCreated__c = FALSE
             AND Status__c IN ('Pending Payment', 'Active')
             LIMIT 1] == 1) {

            scheduler = Public_Works_Account_Scheduler__c.getInstance('SCHEDULER');

            if (scheduler == null) {
                scheduler = new Public_Works_Account_Scheduler__c(Name = 'SCHEDULER');
                insert scheduler;
            }

            if (scheduler.BatchId__c == null || (scheduler.BatchId__c != null && [
                    SELECT count()
                    FROM AsyncApexJob
                    WHERE (Status = 'Queued' OR Status = 'Processing' OR Status = 'Preparing')
                    AND Id = :scheduler.BatchId__c] == 0)) {

                if (([SELECT count() FROM AsyncApexJob WHERE Status = 'Queued' OR Status = 'Processing' OR Status = 'Preparing'] < 5)) {
                    scheduler.BatchId__c = Database.executeBatch(new createAccountForPublicWorksBatch(), 1);
                    update scheduler;
                }
            }
        }
    }
}