force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rejection_Defect__c/Rejection_Defect__c.object-meta.xml
<CustomObject>
    <description>Junction object between Rejections and Defects.</description>
    <label>Rejection Defect</label>
    <nameField>
        <displayFormat>RJD-{0000000}</displayFormat>
        <label>Rejection Defect Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rejection Defects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rejection_Defect__c/fields/Applies__c.field-meta.xml
<CustomField>
    <fullName>Applies__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Applies?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <label>Item Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/fields/Location_of_Defect__c.field-meta.xml
<CustomField>
    <fullName>Location_of_Defect__c</fullName>
    <formula>TEXT( Defect__r.Section__c )+
IF(NOT(ISBLANK(TEXT(Defect__r.Sub_Section__c))),"-", "" )+
TEXT(Defect__r.Sub_Section__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location of Defect</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Rejection Defects</relationshipLabel>
    <relationshipName>Rejection_Defects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/fields/Resolved__c.field-meta.xml
<CustomField>
    <fullName>Resolved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Values from this field roll up to Registration via DLRS</description>
    <inlineHelpText>Has this defect been resolved?</inlineHelpText>
    <label>Resolved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rejection_Defect__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegistrationDefectErrorMsgsController.cls
public class RegistrationDefectErrorMsgsController {

    public List<Rejection_Defect__c>  rejDefects { get; set; }
    @TestVisible
    private static String registrationId;

public RegistrationDefectErrorMsgsController (){

    registrationId = ApexPages.CurrentPage().getParameters().get('id');
    getDefects();

    }
 
    public List<Rejection_Defect__c> getDefects(){
        
        rejdefects = new List<Rejection_Defect__c>();
        
        if(String.isBlank(registrationId))
        {
            return rejDefects ;
        }
        
        rejdefects = [
                    SELECT id
                        , Name
                        , Item_Name__c
                        , Section__c 
            			, Location_of_Defect__c
                        , Applies__c
                        , Resolved__c
                        , Registration__r.id
                    FROM Rejection_Defect__c
                    WHERE Registration__r.id =: registrationId
                    AND Applies__c = TRUE
                    AND Resolved__c = FALSE
                ];
        System.Debug('rejDefects:' + rejDefects);

        return rejDefects ;
    }

}