force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in a conga workflow that sends a license to the applicant.</description>
    <label>Approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Last_Verification_Business__c.field-meta.xml
<CustomField>
    <fullName>Last_Verification_Business__c</fullName>
    <label>Last Verification Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Last_Verification_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Verification_Date_Time__c</fullName>
    <label>Last Verification Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Last_Verification_Email__c.field-meta.xml
<CustomField>
    <fullName>Last_Verification_Email__c</fullName>
    <label>Last Verification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Last_Verification_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Verification_Number__c</fullName>
    <label>Last Verification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Send_FLC_Verification_Boolean__c.field-meta.xml
<CustomField>
    <fullName>Send_FLC_Verification_Boolean__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send FLC Verification Boolean</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/Farm_Labor_Contractor.recordType-meta.xml
<RecordType>
    <fullName>Farm_Labor_Contractor</fullName>
    <active>true</active>
    <label>Farm Labor Contractor</label>
</RecordType>

force-app/main/default/objects/Registration_Verification__c/Registration_Verification__c.object-meta.xml
<CustomObject>
    <label>Registration Verification</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Registration Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Verifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Verification__c/fields/Business_Entity__c.field-meta.xml
<CustomField>
    <fullName>Business_Entity__c</fullName>
    <label>Business Entity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Verification__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Verifications</relationshipLabel>
    <relationshipName>Registration_Verifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Verification__c/fields/Requested_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date_Time__c</fullName>
    <label>Requested Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Registration_Verification__c/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/RegistrationVerificationController.cls
public without sharing class RegistrationVerificationController {
    
    public Id regId {get;set;}
    public String businessName{get;set;}
    public String emailAddress{get;set;}
    public static RegistrationVerificationController classInstance = null;
    
    private static Boolean stopEWPRecursion {get; set;}
    
    public RegistrationVerificationController() {
        regId = apexpages.currentpage().getparameters().get('id');
        //emailAddress = apexpages.currentpage().getparameters().get('emailAddr');
        
        stopEWPRecursion = false;
    }
    
    public static RegistrationVerificationController getInstance(){
        if (null == classInstance) {
            classInstance = new RegistrationVerificationController ();
        }
        return classInstance;
    }
    
    public void sendLicenseRegistrationPermitPDF() {
        System.debug('************* start sendLicenseRegistrationPermitPDF');
        
        Registration_Verification__c vr = new Registration_Verification__c();
        vr.Registration__c = regid;
        vr.Business_Entity__c = businessName;
        vr.Requestor_Email__c = emailAddress;
        vr.Requested_Date_Time__c = DateTime.now();
        insert vr;
        
        Registration_Verification__c newVr = [
            SELECT Id, Name, Requested_Date_Time__c
            FROM Registration_Verification__c
            WHERE Id =: vr.Id
        ];
        
        License_Registration__c lrSendPDF = [
            SELECT Id, Approved__c, Record_Type_Name__c
            FROM License_Registration__c
            WHERE Id =: regId
        ];
        
        lrSendPDF.Last_Verification_Number__c = newVr.Name;
        lrSendPDF.Last_Verification_Business__c = businessName;
        lrSendPDF.Last_Verification_Email__c = emailAddress;
        lrSendPDF.Last_Verification_Date_Time__c = newVr.Requested_Date_Time__c;
        
        update lrSendPDF;
        
        if (lrSendPDF.Record_Type_Name__c == 'Farm_Labor_Contractor') 
        {
            lrSendPDF.Send_FLC_Verification_Boolean__c = true;
        }
        
        update lrSendPDF;
    }
}