force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/No_of_Years__c.field-meta.xml
<CustomField>
    <fullName>No_of_Years__c</fullName>
    <formula>IF(ISPICKVAL(Registration_Period_July1__c,""),
Case( Registration_Period__c,
"1",1,
"2",2,
"3",3,
0),
CASE(Registration_Period_July1__c,
"1",1,
"2",2,
0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No of Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Renewal__c.field-meta.xml
<CustomField>
    <fullName>Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if this is a renewal applicaiton.</description>
    <inlineHelpText>Check if this is a renewal application.</inlineHelpText>
    <label>Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/registerationSuccessController.cls
public class registerationSuccessController {
    
    public Id regId {get;set;}
    public Boolean showMoreDetails {get;set;}
    public License_Registration__c newReg{get;set;}
    
    public registerationSuccessController(){
        
        showMoreDetails = false;
        
        try{
        regId = apexpages.currentpage().getparameters().get('id');    
        newReg = [SELECT id,Effective_Date__c,No_of_Years__c,renewal__c,Expiration_Date__c FROM License_Registration__c where id= :regId];
        if(!newReg.renewal__c){
            showMoreDetails = true;
        }            
        }catch(Exception e){
          showMoreDetails = false;  
        }

    }
    
    public pagereference redirectToHomePage(){
        pagereference pr = new pagereference('/registrations/apex/CommunityRegistration');
        return pr;
    }

}