force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Number_of_Registration_Exams__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Registration_Exams__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count of exams for Registrations Owners and Managers</description>
    <label>Number of Registration Exams</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registrations_Exam__c/Registrations_Exam__c.object-meta.xml
<CustomObject>
    <description>Used record FLC and Garment exams</description>
    <label>Registrations Exam</label>
    <nameField>
        <displayFormat>EX-{000000}</displayFormat>
        <label>Exam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registrations_Exam__c/fields/Exam_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Exam_Disposition__c</fullName>
    <inlineHelpText>Select from Pick list</inlineHelpText>
    <label>Exam Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Not Taken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registrations_Exam__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registrations_Exam__c/fields/Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Registration_Id__c</fullName>
    <formula>IF(ISBLANK(Ownership__c), Registration_Account__r.Registration__r.Id , Ownership__r.Registration__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegistrationsExamHandler.cls
public class RegistrationsExamHandler {
    private static registrationsExamHandler classInstance = null;
    public Boolean stopRecursion {get; set;}
    
    private RegistrationsExamHandler() {
        stopRecursion = FALSE;
    }
    
    public static RegistrationsExamHandler getInstance(){
        if (null == classInstance) {
            classInstance = new registrationsExamHandler();
        }
        return classInstance;
    }
    
    public void onBeforeInsert(List<Registrations_Exam__c> newList){ 
    }
    
    public void onAfterInsert(List<Registrations_Exam__c> newList , Map<id, Registrations_Exam__c> newMap){  
    }
    
    public void onBeforeUpdate(List<Registrations_Exam__c> newList, Map<id, Registrations_Exam__c> newMap, Map<id, Registrations_Exam__c> oldMap){
    }
    
    public void onAfterUpdate(List<Registrations_Exam__c> newList, Map<id, Registrations_Exam__c> newMap, Map<id, Registrations_Exam__c> oldMap){
        if(stopRecursion == null || !stopRecursion)
        {
            stopRecursion = TRUE;
            updateNumberOfExams(newList, 'update');
            stopRecursion = FALSE;
        }
    }
    
    public void onBeforeDelete(List<Registrations_Exam__c> oldList, Map<id, Registrations_Exam__c> oldMap){
        if(stopRecursion == null || !stopRecursion)
        {
            stopRecursion = TRUE;
            updateNumberOfExams(oldList, 'delete');
            stopRecursion = FALSE;
        }
    }
    
    public void onAfterDelete(list<Registrations_Exam__c> oldList, Map<id, Registrations_Exam__c> oldMap){

    }
    
    private void updateNumberOfExams(List<Registrations_Exam__c> oldREList, String action){
        List<License_Registration__c> lReg = [SELECT Id, Number_of_Registration_Exams__c FROM License_Registration__c WHERE Id =: oldREList[0].Registration_Id__c];
        //System.debug('lReg:' + lReg[0]);
        System.debug('lReg:' + lReg.size());
        
        List<Registrations_Exam__c> numberOfExams = [SELECT Id, Registration_Id__c FROM Registrations_Exam__c WHERE Registration_Id__c =: oldREList[0].Registration_Id__c AND Inactive__c = FALSE AND Exam_Disposition__c  != 'Not Taken'];
        //System.debug('numberOfExams:' + numberOfExams[0]);
        System.debug('numberOfExams:' + numberOfExams.size());
        
        if(lReg.size() > 0){ 
            if(numberOfExams.size() > 0){
                if(action == 'delete'){
                    lReg[0].Number_of_Registration_Exams__c = numberOfExams.size() - 1;
                }
                else if(action == 'update'){
                    lReg[0].Number_of_Registration_Exams__c = numberOfExams.size();
                }
            } 
            else if(numberOfExams.size() < 1){
                lReg[0].Number_of_Registration_Exams__c = 0;
            }
        }
        update lReg;
    }
}