force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Initial_Defect_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Defect_Date__c</fullName>
    <description>The first date that application was placed in "Defect" status.</description>
    <inlineHelpText>The first date that application was placed in "Defect" status.</inlineHelpText>
    <label>Initial Defect Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Initial_Reject_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Reject_Date__c</fullName>
    <description>Used in Garment Registration for subsequent process</description>
    <inlineHelpText>Initial Reject Date</inlineHelpText>
    <label>Initial Reject Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateSubReg70dayRejectDtIterable.cls
public without sharing class UpdateSubReg70dayRejectDtIterable implements Iterable<SObject>{
    
        public Iterator<SObject> iterator() {
        List<License_Registration__c> sobjects = new List<License_Registration__c>();
        List<License_Registration__c> records2 = new List<License_Registration__c>();
        List<License_Registration__c> registrationList = new List<License_Registration__c>();
        List<License_Registration__c> successList = new List<License_Registration__c>();
                       
        //* Update Initial Rejection date at 71 day subsequent start - allowing 10 day grace period from the warning email for 61st day.
        Date myDate = Date.today().addDays(-71); 
        //Date newDate = myDate.addDays(-71);
            
         String query2 = 'SELECT id, Applicant__r.Id, Applicant__r.Email,Initial_Reject_Date__c,Initial_Defect_Date__c '
            + ' FROM License_Registration__c'
            + ' WHERE Status__c = \'Pending / Defect\''
            + ' AND Applicant__r.id != NULL'
            + ' AND Account__r.id != NULL'
            + ' AND Initial_Defect_Date__c =: myDate'
            + ' AND Initial_Reject_Date__c = NULL'
            + ' AND RecordType.Name = \'Garment Manufacturers and Contractors\'';
        
        records2 = Database.query(query2);
        if (!records2.isEmpty()) {
            for(License_Registration__c eachRecord : records2){
                               
                eachRecord.Initial_Reject_Date__c = System.Today();
                registrationList.add(eachRecord);
                //if(eachRecord.Initial_Reject_Date__c == NULL){    // Intial Reject date
                                
                }
                
            }
                                        
            if(!registrationList.isEmpty()){
                Database.SaveResult[] updateResults = Database.update(registrationList,false);
                
               for(Integer i=0;i<updateResults.size();i++){
                  if (updateResults.get(i).isSuccess()){
                         successList.add(registrationList.get(i));

                  } else{ 
                      
                      System.debug('Failure records:' + registrationList.get(i));
                  }
                  
              } // for loop 
            }// If !registrationList.isEmpty()
    
    //sobjects.addAll(records3);
    sobjects.addAll(successList); 
    //sobjects.addAll(emailWarningList); 
    //sobjects.addAll(closedList);     
    return sobjects.iterator();

}
}