force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Approval_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date_Time__c</fullName>
    <description>Store Approval Date Time for identifying auto-renewal. This field is to be updated by wfr "REG: Capture Approval DateTime"</description>
    <label>Approval Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in a conga workflow that sends a license to the applicant.</description>
    <label>Approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Assigned_Deputy__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Deputy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Deputy that is going to process this registration.</inlineHelpText>
    <label>Assigned Deputy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DIR_Employee__c.Position__c</field>
            <operation>equals</operation>
            <value>Registration Services</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DIR_Employee__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Enter_Your_Name__c.field-meta.xml
<CustomField>
    <fullName>Enter_Your_Name__c</fullName>
    <label>Enter Your Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Enter_Your_Name_Labor_Code__c.field-meta.xml
<CustomField>
    <fullName>Enter_Your_Name_Labor_Code__c</fullName>
    <inlineHelpText>Enter the full name of the owner,  or authorized corporate officer or partner.</inlineHelpText>
    <label>Enter Your Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Expiration Date of the License/Registration</description>
    <inlineHelpText>Expiration Date of the License/Registration</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/I_Acknowledge_Labor_Code_Compliance__c.field-meta.xml
<CustomField>
    <fullName>I_Acknowledge_Labor_Code_Compliance__c</fullName>
    <label>I Acknowledge Labor Code Compliance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Bond</fullName>
                <isActive>false</isActive>
                <label>Bond</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/I_Agree__c.field-meta.xml
<CustomField>
    <fullName>I_Agree__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Must be checked to submit form.</description>
    <inlineHelpText>Check here to confirm acknowledgement and agreement with the disclaimer above.</inlineHelpText>
    <label>I Agree</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/I_Agree_YesNo__c.field-meta.xml
<CustomField>
    <fullName>I_Agree_YesNo__c</fullName>
    <label>I Agree</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Imported_From__c.field-meta.xml
<CustomField>
    <fullName>Imported_From__c</fullName>
    <description>Indicates that data came from FM</description>
    <label>Imported From</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FM-TIPP</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Internal_Notes__c.field-meta.xml
<CustomField>
    <fullName>Internal_Notes__c</fullName>
    <label>Internal Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Ready_to_Resubmit__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Resubmit__c</fullName>
    <inlineHelpText>Are you ready to submit your changes?</inlineHelpText>
    <label>Ready to Resubmit?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Ready_to_Submit__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Submit__c</fullName>
    <label>Ready to Complete Payment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Registration_Duration__c.field-meta.xml
<CustomField>
    <fullName>Registration_Duration__c</fullName>
    <label>Registration Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 Days - Temporary Permit</fullName>
            </value>
            <value>
                <fullName>6 Months - Permit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Renewal__c.field-meta.xml
<CustomField>
    <fullName>Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if this is a renewal applicaiton.</description>
    <inlineHelpText>Check if this is a renewal application.</inlineHelpText>
    <label>Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
                <default>true</default>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Fee Calculation Ready</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Temporary Approved</fullName>
            </value>
            <value>
                <fullName>Pending / Defect</fullName>
            </value>
            <value>
                <fullName>Referred for Investigation</fullName>
            </value>
            <value>
                <fullName>Referred to Legal</fullName>
            </value>
            <value>
                <fullName>In Violation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Denied</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Revoked</fullName>
            </value>
            <value>
                <fullName>Closed_Suspended</fullName>
                <label>Closed - Suspended</label>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed - Renewed</fullName>
                <label>Renewed</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Status_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Payment__c</fullName>
    <description>Sets the payment status for display on community page based on the amount due and the balance due.</description>
    <formula>IF(
 Amount_Due__c &lt;= 0, '',
 IF( Balance__c &gt; 0, "Not Paid", "Paid / No Balance Due") )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status of Payment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Submission_Type__c</fullName>
    <label>Submission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
                <default>true</default>
                <label>Online</label>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/VIP_Date_Time_Submitted__c.field-meta.xml
<CustomField>
    <fullName>VIP_Date_Time_Submitted__c</fullName>
    <label>Date/Time Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/Entertainment_Work.recordType-meta.xml
<RecordType>
    <fullName>Entertainment_Work</fullName>
    <active>true</active>
    <description>Registration for Entertainment Work Permit</description>
    <label>Entertainment Work</label>
</RecordType>

force-app/main/default/objects/Registration_Account__c/Registration_Account__c.object-meta.xml
<CustomObject>
    <description>Staging object used to collect Company/Account information on Registration forms.</description>
    <label>Registration Account</label>
    <nameField>
        <displayFormat>RA-{000000000}</displayFormat>
        <label>Registration Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Account__c/fields/Imported_From__c.field-meta.xml
<CustomField>
    <fullName>Imported_From__c</fullName>
    <label>Imported From</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Legacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Submission_Type__c</fullName>
    <formula>TEXT(Registration__r.Submission_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Submission Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LRHandlerRegistrations.cls
public class LRHandlerRegistrations {
    public static LRHandlerRegistrations classInstance = null;
    private static Boolean stopEWPRecursion {get; set;}
    
    public LRHandlerRegistrations () {
        stopEWPRecursion = false;
    }
    
    
    public static LRHandlerRegistrations getInstance(){
        if (null == classInstance) {
            classInstance = new LRHandlerRegistrations ();
        }
        return classInstance;
    }
    
    public void CreateRegistrations(list<License_Registration__c> newList)
    {
        if(stopEWPRecursion == null || !stopEWPRecursion){

            stopEWPRecursion = true;
            
            DescribeSObjectResult describeResult = License_Registration__c.sObjectType.getDescribe();
            List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
            sObject newLicenseRegObj = NULL;
            
            String recordId = newList[0].Id; 
            String query = '';
            
            describeResult = License_Registration__c.sObjectType.getDescribe();
            fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
            
            query =
                ' SELECT ' +
                String.join( fieldNames, ',' ) +
                ' FROM ' +
                describeResult.getName() +
                ' WHERE ' +
                ' Id = :recordId ' +
                ' '
                ;               
            List<License_Registration__c> toCloneLicRegObj = Database.query( query );
            
            License_Registration__c  lr = toCloneLicRegObj[0];
            
            if(isDuplicateRegistration(lr)){
                //System.debug('************* Duplicates found: ' +  lr.id);
                stopEWPRecursion = false;
                return;
            }

            //for(License_Registration__c  lr: toCloneLicRegObj){
            //System.debug('*************lr.Record_Type_Name__c: ' +  lr.Record_Type_Name__c);
            //System.debug('*************lr.Status_of_Payment__c: ' + lr.Status_of_Payment__c);
            //System.debug('*************lr.Status__c: ' + lr.Status__c);
            //System.debug('*************lr.Registration_Duration__c: ' + lr.Registration_Duration__c);
            //System.debug('*************lr.Submission_Type__c: ' + lr.Submission_Type__c);
            
            if( lr.Record_Type_Name__c == 'Entertainment_Work'
               && lr.Registration_Duration__c  == '10 Days - Temporary Permit'
               && lr.Submission_Type__c == 'Online')
            {
                newLicenseRegObj = lr.clone(false, false, false, false);
                //sObject newLicenseRegObj = new License_Registration__c();
                
                newLicenseRegObj.put('OwnerId', lr.OwnerId);
                //newLicenseRegObj.put('License_Registration_Number__c', oldMap.get(lr.Id).License_Registration_Number__c);
                //newLicenseRegObj.put('Applicant__c', lr.Applicant__c);
                //newLicenseRegObj.put('OwnerId', lr.OwnerId);
                //	I_Agree__c
                //newLicenseRegObj.put('License_Registration_Number__c', lr.License_Registration_Number__c);
                newLicenseRegObj.put('Enter_Your_Name__c', NULL);
                newLicenseRegObj.put('I_Agree_YesNo__c', NULL);
                newLicenseRegObj.put('Effective_Date__c', Date.today().addDays(11));
                newLicenseRegObj.put('Expiration_Date__c', Date.today().addMonths(6));
                newLicenseRegObj.put('Renewal__c', False);
                newLicenseRegObj.put('Internal_Notes__c', NULL);
                newLicenseRegObj.put('Ready_To_Submit__c', NULL);
                newLicenseRegObj.put('Ready_to_resubmit__c', NULL);
                newLicenseRegObj.put('Assigned_Deputy__c', NULL);
                newLicenseRegObj.Put('Imported_From__c', NULL);
                newLicenseRegObj.put('Submission_Type__c', 'Online');
                
                newLicenseRegObj.Put('Approval_Date_Time__c', NULL);
                newLicenseRegObj.Put('Approved__c', false);
                //newLicenseRegObj.put('Status_of_Payment__c', NULL );
                newLicenseRegObj.put('Status__c', 'Incomplete');
                newLicenseRegObj.put('Service_Type__c', 'New');
                newLicenseRegObj.put('Registration_Duration__c', '6 Months - Permit');
                newLicenseRegObj.Put('I_Acknowledge_Labor_Code_Compliance__c', NULL);
                newLicenseRegObj.Put('Enter_Your_Name_Labor_Code__c', NULL);
                newLicenseRegObj.Put('VIP_Date_Time_Submitted__c', NULL);
                
                newLicenseRegObj.Put('Payment_Date_Time__c', NULL);
                newLicenseRegObj.Put('Payment_Method__c', NULL);
                newLicenseRegObj.Put('Payment_Status__c', NULL);
                newLicenseRegObj.Put('Ready_For_Payment_Email_Sent__c', FALSE);
                newLicenseRegObj.Put('Amount_Paid_Online__c', NULL);
                newLicenseRegObj.Put('Amount_Paid_Manually__c', NULL);
                newLicenseRegObj.Put('Amount_Due__c', NULL);
                
                newLicenseRegObj.Put('Ready_to_Submit__c', NULL);
                //newLicenseRegObj.Put('Status_of_Payment__c', NULL);
                newLicenseRegObj.Put('Submit_Payment__c', NULL);
                
                If (lr.VIP_Template_Status__c != null)
                    newLicenseRegObj.put('VIP_Template_Status__c', lr.VIP_Template_Status__c.Replace('Completed', 'Incomplete'));
                
                System.debug('##### Ready to insert NewLicenseRegObj: ' + newLicenseRegObj);
                insert newLicenseRegObj;
                
                newLicenseRegObj.put('License_Registration_Number__c', lr.License_Registration_Number__c);
                
                update newLicenseRegObj;
                
                describeResult = Registration_Account__c.sObjectType.getDescribe();
                
                fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
                
                query =
                    ' SELECT ' +
                    String.join( fieldNames, ',' ) +
                    ' FROM ' +
                    describeResult.getName() +
                    ' WHERE ' +
                    ' Registration__c = :recordId ' +
                    ' '
                    ;               
                List<Registration_Account__c> toRegistrationAccountsList = Database.query( query ); 
                
                List<Registration_Account__c> newRegistrationAccountsList = new List<Registration_Account__c>(); 
                for(Registration_Account__c toRegistrationAccountsObj: toRegistrationAccountsList){
                    Registration_Account__c newRegistrationAccountsObj = toRegistrationAccountsObj.clone(false, false, false, false);
                    newRegistrationAccountsObj.put('Registration__c', newLicenseRegObj.Id);
                    //                        System.debug('****************newRegistrationAccountsObj.Registration__c: ' + newRegistrationAccountsObj.Registration__c);
                    //                        System.debug('****************newRegistrationAccountsObj.Registration__r.Registration_Duration__c: ' + newRegistrationAccountsObj.Registration__r.Registration_Duration__c);
                    
                    newRegistrationAccountsList.add(newRegistrationAccountsObj);
                }
                insert newRegistrationAccountsList;
            }
            //}
            
            //           Map<Id, License_Registration__c> lrMap = new Map<Id, License_Registration__c>([SELECT Id, Account__c, Applicant__r.AccountId, Company_Type__c FROM License_Registration__c WHERE ID IN: newList]);
            stopEWPRecursion = false;
        }
    }
    
    private Boolean isDuplicateRegistration(License_Registration__c lreg){
        List<License_Registration__c> existingLreg = [SELECT id
                                                      , License_Registration_Type__c
                                                      , License_Registration_Number__c
                                                      , Record_Type_Name__c
                                                      , Submission_Type__c
                                                      , Registration_Duration__c
                                                      , Effective_Date__c
                                                      , Expiration_Date__c 
                                                      FROM License_Registration__c 
                                                      WHERE License_Registration_Number__c =: lreg.License_Registration_Number__c
                                                      AND Record_Type_Name__c = 'Entertainment_Work'
                                                      AND Registration_Duration__c = '6 Months - Permit'
                                                      AND Service_Type__c = 'New'
                                                      AND Status__c = 'Incomplete'];
        
        if(!existingLreg.isEmpty()){
            //System.debug('****************duplicate found: ');
            return true;
        }
        //System.debug('****************duplicate not found: ');
        return false;
    }
}