force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Business</relationshipLabel>
    <relationshipName>Licenses_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Number__c</fullName>
    <description>Number that Corresponds to the License/Registration</description>
    <inlineHelpText>Number that Corresponds to the License/Registration</inlineHelpText>
    <label>License/Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/License_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Registration_Type__c</fullName>
    <label>License/Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>Agricultural Employers of Minors</fullName>
            </value>
            <value>
                <fullName>Agricultural Produce Unloaders</fullName>
            </value>
            <value>
                <fullName>BOE/Seller’s Permit</fullName>
            </value>
            <value>
                <fullName>Bureau of Automotive Repair</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Car Wash</fullName>
            </value>
            <value>
                <fullName>Child Performer Services</fullName>
            </value>
            <value>
                <fullName>CSLB</fullName>
            </value>
            <value>
                <fullName>DOL</fullName>
            </value>
            <value>
                <fullName>DSS Facility</fullName>
            </value>
            <value>
                <fullName>Electricians and electrician trainees</fullName>
            </value>
            <value>
                <fullName>FBNS</fullName>
            </value>
            <value>
                <fullName>Farm Labor Contractor</fullName>
            </value>
            <value>
                <fullName>Garment Manufacturers and Contractors</fullName>
            </value>
            <value>
                <fullName>Health Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworker Permit</fullName>
            </value>
            <value>
                <fullName>Industrial Homeworkers</fullName>
            </value>
            <value>
                <fullName>Industrial Homework License</fullName>
            </value>
            <value>
                <fullName>Janitorial</fullName>
            </value>
            <value>
                <fullName>Secretary of State Number</fullName>
            </value>
            <value>
                <fullName>SEIN</fullName>
            </value>
            <value>
                <fullName>Sheltered Workshops (non‐profit)</fullName>
            </value>
            <value>
                <fullName>Special Minimum Wage</fullName>
            </value>
            <value>
                <fullName>Studio Teacher Certification</fullName>
            </value>
            <value>
                <fullName>Talent Agency</fullName>
            </value>
            <value>
                <fullName>Work Permits for Child Performers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>BSIS</fullName>
            </value>
            <value>
                <fullName>Entertainment Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Date__c</fullName>
    <inlineHelpText>Date this Registration was first Submitted. VIP Date/Time Submitted shows most recent submission time.</inlineHelpText>
    <label>Original Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RegistrationResultsControllerTest.cls
@istest
public class RegistrationResultsControllerTest {

    public static testMethod void testRegistrationResults1(){
        Account acc = new Account(
            Name = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert acc;
        
        Contact c = new Contact();
        c.FirstName = 'First';
        c.LastName = 'Last';
        c.Email = 'first.last@gmail.com';
        insert c;
        
        
        Id RecordTypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();
        
        License_Registration__c lReg1 = new License_Registration__c ();
        lReg1.Account__c = acc.Id;
        lReg1.RecordTypeId = RecordTypeId;
        lReg1.License_Registration_Number__c = acc.Id;
        lReg1.License_Registration_Type__c = '3333';
        lReg1.Submitted_Date__c = Date.today() - 3;
        lReg1.Mailing_City__c = 'Denver';
        lReg1.Applicant__c = c.Id;
        insert lReg1;
        
        
        test.startTest();
            RegistrationResultsController RegistrationResults = new RegistrationResultsController();
            
            System.currentPageReference().getParameters().put('registrationNumberStr', '80212');

            System.currentPageReference().getParameters().put('legalEntityStr', '80212');
            System.currentPageReference().getParameters().put('effectiveDate', String.valueOf(Date.today()-10));
            System.currentPageReference().getParameters().put('expirationDate', String.valueOf(Date.today()+10));
            System.currentPageReference().getParameters().put('dbaNameStr', '80212');
            System.currentPageReference().getParameters().put('locationAddressStr', '80212');
            System.currentPageReference().getParameters().put('locationCityStr', '80212');
            System.currentPageReference().getParameters().put('locationStateStr', '80212');
            System.currentPageReference().getParameters().put('locationZipStr', '80212');
            System.currentPageReference().getParameters().put('workersCompTypeStr', '80212');
            System.currentPageReference().getParameters().put('workersCompInsurerStr', '80212');
            System.currentPageReference().getParameters().put('bondIssuerStr', '80212');
            System.currentPageReference().getParameters().put('bondEffectiveStart', String.valueOf(Date.today()-30));
            System.currentPageReference().getParameters().put('bondEffectiveEnd', String.valueOf(Date.today()+30));
        	System.currentPageReference().getParameters().put('serviceType', 'New');
        
           
            String registrationNumberStr = '80212';
            String legalEntityStr = '80212';
            String effectiveDateStart = String.valueOf(Date.today()-30);
            String effectiveDateEnd = String.valueOf(Date.today()+30);
            String expirationDateStart = String.valueOf(Date.today()-30);
            String expirationDateEnd = String.valueOf(Date.today()+30);
            String dbaNameStr = 'aaa';
            String locationAddressStr = 'Denver';
            String locationCityStr = 'Denver';
            String locationStateStr = 'aaaa';
            String locationZipStr = '12343';
            String workersCompTypeStr = 'aaaaa';
            String workersCompInsurerStr = 'aaaaa';
            String bondIssuerStr = 'aaaaa';
            String bondEffectiveStart = String.valueOf(Date.today()-30);
            String bondEffectiveEnd = String.valueOf(Date.today()+30);
        	String selectedRecordType = 'Car Wash';
        	String selectedStatus = 'Approved';
        	String serviceType = 'New';
        
            RegistrationResultsController.getAllRegistrations(registrationNumberStr, serviceType, selectedRecordType, selectedStatus, legalEntityStr, effectiveDateStart, effectiveDateEnd, expirationDateStart, expirationDateEnd,
            dbaNameStr, locationAddressStr, locationCityStr, locationStateStr, locationZipStr, workersCompTypeStr, workersCompInsurerStr,
            bondIssuerStr, bondEffectiveStart, bondEffectiveEnd);
            
            RegistrationResults.BackToSearch();

            
            
        test.stopTest();
    }
    
    public static testMethod void testRegistrationResults2(){
        Account acc = new Account(
            Name = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert acc;
        
        Contact c = new Contact();
        c.FirstName = 'First';
        c.LastName = 'Last';
        c.Email = 'first.last@gmail.com';
        insert c;
        
        
        Id RecordTypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();
        
        License_Registration__c lReg1 = new License_Registration__c ();
        lReg1.Account__c = acc.Id;
        lReg1.RecordTypeId = RecordTypeId;
        lReg1.License_Registration_Number__c = acc.Id;
        lReg1.License_Registration_Type__c = '3333';
        lReg1.Submitted_Date__c = Date.today() - 3;
        lReg1.Mailing_City__c = 'Denver';
        lReg1.Applicant__c = c.Id;
        insert lReg1;
        
        
        test.startTest();
            RegistrationResultsController RegistrationResults = new RegistrationResultsController();
            
            System.currentPageReference().getParameters().put('registrationNumberStr', '80212');

            System.currentPageReference().getParameters().put('legalEntityStr', '80212');
            System.currentPageReference().getParameters().put('effectiveDate', String.valueOf(Date.today()-10));
            //System.currentPageReference().getParameters().put('expirationDate', String.valueOf(Date.today()+10));
            System.currentPageReference().getParameters().put('dbaNameStr', '80212');
            System.currentPageReference().getParameters().put('locationAddressStr', '80212');
            System.currentPageReference().getParameters().put('locationCityStr', '80212');
            System.currentPageReference().getParameters().put('locationStateStr', '80212');
            System.currentPageReference().getParameters().put('locationZipStr', '80212');
            System.currentPageReference().getParameters().put('workersCompTypeStr', '80212');
            System.currentPageReference().getParameters().put('workersCompInsurerStr', '80212');
            System.currentPageReference().getParameters().put('bondIssuerStr', '80212');
            System.currentPageReference().getParameters().put('bondEffectiveStart', String.valueOf(Date.today()-30));
            //System.currentPageReference().getParameters().put('bondEffectiveEnd', String.valueOf(Date.today()+30));
           	System.currentPageReference().getParameters().put('serviceType', 'New');
            String registrationNumberStr = '80212';
            String legalEntityStr = '80212';
            String effectiveDateStart = String.valueOf(Date.today()-30);
            String effectiveDateEnd = null;
            String expirationDateStart = String.valueOf(Date.today()-30);
            String expirationDateEnd = null;
            String dbaNameStr = 'aaa';
            String locationAddressStr = 'Denver';
            String locationCityStr = 'Denver';
            String locationStateStr = 'aaaa';
            String locationZipStr = '12343';
            String workersCompTypeStr = 'aaaaa';
            String workersCompInsurerStr = 'aaaaa';
            String bondIssuerStr = 'aaaaa';
            String bondEffectiveStart = String.valueOf(Date.today()-30);
            String bondEffectiveEnd = null;
        	String selectedRecordType = 'Car Wash';
        	String selectedStatus = 'Approved';
        	String serviceType = 'New';
            RegistrationResultsController.getAllRegistrations(registrationNumberStr, serviceType, selectedRecordType, selectedStatus, legalEntityStr, effectiveDateStart, effectiveDateEnd, expirationDateStart, expirationDateEnd,
            dbaNameStr, locationAddressStr, locationCityStr, locationStateStr, locationZipStr, workersCompTypeStr, workersCompInsurerStr,
            bondIssuerStr, bondEffectiveStart, bondEffectiveEnd);
            
            RegistrationResults.BackToSearch();

            
            
        test.stopTest();
    }
    
    
    public static testMethod void testRegistrationResults3(){
        Account acc = new Account(
            Name = 'test acct 123',
            ShippingStreet = '123 fake st\r\nBldg A\r\nUnit A',
            ShippingCity = 'Denver',
            ShippingState = 'CO',
            ShippingPostalCode = '80212'
        );
        insert acc;
        
        Contact c = new Contact();
        c.FirstName = 'First';
        c.LastName = 'Last';
        c.Email = 'first.last@gmail.com';
        insert c;
        
        
        Id RecordTypeId = Schema.SObjectType.License_Registration__c.getRecordTypeInfosByName().get('Car Wash').getRecordTypeId();
        
        License_Registration__c lReg1 = new License_Registration__c ();
        lReg1.Account__c = acc.Id;
        lReg1.RecordTypeId = RecordTypeId;
        lReg1.License_Registration_Number__c = acc.Id;
        lReg1.License_Registration_Type__c = '3333';
        lReg1.Submitted_Date__c = Date.today() - 3;
        lReg1.Mailing_City__c = 'Denver';
        lReg1.Applicant__c = c.Id;
        insert lReg1;
        
        
        test.startTest();
            RegistrationResultsController RegistrationResults = new RegistrationResultsController();
            
            System.currentPageReference().getParameters().put('registrationNumberStr', '80212');

            System.currentPageReference().getParameters().put('legalEntityStr', '80212');
            //System.currentPageReference().getParameters().put('effectiveDate', String.valueOf(Date.today()-10));
            System.currentPageReference().getParameters().put('expirationDate', String.valueOf(Date.today()+10));
            System.currentPageReference().getParameters().put('dbaNameStr', '80212');
            System.currentPageReference().getParameters().put('locationAddressStr', '80212');
            System.currentPageReference().getParameters().put('locationCityStr', '80212');
            System.currentPageReference().getParameters().put('locationStateStr', '80212');
            System.currentPageReference().getParameters().put('locationZipStr', '80212');
            System.currentPageReference().getParameters().put('workersCompTypeStr', '80212');
            System.currentPageReference().getParameters().put('workersCompInsurerStr', '80212');
            System.currentPageReference().getParameters().put('bondIssuerStr', '80212');
            //System.currentPageReference().getParameters().put('bondEffectiveStart', String.valueOf(Date.today()-30));
            System.currentPageReference().getParameters().put('bondEffectiveEnd', String.valueOf(Date.today()+30));
        	System.currentPageReference().getParameters().put('serviceType', 'New');
            String registrationNumberStr = '80212';
            String legalEntityStr = '80212';
            String effectiveDateStart = null;
            String effectiveDateEnd = String.valueOf(Date.today()+10);
            String expirationDateStart = null;
            String expirationDateEnd = String.valueOf(Date.today()+30);
            String dbaNameStr = 'aaa';
            String locationAddressStr = 'Denver';
            String locationCityStr = 'Denver';
            String locationStateStr = 'aaaa';
            String locationZipStr = '12343';
            String workersCompTypeStr = 'aaaaa';
            String workersCompInsurerStr = 'aaaaa';
            String bondIssuerStr = 'aaaaa';
            String bondEffectiveStart = null;
            String bondEffectiveEnd = String.valueOf(Date.today()+30);
        	String selectedRecordType = 'Car Wash';
        	String selectedStatus = 'Approved';
        	String serviceType = 'New';
            RegistrationResultsController.getAllRegistrations(registrationNumberStr, serviceType, selectedRecordType, selectedStatus, legalEntityStr, effectiveDateStart, effectiveDateEnd, expirationDateStart, expirationDateEnd,
            dbaNameStr, locationAddressStr, locationCityStr, locationStateStr, locationZipStr, workersCompTypeStr, workersCompInsurerStr,
            bondIssuerStr, bondEffectiveStart, bondEffectiveEnd);
            
            RegistrationResults.BackToSearch();

            
            
        test.stopTest();
    }
    
}