force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day Care</fullName>
            </value>
            <value>
                <fullName>Pre-K</fullName>
            </value>
            <value>
                <fullName>Kindergarten</fullName>
            </value>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>2nd</fullName>
            </value>
            <value>
                <fullName>3rd</fullName>
            </value>
            <value>
                <fullName>4th</fullName>
            </value>
            <value>
                <fullName>5th</fullName>
            </value>
            <value>
                <fullName>6th</fullName>
            </value>
            <value>
                <fullName>7th</fullName>
            </value>
            <value>
                <fullName>8th</fullName>
            </value>
            <value>
                <fullName>9th</fullName>
            </value>
            <value>
                <fullName>10th</fullName>
            </value>
            <value>
                <fullName>11th</fullName>
            </value>
            <value>
                <fullName>12th</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Height_ft__c.field-meta.xml
<CustomField>
    <fullName>Height_ft__c</fullName>
    <label>Height (ft.)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Height_in__c.field-meta.xml
<CustomField>
    <fullName>Height_in__c</fullName>
    <label>Height (in.)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <label>Middle Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Natural_Eye_Color__c.field-meta.xml
<CustomField>
    <fullName>Natural_Eye_Color__c</fullName>
    <label>Natural Eye Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Hazel</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>-Select Eye Color-</fullName>
                <isActive>false</isActive>
                <label>-Select Eye Color-</label>
            </value>
            <value>
                <fullName>No eyes</fullName>
                <isActive>false</isActive>
                <label>No eyes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Natural_Hair_Color__c.field-meta.xml
<CustomField>
    <fullName>Natural_Hair_Color__c</fullName>
    <label>Natural Hair Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>-Select Hair Color-</fullName>
                <default>true</default>
                <label>-Select Hair Color-</label>
            </value>
            <value>
                <fullName>Auburn</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Blond</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Chestnut</fullName>
            </value>
            <value>
                <fullName>No Hair</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Strawberry Blond</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Registration_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the registration account that became the account on this registration. Used for matching during renewal</description>
    <label>Registration Account</label>
    <referenceTo>Registration_Account__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations_Key_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Residential_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Residential_Address_Line_1__c</fullName>
    <inlineHelpText>P.O. Box address is not allowed.</inlineHelpText>
    <label>Residential Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Residential_City__c.field-meta.xml
<CustomField>
    <fullName>Residential_City__c</fullName>
    <label>Residential City / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Residential_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Residential_Postal_Code__c</fullName>
    <label>Residential Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <label>Professional Name (Stage Name)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/License.recordType-meta.xml
<RecordType>
    <fullName>License</fullName>
    <active>true</active>
    <description>Public Works lookup back to Registration</description>
    <label>License</label>
</RecordType>

force-app/main/default/objects/Registration_Account__c/Registration_Account__c.object-meta.xml
<CustomObject>
    <description>Staging object used to collect Company/Account information on Registration forms.</description>
    <label>Registration Account</label>
    <nameField>
        <displayFormat>RA-{000000000}</displayFormat>
        <label>Registration Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Account__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Height_in__c.field-meta.xml
<CustomField>
    <fullName>Height_in__c</fullName>
    <label>Height (in.)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Natural_Hair_Color__c.field-meta.xml
<CustomField>
    <fullName>Natural_Hair_Color__c</fullName>
    <label>Natural Hair Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auburn</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Blond</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Chestnut</fullName>
            </value>
            <value>
                <fullName>No Hair</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Strawberry Blond</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>License_Registration__c</referenceTo>
    <relationshipLabel>Registration Accounts</relationshipLabel>
    <relationshipName>Registration_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Residential_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Residential_Address_Line_2__c</fullName>
    <label>Residential Address Line 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Residential_City__c.field-meta.xml
<CustomField>
    <fullName>Residential_City__c</fullName>
    <label>Residential City / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Residential_Phone__c.field-meta.xml
<CustomField>
    <fullName>Residential_Phone__c</fullName>
    <description>Residential Phone</description>
    <inlineHelpText>Phone number must be 10 numbers (no dashes or spaces.)</inlineHelpText>
    <label>Residential Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Residential_State__c.field-meta.xml
<CustomField>
    <fullName>Residential_State__c</fullName>
    <label>Residential State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <label>School Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <label>Professional Name (Stage Name)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/fields/Weight_In_Pounds__c.field-meta.xml
<CustomField>
    <fullName>Weight_In_Pounds__c</fullName>
    <label>Weight In Pounds</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration_Account__c/recordTypes/Individual_Permit.recordType-meta.xml
<RecordType>
    <fullName>Individual_Permit</fullName>
    <active>true</active>
    <label>Individual Permit</label>
</RecordType>

force-app/main/default/objects/Registration_Account__c/recordTypes/Parent_Guardian.recordType-meta.xml
<RecordType>
    <fullName>Parent_Guardian</fullName>
    <active>true</active>
    <label>Parent Guardian</label>
</RecordType>

force-app/main/default/classes/RegistrationEWPPDFController.cls
global class RegistrationEWPPDFController {
    
        private String registrationId { get; set; }
    public List<WrapRegistrationAccounts> permitInfo { get; set; }
    public Boolean checkBox { get; set; }
    
    public RegistrationEWPPDFController() {
        registrationId = ApexPages.CurrentPage().getParameters().get('Id');
        renderingService = ApexPages.CurrentPage().getParameters().get('renderingService');
        renderedFileName = ApexPages.CurrentPage().getParameters().get('renderedFileName');
        
        permitInfo = getPermitInfo(registrationId);
        
    }
    
    // public Registration_Account__c getLicense(Id regId) {
    //license = new Registration_Account__c();
    //license.Id = regId;
    //license.First_Name__c = 'Bao';
    
    //license = getPermitInfo(registrationId);
    //return license;
    // }
    
    public List<WrapRegistrationAccounts> getPermitInfo(Id pRegId){
        
        List<License_Registration__c> regLicense = new List<License_Registration__c>();
        List<WrapRegistrationAccounts> wrapRALists = new List<WrapRegistrationAccounts>();
        
        String query = 'SELECT'
            + ' Id'
            + ' , First_Name__c'
            + ' , Middle_Name__c'
            + ' , Last_Name__c'
            + ' , Stage_Name__c'
            + ' , Residential_Address_Line_1__c'
            + ' , Residential_Address_Line_2__c'
            + ' , Residential_City__c'
            + ' , Residential_State__c'
            + ' , Residential_Postal_Code__c'
            + ' , Residential_Phone__c'
            + ' , School_Name__c'
            + ' , Grade__c'
            + ' , Birth_Date__c'
            + ' , Height_ft__c'
            + ' , Height_in__c'
            + ' , Weight_In_Pounds__c'
            + ' , Natural_Hair_Color__c' 
            + ' , Natural_Eye_Color__c'
            + ' , Gender__c'
            + ' , RecordType.DeveloperName'
            + ' , (Select Id, First_Name__c, Middle_Name__c, Last_Name__c,Residential_Phone__c from Registration_Accounts__r where RecordType.DeveloperName = \'Parent_Guardian\')'
            + ' FROM License_Registration__c'
            + ' WHERE Id  = ' + '\'' + pRegId + '\'';
           // + ' AND RecordType.DeveloperName= \'Individual_Permit\'';
        
        
        query += ' ORDER BY Name DESC';
        System.debug('Query=======>'+query);
//        if(!Test.isRunningTest()){
            regLicense = Database.query(query);
//        }
        
        String minors_First_Name;
        String minors_Middle_Name;
        String minors_Last_Name;
        String minors_Full_Name;
        String minors_Stage_Name;
        String minors_Street;
        String minors_Street2;
        String minors_Address;
        String minors_City;        
        String minors_State;
        String minors_Zip;
        String minors_Home_Phone;
        String minors_School;
        String minors_Grade;
        Date minors_Birth_Date;
        String minors_Height;
        String minors_Weight;
        String minors_Hair_Color;
        String minors_Eye_Color;
        String minors_Gender;
        String parents_Full_Name;
        String parents_Phone;
               
  
        for(License_Registration__c eachLicense : regLicense){
           for(Registration_Account__c eachRA : eachLicense.Registration_Accounts__r){
            //if(eachRA.RecordType.DeveloperName == 'Parent_Guardian'){
                parents_Full_Name = eachRA.First_Name__c == null ? '' : eachRA.First_Name__c + ' ';
                parents_Full_Name += eachRA.Middle_Name__c == null ? '' : eachRA.Middle_Name__c + ' ';
                parents_Full_Name += eachRA.Last_Name__c == null ? '' : eachRA.Last_Name__c;
                parents_Phone = eachRA.Residential_Phone__c;
            //}
            }
                minors_First_Name = eachLicense.First_Name__c == null ? '' : eachLicense.First_Name__c;
                minors_Middle_Name = eachLicense.Middle_Name__c == null ? '' : eachLicense.Middle_Name__c;
                minors_Last_Name = eachLicense.Last_Name__c == null ? '' : eachLicense.Last_Name__c;
                minors_Full_Name = minors_First_Name + ' ' + minors_Middle_Name + ' ' + minors_Last_Name;
                minors_Stage_Name = eachLicense.Stage_Name__c == null ? '' : eachLicense.Stage_Name__c ;
                minors_Street = eachLicense.Residential_Address_Line_1__c == null ? '' : eachLicense.Residential_Address_Line_1__c;
                minors_Street2 = eachLicense.Residential_Address_Line_2__c == null ? '' : eachLicense.Residential_Address_Line_2__c;
                minors_Address = minors_Street + ' ' + minors_Street2;
                minors_City = eachLicense.Residential_City__c == null ? '' : eachLicense.Residential_City__c;     
                minors_State = eachLicense.Residential_State__c == null ? '' : eachLicense.Residential_State__c;
                minors_Zip = eachLicense.Residential_Postal_Code__c == null ? '' : eachLicense.Residential_Postal_Code__c;
                minors_Home_Phone = eachLicense.Residential_Phone__c == null ? '' : eachLicense.Residential_Phone__c;
                minors_School = eachLicense.School_Name__c == null ? '' : eachLicense.School_Name__c;
                minors_Grade = eachLicense.Grade__c == null ? '' : eachLicense.Grade__c;
                minors_Birth_Date = eachLicense.Birth_Date__c;
                minors_Height = eachLicense.Height_ft__c + '\' ' +  eachLicense.Height_in__c +  '\'\'';
                minors_Weight = eachLicense.Weight_In_Pounds__c + ' lbs';
                minors_Hair_Color = eachLicense.Natural_Hair_Color__c == null ? '' : eachLicense.Natural_Hair_Color__c;
                minors_Eye_Color = eachLicense.Natural_Eye_Color__c == null ? '' : eachLicense.Natural_Eye_Color__c;
                minors_Gender = eachLicense.Gender__c == null ? '' : eachLicense.Gender__c;
           
            }
            wrapRALists.add(new WrapRegistrationAccounts(minors_First_Name
                                                         , minors_Middle_Name
                                                         , minors_Last_Name
                                                         , minors_Stage_Name
                                                         , minors_Street
                                                         , minors_Street2 
                                                         , minors_Address
                                                         , minors_City
                                                         , minors_State
                                                         , minors_Zip
                                                         , minors_Home_Phone
                                                         , minors_School
                                                         , minors_Grade
                                                         , minors_Birth_Date
                                                         , minors_Height
                                                         , minors_Weight
                                                         , minors_Hair_Color
                                                         , minors_Eye_Color
                                                         , minors_Gender
                                                         , minors_Full_Name
                                                         , parents_Full_Name
                                                         , parents_Phone));
        
        return wrapRALists;
    }
    
    // Determines what kind of rendering to use for the page request
    public String renderingService { get; private set; }
    // Allow the page to set the PDF file name
    public String renderedFileName {
        get;
        set { renderedFileName = this.sanitizeFileName(value); }
    }
    
    // Rendered content MIME type, used to affect HTTP response
    public String renderedContentType {
        get {
            String renderedContentType = 'text/html'; // the default
            if( ! this.renderingAsHtml() ) {
                // Provides a MIME type for a PDF document
                renderedContentType = 'application/pdf';
                // Add a file name for the PDF file
                if( this.renderedFileName != null) {
                    // This is supposed to set the file name, but it doesn't work
                    renderedContentType += '#' + this.renderedFileName;
                    // This is a work-around to set the file name
                    ApexPages.currentPage().getHeaders().put(
                        'content-disposition', 'attachment; filename=' +
                        this.renderedFileName);
                }
            }
            return renderedContentType;
        }
    }
    
    // Are we rendering to HTML or PDF?
    public Boolean renderingAsHtml() {
        return ( (renderingService == null) ||
                ( ! renderingService.startsWith('PDF')) );
    }
    
    
    // Private helper -- basic, conservative santization
    private String sanitizeFileName(String unsafeName) {
        String allowedCharacters = '0-9a-zA-Z-_.';
        String sanitizedName =
            unsafeName.replaceAll('[^' + allowedCharacters + ']', '');
        // You might also want to check filename length,
        // that the filename ends in '.pdf', etc.
        return(sanitizedName);
    }
    
    global class WrapRegistrationAccounts{
        public String minorsFirstName {get;set;}
        public String minorsMiddleName {get;set;}
        public String minorsLastName {get;set;}
        public String minorsStageName {get;set;}
        public String minorsStreet {get;set;}
        public String minorsStreet2 {get;set;}
        public String minorsAddress {get;set;}
        public String minorsCity {get;set;}
        public String minorsState {get;set;}
        public String minorsZip {get;set;}
        public String minorsHomePhone {get;set;}
        public String minorsSchool {get;set;}
        public String minorsGrade {get;set;}
        public Date minorsBirthDate {get;set;}
        public String minorsHeight {get;set;}
        public String minorsWeight {get;set;}
        public String minorsHairColor {get;set;}
        public String minorsEyeColor {get;set;}
        public String minorsGender {get;set;}
        public String minorsFullName {get;set;}
        public String parentsFullName {get;set;}
        public String parents_Phone {get;set;}

        public WrapRegistrationAccounts(String sMinorsFirstName
                                        , String sMinorsMiddleName
                                        , String sMinorsLastName
                                        , String sMinorsStageName 
                                        , String sMinorsStreet
                                        , String sMinorsStreet2
                                        , String sMinorsAddress
                                        , String sMinorsCity 
                                        , String sMinorsState
                                        , String sMinorsZip 
                                        , String sMinorsHomePhone 
                                        , String sMinorsSchool 
                                        , String sMinorsGrade
                                        , Date sMinorsBirthDate 
                                        , String sMinorsHeight
                                        , String sMinorsWeight 
                                        , String sMinorsHairColor
                                        , String sMinorsEyeColor 
                                        , String sMinorsGender
                                        , String sMinorsFullName 
                                        , String sParentsFullName
                                        , String sParents_Phone)
        {
            minorsFirstName =  sMinorsFirstName == null ? '' : sMinorsFirstName;
            minorsMiddleName = sMinorsMiddleName == null ? '' : sMinorsMiddleName;    
            minorsLastName = sMinorsLastName == null ? '' : sMinorsLastName;    
            minorsStageName = sMinorsStageName == null ? '' : sMinorsStageName;     
            minorsStreet = sMinorsStreet == null ? '' : sMinorsStreet;
            minorsStreet2 = sMinorsStreet2 == null ? '' : sMinorsStreet2;
            minorsAddress = sMinorsAddress == null ? '' : sMinorsAddress;
            minorsCity = 	sMinorsCity == null ? '' : sMinorsCity;
            minorsState = 	sMinorsState == null ? '' : sMinorsState;
            minorsZip = 	sMinorsZip == null ? '' : sMinorsZip;
            minorsHomePhone = sMinorsHomePhone == null ? '' : sMinorsHomePhone;
            minorsSchool = 	sMinorsSchool == null ? '' : sMinorsSchool;
            minorsGrade = 	sMinorsGrade == null ? '' : sMinorsGrade;
            minorsBirthDate = sMinorsBirthDate;
            minorsHeight = 	sMinorsHeight == null ? '' : sMinorsHeight;
            minorsWeight = 	sMinorsWeight == null ? '' : sMinorsWeight;
            minorsHairColor = sMinorsHairColor == null ? '' : sMinorsHairColor;
            minorsEyeColor = sMinorsEyeColor == null ? '' : sMinorsEyeColor;
            minorsGender = 	sMinorsGender == null ? '' : sMinorsGender;
            minorsFullName = sMinorsFullName == null ? '' : sMinorsFullName;
            parentsFullName = sParentsFullName == null ? '' : sParentsFullName;
            parents_Phone = sParents_Phone == null ? '' : sParents_Phone;
        }
    }
}