force-app/main/default/objects/License_Registration__c/License_Registration__c.object-meta.xml
<CustomObject>
    <description>This object takes the information about business registrations. It will be linked via lookup to the Account Object.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>LR-1{000000000}</displayFormat>
        <label>System Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Registration__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The person who submitted the Registration. Email alerts will be sent to this person.</inlineHelpText>
    <label>Community User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses &amp; Registrations as Applicant</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>calculates the balance due with zero being the lowest it can be.</description>
    <formula>MAX(Amount_Due__c -   Amount_Paid_Manually__c -  Amount_Paid_Online__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/License_Registration__c/fields/Ready_to_Submit__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Submit__c</fullName>
    <label>Ready to Complete Payment?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Registration__c/recordTypes/License.recordType-meta.xml
<RecordType>
    <fullName>License</fullName>
    <active>true</active>
    <description>Public Works lookup back to Registration</description>
    <label>License</label>
</RecordType>

force-app/main/default/classes/CommunitiesLandingController.cls
/**
 * An apex page controller that takes the user to the right start page based on credentials or lack thereof
 */
public with sharing class CommunitiesLandingController {
    
    // Code we will invoke on page load.
    public PageReference forwardToStartPage() {
        // Below code added by Kavya Somashekar for req 170024
        
        list<AssignChargentLicense__e> assignLicense = new list<AssignChargentLicense__e>();  
        //user details
        List<User> userList = [select Id,contactid from user where id =:UserInfo.getUserId()];
        //Check if the Community user has 1 or more registrations in Pending Payment status
        system.debug('userList[0].contactid*****'+userList[0].contactid);
        List<License_Registration__c> lastLR = [SELECT Id, Ready_to_Submit__c,Balance__c FROM License_Registration__c 
                                                    WHERE Ready_to_Submit__c = 'Yes' 
                                                    AND Balance__c >0 
                                                    AND Applicant__c =: userList[0].contactid];
        if(!lastLR.isEmpty()){
              System.debug('##### Registration record meets criteria for license to be assigned to the logged in user');
                AssignChargentLicense__e a = new AssignChargentLicense__e();
                a.UserId__c = userList[0].Id;
                assignLicense.add(a);
                list<Database.SaveResult> results = EventBus.publish(assignLicense);
            
                for(Database.SaveResult sr : results){
                    if(sr.isSuccess()){
                        system.debug('##### Successfully published assign license event');
                    }
                    else{
                        for(Database.Error err : sr.getErrors()){
                            System.debug('##### Error returned from publishing assign license event: ' +
                             err.getStatusCode() +
                             ' - ' +
                             err.getMessage());
                        }
                    }
                }
        }
         
        return Network.communitiesLanding();
    }
    
    public CommunitiesLandingController() {}
}