force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>Populated by Process Builder. Used by search.</description>
    <label>Account Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Role__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</description>
    <inlineHelpText>The Entity being described in this Case Role. Links to the Account Object. - Not Reparentable</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Roles</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Judgement__c/Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment</label>
    <nameField>
        <displayFormat>J-{0}</displayFormat>
        <label>Judgment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgement__c/fields/Attorney_Fees_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Fees_Balance_Due__c</fullName>
    <formula>Attorney_Fees__c - Attorney_Fee_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attorney Fees Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Court__c.field-meta.xml
<CustomField>
    <fullName>Court__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Court</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>The value entered must be an Office record of record type 'Courthouse' or 'County Registrar'</errorMessage>
        <filterItems>
            <field>Office__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Courthouse</value>
        </filterItems>
        <filterItems>
            <field>Office__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>County_Registrar</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Judgments (Court)</relationshipLabel>
    <relationshipName>Court</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Court_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Court_Case_Number__c</fullName>
    <inlineHelpText>Add the court case number when the judgment is returned from the court.</inlineHelpText>
    <label>Court Case Number</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Filing_Fees_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Filing_Fees_Balance_Due__c</fullName>
    <formula>Filing_Fee__c - Filing_Fee_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Filing Fees Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Judgment__c.field-meta.xml
<CustomField>
    <fullName>Judgment__c</fullName>
    <label>Judgment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Post_hearing_Interest_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Post_hearing_Interest_Balance_Due__c</fullName>
    <formula>Interest_Due__c - Post_Hearing_Interest_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Post-Hearing Interest Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Post_judgment_Interest_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Post_judgment_Interest_Balance_Due__c</fullName>
    <formula>Post_Judgement_Interest__c - Post_Judgment_Interest_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Post-Judgment Interest Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending/Open</fullName>
            </value>
            <value>
                <fullName>Open/Unpaid</fullName>
            </value>
            <value>
                <fullName>Open - Partial Payment/Satisfaction</fullName>
            </value>
            <value>
                <fullName>Open - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Closed - Satisfied</fullName>
            </value>
            <value>
                <fullName>Closed - Discharged in Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Stayed - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Stayed - Other</fullName>
            </value>
            <value>
                <fullName>Vacated</fullName>
            </value>
            <value>
                <fullName>Closed-Claimant Judgment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Judgement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ODA by Settlement</fullName>
            </value>
            <value>
                <fullName>ODA</fullName>
            </value>
            <value>
                <fullName>JEU</fullName>
            </value>
            <value>
                <fullName>Tax Lien</fullName>
            </value>
            <value>
                <fullName>Court Judgment</fullName>
            </value>
            <value>
                <fullName>RCI Citation Pre-Hearing</fullName>
            </value>
            <value>
                <fullName>RCI Citation Post-Hearing</fullName>
            </value>
            <value>
                <fullName>Default Clerk Judgment</fullName>
            </value>
            <value>
                <fullName>Citation against subsequent offender  (LC 2810.4(b)(1)(B))</fullName>
            </value>
            <value>
                <fullName>ODA against subsequent offender (LC 2810.4(b)(1)(B))</fullName>
            </value>
            <value>
                <fullName>Other Ruling or award against subsequent offender (LC 2810.4(b)(1)(B))</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/Judgment_Payment__c.object-meta.xml
<CustomObject>
    <description>Records payments made against Judgments and their related interests, filing fees, and attorney fees.</description>
    <label>Judgment Payment</label>
    <nameField>
        <displayFormat>JP-{000000}</displayFormat>
        <label>Judgment Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgment_Payment__c/fields/Judgment__c.field-meta.xml
<CustomField>
    <fullName>Judgment__c</fullName>
    <description>Parent judgment of the payment</description>
    <label>Judgment</label>
    <referenceTo>Judgement__c</referenceTo>
    <relationshipLabel>Judgment Payments</relationshipLabel>
    <relationshipName>Judgment_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Payment_Applied_To__c.field-meta.xml
<CustomField>
    <fullName>Payment_Applied_To__c</fullName>
    <description>Defines to which Judgment Payment category the funds should be applied.</description>
    <label>Payment Applied To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Post-Hearing Interest</fullName>
            </value>
            <value>
                <fullName>Post-Judgment Interest</fullName>
            </value>
            <value>
                <fullName>Filing Fees</fullName>
            </value>
            <value>
                <fullName>Attorney Fees</fullName>
            </value>
            <value>
                <fullName>Judgment Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Payment_On_Behalf_Of__c.field-meta.xml
<CustomField>
    <fullName>Payment_On_Behalf_Of__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment On Behalf Of</label>
    <referenceTo>Liable_Party__c</referenceTo>
    <relationshipLabel>Judgment Payments</relationshipLabel>
    <relationshipName>Judgment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Posted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Posted_Amount__c</fullName>
    <description>Formerly Allocated_Amount__c</description>
    <label>Posted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Recommended_Amount__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Amount__c</fullName>
    <description>amount recommended by the deputy when applying a payment</description>
    <label>Recommended Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Judgment_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Deposited-Returned</fullName>
            </value>
            <value>
                <fullName>Deposited-Returned Deduction</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Corrective Entry</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/Liability_Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment Party</label>
    <nameField>
        <displayFormat>LJ-{0}</displayFormat>
        <label>Judgment Party</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Judgement__c/fields/Judgement__c.field-meta.xml
<CustomField>
    <fullName>Judgement__c</fullName>
    <label>Judgment</label>
    <referenceTo>Judgement__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Liable_Party__c.field-meta.xml
<CustomField>
    <fullName>Liable_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liable Party</label>
    <referenceTo>Liable_Party__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/Liable_Party__c.object-meta.xml
<CustomObject>
    <label>Liable Party</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Liable Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liable Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liable_Party__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The liable party is related to a case role on the record. This field holds the value of that case role and is used for generating output document based on the party.</description>
    <inlineHelpText>Case role of the liable party</inlineHelpText>
    <label>Case Role</label>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Liable Parties</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Liable</fullName>
            </value>
            <value>
                <fullName>Not Liable</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CashJudgmentWrapper.cls
public with sharing class CashJudgmentWrapper{

    @AuraEnabled
    public Judgement__c thisJudgment{get;set;}
    @AuraEnabled
    public String judgmentIdUrl{get;set;}
    /* @AuraEnabled
    public String judgmentTooltip{get;set;} */
    @AuraEnabled
    public String judgmentName{get;set;}
    @AuraEnabled
    public String judgmentPartyName{get;set;}
    @AuraEnabled
    public String judgmentPartyUrl{get;set;}
    @AuraEnabled
    public String courtName{get;set;}
    @AuraEnabled
    public String courtUrl{get;set;}
    @AuraEnabled
    public String judgmentStatus{get;set;}

    @AuraEnabled
    public Id relevantPoboLiablePartyId{get;set;} //This is a Liable Party Id, the same as the LP.Payment_On_Behalf_Of__c field.
                                                  //  (cf 'selectedPobo' here and in the main js class, a Case Role Id, which is
                                                  //  used to populate the POBO dropdown).
    /* @AuraEnabled
    public Id relevantCaseRoleId{get;set;} //Case Role Id of the Judgment Parties. May or may not be related to the relevantPoboLiablePartyId. TODO: not used anywhere, seemingly */
 
    @AuraEnabled
    public Decimal postHearingInterestBalanceDue{get;set;}
    @AuraEnabled
    public Decimal postHearingInterestAllocation{get;set;}
    
    @AuraEnabled
    public Decimal postJudgmentInterestBalanceDue{get;set;}
    @AuraEnabled
    public Decimal postJudgmentInterestAllocation{get;set;}

    @AuraEnabled
    public Decimal attorneyFeesBalanceDue{get;set;}
    @AuraEnabled
    public Decimal attorneyFeesAllocation{get;set;}

    @AuraEnabled
    public Decimal filingFeesBalanceDue{get;set;}
    @AuraEnabled
    public Decimal filingFeesAllocation{get;set;}

    @AuraEnabled
    public Judgment_Payment__c matchingPostHearingInterestJP{get;set;}
    @AuraEnabled
    public Judgment_Payment__c matchingPostJudgmentInterestJP{get;set;}
    @AuraEnabled
    public Judgment_Payment__c matchingAttorneyFeeJP{get;set;}
    @AuraEnabled
    public Judgment_Payment__c matchingFilingFeeJP{get;set;}

    public CashJudgmentWrapper(){} //No-arg constructor seems to be required for some reason.

    public CashJudgmentWrapper(Judgement__c judgment){
        System.debug('54 Entered CashJudgmentWrapper apex class constructor');
        thisJudgment = judgment;
        judgmentIdUrl = '/' + judgment.Id;
        /* judgmentTooltip = '🔴𝙏𝙮𝙥𝙚: ' + judgment.Type__c + '      🟠𝘾𝙤𝙪𝙧𝙩 𝘾𝙖𝙨𝙚 #: ' + judgment.Court_Case_Number__c + '      🟡𝘾𝙤𝙪𝙧𝙩: ' + judgment.Court__r.Name; */
        judgmentName = judgment.Name;
        courtName = judgment.Court__r.Name;
        courtUrl = '/' + judgment.Court__c;
        judgmentStatus = judgment.Status__c;

        // relevantPoboLiablePartyId = '';
        // relevantCaseRoleId = '';

        postHearingInterestBalanceDue = judgment.Post_hearing_Interest_Balance_Due__c != null ? judgment.Post_hearing_Interest_Balance_Due__c : 0;
        postHearingInterestAllocation = 0;

        postJudgmentInterestBalanceDue = judgment.Post_judgment_Interest_Balance_Due__c != null ? judgment.Post_judgment_Interest_Balance_Due__c : 0;
        postJudgmentInterestAllocation = 0;

        attorneyFeesBalanceDue = judgment.Attorney_Fees_Balance_Due__c != null ? judgment.Attorney_Fees_Balance_Due__c : 0;
        attorneyFeesAllocation = 0;

        filingFeesBalanceDue = judgment.Filing_Fees_Balance_Due__c != null ? judgment.Filing_Fees_Balance_Due__c : 0;
        filingFeesAllocation = 0;
        
        /*
        matchingPostHearingInterestJP;
        matchingPostJudgmentInterestJP;
        matchingAttorneyFeeJP;
        matchingFilingFeeJP;
        */        

    }

    @AuraEnabled
    public static List<CashJudgmentWrapper> createJudgmentWrapperList(List<Judgement__c> judgmentList, List<Judgment_Payment__c> jpList,
                                                                        List<Liability_Judgement__c> judgmentPartyList, String selectedPobo){
        
        System.debug('98 jpList: ' + judgmentPartyList);
        List<CashJudgmentWrapper> jwList = new List<CashJudgmentWrapper>();
        //TODO: for now (Phase 2, Iteration 3) JP.POBO is set to whichever POBO has been selected on the Case Payment Allocation screen, assuming that that Case Role has only one Liable Party, since we're
        //   displaying all Judgments on that screen regardless of the selected POBO. This may change in a later phase of development.
        List<Liable_Party__c> effectivePoboLiablePartyList = [SELECT Id FROM Liable_Party__c WHERE Case_Role__r.Id = :selectedPobo LIMIT 1];

        /* //Phase 2 iteration 3: no longer filtering Judgments, just bring in all of them on the case regardless of POBO 
        //No POBO selected on page load, so bring in Judgments for ALL POBOs
        if(selectedPobo == 'ALL' || selectedPobo == null){
            for(Judgement__c judgment : judgmentList){
                jwList.add(new CashJudgmentWrapper(judgment));
            }
        }else{
            for(Judgement__c judgment: judgmentList){
                for(Liability_Judgement__c judgmentParty : judgmentPartyList){
                    if(selectedPobo == judgmentParty.Liable_Party__r.Case_Role__r.Id){  //TODO: may need more finesse in filtering--Judgment Parties are currently derived from the Judgments
                                                                                        //  and filtered by Case Role. Maybe derive from the Liable Parties and filter by Judgment, etc, to make
                                                                                        //  the filtering algorithm more like that of the CIWs
                        jwList.add(new CashJudgmentWrapper(judgment));
                    }
                }
            }
        } */

        //TODO: as stated above, for now (Phase 2 Iteration 3) no longer filtering Judgments, so here we just bring in all of them on the case regardless of selectedPobo
        for(Judgement__c judgment : judgmentList){
            jwList.add(new CashJudgmentWrapper(judgment));
        }

        for(CashJudgmentWrapper jw : jwList){
            for(Judgment_Payment__c jp : jpList){
                if(jp.Judgment__c == jw.thisJudgment.Id){
                    if(jp.Payment_Applied_To__c == 'Post-Hearing Interest'){
                        jw.postHearingInterestAllocation = (jp.Posted_Amount__c == 0 || jp.Posted_Amount__c == null) ? jp.Recommended_Amount__c : jp.Posted_Amount__c;
                        jw.matchingPostHearingInterestJP = jp;
                    }else if(jp.Payment_Applied_To__c == 'Post-Judgment Interest'){
                        jw.postJudgmentInterestAllocation = (jp.Posted_Amount__c == 0 || jp.Posted_Amount__c == null) ? jp.Recommended_Amount__c : jp.Posted_Amount__c;
                        jw.matchingPostJudgmentInterestJP = jp;
                    }else if(jp.Payment_Applied_To__c == 'Attorney Fees'){
                        jw.attorneyFeesAllocation = (jp.Posted_Amount__c == 0 || jp.Posted_Amount__c == null) ? jp.Recommended_Amount__c : jp.Posted_Amount__c;
                        jw.matchingAttorneyFeeJP = jp;
                    }else if(jp.Payment_Applied_To__c == 'Filing Fees'){
                        jw.filingFeesAllocation = (jp.Posted_Amount__c == 0 || jp.Posted_Amount__c == null) ? jp.Recommended_Amount__c : jp.Posted_Amount__c;
                        jw.matchingFilingFeeJP = jp;
                    } //// jp.Payment_Applied_To__c == 'Judgment Amount' means this JP is redundant with one of the LPs. These 'redundant' JPs don't show up on the LWC nor are meant to be directly editable.
                      ////   These JPs are created in CashCreateRendundantJPs, and handled mostly in the LP code: CashCaseIssueWrapper, CashUpdateMatchedLPs.  
                }
            }

            if(!effectivePoboLiablePartyList.isEmpty()){
                jw.relevantPoboLiablePartyId = effectivePoboLiablePartyList[0].Id;
            }
            
            for(Liability_Judgement__c judgmentParty : judgmentPartyList){
                if(judgmentParty.Judgement__c == jw.thisJudgment.Id){ //Assuming all Judgment Parties on one Judgment look up to the same Case Role.

                    Liability_Judgement__c judgmentPartyDetail = [SELECT Id, Liable_Party__r.Case_Role__r.Account_Name__c, Liable_Party__r.Case_Role__r.Entity__c
                                                                    FROM Liability_Judgement__c
                                                                    WHERE Id = :judgmentParty.Id];

                    System.debug('jp name: ' + judgmentPartyDetail.Liable_Party__r.Case_Role__r.Account_Name__c);
                    jw.judgmentPartyName = judgmentPartyDetail.Liable_Party__r.Case_Role__r.Account_Name__c;
                    jw.judgmentPartyUrl = '/' + judgmentPartyDetail.Liable_Party__r.Case_Role__r.Entity__c;
                    /* jw.judgmentTooltip = '🔴𝙅𝙪𝙙𝙜𝙢𝙚𝙣𝙩 𝙋𝙖𝙧𝙩𝙮: ' + judgmentParty.Liable_Party__r.Case_Role__r.Account_Name__c + ' ' + jw.judgmentTooltip; */

                    /* jw.relevantCaseRoleId = judgmentParty.Liable_Party__r.Case_Role__r.Id; */
                    /* jw.relevantPoboLiablePartyId = judgmentParty.Liable_Party__r.Id; */
                }
            }
        }

        return jwList;
    }
}