force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Role__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>This field maintains the relationship between the Case Role and the Case.  Reparentable.</description>
    <inlineHelpText>This field maintains the relationship between the Case Role and the Case.  Reparentable.</inlineHelpText>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Case Role</relationshipLabel>
    <relationshipName>Case_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payee__c/Payee__c.object-meta.xml
<CustomObject>
    <description>Used to capture data for Payee information related to a case and liability</description>
    <label>Payee</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payee__c/fields/Case_Management__c.field-meta.xml
<CustomField>
    <fullName>Case_Management__c</fullName>
    <description>M/D to the Case Management object</description>
    <label>Case Management</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payee__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the claimant of a Case. Filtered to only return case roles that are in the Case Management record.</description>
    <label>Case Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Role__c.Case__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case_Management__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Payees</relationshipLabel>
    <relationshipName>Payees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/Payment_Record__c.object-meta.xml
<CustomObject>
    <label>Payment Record</label>
    <nameField>
        <displayFormat>PR-{0}</displayFormat>
        <label>Payment Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Record__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Record__c/fields/Warrant__c.field-meta.xml
<CustomField>
    <fullName>Warrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warrant</label>
    <referenceTo>Warrant__c</referenceTo>
    <relationshipLabel>Payment Records</relationshipLabel>
    <relationshipName>Payment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warrant__c/Warrant__c.object-meta.xml
<CustomObject>
    <description>Check object for capturing relevant check data</description>
    <label>Warrant</label>
    <nameField>
        <displayFormat>WR-{000000}</displayFormat>
        <label>Warrant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warrants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warrant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case Managment object</description>
    <label>Case</label>
    <referenceTo>DIR_Case__c</referenceTo>
    <relationshipLabel>Warrants</relationshipLabel>
    <relationshipName>Warrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warrant__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Payee to whom the check is written</inlineHelpText>
    <label>Payee</label>
    <referenceTo>Payee__c</referenceTo>
    <relationshipLabel>Warrants</relationshipLabel>
    <relationshipName>Warrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UWFCaseRoleInsertQable.cls
public with sharing class UWFCaseRoleInsertQable implements Queueable{

    List<Case_Role__c> crsToInsert = new List<Case_Role__c>();
    List<Case_Role__c> overflowCRs = new List<Case_Role__c>();
    List<Payee__c> payeesToInsert = new List<Payee__c>();
    List<Payee__c> updatedPayeesToInsert = new List<Payee__c>();
    List<Warrant__c> wrsToInsert = new List<Warrant__c>();
    List<Payment_Record__c> prsToUpdate = new List<Payment_Record__c>();
    Map<String, List<Id>> qJobIdMap = new Map<String, List<Id>>();
    String wbURL;
    String reqType;
    Integer maxRows = 1;
    String actType;

    
    public UWFCaseRoleInsertQable(List<Case_Role__c> crListToInsert, List<Payee__c> payeeListToInsert, List<Warrant__c> wrListToInsert, List<Payment_Record__c> prListToUpdate, String type, String wbLink) {
        system.debug('!!!!!!!!!!!!!!!!!! UWFCaseRoleInsertQable !!!!!!!!!!!!!!!!!!');
        wbURL = wbLink;
        reqType = type;
        crsToInsert = crListToInsert;
        payeesToInsert = payeeListToInsert;
        wrsToInsert = wrListToInsert;
        prsToUpdate = prListToUpdate;
        actType = 'Insert';

        while(crsToInsert.size() > maxRows){
            overflowCRs.add(crsToInsert.remove(maxRows));
        }

    }

    public void execute(QueueableContext qc){
        try{
            system.debug('!!!!!!!!!!!!!!!!!! Insert Case Role !!!!!!!!!!!!!!!!!!');
            insert crsToInsert;
            System.debug('<==================== Inserted Case Roles ====================> ' +crsToInsert);
            for(Payee__c payee: payeesToInsert){
                system.debug('For Loop payee ==> ' + payee);
                Boolean payeeUpdated = false;
                for(Case_Role__c cr: crsToInsert){
                    //system.debug('For Loop payee ==> ' + payee);
                    system.debug('For Loop Case Roles ==> ' + cr);
                    system.debug('<====================== payee.Case_Management__c <======================' + payee.Case_Management__c);
                    system.debug('<====================== payee.Case_Role__c <======================' + payee.Case_Role__c);
                    system.debug('<====================== cr.Case__c <======================' + cr.Case__c);
                    system.debug('<====================== cr.Id <======================' + cr.Id);
                    if(cr.Case__c == payee.Case_Management__c && payee.Case_Role__c == null){
                        payee.Case_Role__c = cr.Id;
                        updatedPayeesToInsert.add(payee);
                        system.debug('Payee after adding Case Role field ==> ' + payee);
                        payeeUpdated = true;
                    }
                }
                if(!payeeUpdated){
                    updatedPayeesToInsert.add(payee);
                }
            }

            qJobIdMap.put('Insert UWF Case Roles', new List<Id>{qc.getJobId()});

            if(!Test.isRunningTest()){
                if(!overflowCRs.isEmpty()){
                    System.enqueueJob(new UWFCaseRoleInsertQable(overflowCRs, payeesToInsert, wrsToInsert, prsToUpdate, reqType, wbURL));
                }
                else{
                    system.debug('!!!!!!!!!!!!!!!!!! Case Role - UWF Payee !!!!!!!!!!!!!!!!!!');
    
                    //Call Insert Payee
                    system.debug('!!!!!!!!!!!!!!!!!! Insert UWF Payees !!!!!!!!!!!!!!!!!!');
                    system.debug('UWF Payees to Insert ==> ' + updatedPayeesToInsert);
                    System.enqueueJob(new UWFPayeeInsertQable(updatedPayeesToInsert, wrsToInsert, prsToUpdate, reqType, wbURL, qJobIdMap));
                }
            }
        }
        catch(Exception e){
            String errorMessage = e.getTypeName() + ': [' + e.getLineNumber() + '] ' + e.getMessage() + '<br/>Stack trace:<br/>' + e.getStackTraceString();
            
            qJobIdMap.put('Insert UWF Case Roles', new List<Id>{qc.getJobId()});

            System.attachFinalizer(new WarrantFinalizer(wbURL, qJobIdMap, actType ,errorMessage));
        }
        
    }
}