force-app/main/default/objects/Case_Role__c/Case_Role__c.object-meta.xml
<CustomObject>
    <description>This object contains a list of Accounts (Employers, Stake Holders, Employees, etc) related to this Case and the Entity</description>
    <label>Case Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Case Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgement__c/Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment</label>
    <nameField>
        <displayFormat>J-{0}</displayFormat>
        <label>Judgment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Judgement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending/Open</fullName>
            </value>
            <value>
                <fullName>Open/Unpaid</fullName>
            </value>
            <value>
                <fullName>Open - Partial Payment/Satisfaction</fullName>
            </value>
            <value>
                <fullName>Open - Payment Plan</fullName>
            </value>
            <value>
                <fullName>Closed - Satisfied</fullName>
            </value>
            <value>
                <fullName>Closed - Discharged in Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Stayed - Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Stayed - Other</fullName>
            </value>
            <value>
                <fullName>Vacated</fullName>
            </value>
            <value>
                <fullName>Closed-Claimant Judgment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/Liability_Judgement__c.object-meta.xml
<CustomObject>
    <label>Judgment Party</label>
    <nameField>
        <displayFormat>LJ-{0}</displayFormat>
        <label>Judgment Party</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Judgment Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liability_Judgement__c/fields/Judgement__c.field-meta.xml
<CustomField>
    <fullName>Judgement__c</fullName>
    <label>Judgment</label>
    <referenceTo>Judgement__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Liability_Judgement__c/fields/Liable_Party__c.field-meta.xml
<CustomField>
    <fullName>Liable_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Liable Party</label>
    <referenceTo>Liable_Party__c</referenceTo>
    <relationshipName>Liability_Judgements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/Liable_Party__c.object-meta.xml
<CustomObject>
    <label>Liable Party</label>
    <nameField>
        <displayFormat>LP-{000000}</displayFormat>
        <label>Liable Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liable Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Liable_Party__c/fields/Case_Role__c.field-meta.xml
<CustomField>
    <fullName>Case_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The liable party is related to a case role on the record. This field holds the value of that case role and is used for generating output document based on the party.</description>
    <inlineHelpText>Case role of the liable party</inlineHelpText>
    <label>Case Role</label>
    <referenceTo>Case_Role__c</referenceTo>
    <relationshipLabel>Liable Parties</relationshipLabel>
    <relationshipName>Liable_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Liable_Party__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Liable</fullName>
            </value>
            <value>
                <fullName>Not Liable</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CashUpdateMatchedJPs.cls
//Match the JW allocations to existing non-'Judgment Amount' JPs, if any.
//   'Judgment Amount' JPs are updated in the CashUpdateMatchingLPs class with their related LPs.
//   Essentially the same algorithm as with matching CIW allocations to LPs, CashUpdateMatchedLPs class, q.v.

public with sharing class CashUpdateMatchedJPs{
    public static void updateMatchedJPs(List<CashJudgmentWrapper> judgmentWrapperList,
                                        List<Liability_Judgement__c> allJudgmentPartyList,
                                        /* String selectedPobo, */
                                        String whichButtonClicked)
        {
        
        for(CashJudgmentWrapper jw : judgmentWrapperList){

            // TODO: Commented out because jw.relevantPoboLiablePartyId should have been populated in JS, CashJudgmentWrapper class, already.
            /* // Determine correct POBO the JP should look up to
            for(Liability_Judgement__c judgmentParty : allJudgmentPartyList){
                if(judgmentParty.Judgement__c == jw.thisJudgment.Id){
                    if(judgmentParty.Liable_Party__r.Case_Role__c == selectedPobo){
                        jw.relevantPoboLiablePartyId = judgmentParty.Liable_Party__r.Id;
                    }
                }
            } */
            
            if(jw.matchingPostHearingInterestJP != null){
                jw.matchingPostHearingInterestJP.Payment_On_Behalf_Of__c = jw.relevantPoboLiablePartyId;

                if(whichButtonClicked == 'Recommend'){
                    jw.matchingPostHearingInterestJP.Recommended_Amount__c = jw.postHearingInterestAllocation;
                    jw.matchingPostHearingInterestJP.Status__c = 'Recommended';
                }else{ //whichButtonClicked == 'Post'
                    jw.matchingPostHearingInterestJP.Posted_Amount__c = jw.postHearingInterestAllocation;
                    jw.matchingPostHearingInterestJP.Status__c = 'Posted';
                }
            }
            if(jw.matchingPostJudgmentInterestJP != null){
                jw.matchingPostJudgmentInterestJP.Payment_On_Behalf_Of__c = jw.relevantPoboLiablePartyId;

                if(whichButtonClicked == 'Recommend'){
                    jw.matchingPostJudgmentInterestJP.Recommended_Amount__c = jw.postJudgmentInterestAllocation;
                    jw.matchingPostJudgmentInterestJP.Status__c = 'Recommended';
                }else{ //whichButtonClicked == 'Post'
                    jw.matchingPostJudgmentInterestJP.Posted_Amount__c = jw.postJudgmentInterestAllocation;
                    jw.matchingPostJudgmentInterestJP.Status__c = 'Posted';
                }
            }
            if(jw.matchingAttorneyFeeJP != null){
                jw.matchingAttorneyFeeJP.Payment_On_Behalf_Of__c = jw.relevantPoboLiablePartyId;

                if(whichButtonClicked == 'Recommend'){
                    jw.matchingAttorneyFeeJP.Recommended_Amount__c = jw.attorneyFeesAllocation;
                    jw.matchingAttorneyFeeJP.Status__c = 'Recommended';
                }else{ //whichButtonClicked == 'Post'
                    jw.matchingAttorneyFeeJP.Posted_Amount__c = jw.attorneyFeesAllocation;
                    jw.matchingAttorneyFeeJP.Status__c = 'Posted';
                }
            }
            if(jw.matchingFilingFeeJP != null){
                jw.matchingFilingFeeJP.Payment_On_Behalf_Of__c = jw.relevantPoboLiablePartyId;

                if(whichButtonClicked == 'Recommend'){
                    jw.matchingFilingFeeJP.Recommended_Amount__c = jw.filingFeesAllocation;
                    jw.matchingFilingFeeJP.Status__c = 'Recommended';
                }else{ //whichButtonClicked == 'Post'
                    jw.matchingFilingFeeJP.Posted_Amount__c = jw.filingFeesAllocation;
                    jw.matchingFilingFeeJP.Status__c = 'Posted';
                }
            }
        }
    }
}