force-app/main/default/objects/Performance_Appraisal_Tracking__c/Performance_Appraisal_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking Appraisal, related to Appointment and Prob Report</description>
    <label>Performance Appraisal Tracking</label>
    <nameField>
        <displayFormat>PAT-{00000}</displayFormat>
        <label>Performance Appraisal Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Appraisal Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Performance_Appraisal_Tracking__c/fields/Appointment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_End_Date__c</fullName>
    <formula>Appointment__r.End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appointment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Performance_Appraisal_Tracking__c/fields/Appraisal_Date__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Date__c</fullName>
    <label>Appraisal Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Performance_Appraisal_Tracking__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <description>To be updated with employee contact name by flow for appraisal reminder sent to supervisor/liaison.</description>
    <label>Employee Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Performance_Appraisal_Tracking__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Appraisal record to become expired after 2nd reminder (is updated by flow HR Appraisal Tracking)</description>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Performance_Appraisal_Tracking__c/fields/First_Appraisal_Period_Formula__c.field-meta.xml
<CustomField>
    <fullName>First_Appraisal_Period_Formula__c</fullName>
    <description>First Appraisal Period year based on 3rd probation due date or appt start date. Based on this field, system can determine if annual appraisal record is to be created.</description>
    <formula>Appointment__r.First_Appraisal_Period_Formula__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First  Appraisal Period Formula</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Performance_Appraisal_Tracking__c/fields/Invalid__c.field-meta.xml
<CustomField>
    <fullName>Invalid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Under circumstances, appraisal record is marked Invalid. Flow considers this field in its progress.</description>
    <label>Invalid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Performance_Appraisal_Tracking__c/fields/Send_Reminder_1__c.field-meta.xml
<CustomField>
    <fullName>Send_Reminder_1__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Scheduled Job Apex class 'HR_Batch_Send_Appraisal_Reminder_1' updates this box to true to send reminder # 1</description>
    <label>Send Reminder 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Performance_Appraisal_Tracking__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <formula>TEXT (Appointment__r.Tenure__c)</formula>
    <label>Tenure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HR_Batch_Appraisal_Expired.cls
global class HR_Batch_Appraisal_Expired implements Database.Batchable <sObject>, schedulable {     
    Integer currentYear = System.Today().year();
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Expired__c, Invalid__c, Employee_Name__c, Tenure__c, Send_Reminder_1__c, Appointment_End_Date__c, Appraisal_Date__c, First_Appraisal_Period_Formula__c from Performance_Appraisal_Tracking__c';
        return Database.getQueryLocator(query); 
    }        
    global void execute(Database.BatchableContext bc,List<Performance_Appraisal_Tracking__c> batch) {
        for (Performance_Appraisal_Tracking__c Appr : batch) {
            IF (Appr.Expired__c == FALSE){
            	Appr.Expired__c = TRUE;           
            }
        }
        UPDATE batch;
    }    
    global void finish(Database.BatchableContext bc) {
        //Do Nothing.
    }   
    global void execute(SchedulableContext sc) {
         ID BatchId = Database.executeBatch(new HR_Batch_Appraisal_Expired(), 200);
    }
}